### ISSUE TITLE
`Clap` is unable to work

### ISSUE THREAD

**Issue by L-Vim** [liuchengxu/vim-clap#10]
- OS: Ubuntu 16.04
 - Neovim version: 0.4
 - vim-clap version: current, 1st October 11:13 AM CEST

**Describe the bug**

The title message appears when trying a clap command, e.g. `:Clap`.

> Error detected while processing function clap#init#[19]..<SNR>29_init_hi_groups[17]..<SNR>29_hi_display_invisible:                                                                                                                                  
line    3:
E421: Color name or number not recognized: ctermfg= guifg=
[vim-clap] Fail to load the provider: _

The line causing the issue is:

```vim
hi ClapDisplay cterm=bold ctermfg=white gui=bold guifg=#FFFFFF
```

When removed, seems to work fine.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/vim-clap
filetype plugin indent on
syntax on
set hidden

hi ClapInput cterm=bold ctermfg=white gui=bold guifg=#FFFFFF
hi ClapDisplay cterm=bold ctermfg=white gui=bold guifg=#FFFFFF
```

2. Start neovim with command: `nvim -u min.vim`

3. Type `:Clap`

**Expected behavior**

Clap's popup with correct colors.

**Comment by liuchengxu** [comment]
Thanks for the pointer. It's actually partially a known issue, `Clap` without any arguments is unable to work, it's designed to list all the available providers, but its `sink` function is broken at the moment, I haven't figured it out. `E421: Color name or number not recognized: ctermfg= guifg=` can be easily fixed.
