### ISSUE TITLE
Disable relative numbers

### ISSUE THREAD

**Issue by davidgaleano** [liuchengxu/vim-clap#100]
Line numbers are disabled by default on the results window but not relative numbers, could it be possible to disable relative numbers too? If not by default at least via an optional setting.

Thanks.

**Comment by liuchengxu** [comment]
It makes sense to disable the relative number by default.

Furthermore, you can always customize the window via the event `ClapOnEnter` and clap api `:h clap-api`.

```vim
function! YourFunction() abort
  call g:clap.display.setbufvar('&relativenumber', 0)
endfunction
autocmd User ClapOnEnter call YourFunction()
```

**Comment by davidgaleano** [comment]
Thanks for fast response and the example.
