### ISSUE TITLE
Auto selection of the source using VS Code command palette like prefix

### ISSUE THREAD

**Issue by 3v1n0** [liuchengxu/vim-clap#101]
**Is your feature request related to a problem? Please describe.**
I like something like vscode, that when you're using the command palette, you can select where to search depending on the prefix.

**Describe the solution you'd like**
I'd like to open the view with a keybinding and then

 `> foo` searches the command `foo`
 `# bar` looks for the symbol bar
 `! file` searches for file `file`

Ofc, changing the prefix allows to quickly change the source.

**Comment by liuchengxu** [comment]
Thanks for creating this issue, it is already on my roadmap actually, but may not be soon.

**Comment by alerque** [comment]
Not exactly what you asked for, but conceptually the [keybindings I use](https://github.com/alerque/que-vim/blob/master/.config/nvim/init.vim#L443) are actually pretty similar and might be a stop-gap solution for you. One key (in my case <kbd>!</kbd>) for all Clap driven searches, then one letter indicating the type of thing I'm searching for (<kbd>f</kbd> for files, <kbd>l</kbd> for lines, etc.). It can't be backspaced over and changed on the fly like your feature suggestion, but I pretty much know what class of thing I'm looking for before I fire off Clap, and it's even less typing than your feature request (no space key after prefix).

```vim
nnoremap <silent> !! :Clap! <Cr>
nnoremap <silent> !b :Clap! buffers ++ef=fzf +async<Cr>
nnoremap <silent> !f :Clap! files<Cr>
nnoremap <silent> !g :Clap! grep<Cr>
nnoremap <silent> !h :Clap! history<Cr>
nnoremap <silent> !l :Clap! lines<Cr>
nnoremap <silent> !m :Clap! marks<Cr>
nnoremap <silent> !p :Clap! yanks<Cr>
nnoremap <silent> !w :Clap! windows<Cr>
```

Obviously there are some I don't use and you could modify this any way you like. I initially tried to use `<leader>` but there are so many other things I already use that for it was hard to find logical non-conflicting keys to go with it. On my keyboard map (programmers dvorak, remapped Kinesis Advantage keyboard) the <kbd>!</kbd> key happens to easy accessible and a single press (no modifier). Also `vim` wasn't using it for anything. You might want to pick a different prefix if your layout requires a <kbd>Shift</kbd> modifier to reach <kbd>!</kbd>.

**Comment by liuchengxu** [comment]
Since we already have `:Clap providers` to show all the existing clap providers, I'm considering a simple way to acheive this goal. When user inputs some special characters, e.g., `!!`, invoke the `providers` provider then you reselect another provider, that needs just a few lines and I think it's very convenient.

**Comment by liuchengxu** [comment]
In #101, you can use `<C-L>` mapping or input `@@` to relaunch the providers pane and then reselect any another provider. It's more convient that the prefix-based relaunch as you don't have to remember to each provider's prefix and they can be conflicted when there are many ones.
