### ISSUE TITLE
Encoding issue in Clap grep

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/vim-clap#103]
**Environment:**
 - OS: Windows 10 v1809(OS Build 17763.503)
 - (Neo)Vim version: Vim 8.1(1-2204)
 - vim-clap version: b139e54810c6ae1f83efdb5c3710efad7eedfbbc
 - Have you reproduced with a minimal vimrc: N/A

**Describe the bug**
Clap grep has encoding issue on Windows, please see pic below

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `Clap files`

4. See screenshot below

**Screenshots**

![image](https://user-images.githubusercontent.com/20545387/67826636-288ab580-fb08-11e9-9cdf-df5b8ba59ff6.png)

**Comment by liuchengxu** [comment]
I don't have windows machine, so I only provide some advices. Have you tried running rg directly in the cmd or something? And you can try the following patch to see if it helps.

```diff
--- a/autoload/clap/dispatcher.vim
+++ b/autoload/clap/dispatcher.vim
@@ -225,7 +225,12 @@ else
   endfunction
 
   function! s:job_start(cmd) abort
-    let job = job_start(['bash', '-c', a:cmd], {
+    if has('win32')
+      let cmd = &shell . ' ' . &shellcmdflag . ' ' . a:cmd
+    else
+      let cmd = split(&shell) + split(&shellcmdflag) + [a:cmd]
+    endif
+    let job = job_start(cmd, {
           \ 'in_io': 'null',
           \ 'err_cb': function('s:err_cb'),
           \ 'out_cb': function('s:out_cb'),
```

**Comment by hongyuanjia** [comment]
Yes, I can confirm running command `rg` directly from cmd works.

And the patch works!

![image](https://user-images.githubusercontent.com/20545387/67827581-6806d100-fb0b-11e9-8ec8-fe0c8d7dfb6f.png)

**Comment by liuchengxu** [comment]
Thanks for the feedback. I have included the patch in the latest version, please pull the latest commit.

**Comment by hongyuanjia** [comment]
That is super quick. Thanks.
