### ISSUE TITLE
frecency support?

### ISSUE THREAD

**Issue by FelipeLema** [liuchengxu/vim-clap#1035]
**Is your feature request related to a problem? Please describe.**
I want to access paths by how frencent I've accessed them. "Frecent" being a mix of "frequent" and "recent"

**Describe the solution you'd like**
Use frecency scoring (feature is best explained at https://github.com/nvim-telescope/telescope-frecency.nvim)

**Describe alternatives you've considered**
see https://github.com/nvim-telescope/telescope-frecency.nvim

**Additional context**
I can implement if maintainers are willing to merge

**Comment by liuchengxu** [comment]
It's already supported in `recent_files` provider, try `:Clap recent_files`.

**Comment by liuchengxu** [comment]
I realize that `recent_files` does not use the same formula with telescope-frecency though, you can create a new issue for adding a new scoring option and work on it if you're interested, the current score is calculated in:

https://github.com/liuchengxu/vim-clap/blob/324148f99ea78462c9c1127650057702421514e1/crates/maple_core/src/recent_files.rs#L87
