### ISSUE TITLE
Support C-n and C-p for up/down by default

### ISSUE THREAD

**Issue by matthsims** [liuchengxu/vim-clap#104]
While it's very easy to add:
``` vim
inoremap <silent> <buffer> <C-n> <C-R>=clap#handler#navigate_result('down')<CR>
inoremap <silent> <buffer> <C-p> <C-R>=clap#handler#navigate_result('up')<CR>
```
to, for example, `after/ftplugin/clap_input.vim`, it seems like this should be the default to match vim's default. There is no documentation for mappings, either, so I had to root around in the code to find out how you mapped it, which is a bit much for restoring vimlike default behavior.

**Comment by liuchengxu** [comment]
This has been discussed before, please see https://github.com/liuchengxu/vim-clap/pull/52 .

**Comment by matthsims** [comment]
I can definitely respect your original design decision, `<C-n/p>` makes sense for input history as well as the result navigation. Do you think it would be worth having some `<Plug>` mappings so that users could change to their liking more easily? At least, documenting it would be nice. 

Aside, I really love the plugin! Great work!

**Comment by liuchengxu** [comment]
Yes, I thought `<Plug>` mappings is convenient, but I just saw this issue https://github.com/vim/vim/issues/5147. Plus the popup of vim is unable to be focused, changing the default key bindings means more works. Hence I'm reluctant to add these `<Plug>` mappings at the moment, it's not hard though.

**Comment by sdemura** [comment]
I'd like to see Ctrl-P/N be the default as well. Not just in Vim, but in many other places Ctrl N/P is the defacto keyboard shortcut for up/down, and I'd expect the same here.

**Comment by liuchengxu** [comment]
Checkout #52, Ctrl-N/P has been reserved for navigating the input history.

**Comment by RobertAudi** [comment]
> While it's very easy to add:
>
> ```vim
> inoremap <silent> <buffer> <C-n> <C-R>=clap#handler#navigate_result('down')<CR>
> inoremap <silent> <buffer> <C-p> <C-R>=clap#handler#navigate_result('up')<CR>
> ```
>
> to, for example, after/ftplugin/clap_input.vim

Just a note for anybody stumbling into this issue: The API changed so the code to use is as follows:

```vim
inoremap <silent> <buffer> <C-n> <C-R>=clap#navigation#linewise('down')<CR>
inoremap <silent> <buffer> <C-p> <C-R>=clap#navigation#linewise('up')<CR>
```
