### ISSUE TITLE
Allow configuring root patterns

### ISSUE THREAD

**Issue by luisdavim** [liuchengxu/vim-clap#1068]
Unfortunately, at work we use a monorepo and that can make finding files with `vim-clap` hard at times.

I've installed https://github.com/airblade/vim-rooter and have configured `coc-wrokspace` with a similar pattern (https://github.com/neoclide/coc.nvim/blob/ede39ea981f47222c5b1185592df7bb1875cec6d/doc/coc.txt#L1113)

But when I call `Clap files` it still displays results from the root of the git repository.

**Describe the solution you'd like**
I'd like to be able to define something like `rootPatterns` and limit clap to only search from the root folder based on it.

**Describe alternatives you've considered**
As mentioned above I've setup `vim-rooter` and `coc-wrokspace`, I my language server (`gopls`) is also set with a `rootPatterns` config.

**Comment by liuchengxu** [comment]
Is `g:clap_project_root_markers` what you are looking for? See `:h g:clap_project_root_markers`.

**Comment by luisdavim** [comment]
Yes, thank you very much, sorry I've missed it.
