### ISSUE TITLE
Selecting a line in `command_history` does nothing

### ISSUE THREAD

**Issue by hupfdule** [liuchengxu/vim-clap#109]
**Environment (please complete the following information):**
 - OS: Linux
 - (Neo)Vim version: NeoVim 0.4.2
 - vim-clap version: git commit 011b857
 - Have you reproduced with a minimal vimrc: No

**Describe the bug**
Calling `:Clap command_history` display the history of vim commands.
I can filter narrow down that list as expected.
When I then hit `enter` on an entry, nothing happens.

**To Reproduce**

1. Inside vim, call:

 ```
 grep FIXME
 ```

 That fills the quickfix list with all files containing the term "FIXME" (use a different term to get actual results).

2. Execute a different search:

```
grep TODO
```

That fills the quickfix list with all files containing the term "TODO".

3. Call

 ```
 :Clap command_history
 ```

4. Search for "FIXME" by entering "FIXME".
    That should put the cursor on the last `grep FIXME`.

5. Hit enter.

6. Open the quickfix list or navigate it. It still contains the "TODO" entries.

**Expected behavior**
What I actually would expect is that the selected command gets executed. In the example above would expect that the `grep FIXME` command is executed again, the quickfix window opened and filled with the entries containing "FIXME".

What is selecting an entry in `command_history` supposed to do?

**Comment by liuchengxu** [comment]
Can you provide a minimal vimrc?

**Comment by hupfdule** [comment]
A minimal vimrc is an empty vimrc.
Please see below screencast. It uses a vimrc that only specifies the packpath.
I only load the vim-clap plugin.

What I notices when recording this screencast is, that the selected command actually lands in the command history. This can be seen in the screencast when navigating the command history (outside vim-clap). But the actual action is not executed. In this case:

 - echoing a string
 - calling the vimhelp for `function-list`
 - opening a vertical split

[![asciicast](https://asciinema.org/a/um8wqsubQgSyR0ZF23ncZO6SQ.png)](https://asciinema.org/a/um8wqsubQgSyR0ZF23ncZO6SQ)

**Comment by liuchengxu** [comment]
Please try #111, see if that helps.

**Comment by hupfdule** [comment]
Sorry for the delay. Didn't have time to look into it yet.

Yes, the current version actually fixes that problem for the commands I tried.

The only thing I found which still doesn't work is echoing a messages.

You can try with:

```vim
:echom "Some text"
" Should display "Some text"
:messages 
" Should display "Some text"
:Clap command_history
" Now select the previously executed 'echom "Some text"'
" I would expect that "Some text" is displayed again, but it doesn't
:messages
" This still displays "Some text" only once. Therefore the command actually wasn't executed.
```

**Comment by liuchengxu** [comment]
@hupfdule Should be fixed now.

**Comment by hupfdule** [comment]
Yes, that works indeed.

Many thanks!
