### ISSUE TITLE
Change keybindings

### ISSUE THREAD

**Issue by phaazon** [liuchengxu/vim-clap#116]
Just a small question: how can I change keybindings? I would like to remap things but I cannot find how. Thanks.

**Comment by liuchengxu** [comment]
For vim, it's impossible for now, I have not came up with a good solution. If you want to hack it, see `popup_filter` and https://github.com/liuchengxu/vim-clap/blob/bee98419ccdc53222a14191e6731f89d827d7d77/autoload/clap/popup.vim#L399-L419 .

For neovim, take a look at https://github.com/liuchengxu/vim-clap/blob/master/ftplugin/clap_input.vim .

```vim
" For example, use <C-n>/<C-p> instead of <C-j>/<C-k>.
autocmd FileType clap_input inoremap <silent> <buffer> <C-n> <C-R>=clap#handler#navigate_result('down')<CR>
autocmd FileType clap_input inoremap <silent> <buffer> <C-p> <C-R>=clap#handler#navigate_result('up')<CR>
```

**Comment by phaazon** [comment]
Aoutch.
