### ISSUE TITLE
"Clap files|buffers" fails when :term is the current buffer

### ISSUE THREAD

**Issue by sscherfke** [liuchengxu/vim-clap#117]
**Environment (please complete the following information):**
 - OS: macOS, Linux
 - (Neo)Vim version: 0.4.x
 - vim-clap version: 97c8837
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When the neovim term (`:term`) is the current buffer, `:Clap files` and `:Clap buffers` only show an error message in the floating window: 
```
provider.on_typed:
function clap#handler#on_typed[9]
..30[2]
..clap#impl#on_typed[6]
..<SNR>91_on_typed_async_impl[11]
..clap#dispatcher#job_start[2]
..<SNR>97_apply_job_start[1]
..<SNR>97_job_start, line 1
Vim(let):E475: Invalid argument: expected valid directory
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:term<CR>:Clap files<CR>` or `:term<CR>:Clap buffers ++ef=fzy +async<CR>`

**Expected behavior**
Show the list of openbuffers.

**Comment by liuchengxu** [comment]
See if the latest commit fixes this issue. And if you really use `:Clap buffers ++ef=fzy +async` in daily life, I highly recommend you just using `:Clap buffers` as clap already supports filtering using fzy if your vim/neovim has the python support. The source of `:Clap buffers` is absolutely a small dataset, using async is an overkill.

**Comment by sscherfke** [comment]
Yes it works.  And thanks for the tip.  I'll try that. :)
