### ISSUE TITLE
highlited item is not visible

### ISSUE THREAD

**Issue by aleksandersumowski** [liuchengxu/vim-clap#118]
**Environment (please complete the following information):**
 - OS: Ubuntu 19.10
 - (Neo)Vim version: 0.4.2
 - vim-clap version: 97c883763267ad26d9504203437b074268ab8ad9 
 - Have you reproduced with a minimal vimrc: yes

When using seoul256 theme when I launch any of actions the first option in the menu is invisible

https://imgur.com/a/3jneHPo

The highlited item is visible if I start neovim with other colorscheme and then switch to seoul256 using `Clap colors`. The behavior was reproduced using only

`call plug#begin('~/test-vim-plugins/')`
`Plug 'liuchengxu/vim-clap'`
`Plug 'junegunn/seoul256.vim'`
`Plug 'morhetz/gruvbox'`
`call plug#end()`
`colorscheme seoul256`

**Comment by liuchengxu** [comment]
See `:h ClapSelected` and `:h clap-highlights`, you have to configure the highlights on your own. The default highlight groups used in clap are not guaranteed to fit your colorscheme.
