### ISSUE TITLE
If delete search query then write query again, 'Clap files' wont show file that dont match previous query

### ISSUE THREAD

**Issue by ybbond** [liuchengxu/vim-clap#119]
## Environment (please complete the following information):
 - OS: MacOS Mojave Latest
 - (Neo)Vim version: Nvim 0.4.2
 - vim-clap version: latest (6 Nov 2019)
 - Have you reproduced with a minimal vimrc: no, but I forked the repo and delete up to commit https://github.com/liuchengxu/vim-clap/pull/112

## Describe the bug
If I do `:Clap files` with a query, then delete the query then write totally different query, it won't show other result that don't match the first query

## To Reproduce

**Note: Name file specific to my project**

1. `:Clap files` search for `Story`
2. Delete entirely the search query of (1) without pressing `<return>` key
3. search for `NewsCard`
4. Only show one result that is `NewsCardStory.js`

## Expected behavior

If I reopen `:Clap files` and directly search for `NewsCard`, it will show 15 matched filenames, with `NewsCardStory.js` one of them

## Screenshots

1. (Bug) Search `Story`, delete, then search `NewsCard`

![bug](https://user-images.githubusercontent.com/25895873/68317107-236fcc80-00ed-11ea-88b0-cba266d93165.gif)

2. If open then directly search `NewsCard`

![try again](https://user-images.githubusercontent.com/25895873/68317116-279bea00-00ed-11ea-9377-a13839ee865a.gif)

## Additional context

I think the culprit is this commit: https://github.com/liuchengxu/vim-clap/pull/112

**NOTE:** fortunately, `:Clap grep` doesn't have the same bug

**Comment by liuchengxu** [comment]
Have you tried the latest version? I seemingly can't reproduce it. Can can you also provider the sample repo?

**Comment by ybbond** [comment]
fortunately, I tried this on my vim (with no other plugin except fugitive)

and it works! but I don't know why in my init.vim, it doesn't work.

for reference, this is my [init.vim](https://gist.github.com/ybbond/16ee5000eeca727899eac43a4c20291c), in the meantime, I will try to debug this myself. If in two days no luck, I will close this issue

**Comment by ybbond** [comment]
hey @liuchengxu it seems that I can't find what setting / plugin collide with `vim-clap` that produce this bug.

before I close this issue, can I know are you using nvim or vim? You said you cannot reproduce this right?

**Comment by ybbond** [comment]
I just tried to fork this repo and try to track from which commit this bug produced, and I found that it is this commit:
https://github.com/liuchengxu/vim-clap/commit/97c883763267ad26d9504203437b074268ab8ad9

**Comment by liuchengxu** [comment]
1. Can you still see it in the latest version?
2. I use neovim more often. But I can not reproduce this issue in both vim and neovim.

**Comment by ybbond** [comment]
1. I can still produce it from the latest version.
so for the time being, I forked this repo and use this extension from my version (with latest commit is https://github.com/liuchengxu/vim-clap/commit/a0d8a7565ba5ce1ea9159307a979fe6f20d4d03e , because the bug starts from https://github.com/liuchengxu/vim-clap/commit/97c883763267ad26d9504203437b074268ab8ad9 )
2. I can produce this issue only from my `neovim`. My `vim` currently has the same setting as neovim, but I cannot reproduce this bug on my `vim`.
I will try to use the neovim from my Linux PC shortly.

**Comment by liuchengxu** [comment]
You should reduce your vimrc to find the culprit. Let me know if you can reproduce this issue with a minimal vimrc, otherwise it's an issue of your own vimrc.

**Comment by johnallen3d** [comment]
I seem to be experiencing a similar issue. I've been tracking this thread and figured for a while that it must be something in my `vimrc`. However just now I've reduced my `vimrc` down to nothing and am still having trouble with the latest `vim-clap` installed from `master` in Neovim, Vim works as expected.

I notice the same issue described by @ybbond and similarly if I type a search string that doesn't match I see "NO MATCHES FOUND" and no further query will return results. I'm experiencing this with both `Clap files` as well as `Clap files ++externalfilter=fzf +async`.

One further thing that may or may not be related is that fuzzy searching doesn't seem to be working for me at all with `Clap files ++externalfilter=fzf +async`. If I type a character that doesn't directly match I see "NO MATCHES FOUND" and am out of luck until I relaunch `Clap files...`.

```sh
❯ nvim --version
NVIM v0.4.0-dev
Build type: Release

❯ /usr/local/bin/vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 15 2019 11:58:47)
macOS version
Included patches: 1-2151
Compiled by Homebrew

❯ fzf --version
0.18.0 (brew)
```

BTW - I ❤️ vim-clap and have continued to use it regardless of these minor issues!

**Comment by ybbond** [comment]
@johnallen3d if you have time to try
can you try to install my fork of vim-clap and see if two of your problems not replicated?

I am in progress to learn vimscript to be able to find fix for this issue (that fixes the issue in my machine, but also doesn't interfere in others machines)

**Comment by liuchengxu** [comment]
Sadly I can't reproduce.

@johnallen3d Actually you don't have to always use the externalfilter as vim-clap already has a built-in fzy support and will switch to the pure async strategy when neccessary.

**Comment by johnallen3d** [comment]
@ybbond - Just installed your fork and it solves the issue for me, thanks!

@liuchengxu - Thanks for the tip about using the built-in support for fzy. If there's another approach to troubleshooting/reproducing the issue I'm happy to give it a try.

**Comment by ybbond** [comment]
@liuchengxu I havent able to learn vimscript but I read the codebase, so maybe I can help you get some idea:

maybe, when I press `<BS>` or `<C-h>`, it is supposed to update the `a:query` and compare it with `s:old_query`, but because it fails to check that the query has been deleted a character, vim clap doesnt rerun the search job


I hope somehow that helps you understand what causes the bug, eventhough you cannot reproduce. I am still trying to learn vimscript while this story still opened.

**Comment by liuchengxu** [comment]
For `s:old_query` you are actually saying `:Clap grep`. That's not the issue you posted originally, that's `:Clap files`. They are seemingly unrelated.

**Comment by ybbond** [comment]
@liuchengxu oh no, the issue is in `:Clap files`, but it seems I am wrong when tried to track where the "maybe" bug is.

but the behavior I observed is:
- write a query in `:Clap files`, e.g `hell`
- it shows two matches, `hello.rb` & `hell.rb`
- added one character, `o`, the query become `hello`
- it shows only one match, `hello.rb`
- I delete one character in the query, back again become `hell`
- it still only shows one match, `hello.rb`
- supposedly, it re-show `hell.rb` and `hello.rb` because the query updated to only contain `hell`

**Comment by ybbond** [comment]
## UPDATE FIXED (I Dont't know how)

@liuchengxu @johnallen3d 

I just did:
- `brew uninstall nvim`
- `rm -rf` all nvim related paths that written in https://github.com/neovim/neovim/issues/1415#issuecomment-470887644
  - includes `/usr/local/bin/nvim` and `/usr/local/share/nvim`
- `rm -rf ~/.local/share/nvim`
- `brew uninstall ripgrep fd` (tools used for `:Clap files`)

then:
- `brew install ripgrep fd`
- `brew install nvim`
- reinstall `vim-plug`
  - install all previously installed packages using `:PlugInstall`

somehow, it fixes this issue. I think my neovim settings is just bloated

**Comment by liuchengxu** [comment]
Glad you sort it out :).

**Comment by johnallen3d** [comment]
Sadly these steps didn't work for me. Must be something in my environment but I haven't been able to pin it down yet. Glad you were able to make something work @ybbond!
