### ISSUE TITLE
:Clap files with last opened buffer selected

### ISSUE THREAD

**Issue by bogdan0083** [liuchengxu/vim-clap#122]
**Is your feature request related to a problem? Please describe.**
I really like that in `Clap buffers` provider when you searching for buffers the last opened buffer is always **pre-selected**, meaning that you can just press Enter to select previously opened buffer. 

Is it possible to create something like this with a custom provider? The same `Clap files` provider but with the previous buffer already **pre-selected**? 

Thanks! :heart:

**Comment by liuchengxu** [comment]
There is no concept of previous buffer in the context of `:Clap files`.
