### ISSUE TITLE
Clap files shows "The handle"

### ISSUE THREAD

**Issue by habamax** [liuchengxu/vim-clap#128]
**Environment (please complete the following information):**
 - OS: Windows 10
 - GVim version: 8.1.2318
 - vim-clap version: current master
 - Have you reproduced with a minimal vimrc: yes
**Describe the bug**
1. Instead of file list -- "The handle" is shown
2. As soon as you start typing -- nothing is found
3. Erase everything -- file list is shown
4. Start typing -- nothing is found

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type 'Clap files' or 'Clap gfiles'

4. No errors, there is no files at all.

**Expected behavior**
Files to be listed and to be searched

**Screenshots**
Clap files
![image](https://user-images.githubusercontent.com/234774/69130003-c0a10c80-0ac0-11ea-9c48-084010ef969e.png)

Start typing (it is veeeeery slow):
![image](https://user-images.githubusercontent.com/234774/69130749-1f1aba80-0ac2-11ea-9ffe-000dcadf357a.png)

No files found:
![image](https://user-images.githubusercontent.com/234774/69130810-3c4f8900-0ac2-11ea-98da-d1ed690b179c.png)

Erase everything:
![image](https://user-images.githubusercontent.com/234774/69130841-48d3e180-0ac2-11ea-9595-8a42a53cebfc.png)

Search for abbreviation file:
![image](https://user-images.githubusercontent.com/234774/69130881-5f7a3880-0ac2-11ea-9890-9f0735c76caa.png)

**PS**
I can see it uses `rg --files` under the hood if it helps.

Clap grep, Clap colors, etc works.

**Comment by liuchengxu** [comment]
I don't have a windows machine, but you can try if this patch helps:

```diff
--- a/autoload/clap/forerunner.vim
+++ b/autoload/clap/forerunner.vim
@@ -61,7 +61,12 @@ if has('nvim')
   endfunction
 else
   function! s:start_forerunner(cmd) abort
-    let job = job_start(['bash', '-c', a:cmd], {
+    if has('win32')
+      let cmd = &shell . ' ' . &shellcmdflag . ' ' . a:cmd
+    else
+      let cmd = split(&shell) + split(&shellcmdflag) + [a:cmd]
+    endif
+    let job = job_start(cmd, {
```

**Comment by habamax** [comment]
> I don't have a windows machine, but you can try if this patch helps:

Yes, now it works. At least files are shown and I can search for them.

Filtering is really slow (compared to leaderF, CtrlP and fzf) but nevertheless works.

**Comment by habamax** [comment]
![vim-clap](https://user-images.githubusercontent.com/234774/69133631-488a1500-0ac7-11ea-92c9-265f997a3431.gif)

**Comment by habamax** [comment]
Just to compare with leaderf (it is instant):
![vim-leaderf](https://user-images.githubusercontent.com/234774/69134287-4ffdee00-0ac8-11ea-867a-76c21719dbe3.gif)

**Comment by liuchengxu** [comment]
That's weird, it should be fast as you only 47 files, that's far from the performance topic. Can you do a profile with the minimal vimrc?

Here is the commands I often use:

```vim
function! s:Profile() abort                                                              
   profile start profile.log                                                              
   profile func *
   profile file *                                                                         
   set verbosefile=verbose.log                                                            
   set verbose=9                                                                          
endfunction
                                                                                                                                                                        
command! Profile call s:Profile()
                                      
command! ProfilePause profile pause | noautocmd wqa!                                     
```

1. open vim.
2. `:Profile`
3. `:Clap files` and input something.
4. `:ProfilePause`
5. Post the profile.log in this issue.

**Comment by habamax** [comment]
https://gist.github.com/habamax/6015fc04ed5e40b7ffb518c8b2b580ee

**Comment by habamax** [comment]
Looks like there are still some other plugins loaded even with minimal vimrc

**Comment by liuchengxu** [comment]
It's obvious that `system()` is the culprit. That should not happen. If you have applied that patch, `g:__clap_forerunner_result` should exist and `s:get_source()` is not supposed to be called. I believe that system call is in `s:get_source()`.

https://github.com/liuchengxu/vim-clap/blob/6b83abdf4cefb45cbaaf9e55a6d8a66a82c04909/autoload/clap/impl.vim#L67

You can try debugging this function. `clap#impl#on_typed()` will be called on your type. In you case, `g:__clap_forerunner_result` branch should be used.

https://github.com/liuchengxu/vim-clap/blob/6b83abdf4cefb45cbaaf9e55a6d8a66a82c04909/autoload/clap/impl.vim#L219-L230

**Comment by habamax** [comment]
```
  let time_start = localtime()
  let l:raw_lines = get(g:, '__clap_forerunner_result', s:get_source())
  echomsg printf("Duration %d", localtime() - time_start)
```
gives me 1 second between each input

So it is somewhere `g:clap.provider` lives, not sure where to continue

**Comment by liuchengxu** [comment]
I actually mean you should checkout why `g:__clap_forerunner_result` does not exist. We have found the reason why it's so slow: `s:get_source()` has a `system()` call which is very slow. Basically it should not happen as `g:__clap_forerunner_result` is supposed to exist.

When you enter the clap window, an async job will be started to try getting the results and then `g:__clap_forerunner_result` should be filled. See if the forerunner job works as expected.

https://github.com/liuchengxu/vim-clap/blob/6b83abdf4cefb45cbaaf9e55a6d8a66a82c04909/autoload/clap/api.vim#L508-L519

**Comment by habamax** [comment]
1. Added your lines to the clap source
2. Opened vim in vimfiles directory
3. Clap files
4. typed `abbr`

![image](https://user-images.githubusercontent.com/234774/69148370-315a2000-0ae5-11ea-9bf7-67878ccc3ac7.png)

**Comment by liuchengxu** [comment]
Terminal vim does not have this `Press ENTER...` prompt. I don't know if the forerunner job is fast enough, but it seems to work as expected.

See if `g:__clap_forerunner_result` is really used.

```diff
diff --git a/autoload/clap/impl.vim b/autoload/clap/impl.vim
index 10a0198..4da1245 100644
--- a/autoload/clap/impl.vim
+++ b/autoload/clap/impl.vim
@@ -64,7 +64,13 @@ function! s:on_typed_sync_impl() abort
 
   let l:has_no_matches = v:false
 
-  let l:raw_lines = get(g:, '__clap_forerunner_result', s:get_source())
+  if exists('g:__clap_forerunner_result')
+    echom "use cached results"
+    let l:raw_lines = g:__clap_forerunner_result
+  else
+    echom "get source"
+    let l:raw_lines = s:get_source()
+  endif
   let l:lines = call(g:clap.provider.filter(), [l:cur_input, l:raw_lines])
 
   if empty(l:lines)
```

**Comment by habamax** [comment]
> Terminal vim does not have this `Press ENTER...` prompt

Nope, it was my last command `:mess`, sorry didn't mention it.

**Comment by habamax** [comment]
> ```diff
> -  let l:raw_lines = get(g:, '__clap_forerunner_result', s:get_source())
> +  if exists('g:__clap_forerunner_result')
> +    echom "use cached results"
> +    let l:raw_lines = g:__clap_forerunner_result
> +  else
> +    echom "get source"
> +    let l:raw_lines = s:get_source()
> +  endif
> ```

THIS!

Now it is lightning fast and echos "use cached results"

**Comment by habamax** [comment]
Looks like `get` evaluates default value even if it is not used.

**Comment by liuchengxu** [comment]
That's really out of my knowledge :). Will fix that very soon.

**Comment by habamax** [comment]
Have just tested it:

```
fun! TestGet() abort
	echom 'I was evaluated!'
	return '1'
endfun

let g:test = 'hello world'
let v = get(g:, 'test', TestGet())
```

it echoes 'I was evaluated'.

**Comment by habamax** [comment]
Probably system calls on linux 100 times faster than in windows and it was not noticeable?

**Comment by habamax** [comment]
One minor thing,

When you start Clap files it lags a bit for a half a second or a second -- that is ok, files are being searched.

When I filter something -- it is fast now. Now if I delete everything, one last deletion of a char makes it lag again like it searches for the files again.

Should it work like that?

**Comment by liuchengxu** [comment]
Yes, I believe `system()` in macOS/Linux is much faster and I never notice that it gets evaluated every time.

>one last deletion of a char makes it lag again like it searches for the files again.

I have checked that and found there is a room to improve.

When you delete the last char, the input is empty, `s:reset_on_empty_input` will be called and `  call g:clap.display.set_lines_lazy(g:clap.provider.get_source())` has `g:clap.provider.get_source()` which is sync, I think it should be blamed

https://github.com/liuchengxu/vim-clap/blob/6b83abdf4cefb45cbaaf9e55a6d8a66a82c04909/autoload/clap/impl.vim#L56-L61

https://github.com/liuchengxu/vim-clap/blob/6b83abdf4cefb45cbaaf9e55a6d8a66a82c04909/autoload/clap/impl.vim#L13-L19

**Comment by habamax** [comment]
Should I fill another issue? (not sure I will be able to resolve it myself)

**Comment by liuchengxu** [comment]
@habamax Can you try this branch https://github.com/liuchengxu/vim-clap/tree/cache-get-source to see if it still lags when the input is empty?

**Comment by habamax** [comment]
> @habamax Can you try this branch https://github.com/liuchengxu/vim-clap/tree/cache-get-source to see if it still lags when the input is empty?

Tried it, no problem with deleting last char, no lags. Thanks!

**Comment by habamax** [comment]
With those fixes your excellent plugin is backup for me instead of CtrlP (for machines where python is not installed it would fit perfectly) thank you again.

What is missing (looking at leaderf and fzf) is support of opening folders with huge amount of files (sometimes it happens). Clap tries hard not showing file list at all and then to find a file entered but it is way slower than the others. They do it in background showing candidates right away with constant update of the list.

![vim-leaderf-huge](https://user-images.githubusercontent.com/234774/69155925-b2b8af00-0af3-11ea-9b0a-1759d76478c2.gif)

I don't know if it is possible to do with Clap at the moment.
![vim-clap-huge](https://user-images.githubusercontent.com/234774/69156143-062afd00-0af4-11ea-8db8-a1489ee04aed.gif)

**Comment by liuchengxu** [comment]
See the related disccussion #75. Neovim already work well in the case that has a monster of items.  Unfortunately, vim doesn't. Furthermore, it's basically impossible for vim to have a decent performance like Leaderf and fzf with vimscript only in this case. And I now use neovim more often so I may not spend more time to optimize for vim.

If you have interests, I believe you could use the thead model used in Leaderf to improve the performance. Or you can talk a look at https://github.com/vim/vim/issues/5143 to submit a another request for reading the output of job in chunks like neovim, this is the bottleneck of vim's job compared to neovim in vim-clap's usage.

**Comment by habamax** [comment]
Yes, I understand the limitations. Just wanted to dblcheck if I didn't miss anything and it could be somehow magically turned on for clap too :).

Thank you again!

PS, unfortunately neovim is way worse in windows than vim, I have both installed, my config works for both but neovim just not really polished for windows.

**Comment by liuchengxu** [comment]
I heard that WSL is a good option for Windows, you may try that. I use terminal vim/neovim only and they both work very well.
