### ISSUE TITLE
Allow using non-english text

### ISSUE THREAD

**Issue by habamax** [liuchengxu/vim-clap#129]
**Is your feature request related to a problem? Please describe.**
Impossible to grep for a russian text and probably open files with russian file names.

**Describe the solution you'd like**
Allow entering text either using keymap (C-^) or non-english text with OS language switch

**Comment by liuchengxu** [comment]
Vim's popup can't get the focus like NeoVim's floating_win, so the search text window and cursor of popup are mocked by vim-clap, which has to remember the emulated cursor position manually. 

https://github.com/liuchengxu/vim-clap/blob/3e16a996027ba7e7924b98eff34df9b634409c28/autoload/clap/popup.vim#L294-L307

vim-clap currently only responses to the ASCII printable characters:

https://github.com/liuchengxu/vim-clap/blob/3e16a996027ba7e7924b98eff34df9b634409c28/autoload/clap/popup.vim#L499-L502

Supporting non-english text means to support multi-byte text, which involves the `s:cursor_idx` calculation mainly. With the right cursor index, the multi-byte text display should be fine, but you have to also take care of these motions, i.e., `<C-A>`, `<C-B>`, etc. 

https://github.com/liuchengxu/vim-clap/blob/3e16a996027ba7e7924b98eff34df9b634409c28/autoload/clap/popup.vim#L458-L470

It's not a job I like, and it's critical for me, so I may won't spend time on this issue. PR is welcome.
