### ISSUE TITLE
Dynamically set the prompt

### ISSUE THREAD

**Issue by meck** [liuchengxu/vim-clap#134]
I want to dynamically set the prompt for each search. Im replicating fzf with source:`fd --type d` sink:`cd`. Then the current dir is shown as prompt in a condensed version.  

Could be a optional provider function `prompt`. I've looked at `g:clap_prompt_format` but that is only sourced once it seems, If that is changed to be checked every time it could be done in `on_enter` I guess?

**Comment by liuchengxu** [comment]
If you want to set the prompt dynamically, that means the prompt window which is an indepent floating window/popup will be adjusted every time the  prompt is changed as the spinner width probably varies.

**Comment by liuchengxu** [comment]
The fundamental api is `s:set_spinner`, you can modify `s:compose_prompt()` locally for now if you want until I find a nice way to support it.

https://github.com/liuchengxu/vim-clap/blob/849747572e492da00d02b63a8e04db243c1a8547/autoload/clap/spinner.vim#L30-L38

**Comment by liuchengxu** [comment]
@meck  Try #265, you can use `g:ClapPrompt` to specify a function used for generating the prompt. 

```vim
function! ClapFormat() abort
  return pathshorten(getcwd()).':'
endfunction

let g:ClapPrompt = function('ClapFormat')
```
