### ISSUE TITLE
Using new ":Clap grep <directory>" incorrectly populates quickfix

### ISSUE THREAD

**Issue by joefiorini** [liuchengxu/vim-clap#135]
First of all, thank you for adding the ability to search within a specific directory.

I did notice one problem with it that severely limits its use for me. That is, when I select multiple options in the search results and press Enter to load them all into the quickfix list, they are scoped to the directory I searched in. That means, afaik, I can't actually open them through the quickfix list. This is very useful as it allows for a fast workflow to fixing similar problems in a number of files. Do you think this is something that would be possible?

**Comment by liuchengxu** [comment]
See if #137 works.

**Comment by joefiorini** [comment]
@liuchengxu Sorry for my delay in getting back to this. I can confirm this is fixed. Thank you very much for fixing, vim-clap is without a doubt my favorite fuzzy finder for vim!
