### ISSUE TITLE
Ignore NERDTree window and others

### ISSUE THREAD

**Issue by adelarsq** [liuchengxu/vim-clap#139]
I use NERDTree a lot on my workflow. Always that the focus is on it and I call Clap choosing a file the file is opened on the NERDTree's window.

Would be nice if it was possible to ignore the NERDTree window, and others, opening the file only on the allowed window.

For now I close the NERDTree's window and I open again after the file been opened. I think it's possible to solve with `ClapOnEnter` and` ClapOnExit` autocommands, but I still didn't have time to test.

**Comment by liuchengxu** [comment]
I don't understand what your exact request is.

**Comment by adelarsq** [comment]
The focus is on the NERTree window. So I execute `Clap files`:

<img width="637" alt="Captura de Tela 2019-11-27 às 23 04 40" src="https://user-images.githubusercontent.com/430272/69771173-a0311c00-116a-11ea-8bf4-e4591e40aaa6.png">

The file is opened on the NERDTree window, instead from the Startify window on the right side:

<img width="637" alt="Captura de Tela 2019-11-27 às 23 07 31" src="https://user-images.githubusercontent.com/430272/69771236-d078ba80-116a-11ea-8fc3-959c0b17dea9.png">

**Comment by liuchengxu** [comment]
What if you have more than two windows,  how to know in which window the selected file should be opend?

**Comment by alerque** [comment]
This is also a problem for [tagbar](https://github.com/majutsushi/tagbar). If there is anything that can be done from the tagbar (or NERDtree) side of things let us know. I don't know exactly how to handle the case of multiple open panes besides these utility panes, but somehow the utility panes know where to send you back when you open a file or navigate to a header from inside them, so it should be possible to capture or pass that information to Clap so it can open files in the correct target pane as well.

**Comment by adelarsq** [comment]
First we need a list from all windows in the current tab. So we can get the filetype for each window and ignore if the window appears in the ignored list. So on the Clap return it can change the focus for the first window on the new list.

The follow filetypes can be ignored I think:

- calendar (https://github.com/itchyny/calendar.vim)
- ctrlspace (https://github.com/vim-ctrlspace/vim-ctrlspace)
- denite (https://github.com/Shougo/denite.nvim)
- diff
- git
- gitcommit
- nerdtree (https://github.com/scrooloose/nerdtree)
- qf
- quickmenu (https://github.com/skywind3000/quickmenu.vim)
- startify (https://github.com/mhinz/vim-startify)
- terminal - used by `autocmd TermOpen * setfiletype terminal`
- todo
- undotree (https://github.com/mbbill/undotree)
- vim-plug (https://github.com/junegunn/vim-plug)
- vista (https://github.com/liuchengxu/vista.vim)
- vcblame (https://github.com/juneedahamed/vc.vim)

**Comment by liuchengxu** [comment]
You still can't guarantee the first one of new list is desired.

**Comment by adelarsq** [comment]
The only way that I think is by precedence. By position would be better, but I don't know if its possible.

**Comment by liuchengxu** [comment]
Actually the position is not a clear rule, e.g., some people like the window on the right side, while some may prefer the one on the left or at the bottom. I'm not interested in this feature myself, but I can accept PR :(.

**Comment by adelarsq** [comment]
No problem. When possible I will create one :).

**Comment by adelarsq** [comment]
Related in some way https://github.com/weirongxu/coc-explorer/commit/6fa5a3d98edc73725a48e490d9be5fe8d48b57b5

**Comment by tssm** [comment]
I think this is highly controversial. If it is implemented it should be based on a list of buffers that the user specifies. I use Neovim terminal a lot, as well as Startify, Quick Fix, Vista and FileBeagle. When I open a file with Clap I expect it to be open in the window with focus, even if it is one the above list.

**Comment by macintacos** [comment]
Surprised that this was closed out; I'm very interested in this feature, since it always throws me for a loop when my file drawer (in this case, NERDTree) is taken over by a file I was trying to open.

FWIW, there are a variety of solutions that folks came up with in this thread for FZF; I'm still really not good with vimscript so it's a bit tough for me to figure out how to make it apply to vim-clap. Maybe someone in this thread knows? https://github.com/junegunn/fzf/issues/453

**Comment by alerque** [comment]
This issue should be reopened. That bot should be shut down.

**Comment by liuchengxu** [comment]
>That bot should be shut down.

Yeah, also find it a bit of annoying.

**Comment by liuchengxu** [comment]
Try #653, you can change the focus to other windows when opening clap as follows:

```vim
autocmd User ClapOnInitialize call TryStartFromOtherWindow()

function! TryStartFromOtherWindow() abort
  " Filter the windows you want to ignore
  if bufname('%') ==# 'NERD_tree' || &filetype ==# 'coc-explorer'
    " Move the focus on the window you prefer.
    noautocmd wincmd l

    " Reset the start window of clap.
    let g:clap.start.bufnr = bufnr('')
    let g:clap.start.winid = win_getid()
    let g:clap.start.old_pos = getpos('.')
  endif
endfunction
```

**Comment by alerque** [comment]
That's looking promising (haven't test driven it yet, but the concept looks about right). But I would argue this should be included by default. I would think it vanishingly rare that anybody would *want* their special purpose panes taken over by Clap. My guess is the expected behavior 99% of the time is going to be to use whatever the most recent buffer in the buffer history is that does not match one of the ignore list. Such a list could be prepopulated with at least a dozen or so of the more popular plugins that create special panes.

**Comment by liuchengxu** [comment]
We can see there are various user requests in https://github.com/junegunn/fzf/issues/453, so my opinion is just to let people themselves decide the list that should be ignored and what to do when they ignore them.
