### ISSUE TITLE
Without Python the filtered list is not updated while deleting the input

### ISSUE THREAD

**Issue by tssm** [liuchengxu/vim-clap#144]
**Environment**
 - OS: macOS Mojave
 - Neovim version: 0.4.2
 - vim-clap version: commit `967aee76380198bdce34c69bbb0d6bdddead3411`
 - Have you reproduced with a minimal vimrc: yup

**Describe the bug**
My understanding is that Python is only needed for the built-in implementation of the fzy algorithm, but I prefer to get rid of Python and keep fzy on my `$PATH`. With that setup when I type text the filter seems to be working, but when I delete what I wrote the window is stuck in its previous state, i. e. it keeps showing the filtered output. I need to close the window with Esc and open it again to see the complete list again. ([I recorded my screen](https://usachcl-my.sharepoint.com/:v:/g/personal/tae_sandoval_usach_cl/EexWyMNWy5JPtAdDfu2achcBa5hJLcdr28Ixhwr3RUW6gA?e=PGJ2Oc).)

**To Reproduce**
1. Create the minimal vimrc `min.vim`:
```vim
let g:loaded_python3_provider=0
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```
2. Start (neo)vim with command: `vim -u min.vim`
3. Type `:Clap files`
4. Type something to filter the list
5. Use backspace to delete some characters
6. The files list will be stuck showing the filtered list

**Expected behavior**
The list should update showing more and more files

**Additional context**
I also tried laughing Neovim with `--noplugin` and manually loaded Clap with `:packadd clap` to ensure that no other plug-ins is messing around but the behaviour is the same

**Comment by liuchengxu** [comment]
I have to say that without python you have to always use the async version of vim-clap for the fuzzy filtering. vim-clap can work without python, but many features will be missing.

**Comment by tssm** [comment]
That was fast! 🚀 Thank you! I have been testing it and looks like all the features that I use (files, buffers and grep) are working as expected 💜
