### ISSUE TITLE
`files` ignores input_delay

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#145]
**Environment (please complete the following information):**
 - OS: Mac/Linux
 - Vim version: 8.1.2380
 - vim-clap version: master

**Describe the bug**
Although I have set the `g:clap_popup_input_delay` and it has 200ms default value, it doesn't seem to honor the value and does the search after each key press which makes it very slow on larger code bases.

The grep command does 

**To Reproduce**
see the screenshot part

**Expected behavior**
It should run the search after the given time value is passed

**Screenshots**

![vim-clap-files](https://user-images.githubusercontent.com/849640/69967428-43d64f80-1510-11ea-844c-f2fb162200fd.gif)

I'm not typing `test` one character at a time, it's Clap trying to do the search and since the code base contains too many files it takes some to do the search and return the result and does it again for the next character

**Comment by liuchengxu** [comment]
See #140 . It's just _slow_,  a performance issue of vim and vimscript.

**Comment by arashm** [comment]
I know the search itself can be slow, but I want the search execution to be delayed until I have finished typing. That shouldn't be related to the above performance issue, is it? And it works fine for `grep`, I type the whole word, then the grep command is triggered and results are shown. `ctrl-p` has the same option that I use and it works fine for files (without input delay that would be slow too).

**Comment by liuchengxu** [comment]
Since you have about 8000 files, vim-clap actually uses the built-in fzy python implementation, which runs **synchronously**, hence it could be slow. If you have more than 10,000 files, vim-clap will switch to the async way automatically. `Clap grep` is always **async**, unless you have hundreds of thousands, it should be fast.

**Comment by arashm** [comment]
I have tried `let g:clap_popup_input_delay = 5000` and vim returns `5000` when doing `:echo g:clap_popup_input_delay` but it has no effect. The search still happens for every character entered.

**Comment by liuchengxu** [comment]
Ok, I know the problem. vim-clap ignores the delay in this case. The original idea is to react fast if possible, for the providers like `jumps`, `marks` are only about one hundred items. This strategy can be improved then. Try commenting out the `is_sync` check and see if it works better. I'll find a better way to check if it should react immediately.

https://github.com/liuchengxu/vim-clap/blob/55b6df867d15fa8c1a0bce1d1ae64bba3a7103cc/autoload/clap/popup.vim#L455-L463

**Comment by liuchengxu** [comment]
I did not find a better checker, now the delay always exists for vim.

**Comment by arashm** [comment]
That's awesome and works perfect. Thank you very much for great maintenance of this gem 👍
