### ISSUE TITLE
zsh:1: command not found: fd

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/vim-clap#15]
**Environment :**
 - OS: macOS 10.14.6
 - Vim version: 8.1.2064
 - vim-clap version: latest
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
<img width="909" alt="Screen Shot 2019-10-02 at 17 53 25" src="https://user-images.githubusercontent.com/4246425/66035593-fe13ff80-e53d-11e9-8692-ffcf8544f2dc.png">

**To Reproduce**

```vim
:Clap files
```

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
let &rtp=&rtp.','.$HOME.'/.vim/bundle/vim-clap'
colorscheme desert "default setting 
filetype plugin indent on
syntax on

```

2. Start (neo)vim with command: `vim -u min.vim`

3. run command:

```vim
:Clap files
```

**Expected behavior**

No error

**Comment by liuchengxu** [comment]
I don't use zsh, but you can try this patch:

```diff
+++ b/autoload/clap/provider/files.vim
@@ -15,7 +15,7 @@ function! s:chain_try() abort
   return ['No usable tools found for the files provider']
 endfunction

-if has('win32')
+" if has('win32')
   let s:tools = {
         \ 'fd': '',
         \ 'rg': '--files',
@@ -23,9 +23,9 @@ if has('win32')
         \ 'find': '.',
         \ }
   let s:files.source = s:chain_try()
-else
-  let s:files.source = 'fd || git ls-tree -r --name-only HEAD || rg --files || find .'
-endif
+" else
+  " let s:files.source = 'fd || git ls-tree -r --name-only HEAD || rg --files || find .'
+" endif
```

**Comment by tracyone** [comment]
It's nothing to do with zsh. 

fd command is not found in my OS.

**Comment by chrisbra** [comment]
Thanks, I believe this fixes my issue I mentioned at reddit https://www.reddit.com/r/vim/comments/daf65f/a_modern_generic_interactive_finder_and/f23eg3u/
