### ISSUE TITLE
`:Clap grep` failed when there is `**___xxx___` in `.gitignore`

### ISSUE THREAD

**Issue by latavin243** [liuchengxu/vim-clap#151]
**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - (Neo)Vim version: neovim v0.5.0-dev
 - vim-clap version: on commit 4874356
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
`:Clap grep` failed when there is `**___jb_tmp___` in `.gitignore`. The error message is shown as follows:
```
Error occurs when dispatching the command
job_id: 6
working directory: /home/user/gowork/src/golang_repo_xxx
command: rg -H --no-heading --vimgrep --smart-case "log"
message: 
./.gitignore: line 92: error parsing glob '**___jb_tmp___': invalid use of **; must be one path component
```

**To Reproduce**

1. Create an empty folder as the working directory afterwards (called test folder). Enter the folder.
```bash
mkdir test_folder
cd test_folder
```

2. Create the minimal vimrc `min.vim` (in the test folder):
```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

3. create a file named .gitignore and write the following line(s) into it.
```
**___xxx___
```

3. Start (neo)vim just in the test folder with command: `vim -u min.vim`

4. Type `:Clap grep` to search under current test folder and type anything to search, e.g. `vimvim`.

5. See error

**Expected behavior**
There will be error message in the floating search window, just under the `grep>` line.
```
Error occurs when dispatching the command
job_id: 6
working directory: /home/user/test_folder
command: rg -H --no-heading --vimgrep --smart-case "vimvim"
message: 
./.gitignore: line 1: error parsing glob '**___xxx___': invalid use of **; must be one path component
```

**Screenshots**
(Sorry it's hard to hide private message on the screenshots under ubuntu, so no screenshots is provided for now. All the error message is pasted in **Expected behavior** section.)

**Comment by liuchengxu** [comment]
I believe it's not an issue of vim-clap. What vim-clap does is to dispatch the command line command in the background and then gather the output of the job. If the related command does not even work in the command line, then it won't work for clap too. As you can see the error message, you could try them from the terminal, i.e., `cd /home/user/test_folder && rg -H --no-heading --vimgrep --smart-case "vimvim"`, you'll run into the same error. You should checkout why rg complains.
