### ISSUE TITLE
Be able to trigger the response to an input manually 

### ISSUE THREAD

**Issue by sefeng211** [liuchengxu/vim-clap#153]
**Is your feature request related to a problem? Please describe.**
Doing grep on large project is slow, and I don't want `vim-clap` to response to an unfinished input pattern on a large projects, this operation is slow. 

**Describe the solution you'd like**
I'd like to be able to trigger the `grep` manually after I typed the pattern. 

**Describe alternatives you've considered**
I don't know if there are alternative methods.

**Comment by liuchengxu** [comment]
I believe you are using vim? Then try to increase the input delay of popup to a decent number, `:h g:clap_popup_input_delay`.

**Comment by liuchengxu** [comment]
Just saw your change of title. vim-clap is initially designed for doing the _real time_ grep and the work flow is intuitive. You stop the typing, the async job starts. If you want to start the job manually, which key mapping should be used for this trigger? That's a question.

**Comment by liuchengxu** [comment]
How about using `<C-X>` for triggering the job manually?

**Comment by sefeng211** [comment]
I see, the problem for real time grep is if the project is large, the cost of typos are expensive because grep would take a long time. 

<C-X> sounds good to me. It would be great if it's configurable.

**Comment by liuchengxu** [comment]
The performance of vim-clap has been greatly improved if you installed the `maple` binary, no slowness any more, so I'm going to close this issue.
