### ISSUE TITLE
Do not use exact searching for fzf (buffers)

### ISSUE THREAD

**Issue by phaazon** [liuchengxu/vim-clap#158]
**Is your feature request related to a problem? Please describe.**
Currently, `:Clap buffers` expect the input string to be an _exact match_. It makes it impossible to refine a search when we have lots of open buffers.

**Describe the solution you'd like**
Imagine we have the following:

![Screenshot 2019-12-12 at 11 00 22](https://user-images.githubusercontent.com/506592/70702579-a678d980-1cce-11ea-91a6-977c0497b4ef.png)

I would like to be able to select one `CMakeLists.txt` file. So I type `cmak` and get this:

![Screenshot 2019-12-12 at 11 00 34](https://user-images.githubusercontent.com/506592/70702633-d32cf100-1cce-11ea-9999-b34b741c456f.png)

Because I have lots of alternatives, I would like to refine my search. A typical and _lovely_ way to do that is to press space and add more items. Let’s say, `lib`.

![Screenshot 2019-12-12 at 11 00 38](https://user-images.githubusercontent.com/506592/70702709-fce61800-1cce-11ea-8df2-83c85dd33492.png)

As you can see, the problem here is that I get no match.

**Describe alternatives you've considered**
[fzf.vm](https://github.com/junegunn/fzf.vim) does the right thing thing for this.

**Additional context**
- Tested on macOS Mojave 10.14.6 and Archlinux (latest kernel).
- `neovim-0.5.0`.

**Comment by liuchengxu** [comment]
Hmm, why not just continue the input? I believe `cmaklib` can also get you the similar results as the match is fuzzy anyway.

Essentially, the built-in fuzzy filter in vim-clap uses the fzy algorithm written in Python https://github.com/liuchengxu/vim-clap/blob/master/pythonx/clap/fzy_impl.py . At present, vim-clap just feeds `cmak lib` into the fzy and return the filtered results. I believe fzy does not have the _substring_ support then. A quick solution is to split these substrings on clap side and then apply the fzy filter continously.

**Comment by phaazon** [comment]
Is there a way to use `fzf` instead? That would basically solve my issue right away.

**Comment by liuchengxu** [comment]
No built-in `fzf` fuzzy filter. You have to use the external `fzf` filter, try `:Clap! buffers ++ef=fzf`. The drawback of external filter is a async job, which would cause a redraw.

I just realized that there is a glitch about the fuzzy matched items highlights for the built-in fzy filter. I'll do a fix soon :(.

**Comment by phaazon** [comment]
Yeah with `fzf` it glitches. :/

**Comment by liuchengxu** [comment]
Please pull the latest commit https://github.com/liuchengxu/vim-clap/commit/b417c5cd295cf6213b2e033e8ee9468692e7296f, the built-in fuzzy matched item highlight should have been fixed, just in case you use the built-in fzy filter for `buffers` again.

The redraw of async job is unfortunately unavoidable, hence I'm trying the improve the performance of built-in Python filter, see also #146 and #147. Any help would also be appreciated.

**Comment by liuchengxu** [comment]
I have shamelessly borrowed the `substr_scorer` from the  same author of Python fzy impl in #159. Let me know if you have more ideas.
