### ISSUE TITLE
Clap doesn't find file with partial inputs

### ISSUE THREAD

**Issue by L-Vim** [liuchengxu/vim-clap#16]
**Environment:**

 - OS: Ubuntu 16.04
 - Neovim version: 0.4
 - vim-clap version: c469dd09ab17bd60d2 (2nd October 12:32 PM CEST)

**Describe the bug**

When looking for a file `LocalInterface` with partial characters contained in that name, matches are no found.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/plugged/vim-clap
filetype plugin indent on
syntax on
set hidden
```

2. Create file `LocalInterface`:

```sh
touch LocalInterface
```

3. Start neovim with command: `nvim -u min.vim`

4. Type `:Clap files`

5. In Clap prompt window, type `loin`.

6. File `LocalInterface` doesn't appear, instead no matches are found.

**Expected behavior**

File is found when searching with partial characters; as in FZF.

**Comment by liuchengxu** [comment]
First of all, vim-clap is not essentially a fuzzy finder, but a more generic filter and dispatcher. Currently only the substring fuzzy filter is available for sync providers, see README, thus `loin` won't find what you want, try `lo in` for now. More fuzzy filter mode will be added, and PR is welcome.

**Comment by liuchengxu** [comment]
@L-Vim If using macOS or Linux, you can try https://github.com/liuchengxu/vim-clap/pull/18 for new fuzzy finders support: fzy and fzf. But you have to run the sync provider using `source_async`, e.g., `:Clap files ++externalfilter=fzy +async`.  But it also has some drawbacks, see #17. Any feedback is appreciated.

**Comment by L-Vim** [comment]
Here is how I tested it.

vim-clap version: bf8effb7c759797e345f57261192cae940110e28 of branch `validator-registration-info`.

**Testing with `:Clap files ++externalfilter=fzf +async` or `:Clap files +async` and previous minimal vimrc**.

1. In a directory containing file `LocalInterface`, no files are displayed:

![image](https://user-images.githubusercontent.com/16366403/66191276-44787400-e68e-11e9-9e1f-a15eb70d31e9.png)

When typing the first letter of `LocalInterface`, message `NO MATCHES FOUND` immediately appears.

2. When testing with a git repo (e.g. my dotfiles repo), no files are displayed at first, like above screenshot. Files only appear after having typed a letter that is contained in the files' name:

![image](https://user-images.githubusercontent.com/16366403/66192064-fbc1ba80-e68f-11e9-8052-2dc128a0c2d2.png)

3. This is the result of searching for file `plugins_settings.vim` with input `insvim`:

![image](https://user-images.githubusercontent.com/16366403/66192574-0fb9ec00-e691-11e9-8028-bd906c1e5b4a.png)

**Now testing with `:Clap gfiles ++externalfilter=fzf +async` or `:Clap gfiles +async`, previous minimal vimrc and my dotfiles repo (https://github.com/L-Vim/dotfiles)**:

1. When using `:Clap gfiles +async` (or `:Clap gfiles ++externalfilter=fzf +async`), no files are displayed at first, but after having typed a letter and deleting it, every file is displayed as expected:

![image](https://user-images.githubusercontent.com/16366403/66192440-c23d7f00-e690-11e9-9d0c-8531f66142e0.png)

2. This is the result of searching for file `plugins_settings.vim` with input `insvim`:

![image](https://user-images.githubusercontent.com/16366403/66193417-c66a9c00-e692-11e9-80b0-9a67601ce078.png)

**Comment by liuchengxu** [comment]
For https://github.com/liuchengxu/vim-clap/pull/18/commits/bf8effb7c759797e345f57261192cae940110e28 only `Clap files +async` and `Clap blines +async` works. The other providers have not been checked. Furthermore, not all sync providers support `async` feature, like `Clap buffers`, it's unworthy.

When you run `Clap files +async` at the first, the display window is empty, that is expected. But now I think it could be improved via fetch all the items without any filtering.

>This is the result of searching for file plugins_settings.vim with input insvim:

I believe that how fzf works, you can try other fuzzy filters if you are unsatisfied with filtered result.

**Comment by liuchengxu** [comment]
@L-Vim Please try https://github.com/liuchengxu/vim-clap/pull/18/commits/d88b7014ee50f77071a88714aef284f29d27aa06 . I have improved a lot, now basically everything could be async!  Now you could use `Clap!` to tell vim-clap to try run async, e.g, `:Clap! blines`. Of source, `+async` also works, it's equal to `:Clap!`.
