### ISSUE TITLE
find_git_root doesn't work for submodules

### ISSUE THREAD

**Issue by gitbugr** [liuchengxu/vim-clap#164]
**Environment (please complete the following information):**
 - OS: Mac OS 10.15.1
 - (Neo)Vim version: NVIM v0.5.0-nightly-851-g6e8c5779c
 - vim-clap version: a2ee49ec87197dd90c4924563e6c476c8448e798
 - Have you reproduced with a minimal vimrc: n/a

**Describe the bug**
for git submodules, the `.git/` folder is actually a file. 

**To Reproduce**

1. Use any vim-clap configuration.

2. Create a git project `git --init`

3. Pull in your git submodule `git submodule add https://github.com/liuchengxu/vim-clap`

4. Pull in another git submodule `git submodule add https://github.com/liuchengxu/vim-which-key`

5. cd into the submodule you want to work on `cd vim-clap`

6. Open vim and search for a file `Clap files` - you will notice files from your other submodule

7. Check the git root `echo clap#util#find_git_root(g:clap.start.bufnr)` - the root is the parent repo. This is wrong.

**Expected behavior**
The git root should point to your submodule.

To fix this temporarily, I replaced the usages of `clap#util#find_git_root(g:clap.start.bufnr)` in _autoload/clap/rooter.vim_ with the old `clap#util#get_git_root()`

**Comment by liuchengxu** [comment]
Seemingly it's not easy to find the git root manually, even though that could be much faster than using the system call. If so, I think we should just stick to `clap#util#get_git_root()`, which talks about 200ms on my machine, I can live with that.

**Comment by liuchengxu** [comment]
Please [this branch](https://github.com/liuchengxu/vim-clap/tree/rewrite-find-git-root) fixes this issue, @gitbugr . I borrowed the strategy of vim-rooter, hoping that's robust enough, at least for the submodule case :(.
