### ISSUE TITLE
default light colorscheme

### ISSUE THREAD

**Issue by gilligan** [liuchengxu/vim-clap#170]
While providing/maintaining multiple colorschemes is understandably a lot of work it would be great if at least there were at least 2 options: 

- *dark* colorscheme
- *light* colorscheme

Right now when I try to use `vim-clap` in my solarized-light theme it is basically not usable. Of course I understand that it is possible to modify the colors but i'm frankly really bad at this.

Maybe this repository could provide either one preset for dark/light as mentioned above or at least some suggestions on how to adjust it for light backgrounds.

![](https://i.ibb.co/hCL2T9V/Selection-001.png)

**Comment by liuchengxu** [comment]
vim-clap merely reuses the colors of your colorscheme, but there is no guarantee that these picked colors all look good. Checkout https://github.com/liuchengxu/vim-clap#change-highlights and #30 for the colors customization.
