### ISSUE TITLE
Installing via minpac

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [liuchengxu/vim-clap#182]
**Environment:**
 - OS: Arch Linux
 - (Neo)Vim version: NVIM v0.4.3
 - vim-clap version: pulled after [commit 130](https://github.com/liuchengxu/vim-clap/commit/997f60aedb93c0b4cfa09cc96c97e86fc8a32b4c)
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
Failure to install and run clap_build_all

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
syntax on
filetype plugin indent on
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})
if executable('sk') && executable('fzy')
	if executable('cargo')
		call minpac#add('liuchengxu/vim-clap', {'do': function('clap#helper#build_all')})
	else
		call minpac#add('liuchengxu/vim-clap', {'do': function('clap#helper#build_maple')})
	endif
elseif executable('cargo')
	call minpac#add('liuchengxu/vim-clap', {'do': function('clap#helper#build_rust_ext')})
else
	call minpac#add('liuchengxu/vim-clap')
endif
packloadall
```

2. Start neovim with command: `nvim -u min.vim`

3.  See error

```vim
function minpac#update[2]..minpac#impl#update[35]..<SNR>105_update_single_plugin[71]..<SNR>105_start_job[2]..<SNR>106_o
n_exit[4]..<SNR>105_job_exit_cb[74]..<SNR>105_invoke_hook, line 12
Vim(call):E117: Unknown function: clap#helper#build_all
```

**Expected behavior**
minpac to install vim-clap and run clap#helper#build_all()

running `:call clap#helper#build_all()` after installing vim-clap returns  
`Unknown function: clap#helper#build_all`. However if I exit neovim, reopen neovim, and run the same `:call clap#helper#build_all()` it runs the function and cargo builds the binary. 

This could be an issue with minpac but this is the only plugin I have this particular issue with.

**Comment by liuchengxu** [comment]
You should report to minpac then, I'm not familiar with it. BTW, you could simply use:

```vim
call minpac#add('liuchengxu/vim-clap', {'do': function('clap#helper#build_all')})
```

The rust extension of vim-clap does not rely on the `sk` and `fzy` executable, but uses their algorithms. `clap#helper#build_all()` will exit automatically and prompt the missing info if `cargo` executable is not found.
