### ISSUE TITLE
Clap files only show files which are in the same directory of current buffer

### ISSUE THREAD

**Issue by mnrce** [liuchengxu/vim-clap#194]
**Environment (please complete the following information):**
 - OS: Ubuntu 16.04
 - (Neo)Vim version: NVIM v0.5.0-278-g22a92a59a (AppImage)
 - vim-clap version: 258c2b3
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
`:Clap files` only show files which are in the same directory of current buffer, not all files in the current working directory, and in this case, when I open a file, I only see an empty buffer.

**To Reproduce**
0. Here is the structure of the test project and content of each file:
![image](https://user-images.githubusercontent.com/13317164/71638976-7fe00a00-2ca0-11ea-850d-5546b6d59360.png)

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `nvim main.cpp -u min.vim`

3. Type `:Clap files`, open a file inside another folder, type `:Clap files` again.

4. Only file in the same directory of current buffer are shown, in this case when open another file, only see an empty buffer.

**Expected behavior**
`Clap files` should show all file in the current working directory.

**Screenshots**
Here is a gif that demonstrates my problem:
![a](https://user-images.githubusercontent.com/13317164/71639080-3e505e80-2ca2-11ea-97db-86d38aa8e9b8.gif)

Edit: I got this issue after running  `:PlugUpdate` on `2019/12/30`, it's been a long time since  I ran update so I don't know which commit(s) introduce this. I will try to bisect when I have time.

**Comment by liuchengxu** [comment]
Try this patch:

```diff
diff --git a/autoload/clap/rooter.vim b/autoload/clap/rooter.vim
index a4d81a0..6142430 100644
--- a/autoload/clap/rooter.vim
+++ b/autoload/clap/rooter.vim
@@ -35,7 +35,7 @@ function! clap#rooter#working_dir() abort
   else
     let git_root = clap#util#find_git_root(g:clap.start.bufnr)
     if empty(git_root)
-      let dir = expand('#'.g:clap.start.bufnr.':p:h')
+      let dir = getcwd()
     else
       let dir = git_root
     endif
```

I believe we should just use the current working directory if no git base directory is found.

**Comment by mnrce** [comment]
> Try this patch:
> 
> ```diff
> diff --git a/autoload/clap/rooter.vim b/autoload/clap/rooter.vim
> index a4d81a0..6142430 100644
> --- a/autoload/clap/rooter.vim
> +++ b/autoload/clap/rooter.vim
> @@ -35,7 +35,7 @@ function! clap#rooter#working_dir() abort
>    else
>      let git_root = clap#util#find_git_root(g:clap.start.bufnr)
>      if empty(git_root)
> -      let dir = expand('#'.g:clap.start.bufnr.':p:h')
> +      let dir = getcwd()
>      else
>        let dir = git_root
>      endif
> ```
> 
> I believe we should just use the current working directory if no git base directory is found.

The patch fixed it for me, thanks.

Is there any configuration to make `clap` always use the cwd even if there is a git base directory?

**Comment by liuchengxu** [comment]
Always use the cwd:

```vim
let g:clap_disable_run_rooter = v:true
```
