### ISSUE TITLE
A weird blue square on top of floating window

### ISSUE THREAD

**Issue by kovetskiy** [liuchengxu/vim-clap#197]
- OS: Arch Linux
 - (Neo)Vim version: NVIM v0.5.0-141-gf79369d42
 - vim-clap version: 10b97ebb327719418c62b6ac5da244a4c51a48f0
 - Have you reproduced with a minimal vimrc: tried, didn't reproduce

There is a big weird blue box on top of the floating window, please see the screenshot.
I was not able to reproduce the problem on minimal vim setup, it works fine there.

Do you have any idea what I should check in my setup? I appreciate any input for fixing the problem.

**Screenshots**
![last](https://user-images.githubusercontent.com/8445924/71644410-ee40be80-2cd8-11ea-8808-7cfe2d17722b.png)

**Comment by liuchengxu** [comment]
You need to find these plugins related in your vimrc by commenting out the others to see if the problem persists using the binary search method. It looks like another floating window, use `<C-W>W` to see if you can jump to that window, see `:echo getbufinfo()` and close it manually.

**Comment by agriffis** [comment]
For what it's worth, I'm seeing the same thing:

![image](https://user-images.githubusercontent.com/50637/71672699-c0915f00-2d44-11ea-9969-f3f394b94b5d.png)

**Comment by agriffis** [comment]
@kovetskiy Do you have `winheight` set? For me that was the culprit.

**Comment by liuchengxu** [comment]
You should shorten your vimrc to find which plugins are related then. Seemingly not an issue of vim-clap itself.

**Comment by liuchengxu** [comment]
If the final culprit is `winheight`, we can reset it in vim-clap and then restore when the vim-clap window is closed.

**Comment by kovetskiy** [comment]
The root problem was the autoresize plugin that calls `resize` and `vertical resize` on `WinEnter` event.

https://github.com/kovetskiy/vim-autoresize/blob/master/autoload/autoresize.vim
