### ISSUE TITLE
Open files horribly broken on master

### ISSUE THREAD

**Issue by dharrigan** [liuchengxu/vim-clap#199]
**Environment (please complete the following information):**
 - OS: Linux
 - (Neo)Vim version: NVIM v0.4.3
 - vim-clap version: master (and also v0.3)
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
With the latest on master, if I do `<leader>f` which is mapped to `nmap <silent> <Leader>f :Clap files --hidden<CR>` to find files, then select a file and open, window goes blank and I can't move the cursor around. I have to quit out of VIM.

Reverting to v0.3 of vim-clap does not reproduce this behaviour.

**Comment by liuchengxu** [comment]
I can't reproduce. Do the other providers work well? Have you tried recompiling the Rust extension?

**Comment by dharrigan** [comment]
Hi,

I'll flip back to master and give it a try.

**Comment by dharrigan** [comment]
Hi,

So, I'm back on master, did a plug clean beforehand then a plug update. I can edit a file directly such as `vim /foo/bar/baz.clj`. Then, I tested using the files and grep providers and it just seems broken now. Files exhibits the behaviour as before, even grep fails, yet on v0.3 all is well.

Using git bisect, I've tracked it down to this commit:

`10b97ebb327719418c62b6ac5da244a4c51a48f0`

Anything before that commit works, anything after that commit fails.

I can't rebuild the rust extension, as I get this error:

```
\033[1;34m==>\033[0m Trying to build rust extension
error: no such subcommand: `+nightly`
make[1]: *** [Makefile:18: run-cargo] Error 101
make[1]: Leaving directory '/home/david/.env/vim/bundle/vim-clap/pythonx/clap'
make: *** [Makefile:7: rust-ext] Error 2
```

**Comment by liuchengxu** [comment]
It's ok to skip building the python dynamic module.  Use `:call clap#helper#build_maple()` for building the external binary only.

https://github.com/liuchengxu/vim-clap/commit/10b97ebb327719418c62b6ac5da244a4c51a48f0 is to add icon support for files provider and should not affect the other providers. Can you post the minimal vimrc you used and screencast the error?

**Comment by dharrigan** [comment]
I think I will mark it as fixed - as rebuilding the rust extension has made the issue go away.

**Comment by liuchengxu** [comment]
Thanks for confirming. I'll improve the helper function and error message later.
