### ISSUE TITLE
No such file or directory: 'setup_python.py'

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#200]
**Environment (please complete the following information):**
 - OS: MacOS
 - Vim version: 8.2
 - vim-clap version: master

**Describe the bug**
When trying to filter files, VIM shows the following error:

```
vim-clap: Vim(py3file):FileNotFoundError: [Errno 2] No such file or directory: 'setup_python.py'
```

Fuzzy search doesn't work as a result. I also can see the `setup_python.py` exist in the plugin directory.

**To Reproduce**
Run `:Clap files`, you can see the error message in `:messages`.

**Comment by arashm** [comment]
I change the path in `autoload/clap/filter.vim:132` to an absolute path, and it's working again

```viml
execute s:pyfile '/Users/arash/.vim/plugged/vim-clap/setup_python.py'
```

Not sure if it's a vim 8.2 issue or something on Mac. Will check this out later at home on my Linux system.

**Comment by liuchengxu** [comment]
Maybe we could just use the absolute path for `setup_python.py`. I also did see this error before, but it somehow just gone and I never see it again.

**Comment by alerque** [comment]
This is the bit of python that I moved out of the heredoc into a file. It shouldn't need an absolute path, but it might need a relative path based on the script being run. Perhaps this has something to do with VIM's search path when cd'ed into somewhere else or using different plugin managers?

**Comment by liuchengxu** [comment]
Can you see if #201 resolves this issue? @arashm 

Not sure why this issue happened occasionally, but it's ok to use the absolute path if it does help, let's just use that then. @alerque .

**Comment by arashm** [comment]
> Can you see if #201 resolves this issue? @arashm

That works fine for me 👍
