### ISSUE TITLE
Opening multiple files with :Clap files wrongly increases buffer numbers

### ISSUE THREAD

**Issue by runar** [liuchengxu/vim-clap#203]
**Environment (please complete the following information):**
 - OS: MacOS 10.15.2
 - Vim version: vim 8.1
 - vim-clap version: master (cb76765)
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When opening multiple files with `:Clap files`, by running the command for each file, the buffer number of the second file is increased to 7. The third file is given the number 8. This causes `:Clap buffers` to only list the first file.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Use `:Clap files` to open a random file.

4. Use `:Clap files` to open a second random file.

5. Run `:buffers` to confirm that the buffer numbers are not incremental, but that all buffers are listed.

6. Run `:Clap buffers` to confirm that only the first file/buffer is listed.

**Expected behavior**
I believe there are two different bugs here: First, the second file/buffer should be given the buffer number 2. Secondly, `:Clap buffers` should list all buffers regardless of «missing» buffers.

**Additional context**
Opening the same two files with `:e` correctly increases the buffer numbers, eliminating this issue.

**Comment by liuchengxu** [comment]
The buffer number is assigned by vim itself, not by vim-clap, I don't see any problem. Showing the listed buffers is expected, that's how it's designed.

**Comment by runar** [comment]
I believe you misunderstood my bug report, so I’ll add some screenshots here to clarify.

I have a test directory with two files: file1.txt and file2.txt. If I open these files in vim using the `:edit` command (e.g. `:edit file1.txt`), `:buffers` will output the following:

![buffers-1](https://user-images.githubusercontent.com/189879/71700743-004c5b00-2dc6-11ea-920d-ef16d0bc8b7e.png)

And `:Clap buffers` will list both files/buffers:

![clap-buffers-1](https://user-images.githubusercontent.com/189879/71700755-0e01e080-2dc6-11ea-9591-10e2f854f0c3.png)

If I open the same files by running `:Clap files` and selecting the files (run the command twice, once for each file), then `:buffers` outputs the following (notice how `file2.txt` is suddenly buffer number 7):

![buffers-2](https://user-images.githubusercontent.com/189879/71700776-27a32800-2dc6-11ea-8694-9edc73d6b0f2.png)

And `:Clap buffers` only lists the first file/buffer:

![clap-buffers-2](https://user-images.githubusercontent.com/189879/71700785-2eca3600-2dc6-11ea-9e12-6d2a849d1d38.png)

Do you see the issue now?

Might this have anything to do with how popup windows are created, and the fact that they are buffers?

**Comment by liuchengxu** [comment]
Every window has to associate with some buffer, so does the popup, hence there is no problem with the buffer number increased.

**Comment by runar** [comment]
If there is no problem, then why does `:Clap buffers` only list the first buffer? Shouldn’t it list the same as `:buffers`?

**Comment by liuchengxu** [comment]
I can't reproduce the missing buffer. It should be the same with `:buffers`, ensure you used the minimal vimrc.

**Comment by runar** [comment]
I’m using the minimal vimrc, and I have the same issue regardless of the number of buffers I open. This started happening today, so I’ll roll back to an earlier version and see if that changes anything. I’ll let you know shortly.

**Comment by liuchengxu** [comment]
You could also check `:echo g:clap.provider._().source()` when or after opening vim-clap with `:Clap buffers`. The output should contain all the buffers. If it's not, then there is a problem.

**Comment by runar** [comment]
Thank you! The output does indeed contain all buffers (some whitespace removed by me):

```
['[8]  file3.txt #', '[7]   7B  file2.txt', '[1]   7B  file1.txt', '[9]  file4.txt %’]
```

However, `:Clap buffers` still only lists the first buffer (file1.txt), and searching for one of the other buffers gives me «NO MATCHES FOUND». Do you have any other suggestions?

This is all done using the minimal vimrc, and no other plugins or settings are loaded.

**Comment by liuchengxu** [comment]
Not sure, but you can try upgrading your vim to the latest version to see if that helps.

**Comment by liuchengxu** [comment]
It's an issue of vim, see https://github.com/vim/vim/issues/5335, upgrade your vim to the latest version.

**Comment by runar** [comment]
I confirm that upgrading vim (using Homebrew, the most recent version at this time is version 8.2.0050) solves this issue.
