### ISSUE TITLE
buffers provider with no buffers open has an error

### ISSUE THREAD

**Issue by wbthomason** [liuchengxu/vim-clap#213]
**Environment:**
 - OS: Arch Linux
 - (Neo)Vim version: Neovim `master`
 - vim-clap version: `master`
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
Running `:Clap buffers` with no buffers open causes a list index out of range error in the line `bufs[1:] + [bufs[0]]`

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim` and **no buffers open**

3. Run `:Clap buffers`

**Expected behavior**
No error should be caused.

**Comment by liuchengxu** [comment]
How did you open nvim without any buffer?

**Comment by wbthomason** [comment]
Oh, I'm sorry - I messed up when testing, and my "minimal vimrc" was not truly minimal. I forgot to use the `--noplugin` flag, so `vim-startify` loaded. With this plugin loaded, it is possible to have `buffers` return an empty list.

The line that causes the bug is https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/buffers.vim#L43; I'd be happy to make a PR to fix this, particularly as I made a mistake in my initial report.

**Comment by liuchengxu** [comment]
Feel free to open up a PR, the fix should be trivial, I'm just curious about your original report :(.

**Comment by wbthomason** [comment]
I use the native packages feature to load plugins, so I forgot that `vim-startify` would be loaded even if I used the minimal vimrc and `nvim -u min.vim`. That means that the minimal vimrc wasn't all that was loaded - some plugins did too, which made the error possible.

With that, I get the following:

Showing that `:buffers` is empty:
![vim1](https://user-images.githubusercontent.com/3729908/71775396-5fd57280-2f4e-11ea-86af-ee54d81ae8d9.png)

Showing the error:
![vim2](https://user-images.githubusercontent.com/3729908/71775402-754a9c80-2f4e-11ea-8ddf-da88d6400a20.png)

I'm making the PR now!
