### ISSUE TITLE
Add to jump list when using `blines`

### ISSUE THREAD

**Issue by marcusbuffett** [liuchengxu/vim-clap#220]
**Is your feature request related to a problem? Please describe.**
Often what I'm trying to do with blines is to search for a line, jump to it, copy something, then jump back. I'm used to Ctrl-o popping me back to where I was, but it seems vim-clap doesn't interact nicely with the jump list.

**Describe the solution you'd like**
It would be nice if after jumping somewhere with blines, my previous location would be added to the jump list

I don't have a good understanding of how the jump list works or if it's easy to interact with, but I know easymotion does something like this, so it should be possible. Also maybe this makes sense to do for all vim-clap sources, just talking about blines because that's been the pain point for me personally.

**Comment by liuchengxu** [comment]
Try #227.

**Comment by marcusbuffett** [comment]
Works perfectly, thank you!
