### ISSUE TITLE
It seems vim-prosessions break internal/previous buffer, and cause errors to vim-clap

### ISSUE THREAD

**Issue by markwu** [liuchengxu/vim-clap#228]
**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - (Neo)Vim version: NeoVim git master head
 - vim-clap version: vim-clap git master head
 - Have you reproduced with a minimal vimrc: ??? Yes

**Describe the bug**
I try to write a provider to integrate with vim-prosession, here comes my implementation

```vim
# autoload/myvim/clap.vim
function! myvim#clap#Prosessions(...)
    let flist = glob(fnamemodify(g:prosession_dir, ':p').'*.vim', 0, 1)
    let flist = map(flist, "fnamemodify(v:val, ':t:r')")
    let flist = map(flist, "substitute(v:val, '%', '/', 'g')")
    return flist
endfunction

# plugin/clap.vim
let g:clap#provider#prosessions# = {
            \   'source': function('myvim#clap#Prosessions'),
            \   'sink': 'Prosession'
            \ }
```
It works very well, I can selection session and open session until I try to switch buffer with `Clap buffers`

![螢幕快照 2020-01-12 下午3 37 38](https://user-images.githubusercontent.com/196861/72215775-b8aa9980-3552-11ea-9ab6-ec38a1fd99f3.png)

It just show me an error, and popup a window with current buffer not buffer list.

```vim
處理 function clap#[35]..clap#for[20]..clap#floating_win#open[4]..62 時發生錯誤:
行    1:
E5555: API call: Invalid buffer id
Press ENTER or type command to continue
```

It seems `prosession` plugin kill all current buffers and load all new buffers from session. And clap can not find previous buffer to return.

**To Reproduce steps**

![vim-clap](https://user-images.githubusercontent.com/196861/72216788-90c23280-3560-11ea-82c6-6bb67697c0dd.gif)

**My minimal vimrc**
```vim
set nocompatible
filetype off

execute 'source ~/.vim/bundle/vim-plug/plug.vim'
call plug#begin('~/.vim/bundle/')

Plug 'junegunn/vim-plug'

" Put your bundle below here
Plug 'tpope/vim-obsession'
Plug 'dhruvasagar/vim-prosession'
Plug 'liuchengxu/vim-clap'
" Put your bundle above here

call plug#end()

syntax on
filetype plugin indent on

" Put your plugin settings below here

" autoload/myvim/clap.vim
function! Myprosessions(...)
    let flist = glob(fnamemodify(g:prosession_dir, ':p').'*.vim', 0, 1)
    let flist = map(flist, "fnamemodify(v:val, ':t:r')")
    let flist = map(flist, "substitute(v:val, '%', '/', 'g')")
    return flist
endfunction

" plugin/clap.vim
let g:clap#provider#prosessions# = {
            \   'source': function('Myprosessions'),
            \   'sink': 'Prosession'
            \ }

map <space>s :Clap prosessions<CR>
map <space>b :Clap buffers<CR>
" Put your plugin settings above here

```

**Expected behavior**
No error messages. Change buffers without problems.

**Comment by liuchengxu** [comment]
Please fill the issue template.

**Comment by markwu** [comment]
@liuchengxu  Okay, I just modify the format and give you a minimal vimrc later.

**Comment by markwu** [comment]
@liuchengxu Done.

**Comment by markwu** [comment]
I tried in vim (git master head), it seems okay.

**Comment by liuchengxu** [comment]
Check if #229 helps.

**Comment by markwu** [comment]
Tested, it works now. Thanks!!
