### ISSUE TITLE
vim-clap command :Clap tags will hangs neovim forever when there are no tags information.

### ISSUE THREAD

**Issue by markwu** [liuchengxu/vim-clap#230]
**Environment (please complete the following information):**
 - OS: macOS 10.14.6
 - (Neo)Vim version: NeoVim git master head
 - vim-clap version: vim-clap git master head
 - vista.vim version: vista.vim git master head

**Describe the bug**
vim-clap command `:Clap tags` will hangs neovim forever when there are no tags information.

**To Reproduce steps**

![vim-clap](https://user-images.githubusercontent.com/196861/72219902-215f3980-3586-11ea-8e6b-0d26e0f373bd.gif)

The only way to exit neovim is to quit terminal application or kill it from command line.

**My minimal vimrc**
```vim
set nocompatible
filetype off

execute 'source ~/.vim/bundle/vim-plug/plug.vim'
call plug#begin('~/.vim/bundle/')

Plug 'junegunn/vim-plug'

" Put your bundle below here
Plug 'liuchengxu/vim-clap'
Plug 'liuchengxu/vista.vim'
" Put your bundle above here

call plug#end()

syntax on
filetype plugin indent on

" Put your plugin settings below here

" Put your plugin settings above here
```

**Expected behavior**
No hangs.

**Comment by liuchengxu** [comment]
Update vista.vim to https://github.com/liuchengxu/vista.vim/commit/221893d85d2e8ed5ec51da12bf23d2e5bada57cf
