### ISSUE TITLE
Bad return from provider

### ISSUE THREAD

**Issue by meck** [liuchengxu/vim-clap#234]
**Environment (please complete the following information):**
 - OS: macOs
 - (Neo)Vim version: 0.4.3
 - vim-clap version: Head
 - Have you reproduced with a minimal vimrc: yes

Im having trouble with a provider I wrote, its calling out to `hoogle` and returning haskell function definitions. when use `clap#dispatcher#job_start()` the results are missing a lot of entries and not returning the top ones. But if I use `maple` with the same command all is well.

[Minimal version of the provider](https://gist.github.com/meck/7c17d44061b51a0fd06bf06d35e7f8d4) It feels like something is not escaped maybe vim script is not a strongpoint for me.

### Correct output (maple):
<img width="1062" alt="Skärmavbild 2020-01-13 kl  15 21 26" src="https://user-images.githubusercontent.com/762115/72263173-a2671100-3618-11ea-98cd-62f8a448be17.png">
### Bad Output:
<img width="1062" alt="Skärmavbild 2020-01-13 kl  15 20 49" src="https://user-images.githubusercontent.com/762115/72263196-b14dc380-3618-11ea-89e0-b147300a6b41.png">

**Comment by liuchengxu** [comment]
Does this issue happen just recently? If so, can you see which commit could be the culprit?

**Comment by meck** [comment]
I did a bisect and it seems the issue was introduced in b1fda940803dd45de0ad7e9687931fec053df944

**Comment by liuchengxu** [comment]
See if #237 fixes this issue.

**Comment by meck** [comment]
Yes, looks good!
