### ISSUE TITLE
Show history when input is empty

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#235]
**Describe the solution you'd like**
When doing `:Clap files` or `:Clap grep`, many times I find myself wanna do the same search as the one I already did to select a different result, for that I need to type the whole input again. It could be cool if Clap could show a list of 10 previous searches when the input is empty, and we could just select it from the list.

**Comment by liuchengxu** [comment]
My original plan is to use `<C-N>`/`<C-P>` for navigating the input history, that could make type the same search easier.

**Comment by svermeulen** [comment]
@liuchengxu is input history available yet as a feature?  `<c-n>` / `<c-p>` does not currently seem to do this

**Comment by liuchengxu** [comment]
Still unimplemented, not a priority for me. PR welcome.

**Comment by mtuzinskiy** [comment]
I miss this feature in vim-clap, would be great to have it

**Comment by liuchengxu** [comment]
Sorry for taking so long on this issue, for the simplicity, a new provider can be added for such a purpose. Could you try this branch https://github.com/liuchengxu/vim-clap/tree/input-history-provider? @arashm @svermeulen @mtuzinskiy It's not complete, but we're starting somewhere anyway. Now you can invoke `:Clap input_history` to show the last 20 queries, and rerun the last _normal_(anyone but not `input_history` and `providers` provider) provider with that query. The future work could be make a decision if we want to show this history whenever the input is empty for any providers or just the `input_history` provider.

**Comment by arashm** [comment]
That's great news @liuchengxu. Will try out that branch today 💪

**Comment by arashm** [comment]
I recompiled the rust stuff, but I still get an empty window no matter what. Other providers I use, seems to be fine.

<img width="742" alt="Screenshot 2022-01-26 at 14 16 41" src="https://user-images.githubusercontent.com/849640/151179546-0d5a7c04-267c-4a4b-91ac-a2040be71e12.png">

**Comment by liuchengxu** [comment]
The input history provider does not require the Rust binary. The idea is to record each input in this provider and use these history inputs as the source and it's not yet persistent, you need to call other providers with queries first and then call the input history provider to resume some query against the last provider.

The whole design is not settled. I'm happy to have some feedback on the UX.

**Comment by liuchengxu** [comment]
@arashm I have pushed a new commit to fix the vim issue you just ran into, please pull the latest commit of that branch and try again. I didn't test Vim, only tested against NeoVim :(.

**Comment by arashm** [comment]
https://user-images.githubusercontent.com/849640/151187393-2135cd8b-1ae4-445e-adfb-53635c611e0c.mov

What am I missing? I did a grep and files.

In terms of UX, I find it easier if I see history of each provider, when I invoke that provider. For example, if I do a `Clap files!` now, I just see some random files at the beginning, before I start typing, preferably if this could be replaced with the history of previous files I open with `files` would be much easier. Same for `grep2`. Having another provider to invoke to get the history is a bit tedious.

**Comment by arashm** [comment]
Oh, I pull again, thanks. Maybe I have to switch to NewoVim too :(

**Comment by arashm** [comment]
Somehow worked now. But I say it's sorted reversed. It doesn't show anything more than the first 10.

<img width="245" alt="Screenshot 2022-01-26 at 15 14 46" src="https://user-images.githubusercontent.com/849640/151191061-a50ca6ef-33c8-436a-a36c-78ccc14aca86.png">

I guess why it shows the command like this is because filer searches stuff after each keypress.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-clap/blob/input-history-provider/autoload/clap/provider/input_history.vim#L8 the history size is limited right now, you can change it to a larger number temporarily. I just pushed another commit to reverse the order.

Basically, the history records the input whenever the query changes, but it does not mean the searching job will be started accordingly since we might use the debounce strategy for the performance reason.

**Comment by liuchengxu** [comment]
>before I start typing, preferably if this could be replaced with the history of previous files I open with files would be much easier. 

I don't quite follow. Can you make an example about what kind of files you'd like to show when the input is empty?

>Having another provider to invoke to get the history is a bit tedious.

I agree, but this is the easiest way to do it, haven't seen any other way to achieve a smooth experience with such trivial changes.

**Comment by arashm** [comment]
The sort is fixed. I have a combination like this in my config for grep:

```
nmap <silent> <leader>gg :Clap grep2 ++query=<cword><CR>
```

Invoking grep like this, won't show anything in the history, only if I manually type in grep window, it will appear in the history.

**Comment by liuchengxu** [comment]
>Invoking grep like this, won't show anything in the history, only if I manually type in grep window, it will appear in the history.

Pushed a new commit, should be fixed now.

**Comment by liuchengxu** [comment]
@arashm Another commit pushed, please try again. Seems to work on my machine this time.

**Comment by arashm** [comment]
Yep, it seems to be working fine now!

**Comment by mtuzinskiy** [comment]
Checked it on my NeoVim (I use Arch btw.), works as expected.

**Comment by liuchengxu** [comment]
Using `<C-N>`/`<C-P>` for navigating the input history as described in https://github.com/liuchengxu/vim-clap/issues/235#issuecomment-573955407 has been implemented in #903, feel free to try it, you need to compile the binary on your own for now.
