### ISSUE TITLE
Can't change background color of the pop window

### ISSUE THREAD

**Issue by delfick** [liuchengxu/vim-clap#236]
**Environment**
 - OS: Mac OSX Mojave
 - (Neo)Vim version:  NVIM v0.4.3
 - vim-clap version: latest (revision 451136aec49caffeff3d07f48d19007faeeae55f) - install with vim plug
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
I can't figure out how to change the background color of the popup window to be different than the background of my vim.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-clap'
Plug 'liuchengxu/vim-clap', { 'do': function('clap#helper#build_all') }
Plug 'iCyMind/NeoSolarized'

call plug#end()

set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types:h11

set termguicolors
set background=dark
let g:neosolarized_termtrans=1
colorscheme NeoSolarized

let mapleader=","
nmap <leader>a :Clap files<CR>
nmap <leader>q :Clap quickfix<CR>
nmap <c-p> :Clap buffers<CR>

hi default link ClapDisplay NeoSolarized
hi default link ClapInput   NeoSolarized
```
2: Open popup window

**Screenshots**

![image](https://user-images.githubusercontent.com/109301/72296743-79915b00-36ae-11ea-8edc-2fb225a0f3e0.png)

**Additional context**
I tried for a long time with different combinations of hi commands and I couldn't figure it out.

**Comment by liuchengxu** [comment]
`NeoSolarized` is not a valid highlight group. Try:

```vim
hi link ClapDisplay CursorLine
hi link ClapSpinner PmenuSel
hi link ClapInput   PmenuSel
```

and see `:h highlight-groups`.

**Comment by delfick** [comment]
I still get the same problem with those settings.

interestingly this works now

```
hi ClapDisplay2 guibg=#9ad9ff
hi default link ClapDisplay ClapDisplay2
```

I swear I tried it before and it wasn't working. sigh. Sorry for the noise

**Comment by delfick** [comment]
I got it much nicer

![image](https://user-images.githubusercontent.com/109301/72302050-e6abed00-36bc-11ea-8f93-b25f2f3dfc7d.png)


```
hi ClapInput2 guibg=#000000
hi link ClapInput ClapInput2

hi YellowAndBlack gui=bold guibg=#7a804d guifg=black
hi link ClapCurrentSelection YellowAndBlack 
hi link ClapNoMatchesFound YellowAndBlack
```

But I can't work out how to change the green color in the matches.

**Comment by liuchengxu** [comment]
`:h g:clap_fuzzy_match_hl_groups`

**Comment by delfick** [comment]
awesome, that worked :)

One last question, the color of the matches is controlled by `ClapFuzzyMatches[1-12]` ?

I'm confused by the `[1-12]` and setting this option doesn't seem to work.

i.e.

```
hi link ClapFuzzyMatches YellowAndBlack
```

Seems to make no difference.

**Comment by liuchengxu** [comment]
`ClapFuzzyMatche1`, `ClapFuzzyMatche2`...

With `g:clap_fuzzy_match_hl_groups`, you don' have to care about `ClapFuzzyMatches[1, 12]`, they are doing the same thing and it should be noted as the deprecated option.

**Comment by delfick** [comment]
I mean the white text in this

![image](https://user-images.githubusercontent.com/109301/72303603-e5c98a00-36c1-11ea-9426-a99c07429bb6.png)

**Comment by liuchengxu** [comment]
That's fg of `ClapDisplay`.

**Comment by delfick** [comment]
If I set say

```
hi ClapDisplay2 guibg=#003f66 guifg=#000000 ctermfg=black
hi default link ClapDisplay ClapDisplay2
```

The text remains white

**Comment by liuchengxu** [comment]
If some syntax ftplugin is enabled, the syntax of display buffer will override `ClapDisplay`. You can disable this behavior, but you'll lose the proper highlight then.

```vim
autocmd User ClapOnEnter call g:clap.display.setbufvar('&syntax', '')
hi ClapDisplay guibg=black guifg=red ctermbg=black ctermfg=red
```

**Comment by delfick** [comment]
hmm, in that minimal config I only have vim clap and NeoSolarized enabled

And NeoSolarized only has a colors directory in it.

Your line does work though

I'll give it a shot and see if I notice anything breaking.

Thanks!
