### ISSUE TITLE
chmod: cannot access 'bin/maple': No such file or directory  

### ISSUE THREAD

**Issue by LinArcX** [liuchengxu/vim-clap#239]
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Void-Linux
 - (Neo)Vim version: NVIM v0.4.3
 - vim-clap version: Release v0.4
 - Have you reproduced with a minimal vimrc: No

**Describe the bug**
I tried to install prebuilt binary version:
> " The bang version will try to download the prebuilt binary if cargo does not exist.
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary!' }

But it gave me this error:
>curl: (22) The requested URL returned error: 404 Not Found                                                                    │   27 Plug 'honza/vim-
  chmod: cannot access 'bin/maple': No such file or directory  

**To Reproduce**
1. Use vim-plug to install prebuilt binary version of vim-clap.

**Expected behavior**
Works without any issue.

**Comment by liuchengxu** [comment]
Please pull the latest commit and rerun `:Clap install-binary!`, v0.5 is just released.

**Comment by LinArcX** [comment]
Yes, thank you so much. it fixed.
