### ISSUE TITLE
How to set highlights of unselected items.

### ISSUE THREAD

**Issue by niumeng07** [liuchengxu/vim-clap#243]
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 12 2019 16:52:17)
macOS version
Compiled by Homebrew

![image](https://user-images.githubusercontent.com/12561180/72503120-eefb5800-3875-11ea-9935-50771e790ea3.png)
![image](https://user-images.githubusercontent.com/12561180/72503070-d1c68980-3875-11ea-9ded-43aed77e981e.png)

**Comment by liuchengxu** [comment]
- Use another colorscheme.
- `:h ClapDisplay` and `:h clap-highlights`.
- Disable the syntax higlight  completely via `autocmd User ClapOnEnter call g:clap.display.setbufvar('&syntax', '')`

**Comment by niumeng07** [comment]
`autocmd User ClapOnEnter call g:clap.display.setbufvar('&syntax', '')`
It works, thanks.
