### ISSUE TITLE
Feature request: open file like ivy-mode and findr.vim

### ISSUE THREAD

**Issue by hujianxin** [liuchengxu/vim-clap#245]
I want to find a plugin which can open file in the way of emacs ivy-mode, I found it today, it's name is findr.vim https://github.com/conweller/findr.vim

but, this plugin only works for neovim, it will be wonderful if i can use this funtion in clap. thanks

**Comment by liuchengxu** [comment]
Try #272, `:Clap filer`, the Rust binary `maple` is required, you have to compile it locally for now as no new release yet.

**Comment by hujianxin** [comment]
非常感谢你的付出。

遇到一个问题，如图
![image](https://user-images.githubusercontent.com/9526904/73323642-0f1e1480-4283-11ea-9ef6-495cb5f12474.png)
预期效果：
1. 在vim-clap目录下，有很多文件、文件夹
2. 我输入ci/之后，clap的输入会自动刷新，内容变成ci/这个目录下的内容（文件、文件夹）
3. 也就是说，vim-clap按理应该会实时判断是否输入/

**Comment by hujianxin** [comment]
![image](https://user-images.githubusercontent.com/9526904/73323825-b13dfc80-4283-11ea-969a-d260dc116b00.png)
Congratulate 😄

**Comment by liuchengxu** [comment]
The design is to press `<Tab>` to expand the directory, otherwise your input is to do the filtering on the entries under the current directory.

**Comment by hujianxin** [comment]
I test some cases, `<Tab>` works fine.

But add a `/` trigger besides `<Tab>` may not introduce too much ambiguity. It will be more perfect if there is this trigger, but if there's no, it's alse fine. Thanks again

**Comment by hujianxin** [comment]
Other question.

I ivy-mode and findr.vim, if there's no file matching, and user enter `enter` key, vim will create a new file.
