### ISSUE TITLE
Feature request: provider for `:hlep xxx`

### ISSUE THREAD

**Issue by LinArcX** [liuchengxu/vim-clap#247]
**Is your feature request related to a problem? Please describe.**
Hi, i think if we have a dedicated provider for `:hlep xxx` will be awesome.

**Describe the solution you'd like**
Although i found this provider [here](https://github.com/tamago324/vim-clap-help). But it hasn't preview for each page, like grep provider. And it's slow. because it should search between more than 10.000 search results, So i think we need some tweaks to make it faster and smoother.

Also i think this provider is very important and should be part of vim-clap as default providers.

**Comment by liuchengxu** [comment]
I believe you should send the feature request in https://github.com/tamago324/vim-clap-help.

**Comment by LinArcX** [comment]
If anyone knows how to implement this feature please send a PR.
I think it's better to have this as one of default providers in vim-clap.
