### ISSUE TITLE
Spell suggest provider

### ISSUE THREAD

**Issue by Olical** [liuchengxu/vim-clap#250]
I use `z=` a lot on badly spelled words to suggest a list of possible corrections, you _usually_ want the first one but sometimes you want something else. When you hit `z=` your entire screen is replaced by a huge list of possible items, this is kind of jarring if you're in the flow of things.

I think a provider that works like `z=` (spellings for the word under the cursor) within vim-clap would be a good fit for the UI / UX.

`spellsuggest({word} [, {max} [, {capital}]])` will be more than good enough for this provider since it returns a list of possible works. The provider will just have to pull the word from under the cursor and replace it if one is selected.

## Other considerations

`spellbadword()` could be used to jump to a poorly spelled word as the provider is invoked but maybe this is overkill. A user could compose that function call with vim-clap if they wanted to anyway.

**Comment by liuchengxu** [comment]
Sounds not hard since you already have the `source` and `sink`. Check out https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md if you are interested in making one. I don't use this function so I'm not going to do it myself.

**Comment by Olical** [comment]
Awesome sounds good! I'm more than happy to implement it, just wanted to get your approval of the idea first. Quite busy at the moment but have lots of free time coming up, will notify you when the PR is up :smile:

**Comment by Olical** [comment]
I'm not going to get around to this for a while, rather than clogging up the issues I'll close this one.

I gave it some more thought and I don't think it's a good fit for clap anyway. Most of the time the spell correction will all be very similar other than a few characters inside the word.

So you're mostly going to want the first result but sometimes a sparse result, say, the 12th suggestion. The best way to pick these is with a number rather than fuzzy text filtering, order is highly important in spell suggestions. I think `z=` with order maintained using numbers to select makes sense.

Maybe I'll change my mind some day!
