### ISSUE TITLE
List dedicated for own custom commands.

### ISSUE THREAD

**Issue by thepenguinthatwants** [liuchengxu/vim-clap#251]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when I need to search command history instead of just seeing few commonly used commands that I've defined in to a list

**Describe the solution you'd like**
Able to open a file that has own defined commands. That are not usually used to have keybinding but good enough to have a quick cheatlist.

**Comment by liuchengxu** [comment]
You can define your own provider with just a few lines. Here it the quick example:

```vim
let s:quick_cmd = {'ALEInfo': 'ALE debugging info', 'ALENext': 'ALE next error or warning'}

function! s:on_move() abort
  let curline = g:clap.display.getcurline()
  call g:clap.preview.show([s:quick_cmd[curline]])
endfunction

let g:clap_provider_quick_cmd = {
      \ 'source': keys(s:quick_cmd),
      \ 'on_move': function('s:on_move'),
      \ 'sink': { selected -> execute(selected, '')}
      \ }
```

Use `:Clap quick_cmd` to open it. Checkout https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md for details.

**Comment by thepenguinthatwants** [comment]
Hi thanks!

I seem to grasp a bit of your quick example. Can you elaborate more about what different lines do?

**Comment by liuchengxu** [comment]
Have you read https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md#create-non-pure-async-provider? I have explained the details ther, let me know if you have any more questions.

**Comment by thepenguinthatwants** [comment]
Hi!

Yes I read the documentation.

The thing I tried might be out of the scope.

I wanted to create a list of commands that I can choose from the list.

let g:clap_provider_commands= {
      \ 'source': ['codi!!', 'UltiSnipsEdit'],
      \ 'on_enter',
      \ }

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-clap/wiki/Examples#execute-custom-commands
