### ISSUE TITLE
Support for finding vim sessions

### ISSUE THREAD

**Issue by thepenguinthatwants** [liuchengxu/vim-clap#252]
It would be nice to have an ability to load saved vim sessions from a list from a folder that has being defined.

Otherwise nowadays controlling and opening sessions is kinda cumbersome.

**Comment by markwu** [comment]
I have one, but it works with vim-prosession/vim-obsession. If you think it okay, will shoot a PR.
![image](https://user-images.githubusercontent.com/196861/72868023-be0a9f80-3d1b-11ea-9c3f-552b1892fe08.png)

**Comment by markwu** [comment]
If you can't wait for it, just add the following scripts to your .vimrc

```vim
function! ClapProsessions(...)
    let flist = glob(fnamemodify(g:prosession_dir, ':p').'*.vim', 0, 1)
    let flist = map(flist, "fnamemodify(v:val, ':t:r')")
    let flist = map(flist, "substitute(v:val, '%', '/', 'g')")
    return flist
endfunction

let g:clap#provider#prosessions# = {
            \ 'source': function('ClapProsessions'),
            \ 'sink': 'Prosession'
            \ }
```

That's it.

**Comment by liuchengxu** [comment]
You could also extract your provider as a standalone plugin, so that people can reuse it easily. @markwu 

By the way, I also found https://github.com/hokorobi/vim-clap-sessions via https://github.com/topics/vim-clap, not sure if it's exactly what you want @thepenguinthatwants .

**Comment by markwu** [comment]
It's not the same, this plugin https://github.com/hokorobi/vim-clap-sessions manage sessions by it self. That's means it handle save/load session by itself.

But, I prefer manage session through vim-prosession/vim-obsession, becasue it will manage my session automatically and saves me a lot of time to make `mksession` work properly.

**Comment by markwu** [comment]
Ha, I remember why I didn't extract the provider as a plugin, because I want to reduce my number of plugin ...

**Comment by thepenguinthatwants** [comment]
Hi!
I usually just make sessions and get it back by sourcing.
:source ~/.vimsessions/project_python

I dont mind using vim-obsession/procession as it doesnt come into way I guess. As long as it can easily load sessions from a certain folder. Then Its definitely good to go.

**Comment by liuchengxu** [comment]
I have created the Examples page in wiki https://github.com/liuchengxu/vim-clap/wiki/Examples, feel free to share your providers there so that people can find them easily if you don't want to create a new plugin. @markwu

**Comment by liuchengxu** [comment]
I believe https://github.com/hokorobi/vim-clap-sessions already does the work for you @thepenguinthatwants , closing.
