### ISSUE TITLE
Resume last invocation

### ISSUE THREAD

**Issue by languitar** [liuchengxu/vim-clap#256]
**Is your feature request related to a problem? Please describe.**
Sometimes you accidentally open the wrong result of a search done with vim clap. You have to retype your search pattern to fix this error.

**Describe the solution you'd like**
Denite has an option that resumes your last invocation and you can easily continue browsing the search results without having to retype the pattern all the time.

**Comment by liuchengxu** [comment]
Duplicate as https://github.com/liuchengxu/vim-clap/issues/235#issuecomment-573955407.

**Comment by languitar** [comment]
Does the mentioned idea also include resuming the last mode and cursor location in the result list? That would be really handy.

**Comment by liuchengxu** [comment]
Nope. I'm not interested in this.

**Comment by languitar** [comment]
Do you have a proposal how to handle such a case where I want to handle multiple candidates from a result list in clap?

**Comment by languitar** [comment]
> Nope. I'm not interested in this. If you always need to resume the last search, why not just select all the items you need once?

I tried that, but received: `vim-clap: <Tab> is unusable, set g:clap_multi...n_warning_silent = 1 to suppress this warning.`

**Comment by liuchengxu** [comment]
Well, the message is pretty clear. That provider does not have the multi-select support yet(need to implement `sink*`), currently only `grep` provider supports that, it should not be hard to add multi-select support for `files` provider.

**Comment by liuchengxu** [comment]
I have added the `files` multi-select support in https://github.com/liuchengxu/vim-clap/pull/258, feel free to try it, have not decided the` text` used for each qf entry, let me know if you have any suggestions.

**Comment by languitar** [comment]
Thanks!

**Comment by rafi** [comment]
> If you always need to resume the last search, why not just select all the items you need once?

@liuchengxu Not _always_, but sometimes I'm not sure exactly, specially with grepping. So "resuming" to the last provider and cursor position is _extremely_ valuable, _sometimes_. I do understand though it's a fundamental change to save & restore the last state...

**Comment by cj** [comment]
It would be great to be able to resume the last active Clap invocation just like Denite.

**Comment by liuchengxu** [comment]
Actually the cache feature of vim-clap is partial of this request, but with only the results, the last cursor position is missing. When using the cache, you are reusing the last search result.
