### ISSUE TITLE
Navigate window items with cursor keys

### ISSUE THREAD

**Issue by MichaelAquilina** [liuchengxu/vim-clap#26]
The default way to move between items in windows feels quite unintuitive (at least compared to other alternatives like fzf.vim). It would be nice if there was the option to navigate between the items using the keyboard cursor keys as an alternative.

**Comment by liuchengxu** [comment]
I don't quite understand what you mean by window items and keyboard cursor keys.

> quite unintuitive

Please elaborate.

**Comment by MichaelAquilina** [comment]
> I don't quite understand what you mean by window items and keyboard cursor keys.

When the popup window is displayed, there are multiple "items/entries" shown under the text input. You are currently able to navigate between the available items using `Ctrl-j` and `Ctrl-k`.

> Please elaborate.

Sure! :) I had to go to the README and figure out how to move between the items to actually do what I intended. The fact I had to look it up means it's not intuitive because it was not any of the guesses I tried.

Most tools support navigating with the cursor keys and I think users would try using those to move between items. To me that is the definition of intuitive.

**Comment by zealot128** [comment]
I would also prefer a arrow key navigation. Currently, there is no way to achieve this, but to fork/modify plugin:

```diff
diff --git a/ftplugin/clap_input.vim b/ftplugin/clap_input.vim
index fe7a0c7..82997a0 100644
--- a/ftplugin/clap_input.vim
+++ b/ftplugin/clap_input.vim
@@ -56,8 +56,8 @@ nnoremap <silent> <buffer> <Esc> :call clap#handler#exit()<CR>
 inoremap <silent> <buffer> <C-c> <Esc>:call clap#handler#exit()<CR>
 inoremap <silent> <buffer> <Esc> <Esc>:call clap#handler#exit()<CR>

-inoremap <silent> <buffer> <C-j> <C-R>=clap#handler#navigate_result('down')<CR>
-inoremap <silent> <buffer> <C-k> <C-R>=clap#handler#navigate_result('up')<CR>
+inoremap <silent> <buffer> <Down> <C-R>=clap#handler#navigate_result('down')<CR>
+inoremap <silent> <buffer> <Up> <C-R>=clap#handler#navigate_result('up')<CR>

 inoremap <silent> <buffer> <Tab> <C-R>=clap#handler#select_toggle()<CR>
```

Maybe a config switch would be nice :)

**Comment by liuchengxu** [comment]
Since I personally don't use the arrow keys, so I rarely notice these _intuitive_things :(. But it's utterly easy to support this, so the mouse related keys are. PR is welcome, and I think we could have the both :(, for CTRL-J/K also works in other similar plugins.

**Comment by liuchengxu** [comment]
I have added the <Down> and <Up> keys. Let me know if you have more ideas about the arrow keys.

**Comment by zealot128** [comment]
Perfect! Thank you for the making this great plugin.
