### ISSUE TITLE
:Clap grep returns 0 results

### ISSUE THREAD

**Issue by tssm** [liuchengxu/vim-clap#261]
It's the same described in #223, but reverting to an older commit doesn't seem to solve the problem. `g:clap.display.bufnr` also returns a number that I don't see in the buffers list

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - (Neo)Vim version: Neovim 0.4.3
 - vim-clap version: b12b01863d2f9b9d8e04e8e3575ebb77c74483cd
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
No mater what I type in the grep window it doesn't return any result

**Clap debug**

```
            has cargo: 0
            has maple: /Users/tae/.local/share/nvim/site/pack/general/start/clap/target/release/maple
         has +python3: 1
         has py dylib: 0
     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/tae/.local/share/nvim/site/pack/general/start/clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign_done = '*'
    let g:clap_forerunner_status_sign_running = '!'
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
```

(That's what I get when I execute `:Clap debug+`. Looks like it was truncated).

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start Neovim

3. Execute `:Clap grep`

4. Type something you know should be find

**Expected behavior**
Grep results should be filtered

**Screenshots**
![Screenshot 2020-01-24 at 14 15 14](https://user-images.githubusercontent.com/1188977/73071770-f47b2280-3eb3-11ea-8b31-ff8df1a4fbc8.png)

**Comment by liuchengxu** [comment]
Try to rerun `:Clap install-binary!`.

**Comment by tssm** [comment]
Thanks, that did the trick. I installed maple manually before, I guess that's where I messed up
