### ISSUE TITLE
:Clap grep ++query=<cword>` do not catch the correct word under cursor.

### ISSUE THREAD

**Issue by yech1990** [liuchengxu/vim-clap#263]
**Environment:**
 - OS: Linux
 - (Neo)Vim version: NVIM v0.4.3
 - vim-clap version: master
 - Have you reproduced with a minimal vimrc: Not yet

**Describe the bug**

By running vim-clap plugin with dein plugin manager with lazy load, `expand('<cword>')` catch the word under cursor in a wrong order **for the first time**. eg, Abc in to bcA. 
If I close the floating windows and run this command again, everything will be fine.

**Clap debug**

```

            has cargo: 1
            has maple: v:null
         has +python3: 1
has py dynamic module: 0
     Current FileType: go
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/xx/.cache/vim/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign_done = '*'
    let g:clap_forerunner_status_sign_running = '!'
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

......

**Expected behavior**

**Screenshots**

![clap_bug](https://user-images.githubusercontent.com/5415510/73120483-7436e900-3fa9-11ea-9b96-e84eee9ac95e.png)

![clap_work](https://user-images.githubusercontent.com/5415510/73120488-96c90200-3fa9-11ea-9298-81ccda02b309.png)

**Comment by yech1990** [comment]
Meanwhile, `not an editor command` error is shown up occasionally.
![Uploading errr.png…]()

**Comment by liuchengxu** [comment]
Please fill the issue template.

**Comment by yech1990** [comment]
Seem that `vim-clap` is conflict with `https://github.com/kana/vim-smartchr`. After removing smartchr plugin, this bug disappear.

**Comment by liuchengxu** [comment]
Closing then, you have to find the workaround on your own as it's not an issue of clap and I don't use vim-smartchr.
