### ISSUE TITLE
Support skim fuzzy finder

### ISSUE THREAD

**Issue by polyzen** [liuchengxu/vim-clap#27]
Just opening this to show interest and track progress.

Referencing https://github.com/liuchengxu/vim-clap/blob/7fb32bf2211352109c201f85c0b3c81ad05aa2c2/autoload/clap/filter.vim#L16

**Comment by liuchengxu** [comment]
Thanks for this issue. I have opened an issue at https://github.com/lotabout/skim/issues/225. Vim-clap could easily support skim once the score could be disabled in the filter mode as I don't want to the extra job in the vim-clap side.
