### ISSUE TITLE
Feature request: project-provider

### ISSUE THREAD

**Issue by LinArcX** [liuchengxu/vim-clap#273]
**Is your feature request related to a problem? Please describe.**
Right now it's tedious to change directories with `:cd <directory-name>`. If we have a clap provider that do this for us, it'll be awesome.

**Describe the solution you'd like**
My idea is about changing directory with help of a floating window that `project-provider` will provides for us. 
Actually users can add path like this: `:AddPath </my-desire-path>` and they can jump into those directories with: `Clap projects`. A floating window will shows up and we can select our desire directory to change.

**Comment by liuchengxu** [comment]
It's not a typical clap built-in provider. You should learn how to write your own provider, check out https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md and https://github.com/liuchengxu/vim-clap/wiki/Examples.

**Comment by liuchengxu** [comment]
With the latest provider `:Clap filer`, you can go to any directory easily, which paritially meets your need. The case you descirbed is not sutiable to be a built-in provider, again, you should learn how to write your own provider for your own use, closing.

**Comment by LinArcX** [comment]
Hmm.. `:Clap filer` doesn't change cwd, am i right?

**Comment by LinArcX** [comment]
Actually i create it:
https://gist.github.com/LinArcX/408f69625563f94917300f5f938dd90d

But currently it has some problems:
1. You should add your directories by hand.
2. It needs some __Cleaning__.

Do you agree to add this as a separate provider? If yes, i can send a PR.

**Comment by liuchengxu** [comment]
You should learn how to manage your cwd then. Also check out `ClapOnExit` hook https://github.com/liuchengxu/vim-clap#execute-some-code-during-the-process, you can execute any code after you apply the sink of `filer`.

```vim
function! OnExit() abort
  if g:clap.provider.id ==# 'filer'
    execute 'lcd' getcwd()
  endif
endfunction
autocmd User ClapOnExit call OnExit()
```

As I have said, it's not suitable for a built-in provider, feel free to share it at https://github.com/liuchengxu/vim-clap/wiki/Examples when you finish it.

**Comment by RicardoMing** [comment]
I have written a [plugin](https://github.com/RicardoMing/projectile.nvim), which can find and store projects information automatically, and use fzf to switch between projects. It's like a simple implementation of ivy-projectile for neovim.

![image](https://user-images.githubusercontent.com/11895323/73720665-747b7500-475d-11ea-84f1-be4dcd98075b.png)
After selecting and pressing Enter, it will cd to the root directory of project and open a floating window to search project files:
![image](https://user-images.githubusercontent.com/11895323/73720851-e5bb2800-475d-11ea-82bd-9a70cf4b8088.png)

However, the plugin conflicts with other plugins, such as coc.nvim and vim-fugitive. I have no idea how to solve this problem now.

I hope vim-clap can support this feature officially, so I can use vim-clap as the primary fuzzy matcher.
