### ISSUE TITLE
Float Window/Popup Menu placement

### ISSUE THREAD

**Issue by skbolton** [liuchengxu/vim-clap#276]
I am loving this library and it is becoming my daily driver. Thanks for the work!

One small annoyance is how the floating window is always constrained by the buffer that it was launched from. I would have a preference towards it always being centered and above whatever buffers are behind it.

Let me know your thoughts and and possible restrictions on this.

**Comment by liuchengxu** [comment]
Unsure what your problem is. Have you read about `:h g:clap_layout`?

**Comment by skbolton** [comment]
That solves it!
