### ISSUE TITLE
How to `Clap grep` with a ++query="term with space"

### ISSUE THREAD

**Issue by thalesmello** [liuchengxu/vim-clap#277]
I have a personal key mapping that searches the visual selected text.

I'm having trouble searching the term when it has a space.

For instance:

```
Clap grep ++query='nnoremap <silent>'
```
will search for `nnoremap`

If I do
```
Clap grep ++query='nnoremap <silent>'
```
will only search for `'nnoremap'`

Which looks a little weird.

I don't know whether this is a bug or there's another way of actually doing it.

**Comment by liuchengxu** [comment]
The `query` argument is parsed manually by vim-clap, thus the support is very limited and I also don't have a plan to improve it. Let me know if you have better ideas about the parser.

https://github.com/liuchengxu/vim-clap/blob/ba104caa8a81e34c5caca321a49a754a14f245aa/autoload/clap.vim#L326-L349

For your case of searching the visual selected text, I thought that before, the solution is to introduce a new command `ClapVisual`, but I'm not happy to add such a command, I prefer to have only one `Clap` command, so I did not continue to bring it in. In this branch https://github.com/liuchengxu/vim-clap/tree/support-visual-selection , you can feed the visual selected text to clap via `ClapVisual`.

```vim
vnoremap <Leader>vg :ClapVisual grep<CR>
```

**Comment by rafi** [comment]
@thalesmello 

```vim
xnoremap <silent><Leader>gg :<C-u>Clap! grep ++query=<C-R>=<SID>get_visual_selection()<CR><CR>

function! s:get_visual_selection()
	" Why is this not a built-in Vim script function?!
	" Credits: https://stackoverflow.com/a/6271254/351947
	let [line_start, column_start] = getpos("'<")[1:2]
	let [line_end, column_end] = getpos("'>")[1:2]
	let lines = getline(line_start, line_end)
	if len(lines) == 0
			return ''
	endif
	let lines[-1] = lines[-1][: column_end - (&selection ==# 'inclusive' ? 1 : 2)]
	let lines[0] = lines[0][column_start - 1:]
	return join(lines, "\n")
endfunction
```

Seems like `++query` cuts everything after a space in input...

**Comment by liuchengxu** [comment]
@thalesmello   In #336, you can use `++query=@visual` for selecting the text visually:

```vim
vnoremap <C-P> :Clap grep ++query=@visual<CR>
```

**Comment by mnrce** [comment]
> @thalesmello In #336, you can use `++query=@visual` for selecting the text visually:
> 
> ```viml
> vnoremap <C-P> :Clap grep ++query=@visual<CR>
> ```

How about operator mapping?
e.g.
```
nnoremap <leader>g :<C-u>set operatorfunc=<SID>GrepFromSelected<CR>g@

function! s:GrepFromSelected(type)
  let saved_unnamed_register = @@
  if a:type ==# 'v'
    normal! `<v`>y
  elseif a:type ==# 'char'
    normal! `[v`]y
  else
    return
  endif
  let word = substitute(@@, '\n$', '', 'g')
  let word = escape(word, '| ')
  echo word
  let @@ = saved_unnamed_register
  execute "Clap grep ++query=".word
endfunction
```
(from `coc.nvim`)

I can press `\gil` (I have line text object) to grep the current line.
But if the current line have space then I can grep only till the space.

**Comment by liuchengxu** [comment]
@mnrce  Not sure the advantage of that way, https://github.com/liuchengxu/vim-clap/pull/336/files is much simpler. Feel free to open a PR if the operator mapping has more features.
