### ISSUE TITLE
Keep last input used by user

### ISSUE THREAD

**Issue by thalesmello** [liuchengxu/vim-clap#278]
This feature would be useful to keep the last text inputted by the user before he pressed enter.

It could be used to reopen the clap window using with the last used text already filled in.

It is useful for the situations in which:

- You search for a keyword using grep
- Select an entry and go to the buffer
- It's not quite what you were looking for, so you reopen Clap from where you left off, with the previous input already filled in

**Comment by liuchengxu** [comment]
People keep asking for this feature, also see #256, but I never rely on this, so it's low priority for me, PR welcome.

**Comment by thalesmello** [comment]
Just wanted to document here I found a way of registering input for later use with clever use of hooks.

```
" In ./autoload/clap_config.vim
function! clap_config#from_query_term(mode, query_term)
  execute "Clap" a:mode "."
  call feedkeys("\<c-e>")
  call g:clap.input.set(a:query_term)

  if exists("g:clap#provider#" . a:mode ."#.on_typed")
    call g:clap#provider#{a:mode}#.on_typed()
  endif
endfunction

function! clap_config#from_last_input(mode)
  if !exists("g:clap_config_last_input")
      let g:clap_config_last_input = {}
  endif

  let last_term = get(g:clap_config_last_input, a:mode, "")
  call clap_config#set_input_hook(a:mode)
  call clap_config#from_query_term(a:mode, last_term)
endfunction

function! clap_config#with_input_hook(mode, term)
  call clap_config#set_input_hook(a:mode)
  call clap_config#from_query_term(a:mode, a:term)
endfunction

function! clap_config#set_input_hook(keyword)
  if !exists("g:clap_config_last_input")
      let g:clap_config_last_input = {}
  endif

  augroup ClapConfigLastUsedGroup
    autocmd!
    execute "autocmd CursorMovedI * let g:clap_config_last_input['" . a:keyword . "'] = g:clap.input.get()"
    autocmd User ClapOnExit call clap_config#unset_input_hook()
  augroup END
endfunction

function! clap_config#unset_input_hook()
  autocmd! ClapConfigLastUsedGroup
endfunction
```

Then, create a map such as:
```
nnoremap <silent> <c-f> :<c-u>call clap_config#from_last_input("grep")<cr>
```

The idea is:

- You call a special function that will set a two auto cmd:
  - When CursorHoldI, save the the current input to `g:clap_config_last_input`
  - When ClapExit, remove the autocommands
- Next time the same function is called, set the value stored in `g:clap_config_last_input` to the current input

It's hacky and re-executes grep every time I run it, but I find this to be quite a timesaver. Hope other people find it useful.
