### ISSUE TITLE
Hidden files are not included in `:Clap files`

### ISSUE THREAD

**Issue by entropitor** [liuchengxu/vim-clap#28]
**Expected behavior**
Hidden files are included in the list of files returned

**Comment by liuchengxu** [comment]
For now, the files provider args has not been supported. If you are eager to use, try adding `--hidden` to the `fd` or `rg` options until this issue is really resolved.

https://github.com/liuchengxu/vim-clap/blob/7fb32bf2211352109c201f85c0b3c81ad05aa2c2/autoload/clap/provider/files.vim#L12-L13

**Comment by dharrigan** [comment]
Hi!

Firstly great plugin! Really enjoying using it. Secondly, yes please for this! I was wondering why some of my dot files where not showing in the window. I look forward to this enhancement being done :-)
