### ISSUE TITLE
Error detected while processing function clap#[35]..clap#for[20]..clap#floating_win#open[6]..47: line 12 Invalid value of 'relative' key

### ISSUE THREAD

**Issue by karlc1** [liuchengxu/vim-clap#282]
**Environment (please complete the following information):**
 - OS: ubuntu 18.04
 - (Neo)Vim version: neovim v0.4.0
 - vim-clap version: master
 - Have you reproduced with a minimal vimrc: Yes, same result

**Describe the bug**

:Clap files, :Clap tags etc produces the same error output; `Error detected while processing function clap#[35]..clap#for[20]..clap#floating_win#open[6]..47:  
line 12  
Invalid value of 'relative' key`

**Clap debug**

```
            has cargo: 1
            has maple: /home/karlc/.vim/plugged/vim-clap/bin/maple
           maple info: fail to fetch version info
         has +python3: 1
has py dynamic module: 1
     Current FileType: netrw
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/karlc/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!'}
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```
```
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

**Additional context**
I have tried both with of without maple, both getting it via cargo and by downloading binary form latest release.

**Comment by liuchengxu** [comment]
You might be using an old version of neovim, try upgrading your neovim.

**Comment by karlc1** [comment]
@liuchengxu I replaced nvim 0.4.0 with 0.4.3, which actually did work for `Clap files`. Thanks! However, the error message for `Clap tags` now shows 
```
Error detected while processing function clap#[35]..clap#for[20]..clap#floating_win#open[13]..clap#_init[5]..<SNR>112_detect_source_type[9]..378:
line    8:                                                                                                                                                                                                                                                                                                                                                                          
E117: Unknown function: vista#source#Update
```
Any ideas on this?

**Comment by liuchengxu** [comment]
Then the mininal required version for neovim is not v0.4.0 then :(, I thought v0.4.0 is just enough.

Check out the requirement of `:Clap tags` https://github.com/liuchengxu/vim-clap#commands, you need https://github.com/liuchengxu/vista.vim.

**Comment by karlc1** [comment]
@liuchengxu Yes, sorry you are correct, I missed the Vista requirement. I installed it, and it works fine now. And yes, it does seem like minimal version should be increased. I checked with a colleague who  recommended Clap to me, and he uses 0.4.2 so at least that is working.

**Comment by liuchengxu** [comment]
Thanks for the info, I have updated the README.
