### ISSUE TITLE
Project root for mono-repos

### ISSUE THREAD

**Issue by yormi** [liuchengxu/vim-clap#283]
First, thanks for vim-clap ! Very promising project to improve over `ctrlp` :)

**Is your feature request related to a problem? Please describe.**
It will be nice to be able to restrict the how far up the directory tree the search goes. We use a monorepo and when we work in one project, we don't want to get results from other project in the git repo.

**Describe the solution you'd like**
I think the way ctrlp handle this works pretty well. Having a `.vimclapstopper` file that indicates were to stop searching up the directory tree. 

**Describe alternatives you've considered**
Since the solution mentioned above seems to work well, I haven't thought much of other solution. That is the cleanest one that comes to my mind.

I'm currently the `let g:clap_disable_run_rooter = v:true` option and it's a fine workaround but it'd be great not having to keep yet another thing in mind :P

**Comment by liuchengxu** [comment]
A general solution is to introduce a project root marker, the root marker is `['.git', '.git/']` for the git-based project. We can use an option `g:clap_project_root_marker`, putting `.root` in the directory indicates that's the project root directory and we just stop there.
```vim
let g:clap_project_root_marker = ['.root', '.git', '.git/']
```

**Comment by yormi** [comment]
Ah that's perfect ! Does that already exists ? I haven't seen it !?

**Comment by liuchengxu** [comment]
Try #290

**Comment by yormi** [comment]
Wow ! You are effective !

It works like a charm ! 

Thank you for the amazing work :)
