### ISSUE TITLE
floating_win of neovim doesn't close when you focus out

### ISSUE THREAD

**Issue by thalesmello** [liuchengxu/vim-clap#287]
If you focus out of the clap floating window, it doesn't close automatically.

**Comment by thalesmello** [comment]
Somehow this code is supposed to make it work, but it apparently isn't being called.

https://github.com/liuchengxu/vim-clap/blob/ae50295a4fede1a1275c304cb686093c8c5b267c/autoload/clap/floating_win.vim#L290

**Comment by liuchengxu** [comment]
Ensure you stay in the input window and are in the insert mode when you about to close vim-clap. Otherwise the behaviour is not well defined and not guarentted. I can't recall why that's commented, there are possibly some edge cases around here.

**Comment by thalesmello** [comment]
I commented out and started testing it out.

With the line uncommented, from what I could tell:

1. You apparently use two floating windows: one for the input, another for the list of entries (also a third window if you count the preview window as well)
2. If you click the buffer with the text open in the background, the floating window closes (behavior I'm looking for)
3. If you click any of the entries, the expected behavior would be to select that entry, but it's currently being closed because you left the input window.

The fix to this problem would be to figure out a way of calling the close clap function only when you leave any of the clap windows.

One way I think would be possible to implement this would be to:

1. make sure all the clap buffers are created with a buffer variable stating it's a clap buffer
2. enforce the close clap behavior on `BufWinEnter` when the new buffer doens't have a `b:is_clap_buffer` defined.

**Comment by thalesmello** [comment]
For now I'm happy with the close when focus out behavior, as I mostly use the keyboard, so I will use my personal fork. Just leaving this documented here in case someone is interested on working on this sometime in the future.

**Comment by liuchengxu** [comment]
For this special case, you actually don't have to maintain your own fork, just use the `ClapOnEnter` hook.

```vim
function! s:ensure_closed() abort
  call clap#floating_win#close()
  silent! autocmd! ClapEnsureAllClosed
endfunction

function! MyClapOnEnter() abort
    augroup ClapEnsureAllClosed
    autocmd!
    autocmd BufEnter,WinEnter,WinLeave * call s:ensure_closed()
  augroup END
endfunction

autocmd User ClapOnEnter call MyClapOnEnter()
```

**Comment by comfortablynick** [comment]
Thanks for this, I wanted this behavior too. I simplified it a bit, making use of the `++once` argument for autocommands. Seems to work the same.

```vim
augroup MyClapCommands
  autocmd!                                                                                                                             
  autocmd User ClapOnEnter                                                                                                             
    \ autocmd MyClapCommands                                                                                          
    \ BufEnter,WinEnter,WinLeave * ++once call clap#floating_win#close()                                                                           
augroup END      
```

**Comment by liuchengxu** [comment]
Simplify the above workaround a bit using `++once`:

```vim
function! MyClapOnEnter() abort
  augroup ClapEnsureAllClosed
    autocmd!
    autocmd BufEnter,WinEnter,WinLeave * ++once call clap#floating_win#close()
  augroup END
endfunction

autocmd User ClapOnEnter call MyClapOnEnter()
```

Closing as the workaround is already simple enough and works.
