### ISSUE TITLE
Disable Coc's completeopt

### ISSUE THREAD

**Issue by L-Vim** [liuchengxu/vim-clap#29]
Similar to #9 but with coc.nvim

**Comment by liuchengxu** [comment]
#13 should work for coc.nvim as well unless coc modifies `completeopt` on its side. I believe this should be handled in coc.nvim. Vim-clap has done what it can.

**Comment by tracyone** [comment]
'completeopt' is a global value, `setlocal` is not work. 

https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/popup.vim#L163

Your commit make a mistake, completeopt is cleared globally

**Comment by liuchengxu** [comment]
@tracyone  Thanks, fixed.
