### ISSUE TITLE
Delete the words before the cursor CTRL+W 

### ISSUE THREAD

**Issue by Trskldn** [liuchengxu/vim-clap#291]
**Is your feature request related to a problem? Please describe.**
default for bash behavior when a CTRL+W  pressed - delete the words before the cursor

**Describe the solution you'd like**
In ClapSearchLine,  CTRL+W must delete the words before the cursor

**Comment by liuchengxu** [comment]
`CTRL-W` works for neovim by default. For vim, you can vote the feature request in https://github.com/vim/vim/issues/5639 as I don't have to a plan to support it inside the plugin.
