### ISSUE TITLE
Error on `:Clap` with `vim -u NONE`

### ISSUE THREAD

**Issue by olmokramer** [liuchengxu/vim-clap#3]
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Arch Linux
 - (Neo)Vim version: Vim 8.1.1968
 - vim-clap version: 95fc330
 - Have you reproduced with a minimal vimrc: I have reproduced with `vim -u NONE`.

**Describe the bug**

I get an error whenever I run the `:Clap` command (e.g. `:Clap files`):

```
Error detected while processing /home/olmo/.vim/pack/plugins/start/clap/autoload/clap.vim:
line   17:
E116: Invalid arguments for function map(
line   18:
E10: \ should be followed by /, ? or &
line   19:
E10: \ should be followed by /, ? or &
line   20:
E10: \ should be followed by /, ? or &
line   22:
E121: Undefined variable: s:builtin_providers
line   24:
E15: Invalid expression: {
line   25:
E10: \ should be followed by /, ? or &
line   26:
E10: \ should be followed by /, ? or &
line   27:
E10: \ should be followed by /, ? or &
line   29:
E121: Undefined variable: s:provider_alias
E116: Invalid arguments for function extend(s:provider_alias, get(g:, 'clap_provider_alias', {}))
line   31:
E15: Invalid expression: {
line   32:
E10: \ should be followed by /, ? or &
line   33:
E10: \ should be followed by /, ? or &
line   34:
E10: \ should be followed by /, ? or &
line   35:
E10: \ should be followed by /, ? or &
Error detected while processing function clap#init#[19]..<SNR>3_init_hi_groups[2]..<SNR>3_hi_spinner:
line   17:
E116: Invalid arguments for function printf(
Error detected while processing function clap#[20]..clap#for:
line    1:
E121: Undefined variable: s:provider_alias
E116: Invalid arguments for function has_key(s:provider_alias, a:provider_id_or_alias)
```

**To Reproduce**

1. Make sure `vim-clap` is in `'packpath'`, e.g. `mkdir -p ~/.vim/pack/plugins/start && git clone https://github.com/liuchengxu/vim-clap .vim/pack/plugins/start/vim-clap`.

2. Start (neo)vim with command: `vim -u NONE`.

3. Type `:packadd vim-clap<CR>`.

4. Check that only the vim-clap scripts are loaded with `scriptnames`:

```
  1: ~/.vim/pack/plugins/start/clap/plugin/clap.vim
  2: ~/.vim/pack/plugins/start/clap/autoload/clap.vim
  3: ~/.vim/pack/plugins/start/clap/autoload/clap/init.vim
  4: ~/.vim/pack/plugins/start/clap/autoload/clap/util.vim
``` 

5. Type `:Clap files`.

6. Get the error above.

**Expected behavior**
I would not expect an error on a Vim with no configuration.

**Comment by liuchengxu** [comment]
Thanks for the report. Please pull the latest version to fix it.

**Comment by olmokramer** [comment]
Wow that was quick. Thanks!
