### ISSUE TITLE
Changing the search header's contrast

### ISSUE THREAD

**Issue by bigardone** [liuchengxu/vim-clap#30]
**Is your feature request related to a problem? Please describe.**
Hi! First of all congrats and thanks for this plugin 🙌 . 
I'm using [Nova](https://github.com/trevordmiller/nova-vim) color scheme, and the search header in the floating window is really hard to read due to its lack of contrast:

![image](https://user-images.githubusercontent.com/1090272/66372580-9d098300-e9a6-11e9-8992-43af2fa9b65f.png)

I'm not familiar with neovim's styling syntax. I have read the highlights section of the readme file, and have been playing around with the options, but unfortunately, I haven't been able to change the contrast at all. Could you point me in the right direction to change the background color so it's more readable?

Thanks in advance :)

**Comment by liuchengxu** [comment]
Change the color to what you like:

```vim
autocmd ColorScheme * hi ClapSpinner cterm=bold gui=bold ctermfg=242 guifg=#DF8C8C ctermbg=0 guibg=#7FC1CA
```

**Comment by bigardone** [comment]
Awesome! thank you so much :)
