### ISSUE TITLE
Support dynamic update in maple for grep/files provider

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vim-clap#302]
Currently maple only responses when the job is finished, i.e., there is no dynamic update for the time-consuming jobs. We have a spinner in the vim window, that's good, but not perfect. We have introduced a new rpc-based provider in #272, that means all the work required on the vim side has been done, now the job is to implement a dynamic update for running a system command in maple, but it's obviously not easy. It sounds like the core logic of skim without drawing the UI.

1. Start the maple service and run the command on start.
2. User type inside vim.
3. Send the input event to maple via job channel.
4. Response the input event and send back the update periodly.

-------------

- [x] files provider will support dyn filter after #364 is merged.
    - And any provider can benefit from it if the `source` is a String or a function that returns a String.
    - From what I have seen, neovim works great as always with the dyn filter, but vim still behaves bad due to the linewise job invocation. I believe using a timer to reading the output periodly can help, but I'm a neovim user, this timer improvement will be indefinite.
- [ ] new grep2 provider #383, with cache and dynamic refresh support.

**Comment by ImmemorConsultrixContrarie** [comment]
Just to make sure I know what I'm talking about, before I actually start talking about it: what is "maple"? A Rust or a Python extension?

**Comment by liuchengxu** [comment]
@ImmemorConsultrixContrarie  https://github.com/liuchengxu/vim-clap/blob/master/Cargo.toml#L2 The silly Rust external binary for vim-clap :(.

**Comment by ImmemorConsultrixContrarie** [comment]
One more question: there's a big uncommented matcher in `Maple::run()`, which part of this matcher should provide dynamic results?
@liuchengxu

**Comment by liuchengxu** [comment]
The dynamic update is still unimplemented, but I think the current filter/matcher can be reused.

**Comment by ImmemorConsultrixContrarie** [comment]
> 
> 
> The dynamic update is still unimplemented, but I think the current filter/matcher can be reused.

No-no-no, There's a match for commands, and I don't understand which command you want to change.
```
        match self.command {
            Cmd::Version => {
                version();
            }
            Cmd::RPC => {
                crate::cmd::rpc::run_forever(std::io::BufReader::new(std::io::stdin()));
            }
            Cmd::Filter { query, input, algo } => {
                let source = input.map(Into::into).unwrap_or(Source::Stdin);
                crate::cmd::filter::run(
                    query,
                    source,
                    algo,
                    self.number,
                    self.enable_icon,
                    self.winwidth,
                )?;
            }
            Cmd::Blines { query, input } => {
                crate::cmd::filter::blines(query, input, self.number, self.winwidth)?;
            }
            Cmd::Exec {
                cmd,
                output,
                cmd_dir,
                output_threshold,
            } => {
                crate::cmd::exec::run(
                    cmd,
                    output,
                    output_threshold,
                    cmd_dir,
                    self.number,
                    self.enable_icon,
                )?;
            }
            Cmd::Grep {
                grep_cmd,
                grep_query,
                glob,
                cmd_dir,
            } => {
                crate::cmd::grep::run(
                    grep_cmd,
                    grep_query,
                    glob,
                    cmd_dir,
                    self.number,
                    self.enable_icon,
                )?;
            }
            Cmd::Helptags { meta_info } => crate::cmd::helptags::run(meta_info)?,
            Cmd::RipgrepForerunner { cmd_dir } => {
                crate::cmd::grep::run_forerunner(cmd_dir, self.number, self.enable_icon)?
            }
        }
 ```

Is it `::Filter` or some other part? And how does it return results? With `println_json!()` macro?

**Comment by liuchengxu** [comment]
The dynamic update function will be part of the `RPC` subcommand, which uess the way of stdio.

**Comment by ImmemorConsultrixContrarie** [comment]
> 
> 
> The dynamic update function will be part of the `RPC` subcommand, which uess the way of stdio.

Okay, I have problems understanding what you want to do with you code, so let's start again without any code. I don't know what RPC is and what it should do as a Maple command. Can you describe it? Like "when dog barks it makes sound", or "when I run helloworld.rs it prints `Hello, world!` on the screen", or "when I use RPC subcommand in this vim plugin, I do X and get result Y".

**Comment by liuchengxu** [comment]
Checkout https://github.com/liuchengxu/vim-clap/blob/master/src/cmd/rpc/mod.rs and `filer.rs` if you are interested. The idea is when you type anything inside vim, clap will send the request to the maple backend via job channel, then maple processes the request and send back the result, we deal with that response in the job's callback, drop the outdated response and display the latest result.
