### ISSUE TITLE
What about to open vim-clap in a new tab?

### ISSUE THREAD

**Issue by lourenci** [liuchengxu/vim-clap#304]
I know the plugin is based on the new popup feature, but it'd be nice if you go beyond that and allow us to open it in a new tab window.

I don't like the new popup feature for complex things, I prefer to take advantage of the entire window to those kinds of.

**Comment by liuchengxu** [comment]
Replacing the popup with a new tab window means to write another UI components. That's not the scope of my goal. I can accept PR :(.

If you merely want to a wider popup, try playing with `g:clap_layout`, `:h g:clap_layout`:

```vim
" Wider clap
let g:clap_layout = {'width': '95%', 'col': '5%'}
```

**Comment by lourenci** [comment]
Sorry, I'm a layman in vimscript.

I'll try to use like you have mentioned.

Thanks for the plugin.
