### ISSUE TITLE
Ctags project-wide search in vim-clap

### ISSUE THREAD

**Issue by saaguero** [liuchengxu/vim-clap#305]
As of now, the `:Clap tags` command will just show the tags for the current buffer.

It would be nice to have a way to filter project-wide ctags through vim-clap, much like fzf does through the command `:Tags`. 

Reference: https://github.com/junegunn/fzf.vim/blob/master/doc/fzf-vim.txt#L114

It will also run the command `ctags -R` if it needs to. This may be optional for vim-clap if it gets hard to implement.

**Comment by liuchengxu** [comment]
Better to implement a pure-async provider for this purpose as `ctags -R` is normally very slow. I'm not intersted, PR welcome.

**Comment by liuchengxu** [comment]
Try #391, but you have to build the Rust binary at the moment.
