### ISSUE TITLE
Add configuration to ignore some directories

### ISSUE THREAD

**Issue by safv12** [liuchengxu/vim-clap#307]
In some projects autogenerated directories could add mess to the Clap windows. For example in node projects the `node_modules` directory is so big and it could be ignored.

![image](https://user-images.githubusercontent.com/5117021/73882273-6003af00-4827-11ea-9974-29392306946c.png)

Others directories that could be ignored: `node_modules|target|dist|vendor|bin|obj|build` and so on.

It could be a good idea to be able to indicate Clap which directories to ignore depending on the project.

**Comment by safv12** [comment]
I discovered that you are ignoring the files contained in the .gitignore file. Is that correct?

If so, we can close this issue.

**Comment by liuchengxu** [comment]
The default command used by `files` https://github.com/liuchengxu/vim-clap/blob/2c34f53018/autoload/clap/provider/files.vim#L9, `fd` will ignore the files in `.gitignore`, etc. You can also pass any arguments, e.g., do not ignore these files, `:Clap files ++finder=fd --type f --no-ignore`.
