### ISSUE TITLE
allow provider to update the list when search text changes

### ISSUE THREAD

**Issue by prabirshrestha** [liuchengxu/vim-clap#316]
Is there a sample provider that updates the list when `on_type` changes?

In the below example, as use searches for npm packages I run curl after some debounce. I'm currently using (quickpick.vim](https://github.com/prabirshrestha/quickpick.vim) and I would like to know if vim-clap supports this scenario or if it is possible to add this scenario.

![NPM Picker](https://user-images.githubusercontent.com/287744/50551057-55441700-0c30-11e9-8842-d79182cdcaf0.gif)

I'm mainly trying to expose api's [vim-lsp](https://github.com/prabirshrestha/vim-lsp) for custom provider specially `:LspWorkspaceSymbol`. This way as the user is searching I can make requests to language server protocol and then update the results.

Some of my thoughts can be found here:
https://github.com/mattn/vim-fz/issues/4
https://github.com/mattn/gof/issues/18

**Comment by liuchengxu** [comment]
It's not hard to add an API for updating the source list if the `source` of provider returns a List instead of String. `l:raw_lines` is what we need to set dynamically if you are interested.

https://github.com/liuchengxu/vim-clap/blob/41ebbfde1f6775ab4b4dfb9154cccec015dc0d20/autoload/clap/impl.vim#L87

But I'm still unsure about the interaction when the `source` List can be obtained in async. If this operation takes some time, when you enter the clap window, you start the async job but there is no content yet, what you typed right now does nothing until the async data comes.

**Comment by prabirshrestha** [comment]
Here is an example using quickpick: https://github.com/prabirshrestha/quickpick-npm.vim/blob/4f4d913a103f84b8844ef59bd06afd52e13fc07b/autoload/quickpick/pickers/npm/search_packages.vim

`source list` can change any time. Which means as a provider author I need to be able to reset the list, set the busy status, update the list and debounce as needed.

At high level I would like to achieve something like this. Think of like creating an autocomplete search results. Clap should care if it is async job or some other api.

```vim
function! s:on_type(query) abort
    if exists('s:timer')
        call timer_stop(s:timer)
        unlet s:timer
    endif
    let s:timer = timer_start(250, {->s:search(query)})
endfunction

function! s:search(query) abort
    call clap#set_busy(1)
    if exists('s:last_req_id')
        call lsp#cancel_request(s:last_req_id)
    endif
    let s:last_req_id = lsp#send_request({
        \ 'on_notification': {result->s:on_result(result)}
        \ })
endfunction

function! s:on_result(result, id) abort
    unlet s:last_req_id
    call clap#set_busy(0)
    call clap#set_items(a:result)
endfunction
```

**Comment by liuchengxu** [comment]
Actually a provider author is able to this right now, all basic APIs are avaliable, see `:Clap grep`, the data is fetched in async. But that has to be a pure-async provider, which means the provider author must provide the `on_typed` implementation by himself.

**Comment by liuchengxu** [comment]
Use `g:clap.display` related API to manipulate the display window, e.g., `g:clap.display.set_lines()` can be used for setting the source list at any time, see the complete list https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/api.vim#L69 . Closing as it's already supported, let me know if you have more questions.
