### ISSUE TITLE
Long matched results can cause the matched portion to not be visible

### ISSUE THREAD

**Issue by YellowKirby** [liuchengxu/vim-clap#317]
**Is your feature request related to a problem? Please describe.**

When matching entries that are really long, it is possible for the matched/highlighted portion to exist outside of the visible window. e.g., when using `:Clap files` to search by filename in a project that has a deeply-nested folder structure:

<img width="851" alt="image" src="https://user-images.githubusercontent.com/1654019/74172011-59d55000-4be4-11ea-847a-924c5a780b58.png">

This can make it difficult to understand which entry is actually being selected.

**Describe the solution you'd like**

It would be nice if vim-clap could truncate or justify the entry so that the highlighted portion is visible within the window:

<img width="580" alt="image" src="https://user-images.githubusercontent.com/1654019/74172857-d3ba0900-4be5-11ea-8f8a-542237f1fcd1.png">

Thank you! vim-clap has been really nice to use :)

**Comment by liuchengxu** [comment]
Try #330, but you have to build the Rust binary manually via `:call clap#installer#build_all()` until the new release.
