### ISSUE TITLE
Window miscorrectly placed and sized when changing terminal dimensions

### ISSUE THREAD

**Issue by MichaelAquilina** [liuchengxu/vim-clap#32]
1) Start up terminal with a smallish size (e.g. left half off screen)
2) Start neovim with plugin installed
3) Run `Clap files` and notice that window is correctly sized
4) Resize terminal (e.g. full screen)
5) Run `Clap files` and notice the window is not correctly centered and is not the correct size

![2019-10-08_22-58-20](https://user-images.githubusercontent.com/2650040/66436526-2b215000-ea1f-11e9-90cc-a5874760b668.png)

**Comment by liuchengxu** [comment]
Thanks for the report. Let me know if the patch doesn't work.

**Comment by MichaelAquilina** [comment]
Can confirm the patch works - thanks!
