### ISSUE TITLE
Can't close the files pop-up (may also affect other pop-ups)

### ISSUE THREAD

**Issue by dharrigan** [liuchengxu/vim-clap#325]
Hi,

Latest neovim and vim-clap.

I've noticed that since the most recent updates, if the files pop-up is displayed, I can no longer dismiss the pop-up using the escape key (or the capslock key which I've remapped). Instead, the input box shows a `0` when I press escape (please see attached picture).  I am forced to choose a file (which I don't want to do - I could change my mind about opening a file) or I have to quit out of neovim altogether.
![files-with-zero](https://user-images.githubusercontent.com/427150/74721840-e6f55600-522f-11ea-9ff7-58dbf8c2c7ca.png)

Thank you.

**Comment by liuchengxu** [comment]
See https://github.com/liuchengxu/vim-clap/pull/322 and please fill the issue template next time.

**Comment by dharrigan** [comment]
Hi,

Thank you!
