### ISSUE TITLE
Clap tags errors

### ISSUE THREAD

**Issue by bigardone** [liuchengxu/vim-clap#33]
I'm using Vista + Coc, and I wanted to try out `:Clap tags`, and I have found the following:

While running the command for the first time, it throws the following errors on neovim:

```
UpdateLastColumn failed to find bufnr 6 in w:BufKillList
UpdateLastColumn failed to find bufnr 6 in w:BufKillList
Press ENTER or type command to continue
```

After pressing ENTER, it displays the tags as expected:

![image](https://user-images.githubusercontent.com/1090272/66455439-12d72280-ea6b-11e9-9360-9a95e79ae6ef.png)

However, the search doesn't work:

![image](https://user-images.githubusercontent.com/1090272/66455462-284c4c80-ea6b-11e9-8f88-88936344470f.png)

And if I delete the search text, it doesn't list the tags anymore:

![image](https://user-images.githubusercontent.com/1090272/66455497-4914a200-ea6b-11e9-9ab1-57aa44678c84.png)

**Comment by liuchengxu** [comment]
Please fill the issue template, provide the sample file, minimal vimrc and exact steps to reproduce. `:Clap tags` works for me.

**Comment by tracyone** [comment]
it seems that `Clap tags` depends on vista.vim

<img width="903" alt="Screen Shot 2019-10-09 at 21 57 48" src="https://user-images.githubusercontent.com/4246425/66487991-d7c30680-eadf-11e9-82c2-fe6221915f0e.png">

**Comment by liuchengxu** [comment]
README already declares the vista.vim requirement for `Clap tags`.

**Comment by tracyone** [comment]
<img width="903" alt="Screen Shot 2019-10-12 at 22 59 06" src="https://user-images.githubusercontent.com/4246425/66703326-09d4a280-ed44-11e9-80e9-06f072adbe63.png">

**Comment by liuchengxu** [comment]
You should create a new issue. @tracyone
