### ISSUE TITLE
TypeError: fuzzy_match() takes at most 2 positional arguments

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#331]
**Environment (please complete the following information):**
 - OS: MacOS
 - Vim version: 8.2.250
 - vim-clap version: master
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
After commit f6e5860 I'm receiving the following error:

```
vim-clap: Vim(let):TypeError: fuzzy_match() takes at most 2 positional arguments (3 given)
```

as a result, the search popup window opens and I can search, but I have to be exact about the file names, e.g. searching "lightcomm" won't return "light_command.rs" in the results, I have to search "light_comm" to see it in the results.

**Comment by liuchengxu** [comment]
Your Python dynamic module is outdated, you should build it again, try running `make` in the plugin root directory.

**Comment by arashm** [comment]
Ok, that fixed the issue. Shouldn't `:Clap install-binary` do that though?

**Comment by liuchengxu** [comment]
`:Clap install-binary!` should do, it actually just runs `make` on unix system.

**Comment by arashm** [comment]
Does it need the nightly rust?

**Comment by liuchengxu** [comment]
Yes, building Python dynamic module needs nightly, the auto-installer will exit if it detects there is no nightly Rust on your system.

**Comment by arashm** [comment]
Yeah, I had it before but since you removed the part where mentioned nightly in the docs, I also removed it from the toolchain. I could see that the `:Clap install-binary` updates and compile just fine without any error without nightly. But then now that I did `make`, it throw an error that you need nightly.
