### ISSUE TITLE
Disable normal mode completely

### ISSUE THREAD

**Issue by mhartington** [liuchengxu/vim-clap#332]
**Is your feature request related to a problem? Please describe.**
Hi there! First off, thank you for your project! It's really great. Recently I upgraded and saw the addition of a normal mode for the clap window. While this could be nice, it doesn't really fit ever use case/need. It would be great if there was an option to disable it all together for those who do not want it.

**Describe the solution you'd like**
An option to disable normal in vim-clap buffer

```vim
let g:clap_normal_mode_support = 0 "or 1 to enable
```

Something like this would be great. Given the context a fuzzy searcher, I'm never doing anything where I wish I could exit insert mode.

**Comment by liuchengxu** [comment]
Make sense, I can add an option `g:clap_insert_mode_only` to disable the feature of other modes which will be enabled by default and you need to disable it explicitly.

**Comment by liuchengxu** [comment]
Use `let g:clap_insert_mode_only = v:true` in #335.
