### ISSUE TITLE
Icons in :Clap files like in :Clap grep

### ISSUE THREAD

**Issue by GoldsteinE** [liuchengxu/vim-clap#337]
`:Clap grep` shows filetype devicons and `:Clap files` doesn't.

**Describe the solution you'd like**
`:Clap files` (and other providers, like `:Clap gfiles`) should also have option to show devicons.

**Describe alternatives you've considered**
Maybe icons can be implemented not on provider level, but in Clap itself.

**Comment by liuchengxu** [comment]
`files` like icon support is only avaiable when you are using the Rust extension, see #191. I don't have to time to optimize for the pure-vimscript implementation as that affects the performance. Checkout `convert` property of provider and the example in `:Clap grep` if you are interested. The icon support has be done in each provider, clap, as the framework itself, has no idea to implement a generic icon support.
