### ISSUE TITLE
Cant quit by esc -button anymore?

### ISSUE THREAD

**Issue by thepenguinthatwants** [liuchengxu/vim-clap#338]
**Environment (please complete the following information):**
 - OS: arch linux
 - (Neo)Vim version: 0.4.3
 - vim-clap version:  The newest that this day contains?
 - Have you updated to the latest plugin version: yes!
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**
Earlier I could escape from the view by clicking esc. Right now only way is to enter, which sometimes chooses options that I dont need to.

**Clap debug**

             has cargo: 1
              has maple: /home/ninja/.dotfiles/arch/.config/nvim/plugged/vim-clap/target/release/maple
             maple info: version 0.1.8, built for x86_64-unknown-linux-gnu by rustc 1.41.0.
           has +python3: 1
  has py dynamic module: 0
       Current FileType: startify
  Third Party Providers: []
         Global Options:
      let g:clap#autoload_dir = '/home/ninja/.dotfiles/arch/.config/nvim/plugged/vim-clap/autoload'
      let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
      let g:clap#themes#material_design_dark#palette = {'current_selection_sign': {'ctermfg': '196', 'guifg': '#f2241f'}, 'spinner': {'gui': 'bold', 'ctermbg': '60', 'ctermfg': '11', 'guibg': '#3e4461', 'cterm': 'bold', 'guifg': '#ffe500'}
  , 'current_selection': {'gui': 'bold', 'ctermbg': '236', 'guibg': '#31364D', 'cterm': 'bold'}, 'search_text': {'gui': 'bold', 'ctermbg': '60', 'ctermfg': '195', 'guibg': '#3e4461', 'cterm': 'bold', 'guifg': '#CADFF3'}, 'selected_sign': {
  'ctermfg': '196', 'guifg': '#f2241f'}, 'preview': {'ctermbg': '238', 'guibg': '#363c55'}, 'input': {'ctermbg': '60', 'guibg': '#3e4461'}, 'selected': {'gui': 'bold,underline', 'ctermfg': '81', 'cterm': 'bold,underline', 'guifg': '#5FD7d7
  '}, 'display': {'ctermbg': '235', 'guibg': '#272d3D'}}
      let g:clap_disable_bottom_top = 0
      let g:clap_enable_icon = 0
      let g:clap_forerunner_status_sign = {'done': '•', 'running': '!'}
      let g:clap_no_matches_msg = 'NO MATCHES FOUND'
      let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
      let g:clap_search_box_border_style = 'nil'
      let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
      let g:clap_session_dir = '~/.config/nvim/sessions/'
      let g:clap_theme = 'PaperColor'
    Provider Variables:
      let g:clap_provider_commands = {'source': ['Codi!!', 'UltiSnipsEdit', 'CocConfig'], 'sink': function('<lambda>2')}
      let g:clap_provider_dotfiles = {'source': ['~/.config/nvim/init.vim', '~/.config/i3/config', '~/.bashrc', '~/.tmux.conf', '/home/ninja/DOCS/makeinstall/Makefile'], 'sink': 'e'}

```
```

**Comment by liuchengxu** [comment]
Please see https://github.com/liuchengxu/vim-clap/pull/322 and CHANGELOG.  In https://github.com/liuchengxu/vim-clap/pull/335 I'll add a new option `g:clap_insert_mode_only` to allow disabling the feature of other modes completely. If you set `let g:clap_insert_mode_only` to true, the`<Esc>` will use the old beviour, i.e., quit clap.
