### ISSUE TITLE
Is there a way to change foreground color of files/history and also matches?

### ISSUE THREAD

**Issue by habamax** [liuchengxu/vim-clap#339]
I have tried to look up it in the source code but couldn't find anything.

![image](https://user-images.githubusercontent.com/234774/75607501-e51d7380-5b08-11ea-86cb-8d32ca2bc6a9.png)

PS, and for grep?

![image](https://user-images.githubusercontent.com/234774/75607566-72f95e80-5b09-11ea-9886-4d847b8b3306.png)

**Comment by liuchengxu** [comment]
1. For the highlight of fuzzy matched items, see `:h g:clap_fuzzy_match_hl_groups`.

2. I mentioned a bit in https://github.com/liuchengxu/vim-clap#change-highlights. If the provider has its own syntax file, you have to look up the syntax file directly to change the highlights, see https://github.com/liuchengxu/vim-clap/blob/master/syntax/clap_grep.vim for `Clap grep` and https://github.com/liuchengxu/vim-clap/blob/master/syntax/clap_files.vim for `Clap files`.

**Comment by habamax** [comment]
Thank you, exactly what I need!
