### ISSUE TITLE
Commands Ctrl+t and friends throw error

### ISSUE THREAD

**Issue by alerque** [liuchengxu/vim-clap#34]
The shortcuts for opening files in a new tab or split return an error.

 - OS: Linux (Arch)
 - NeoVim version: 0.4.2
 - vim-clap version: current HEAD
 - Have you reproduced with a minimal vimrc: yes

`:Clap! files` to launch the files provider, select any file, and hit <kbd>Ctrl</kbd><kbd>t</kbd> to open file in a new tab. The following error is thrown:

```txt
Error detected while processing function <SNR>39_action:
line 2:
E117: Unknown function: <SNR>39_sink
```

**Comment by liuchengxu** [comment]
<img width="921" alt="屏幕快照 2019-10-09 下午4 03 29" src="https://user-images.githubusercontent.com/8850248/66462794-67e85800-eaae-11e9-997c-7e34a589ccfb.png">

It's still in an unimplemented state.

**Comment by alerque** [comment]
@liuchengxu That is not very clear from the documentation. Other things marked that way _are_ implemented (e.g. <kbd>Ctrl</kbd><kbd>h</kbd>). It would be a lot more clean if ⓐ it was up to date and ⓑ the _completed_ items used the same Markdown notation, marking the boxes as checked (`- [x]`). Mixing and matching notations leaves the intention unclear.

**Comment by liuchengxu** [comment]
Feel free to improve it :(.

**Comment by alerque** [comment]
Will do. Lets also repurpose this issue as a feature request for those things since it's a bit easier to track here than in a README ;-)

**Comment by numbcoder** [comment]
> <img alt="屏幕快照 2019-10-09 下午4 03 29" width="921" src="https://user-images.githubusercontent.com/8850248/66462794-67e85800-eaae-11e9-997c-7e34a589ccfb.png">
> 
> It's still in an unimplemented state.

When will this feature be implemented? It's so useful

**Comment by liuchengxu** [comment]
No ETA. A lot of more important things need to be done.

**Comment by alerque** [comment]
@liuchengxu I understand everybody has different priorities, but in evaluating this for my own use this was the only thing I found that was a blocker to migrate from my `fzf-tmux` setup which has this feature. Everything else I actively use was on par or better with what.

**Comment by liuchengxu** [comment]
I have raised the priority of this issue in the favor of the requests. Please have a try with #39 and let me know if that doesn't work. @alerque @numbcoder
