### ISSUE TITLE
Python crashes during ":Clap files" after typing full file name

### ISSUE THREAD

**Issue by rliebz** [liuchengxu/vim-clap#341]
**Environment (please complete the following information):**
 - OS: MacOS
 - (Neo)Vim version: NVIM v0.5.0-e35ff7371 / VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 17 2020 07:39:47) — Same issue on both
 - vim-clap version: `5b48e30466517eac6d73bf9cacecfedadda28c5b` (latest)
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary:  Yes

**Describe the bug**
When doing a `:Clap files`, then typing the full name of a file in that directory, python will crash. For example, if there is a file called `README.md`, type `README.md` in the clap window. The crash should happen on the last character press.
```
vim-clap: Vim(return):Error invoking 'python_eval' on channel 4 (python3-script-host):^@ch 4 was closed by the client 
```

**Clap debug**

```
            has cargo: 1
            has maple: /Users/rliebz/.dotfiles/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.8, built for x86_64-apple-darwin by rustc 1.41.0 (5e1a79984 2020-01-27).
         has +python3: 1
has py dynamic module: 1
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/rliebz/.dotfiles/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!'}
    let g:clap_insert_mode_only = v:false
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_providers_relaunch_code = '@@'
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `nvim -u min.vim`

3. Type `:Clap files`

4. Type the full path of a file in the clap window, such as `README.md` while browsing files in `vim-clap`. 

5. Python will crash. In neovim, the following error message is produced:
```
vim-clap: Vim(return):Error invoking 'python_eval' on channel 4 (python3-script-host):^@ch 4 was closed by the client 
```

Regular `vim` will crash completely and produce the following error message:
```
Vim: Caught deadly signal ABRT
```

**Expected behavior**
Fuzzy filtering should continue normally without any crashing.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by liuchengxu** [comment]
Have you compiled the latest python dymamic module? You can try running `make` in the plugin root directory. I saw a similar issue and fixed it in https://github.com/liuchengxu/vim-clap/commit/18418f381c3c6b95166b2d512f12202d7ab2ef35. And I can't reproduce this issue now.

**Comment by rliebz** [comment]
Just tried running `make`, same issue. I also tried removing the `vim-clap` directory and reinstalling, same issue again.

For installation I used the following (I do have cargo on my system):
```vim
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary!' }
```

Something else I noticed now in debugging is that the issue is case sensitive, so `readme.md` will not trigger the crash if the file name is `README.md`.

**Comment by liuchengxu** [comment]
Just tried `README.md`, still works for me.

<img width="1141" alt="截屏2020-03-02下午8 44 17" src="https://user-images.githubusercontent.com/8850248/75677563-b8af5600-5cc6-11ea-987b-ec78a4d89dae.png">

If nothing helps, you could try disabling the python dynamic module by adding `let g:clap_use_pure_python = 1` to your vimrc. The performance should still be good as it will use the external Rust binary maple when neccessary.

**Comment by rliebz** [comment]
No crashing after `let g:clap_use_pure_python = 1`, so that's good news.
