### ISSUE TITLE
How to add self defined provider to command  and provider window?

### ISSUE THREAD

**Issue by leoatchina** [liuchengxu/vim-clap#346]
**Is your feature request related to a problem? Please describe.**
For example, I wrote this config in my .vimrc
```
    let g:clap_provider_config = {
                \ 'source': ['~/.vim.conf/init.vim', '~/.vimrc', '~/.zshrc', '~/.bashrc', '~/.tmux.conf'],
                \ 'sink': 'e',
                \ }
```

**Describe the solution you'd like**
This config works, furthermore,  I want to 
- `:Clap conf`, then followed by tap `<Tab>`, `:Clap config` should appear
- `:Clap providers`, then `config` menu should be added to the windows

**NOTES**,  do not write to  `autoload`

**Comment by liuchengxu** [comment]
That's unsupported at present.

**Comment by leoatchina** [comment]
So it has to be added to `autoload/provider` ?

**Comment by liuchengxu** [comment]
See how `Clap providers` is implemented https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/providers.vim. You have to also parse all the global variables for your case.

**Comment by leoatchina** [comment]
Ok , I got it

**Comment by liuchengxu** [comment]
See how `g:clap_provider_*` is added in debugging info https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/debugging.vim#L71-L78 if you are interested.
