### ISSUE TITLE
Error detected while processing function <lambda>4[1]..<SNR>39_buffers_on_move

### ISSUE THREAD

**Issue by delfick** [liuchengxu/vim-clap#355]
**Environment (please complete the following information):**
 - OS:  MacOS Catalina 10.15.3
 - (Neo)Vim version: neovim v0.4.3
 - vim-clap version: 516c369ec521cb83653947ac5bc0be8020540cb5
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary:  yes

**Describe the bug**
When I do `:Clap buffers` and move between files in the window, sometimes it'll give me an error about 39_buffers_on_move when I press enter to select that file. Note that it still does change to that file.

Sometimes it takes doing this a few times before it starts complaining, but once it starts it happens for every file. 

**Clap debug**

```
            has cargo: 1
            has maple: /Users/stephenmoore/.dotfiles/files/vim/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.9, built for x86_64-apple-darwin by rustc 1.41.0.
         has +python3: 1
has py dynamic module: 0
     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/stephenmoore/.dotfiles/files/vim/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_insert_mode_only = v:false
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_providers_relaunch_code = '@@'

```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-clap'
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }

call plug#end()
```

2. Start (neo)vim with command: `nvim -u min.vim`

3. do `:Clap buffers`. Move around and choose a file. Repeat a few times and eventually you'll see the following error

```
Error detected while processing function <lambda>4[1]..<SNR>39_buffers_on_move:
line    2:
E716: Key not present in Dictionary: 0
Error detected while processing function <lambda>4[1]..<SNR>39_buffers_on_move:
line    2:
E116: Invalid arguments for function matchstr
Error detected while processing function <lambda>4[1]..<SNR>39_buffers_on_move:
line    2:
E116: Invalid arguments for function str2nr
Error detected while processing function <lambda>4[1]..<SNR>39_buffers_on_move:
line    2:
E15: Invalid expression: str2nr(matchstr(s:line_info[bufnr], '\d\+'))
```

**Comment by liuchengxu** [comment]
Although I can simply silence this error as it's not critical, I want to reproduce it. Can you provide a more determistic way to reproduce? I can't reproduce with your current info.

**Comment by delfick** [comment]
Here's a video

https://www.youtube.com/watch?v=a68Vguf_IIs&feature=youtu.be

With your debugging info I get

```
curline:, s:extract_bufnr():, s:line_info:{'1': 'line 1', '2': 'line 1', '3': 'line 1', '4': 'line 1'}
```

**Comment by delfick** [comment]
thanks!
