### ISSUE TITLE
Support Open Action for Custom Providers

### ISSUE THREAD

**Issue by khalidchawtany** [liuchengxu/vim-clap#362]
**Is your feature request related to a problem? Please describe.**
I have a custom provider that lists my files. I want to be able to map `<c-t>` to open in new tab, `<c-s>` to open in split pane. etc.

**Describe the solution you'd like**
The sink could be passed a second argument containing the open action or the key pressed.
Since this means `<c-t>` need to be like `<cr>` terminating the clap selection window, a dictionary of keys that are to be treated as *open action* keys needs to be passed to the provider.

**Comment by liuchengxu** [comment]
`g:clap_open_action` works for all the clap providers, including the custom ones, so I don't understand what your request is.

**Comment by khalidchawtany** [comment]
I am sorry maybe I am doing something wrong. Here is what I want to do.
```vim
        let g:clap_laravel_entries =  {
                    \ 'Views': 'resources/views',
                    \ 'Models (PHP)': 'app',
                    \ 'Models (JS)': 'resources/assets/js/models/'
                    \ }

        let g:clap_provider_laravel = {
                    \ 'source': sort(keys(g:clap_laravel_entries)),
                    \ 'sink': { selected -> execute('edit ' .  g:clap_laravel_entries[selected])},
                    \ }

```

**Comment by liuchengxu** [comment]
```vim
        function! s:laravel_sink(selected)
          if has_key(g:clap, 'open_action')
            execute g:clap.open_action
          endif
          call execute(cmd)
        endfunction

        let g:clap_provider_laravel = {
                    \ 'source': sort(keys(g:clap_laravel_entries)),
                    \ 'sink': function('s:laravel_sink'),
                    \ 'support_open_action': v:true,
                    \ }
```

The default implementation for `open_action` is only avaliable for  the providers whose sink is `e/edit/edit!`, you have to tweak your `sink` function and make `support_open_action` be true explicitly, see https://github.com/liuchengxu/vim-clap/blob/master/PROVIDER.md#create-non-pure-async-provider

**Comment by khalidchawtany** [comment]
Thank you very much.
