### ISSUE TITLE
wrap the display window

### ISSUE THREAD

**Issue by ErrEoE** [liuchengxu/vim-clap#367]
I want enable `wrap` the display window of vim-clap, when i set
```
autocmd User ClapOnEnter call g:clap.display.setbufvar('&wrap', 1)
```
but it's no affect. Anyone can help me? I use gvim for windows.

**Comment by liuchengxu** [comment]
The right way to set `wrap` for vim popup seems to use `popup_setoptions()`, this should work.

```vim
autocmd User ClapOnEnter call popup_setoptions(g:clap.display.winid, {'wrap': 1})
```
