### ISSUE TITLE
Lightline does not update after closing clap

### ISSUE THREAD

**Issue by vn-ki** [liuchengxu/vim-clap#374]
**Environment (please complete the following information):**
 - OS: ???
 - (Neo)Vim version: Master
 - vim-clap version: Latest
 - Have you reproduced with a minimal vimrc: Yup

**Describe the bug**
Before invoking clap
![image](https://user-images.githubusercontent.com/31964688/78333229-0f9a9a80-75a7-11ea-87bd-0489f35a64c1.png)
After invoking clap
![image](https://user-images.githubusercontent.com/31964688/78333311-348f0d80-75a7-11ea-9089-2a62a2efb7d7.png)
After closing clap
![image](https://user-images.githubusercontent.com/31964688/78333333-41136600-75a7-11ea-9f7e-0d798f068878.png)

As you can see light line is not updated.

**To Reproduce**

Install lightline and open and close Clap.

**Additional context**
https://github.com/voldikss/vim-floaterm/issues/19 : This issues describes the exact same problem.

**Comment by liuchengxu** [comment]
The interesting thing is that vim don't have this issue, it happens to neovim only.

You can add this workaround in your vimrc, or ask lightline for a neater solution:

```vim
autocmd User ClapOnExit call lightline#update()
```
