### ISSUE TITLE
Ability to add custom key bindings to the popup

### ISSUE THREAD

**Issue by svermeulen** [liuchengxu/vim-clap#376]
**Is your feature request related to a problem? Please describe.**

It would be great if it was possible to change the default bindings found in `clap_input.vim`.  Not everyone would prefer to to use `pagedown`, `<down>`, `<c-k>`, etc. as they are defined in that file

**Describe the solution you'd like**
I'm not sure what the solution would be here.  One way I've seen this done is to assign a name to each of the bindings and then allow the user to add to a global map variable to pass in the keys they want for it.

**Describe alternatives you've considered**
Fork coc.nvim and change this file is the only way I see to do this

**Comment by liuchengxu** [comment]
So you are using neovim? That would be not hard to get this, see https://github.com/liuchengxu/vim-clap/issues/116#issuecomment-549816638.

**Comment by svermeulen** [comment]
Ohh ok great, thanks!  Yes I'm using neovim so I'll just use the approach there.  Btw you might consider mentioning this in the `Movement/Keybindings` section in the docs.  This is where I looked first

**Comment by liuchengxu** [comment]
Thanks for the suggestion. I'll add that to the docs when it's getting more stable. I'm not a fan of `<Plug>` things, and unlike neovim's floating_win, vim's popup is unfocusable, so I have not found a good way to add the custom key bindings.
