### ISSUE TITLE
Should not use gui_running variable for neovim

### ISSUE THREAD

**Issue by svermeulen** [liuchengxu/vim-clap#378]
My understanding of [this](https://github.com/neovim/neovim/pull/4155) neovim pull request is that colorschemes and plugins should not be calling `has('gui_running')` for neovim.  This causes vim-clap to not work well with neovim guis since this value always returns false (or at least does for me)

**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: v0.5.0-398-g51358bca9
 - vim-clap version: 4c6ebbdaa10319b76e2ad4a10af1944e37613698
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**
Neovim guis (eg. neovide) are not compatible with this plugin, because this plugin uses gui_running variable

**Clap debug**

![image](https://user-images.githubusercontent.com/810762/78507411-b1032700-7734-11ea-8d5f-0c1d30b8a15d.png)

```
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
call plug#begin('~/.vim/plugged')

Plug 'liuchengxu/vim-clap'

call plug#end()
```

2. Start neovide

3. Type 'Clap files'

4. See error:
![image](https://user-images.githubusercontent.com/810762/78507490-17884500-7735-11ea-9df6-62668033036c.png)

**Expected behavior**
Should not get errors when opening vim-clap from a neovim gui like neovide

**Comment by svermeulen** [comment]
Corresponding neovide bug was here: https://github.com/Kethku/neovide/issues/229

**Comment by liuchengxu** [comment]
Try this, should work for neovide at least.

```diff
diff --git a/autoload/clap/icon.vim b/autoload/clap/icon.vim
index 2d5db8f..acc7816 100644
--- a/autoload/clap/icon.vim
+++ b/autoload/clap/icon.vim
@@ -220,7 +220,7 @@ function! s:get_attrs(group) abort
 endfunction
 
 function! clap#icon#def_color_components() abort
-  let s:use_gui = has('gui_running') || (has('termguicolors') && &termguicolors)
+  let s:use_gui = exists('g:neovide') || has('gui_running') || (has('termguicolors') && &termguicolors)
   let s:gui_or_cterm = s:use_gui ? 'gui' : 'cterm'
 
   let s:normal_fg = s:get_color('Normal', 'fg')
```

**Comment by svermeulen** [comment]
Thanks, I'll use this for now
