### ISSUE TITLE
Ability to filter file name only instead of the full path for files provider

### ISSUE THREAD

**Issue by svermeulen** [liuchengxu/vim-clap#379]
**Is your feature request related to a problem? Please describe.**
I used to use LeaderF before transitioning to vim-clap, and I miss a feature that it has, where you can match only on file name instead of the entire file path.  This is also really nice when dealing with long paths because you can't even see the file name in that case when using `Clap files`

**Describe the solution you'd like**
An argument to `Clap files` which changes the behaviour to only list the file names and not the entire paths. eg `--names-only`

**Describe alternatives you've considered**
Implementing my own clap provider that does this instead of Clap files

**Comment by liuchengxu** [comment]
Just type what you want to search and you'll see them. Since #330, the long matched items won't invisible completely.

**Comment by liuchengxu** [comment]
Try #389, but you have to build the Python dynamic module, or uses the cached content for external dyn filter. I don't have time to optimize for the pure Python version.

**Comment by svermeulen** [comment]
How do I change to use the "python dynamic module" ?   I tried using that branch and it didn't work so I am guessing I'm not doing that currently

**Comment by liuchengxu** [comment]
See https://github.com/liuchengxu/vim-clap/blob/master/INSTALL.md#python-dynamic-module.

If you are using macOS or Linux, just go to the clap root directory and then running `make` should be ok. Finally, check if you have built it successfully via the info of `:Clap debug`.

**Comment by svermeulen** [comment]
Yep that fixed it.   Thanks for your work!
