### ISSUE TITLE
what hightlight group of border?

### ISSUE THREAD

**Issue by taigacute** [liuchengxu/vim-clap#380]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macos 10.15.4
 - (Neo)Vim version: neovim 0.5.0 nightly
 - vim-clap version: latest.
 - Have you reproduced with a minimal vimrc: not a bug
 - Have you updated to the latest plugin version: not a bug
 - Have you upgraded to/compiled the latest Rust binary: compiled

**Describe the bug**
Thanks for your great work. what highlight group of this area?

**Expected behavior**
I think set this bg to NONE its greate .

**Screenshots**
![image](https://user-images.githubusercontent.com/41671631/78533670-e8003800-781b-11ea-90b2-7faf43122439.png)

**Comment by liuchengxu** [comment]
It should be set to `NONE` automatically, something wrong with your `Normal` highlight group. Try setting `ClapSymbol` on your own.

**Comment by taigacute** [comment]
because i use the colorscheme provide  transparent background. another question is how can i build binary on dein? dein doesn't have a `do` hook.

**Comment by liuchengxu** [comment]
I don't use dein, ask at dein repo.

**Comment by MindTooth** [comment]
```viml
call dein#add('liuchengxu/vim-clap')
call dein#config('vim-clap', {
	\ 'hook_post_update': '
	\ 	call clap#installer#download_binary()
	\ ' })
```
