### ISSUE TITLE
UI leaves remnants of popup after Escaping action

### ISSUE THREAD

**Issue by alerque** [liuchengxu/vim-clap#388]
**Environment (please complete the following information):**
 - OS: Neovim
 - (Neo)Vim version: latest stable
 - vim-clap version: latest master (has been true for months now)
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes (isn't this redundant question)
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
Over the last several months I keep finding myself with the Clap popup window and/or artifacts from in up over my buffer that are not part of my active work.

The issue seems to be that <kbd>Esc</kbd> does not effectively close the window, although it does usually change the input focus to something else. This creates all sorts of messes when I start trying to use Clap for something and then change my mind rather than opening a file or completing at action.

I have in fact started to bake <kbd>CTRL-W</kbd> <kbd>O</kbd> into muscle memory to make my buffer pane the only thing open as a way to clear artifacts from Clap leftover from failed attempts to escape from it.

I think the fix is to be more aggressive about cleanup up the UI when input focus changes, even if this wasn't the result of a completed action.

**Comment by liuchengxu** [comment]
#387
