### ISSUE TITLE
webdevicons - support for custom icons

### ISSUE THREAD

**Issue by adelarsq** [liuchengxu/vim-clap#392]
I'm creating a plugin ([vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme)) that use [webdevicons](https://github.com/ryanoasis/vim-devicons) behind the scenes to allow use of emojis for filetypes instead of patched fonts.

For example NERDTree shows like this:

<img width="275" alt="Captura de Tela 2020-04-13 às 10 32 26" src="https://user-images.githubusercontent.com/430272/79124172-22188f00-7d72-11ea-9133-71d5cca1f0e9.png">

To support clap my plugin needs that this plugin use the icons provided by webdevicons (using something like the `WebDevIconsGetFileTypeSymbol(absolute_file_path)` function for example).

Is it possible?

**Comment by liuchengxu** [comment]
Hmm, that could be partially supported. It's possible for the sync filter, I can make the icons used in vimscript overridable.

https://github.com/liuchengxu/vim-clap/blob/ae4b74557b5107add599b2872cd52066d41fc580/autoload/clap/icon.vim#L11

But it's impossible to configure the icons used in Rust code https://github.com/liuchengxu/vim-clap/blob/master/crates/icon/src/constants.rs. I'm not sure if people can bare with these inconsistent icons.

**Comment by adelarsq** [comment]
> But it's impossible to configure the icons used in Rust code https://github.com/liuchengxu/vim-clap/blob/master/crates/icon/src/constants.rs. I'm not sure if people can bare with these inconsistent icons.

They can't. This turns the plugin unusable with clap at the moment. One on the objectives from the plugin (for the far future) is to create a interface that is consistent across plugins, even if is there no relation between each. For example a icon for a `buffer` on one plugin is the same for another.

> If people do want to change the icons used in Rust, the process is not convenient at present. He can update https://github.com/liuchengxu/vim-clap/blob/master/crates/icon/exactmatch_map.json, run python3 update_constants.py and recompile the maple binary.

What about to read this values from a `json` without use Python? Just a `*.json` file passed as argument for the Rust code with the desired icons.  So `EXTENSION_ICON_TABLE` and `EXACTMATCH_ICON_TABLE` can be filled at runtime.

**Comment by liuchengxu** [comment]
I'm reluctant as that's not the way of having optimal performance. If you can provide a JSON of emojis, I can consider make it a new builtin option.

**Comment by adelarsq** [comment]
> I'm reluctant as that's not the way of having optimal performance.

Definitely. But maybe that this is not so noticeable.

> If you can provide a JSON of emojis, I can consider make it a new builtin option.

I can provide. Some emojis need to have a space together to render properly on Vim/NeoVim, so need to be writed as strings. This can be done?

**Comment by liuchengxu** [comment]
You are right, an extra space is neccessary.

**Comment by adelarsq** [comment]
Yes. But not all chars. Some are fine on MacOS but are wrong on Linux. So I have to test each char for each platform. About Windows I don't know since I don't have one anymore, but last time that I did a test was working fine with GVim.
If necessary I can provide a different json list for each platform, let's see.

**Comment by adelarsq** [comment]
I have added some support for vim-clap:

<img width="1280" alt="Captura de Tela 2020-04-23 às 20 49 10" src="https://user-images.githubusercontent.com/430272/80160410-f4b6b700-85a3-11ea-9f8d-bfb7d3323896.png">

**Comment by adelarsq** [comment]
At moment I trying to figure out why Vim/NeoVim has so many problems rendering emojis. Some emojis are rendered just half, others keep showing on the screen (tests on Linux, Windows and Mac)... This is more complex than this issue on Clap, since we need to change on the Vim/NeoVim code base side.

So I decided to create another plugin for icons based on NerdFonts and I will close this issue for now. I will turn public the new plugin until next week.

**Comment by adelarsq** [comment]
I found a way to "solve". Basically some icons render right an others dont. So I need to use just the right icons. I will need some work, but works!
I will reopen the issue and provide a custom JSON to be used on this plugin.

**Comment by liuchengxu** [comment]
Hi @adelarsq, any progress on this issue?

**Comment by adelarsq** [comment]
Yes, did notice that depends on the terminal emulator too. For this I plan after the refactoring (to read all chars from a generated json) on next months to detect the terminal. So we will have a good behaviour even on Windows.

At moment I'm using [vim-clap](https://github.com/liuchengxu/vim-clap) with [vim-emoji-icon-theme](https://github.com/adelarsq/vim-emoji-icon-theme) daily and it's behaving well on iTerm. Need some more testing on Kitty since I don't use so often.

**Comment by liuchengxu** [comment]
With #654, you can use the custom icons easier, just modify the json file in https://github.com/liuchengxu/vim-clap/tree/master/crates/icon directly and recompile the Rust binary. But PR is still welcome :(.

**Comment by adelarsq** [comment]
@liuchengxu Nice! Thanks! I will add this feature on the next weeks 🙂
