### ISSUE TITLE
A keybinding to close Clap without select anything.

### ISSUE THREAD

**Issue by vufly** [liuchengxu/vim-clap#397]
**Is your feature request related to a problem? Please describe.**
Sometime I miss type a key and open Clap. However I cannot close it properly.
with `:q` the Clap windows close but there still something left floating on screen

**Describe the solution you'd like**
A keybinding to close Clap without select anything.

**Additional context**
![image](https://user-images.githubusercontent.com/20252099/79323184-0fe84d80-7f38-11ea-8584-2a2638b40913.png)

**Comment by liuchengxu** [comment]
Try `<C-c>` or `<C-g>`, `clap#handler#exit()` is the right way to exit clap.

https://github.com/liuchengxu/vim-clap/blob/aec8e6166dac04b5005c3f52c7313a0e80a4defc/ftplugin/clap_input.vim#L73-L74

But I think it might be worthy to remap `:q` in `clap_input` buffer to exit clap.
