### ISSUE TITLE
Support sync version of :Clap install-binary

### ISSUE THREAD

**Issue by Avi-D-coder** [liuchengxu/vim-clap#398]
`Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }` is non blocking.
If you put it in a command like:
 ```bash
nvim +PlugInstall +UpdateRemotePlugins +PlugUpgrade +PlugUpdate +CocUpdateSync +PlugDiff +'w ~/.PlugDiff' +qa
```
Nvim exits before maple is installed causing the child cargo processes to be killed.

See [`CocUpdateSync`](https://github.com/neoclide/coc.nvim/issues/411).

**Comment by liuchengxu** [comment]
It's intended, using the terminal feature is inherently async.

**Comment by Avi-D-coder** [comment]
In the interim, `Plug 'liuchengxu/vim-clap', { 'do': 'make' }` seems to work. Is there any downside to just calling make on Linux?

**Comment by liuchengxu** [comment]
Nope. `:Clap install-binary` essentially runs `make` using the terminal feature for macOS and Linux, https://github.com/liuchengxu/vim-clap/blob/a2f1dcc897/autoload/clap/installer.vim#L93-L97. If you don't use Windows and have installed the nightly Rust, `make` should always succeed.
