### ISSUE TITLE
Use a pre-existing fuzzy finder (fzy, selecta, pick)

### ISSUE THREAD

**Issue by joereynolds** [liuchengxu/vim-clap#4]
I think it would be beneficial to use a pre-existing fuzzy finder or at least make it configurable for a user to use their own fuzzy finder. There are many different ones and if I were to install this, I'd have two (vim-clap and fzy) on my PC instead of just the one I currently use.

Not to mention also that vim-claps fuzzy finder is coupled to vim so can't be used in the shell.

Thoughts?

**Comment by liuchengxu** [comment]
Well, you may have a misunderstanding here: **vim-clap is not a tool like fzy, selecta and pick, it's absolutely not a fuzzy finder and not designed to work in the shell**. Generally, vim-clap is a vim/neovim plugin based on the newly floating_win or popup to offer vimmers a more friendly way to filter and dispatch something.

**Comment by joereynolds** [comment]
My mistake, it seems I got it wrong here, thanks for the reply!
