### ISSUE TITLE
 preview support for FZF

### ISSUE THREAD

**Issue by blayz3r** [liuchengxu/vim-clap#40]
Just wanted to get clarification whether the preview feature referred to in the Read-Me is equivalent to the image below:

![image](https://user-images.githubusercontent.com/12205650/66595554-31234800-eb69-11e9-8930-401111df2445.png)

**Comment by liuchengxu** [comment]
Should be more flexible than the preview function of fzf in that the preview window of vim-clap is a complete floating window or popup. For example, you are able to scroll in the preview window in theory, but the interaction will become complex then, we'll need to figurate out an intuitive way if the scroll will be added eventually.

**Comment by blayz3r** [comment]
Thanks
