### ISSUE TITLE
Setting nospell for Clap results window

### ISSUE THREAD

**Issue by wbthomason** [liuchengxu/vim-clap#400]
**Environment (please complete the following information):**
 - OS: Linux
 - (Neo)Vim version: `master@e8269a3`
 - vim-clap version: `master@ca6b939`
 - Have you reproduced with a minimal vimrc: N/A
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Current behavior**
Opening a Clap window from a buffer where spell checking is enabled causes "misspelled" words to be highlighted. As Clap results include paths, tags, etc. that are typically not words, this leads to undesirable highlighting in the results behavior.

This can be fixed for the input window using `setlocal nospell` in an `after/ftplugin` for the `clap_input` filetype. However, it seems that the results window has an empty filetype, so this approach is (I think) not feasible for the results.

**Desired behavior**
Arguably, `nospell` should be set for all Clap windows at creation time.

**Comment by liuchengxu** [comment]
Actually you can use the `ClapOnEnter` hook, but I think it could be a default value.

**Comment by wbthomason** [comment]
Will `ClapOnEnter` work if you're trying to set buffer-local `nospell`, rather than global `nospell`? I could easily be wrong, but I thought that would require the results buffer to be the current buffer when `ClapOnEnter` triggers.

**Comment by liuchengxu** [comment]
`:h clap-api`, it's very flexible, with `ClapOnEnter` and `ClapOnExit`, you can basically do anything you want to.
