### ISSUE TITLE
Git Diff Preview Exceeds Window Height

### ISSUE THREAD

**Issue by corbinhesse** [liuchengxu/vim-clap#401]
- OS: macOs
 - (Neo)Vim version: nvim v0.4.3
 - vim-clap version: ca6b9393dbe178252be07689d93f14728aa8c7e7
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**
Window height not truncated in git_diff_files preview.
```
Error detected while processing function <lambda>4[1]..<SNR>89_git_diff_files_on_move[2]..52:
line    8:
E5555: API call: 'height' key must be a positive Integer
```

**To Reproduce**

1. Make numerous modifications in a file that result in multiple hunks and save.
2. Type `:Clap git_diff_files`
3. Navigate to file that exceeds preview window height
4. Error displays 

**Expected behavior**
Window height should truncate like the `files` preview window.

**Screenshots**
![Screen Shot 2020-04-16 at 7 42 08 AM](https://user-images.githubusercontent.com/4355830/79457439-d6eebe00-7fb5-11ea-8a00-80fb8700e513.jpg)

**Additional context**
It might be best to revert commit `ca6b9393dbe178252be07689d93f14728aa8c7e7` to give me more time to fix this issue.

*Acceptance Criteria*
- [ ] Truncate window height if larger than Clap set height.
- [ ] Check for `git` command on_move() after provider loads
- [ ] Pipe `git diff` command into tail to remove index: `| tail -n +5`
- [ ] Set lines on unified format to less than default to display more diff hunks: `git diff -U1`

**Comment by liuchengxu** [comment]
Quick fix:

```diff
diff --git a/autoload/clap/provider/git_diff_files.vim b/autoload/clap/provider/git_diff_files.vim
index f24bbff..3a0618f 100644
--- a/autoload/clap/provider/git_diff_files.vim
+++ b/autoload/clap/provider/git_diff_files.vim
@@ -23,7 +23,7 @@ endfunction

 function! s:git_diff_files_on_move() abort
   let filediff = systemlist('git diff '.g:clap.display.getcurline())
-  call g:clap.preview.show(filediff)
+  call g:clap.preview.show(filediff[:20])
   call g:clap.preview.set_syntax('diff')
 endfunction
```
