### ISSUE TITLE
:Clap install-binary! Failed on windows 10

### ISSUE THREAD

**Issue by TissueFluid** [liuchengxu/vim-clap#404]
**Environment**
 - OS: windows 10
 - Neovim v0.4.3, Gvim v8.2
 - vim-clap version: v0.12
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary:  Having issue when running `:Clap install-binary!`

**Describe the bug**

`:Clap install-binary!` failed on windows 10.

When the path to the install.ps1 contains spaces,  it will be considered as several separate parameters.  The fix is to quote the path to the install.ps1.

And even if the path doesn't contain spaces , windows 10 would prevent user running powershell script based on the default execution policy configuration. The fix is when executing powershell script, add ` -ExecutionPolicy ByPass` to be able to run it. 

Ref: [Powershell Execution Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7)

And even if all the above two problems are fixed, the install.ps1 will still fail showing the DownloadFile function cannot create SSL/TLS secure channel. This is because TLS12 is not enabled in powershell by default. The fix is to add TLS12 to the security protocol .
Mentioned by @masaeedu in https://github.com/lukesampson/scoop/pull/2065#issuecomment-369669048
```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
```
[Net.ServicePointManager](https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepointmanager.securityprotocol?view=netframework-4.8)
[SecurityProtocolType Enum](https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=netframework-4.8#System_Net_SecurityProtocolType_SystemDefault)

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```
Case 1: path contains space
Case 2: path is good
Case 3: path is good and no issues with execution policy

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap install-binary!`
Case 1
![IEUPX``2(BWZD(NT9UUM6JQ](https://user-images.githubusercontent.com/1442702/79655680-7acb9b80-8167-11ea-8d48-d499e4cbcb23.png)
Case 2
![}%@`R{GDPS55_SF@NDAPOOD](https://user-images.githubusercontent.com/1442702/79657220-eca3e500-8167-11ea-95b0-6ec71c4f94aa.png)
Actually this is an output from the command line, but you will see same output from the vim.
Case 3
![D MT46 (Z2E9T$TZ 0X) {0](https://user-images.githubusercontent.com/1442702/79668588-304c1e00-816b-11ea-8f57-ded483cb96e3.png)

**Expected behavior**
Install binaries successfully and see the success message.

I created a PR which did the following things:
1. quote the path to the install.ps1
2. bypass powershell's execution policy
3. Add Tls12 to the security protocal

I tested for both Neovim v0.4.3 and Gvim v8.2 on windows10.
Created a pull request for this #405 . What do you think?

**Comment by TissueFluid** [comment]
Wait, Actually, I found another error message after fixed the above things.

![%U%Y6IAGU X8)RN9B3PO0K7](https://user-images.githubusercontent.com/1442702/79672037-34843580-8183-11ea-8cb6-e26664a0aff5.png)

And although the maple.exe is downloaded successfully. Still it cannot get the version info. 
![JO_20A PND $_(5V6{W_Y@L](https://user-images.githubusercontent.com/1442702/79672188-b45ecf80-8184-11ea-835d-7fdfd9eba068.png)

**Comment by TissueFluid** [comment]
Found another place  where space is not handled properly. When auto determined s:maple_bin has spaces in it, commands constructed with it will not function well.
For example
```
:echo system(clap#maple#binary(). ' version')
```
Again, this only happens when using `:Clap install-binary!`

**Comment by TissueFluid** [comment]
Found some other issues. Discussed in #405

**Comment by liuchengxu** [comment]
I have tested on my mac and linux, `echo system('"' . clap#maple#binary(). '" version')` both works.

Since you have downloaded the maple binary, can you see if it can work as expected on Windows, e.g., run `:Clap grep2`, mostly to see if we need to quote `s:maple_bin` in `autoload/clap.maple.vim`. Currently I'm sure it works on mac and linux, but I'm unsure everything works on windows as I don't have a windows machine. If you have some more time, you could also take a look this issue https://github.com/liuchengxu/vim-clap/issues/370, filer provider is broken on Windows at the moment.

**Comment by liuchengxu** [comment]
This patch should fix the error `Undefined variable: bufnr`.

```diff
diff --git a/autoload/clap/installer.vim b/autoload/clap/installer.vim
index a32d27a..e5cf897 100644
--- a/autoload/clap/installer.vim
+++ b/autoload/clap/installer.vim
@@ -12,7 +12,7 @@ function! s:run_term(cmd, cwd, success_info) abort

   function! s:OnExit(status) closure abort
     if a:status == 0
-      execute 'silent! bd! '.bufnr
+      execute 'silent! bd! '.s:bufnr
       call clap#helper#echo_info(a:success_info)
     endif
   endfunction
@@ -30,7 +30,7 @@ function! s:run_term(cmd, cwd, success_info) abort
           \})
   endif

-  let bufnr = bufnr('')
+  let s:bufnr = bufnr('')

   normal! G
```

**Comment by TissueFluid** [comment]
Thanks for the patch and  I'll take a look at #370

**Comment by TissueFluid** [comment]
Quoting works.
```diff
--- a/autoload/clap/maple.vim
+++ b/autoload/clap/maple.vim
@@ -16,10 +16,10 @@ let s:maple_bin_prebuilt = fnamemodify(g:clap#autoload_dir, ':h').'/bin/maple'.s

 " Check the local built.
 if executable(s:maple_bin_localbuilt)
-  let s:maple_bin = s:maple_bin_localbuilt
+  let s:maple_bin = '"' . s:maple_bin_localbuilt . '"'
 " Check the prebuilt binary.
 elseif executable(s:maple_bin_prebuilt)
-  let s:maple_bin = s:maple_bin_prebuilt
+  let s:maple_bin = '"' . s:maple_bin_prebuilt . '"'
 elseif executable('maple')
   let s:maple_bin = 'maple'
```
I guess this is the minimal change I can do to make it work.
Just had some thoughts on this. I looked at the doc of start_job function.
```
jobstart({cmd}[, {opts}])				*jobstart()*
		Spawns {cmd} as a job.
		If {cmd} is a List it runs directly (no 'shell').
		If {cmd} is a String it runs in the 'shell', like this: >
		  :call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])
		(See |shell-unquoting| for details.)

```
So the cmd can be a list. The same as termopen. If we pass command as a list, we don't need to escape anything. Just like the ` subprocess.call()` function in Python. For example:
```
:call termopen(['c:\Users\A name with space\.vim\plugged\vim-clap\bin\maple.exe', 'version'])
```
This one will give me the correct result
```
version 0.1.12 (git v0.12), built for x86_64-pc-windows-msvc by rustc 1.42.0 (b8cedc004 2020-03-09).

[Process exited 0]
```
If we pass everything as a string. Then, it acutually does `  :call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])`, which will require us to escape characters if needed, because spaces between parameters and spaces as part of the parameter string are different.

**Comment by liuchengxu** [comment]
Using a list sounds a complete solution, we can do this, just need a Windows tester. Will let you know once I'm done with the list job arguments refactoring.

**Comment by TissueFluid** [comment]
I fixed the `:Clap grep2`. There's only 1 place that you forgot to quote cmd_dir
https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/maple.vim#L243

![$)E9}C{Q2PM`VQG8XYJ1)TI](https://user-images.githubusercontent.com/1442702/79710377-ac348c00-8279-11ea-964e-f380876d868b.png)

**Comment by liuchengxu** [comment]
There are some bug fixes about the Rust binary since https://github.com/liuchengxu/vim-clap/releases/tag/v0.12, I'll prepare a new release soon. Remember to update once new release is avaliable :(. @TissueFluid

**Comment by TissueFluid** [comment]
Will do.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-clap/releases/tag/v0.13 has been released. @TissueFluid
