### ISSUE TITLE
Center popup on active split, not full window

### ISSUE THREAD

**Issue by alerque** [liuchengxu/vim-clap#41]
Low priority feature request...

When you have a couple splits open and launch the popup and it centers itself on the window, it is easy to loose track of where you were when you started. The resulting file open, split, or other operation is going to happen in the particular buffer that was active at the time of launching, but with the popup potentially over a different buffer it's easy to get confused.

Positioning (and sizing) the popup centered over the active buffer should make this feel better for many scenarios.

Obviously this should be a configuration option because some peoples' workflows will make the current behaviour more desirable.

**Comment by liuchengxu** [comment]
Try #240.

**Comment by liuchengxu** [comment]
I think it's a nice feature to let clap window relative to current window, so I'll make this the default behaviour.

**Comment by alerque** [comment]
Thanks for working on this! I see there is other layout options for window size too, that will be nice. I'm not going to be in a position to mess about with test this until next week. If you do go ahead and merge before then I think defaulting to the window relative behavior is fine, those that use splits a lot will also be able to configure this to their liking.

**Comment by liuchengxu** [comment]
I have merged #240 . Let me know if you have any other suggestions.
