### ISSUE TITLE
Provider :: Files :: Customise finder executable / finder options using global variables

### ISSUE THREAD

**Issue by lcrockett** [liuchengxu/vim-clap#414]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
In the `grep` provider global provisions have been made available (`clap_provider_grep_executable` + `clap_provider_grep_opts`) to specify the executable and it's to-be used options. See `https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/grep.vim#L9-L10`.

Can the same provisions be made available to the `files` provider ? More specifically, I would like to be able to specify `clap_provider_files_opts` to contain `--exclude .git --hidden --no-ignore-vcs`. I'm aware I can specify `:Clap files --hidden`, but that doesn't cover the other `fd` arguments.

In addition, being able to specify a different finder executable could be beneficial as it seems `fd` is always preferred, even if `rg` or `find` are available on the system.

**Describe alternatives you've considered**
No alternatives have been considered as the feature request entails `vim-clap` internals.

**Additional context**
.

**Comment by liuchengxu** [comment]
`:h clap-files`, use `++finder` to specify another finder executable.

**Comment by lcrockett** [comment]
Perfect, works as intended ! Apologies for the `:h` noise.
