### ISSUE TITLE
Popup :: Preview :: Show line numbers

### ISSUE THREAD

**Issue by lcrockett** [liuchengxu/vim-clap#415]
I would like to enable line numbers in the preview window when doing, for instance, a `:Clap grep` or `:Clap files`. This implies I have to negate the defaults stated in `autoload/clap/popup.vim` on line `132`:

https://github.com/liuchengxu/vim-clap/blob/4eb56cb442d3a62811c7bf950722950a9a6fa703/autoload/clap/popup.vim#L132

I have tried using a `ClapOnEnter` `autocmd` to negate it, however to no avail. Is it possible at all to enable line numbers in the preview window ?

I have been fiddling around with the following snippet:

```
    function! ClapPreviewOptions() abort
        call popup_setoptions(g:clap.preview.winid, {'number': 1})
    endfunction

    autocmd User ClapOnEnter call ClapPreviewOptions()
```

**Comment by liuchengxu** [comment]
Since the workaround works, what's your request then?

**Comment by lcrockett** [comment]
The issue is that the workaround does not work. Therefore I was wondering on how to get it to work.

**Comment by liuchengxu** [comment]
```vim
autocmd User ClapOnEnter call win_execute(g:clap.preview.winid, 'setlocal number')
```

**Comment by lcrockett** [comment]
That seems to work well, thanks !
