### ISSUE TITLE
`:Clap files` results in python import errors

### ISSUE THREAD

**Issue by xulongwu4** [liuchengxu/vim-clap#421]
I have latest `vim-clap` (v0.15) installed and built the python dynamic module successfully. However, when I tried running `:Clap files", I got the following error message:
> vim-clap: Vim(python3):ImportError: cannot import name 'clap_fzy_rs' from 'clap.fzy' (/home/oulongwu/.vim/pack/plugins/start/vim-clap-0.15/pythonx/clap/fzy.py

**Comment by liuchengxu** [comment]
Rebuild the Python dynamic module completely and if the error persists, you can disable the dynamic module using `let g:clap_use_pure_python = 1`. The python dynamic module is not neccessary. And there is no changes about Python dynamic module in since v0.14.

**Comment by xulongwu4** [comment]
> Rebuild the Python dynamic module completely
To be clear, this is a new install from scratch so the python dynamic module is built from scratch. I also tried master branch and the error message is the same.

**Comment by liuchengxu** [comment]
Can't reproduce, could be an issue of your local environment.
