### ISSUE TITLE
:Clap files :: Fuzzy search :: Matches only from left to right

### ISSUE THREAD

**Issue by lcrockett** [liuchengxu/vim-clap#422]
# Behaviour
Using fuzzy searching patterns upon initiating `:Clap files` allows me to match from left to right only. Using the same keywords in a different order, right to left, does not return any results.

# Question
Is there a configuration setting that influences this behaviour ? I would like to specify any exact keyword regardless order and still get a match.

# Example :: Left to right
![vim-clap-left-to-right](https://user-images.githubusercontent.com/58056722/80918389-f5e6a180-8d64-11ea-8578-7d6692087e63.png)

# Example :: Right to left
![vim-clap-right-to-left](https://user-images.githubusercontent.com/58056722/80918391-f7b06500-8d64-11ea-9429-30aaa7f8aa29.png)

# Custom settings
```
    " Option :: Plugin :: vim-clap
    autocmd User ClapOnEnter call ClapPreviewToggle()
    let g:ClapPrompt = function('ClapFormat')
    let g:clap_disable_bottom_top = 1
    let g:clap_layout = { 'width': '88%', 'height': '40%', 'row': '25%', 'col': '8%' }
    let g:clap_on_move_delay = 50
    let g:clap_popup_input_delay = 50
    let g:clap_provider_grep_executable = 'rg'
    let g:clap_provider_grep_opts = '--glob !.git/ --hidden --no-heading --smart-case --vimgrep'
    let g:clap_selected_sign = { 'text': 'ﱣ ', 'texthl': "ClapSelectedSign", "linehl": "ClapSelected" }
    let g:clap_theme = 'material_design_dark'
```

**Comment by liuchengxu** [comment]
That works as expected for the substring algorithm used in clap https://github.com/liuchengxu/vim-clap/blob/master/pythonx/clap/fuzzymatch-rs/src/lib.rs#L16. I'm happy to accept PR that implements the order-insenitive substring filter, but I won't do it myself as the current one works great for me.

**Comment by lcrockett** [comment]
Hi @liuchengxu, thank you for the prompt reply. As i'm not a developer I wouldn't be able to help you with a PR. I'm happy to test or contribute in another way however if this feature does get more attention in the future. Cheers !
