### ISSUE TITLE
[Feature Request] Allow customizing Maple scoring

### ISSUE THREAD

**Issue by wbthomason** [liuchengxu/vim-clap#428]
**Is your feature request related to a problem? Please describe.**
I have noticed that Maple's scoring function doesn't always order results as I would like.

**Describe the solution you'd like**
I would like to be able to configure Maple's scoring, similarly to how Skim allows sort order configuration: https://github.com/lotabout/skim#sort-criteria

**Describe alternatives you've considered**
I could use another filter provider, but then I'd lose features Maple provides in vim-clap.

**Comment by liuchengxu** [comment]
Currently only the `socre` is considered when ranking, mostly what we need to tweak these lines, it's not hard:

https://github.com/liuchengxu/vim-clap/blob/d8ff7dc8b41e3be15810718163202df0c1122405/crates/maple_cli/src/cmd/filter/dynamic.rs#L385

https://github.com/liuchengxu/vim-clap/blob/d8ff7dc8b41e3be15810718163202df0c1122405/crates/maple_cli/src/cmd/filter/dynamic.rs#L364

https://github.com/liuchengxu/vim-clap/blob/d8ff7dc8b41e3be15810718163202df0c1122405/crates/fuzzy_filter/src/lib.rs#L74

What I'm unsure is whether it's easy to also tweak the related part in dynamic filter:

https://github.com/liuchengxu/vim-clap/blob/d8ff7dc8b41e3be15810718163202df0c1122405/crates/maple_cli/src/cmd/filter/dynamic.rs#L101

Or we could just ignore this if it's not trivial. @ImmemorConsultrixContrarie Any suggestions?

**Comment by ImmemorConsultrixContrarie** [comment]
>  @ImmemorConsultrixContrarie Any suggestions?

I need a full description on the options and how they should work. Shouldn't be hard, but I can't write things that I don't know how to write.

**Comment by liuchengxu** [comment]
I'm not familiar with skim's options too, but here are my quick thoughts: Currently we rank the fuzzy filtered items by the score solely(The bigger, the better), thus the order is indeterminate for these items having the same score. Actually we have these info more than the score:

```Rust
// (raw line, score, indices of matched chars)
pub type FuzzyMatchedLineInfo = (String, i64, Vec<usize>);
```

An improved ranking strategy could be:

1. Firstly sort by score, bigger is better.
2. If the scores are equal, compare the first item of matched indices, smaller is better.
3. If the first items are equal, compare the length of raw line, shorter is better.

For the final rule, we need to spend some time learning about the `--tiebreak` option of skim or fzf. @wbthomason Or can you share some more info? You must be more familiar with them.

**Comment by wbthomason** [comment]
@liuchengxu I'm not very familiar with Skim - I read about its options because I read that Maple used Skim's algorithm.

From its README, it seems that it allows users to specify a priority order for breaking ties over the features:
- Score
- Index (raw line number)
- Beginning position of match
- Ending position of match
The order of features (which the user can set at run time) determines what (and in what order) Skim's comparison function checks to break ties between items.

For example, specifying `--tiebreak score,begin,index` would (I believe) sort first by score, then (for any ties) prefer items where the match starts earlier in the string, then (for any remaining ties) prefer items with an earlier line number in the original input.

**Comment by wbthomason** [comment]
I think the main distinction between what @liuchengxu mentions and the approach Skim takes is that the sort strategy is configurable at run time for Skim.

**Comment by liuchengxu** [comment]
The sort criteria feature has been initially supported and can be configured in the user config file in #932. But I find the improvement is limited (for me) in fact as the base matching algorithm is already pretty good. Regarding the ability to configure it at runtime, we can support it by reloading the config file later.
