### ISSUE TITLE
Ability to display floating window popup over top of the full screen instead of just the current window

### ISSUE THREAD

**Issue by svermeulen** [liuchengxu/vim-clap#434]
**Is your feature request related to a problem? Please describe.**
In some cases I find myself opening vim-clap in a window that has a small width, which causes the clap window to be very small as well, and this seems unnecessary given all the extra window space that it could use instead.

**Describe the solution you'd like**
A flag to cause vim-clap to center itself over top of all window splits in the current tab, instead of just the current window

**Describe alternatives you've considered**
N/A

**Additional context**

Example:
![image](https://user-images.githubusercontent.com/810762/82157271-49f98780-9835-11ea-82d8-fae61b692984.png)

**Comment by liuchengxu** [comment]
`let g:clap_layout = { 'relative': 'editor' }`, see `:h g:clap_layout`.

**Comment by svermeulen** [comment]
Thank you!

**Comment by wookayin** [comment]
Why isn't this a default option? Isn't it more sensible?

**Comment by liuchengxu** [comment]
Well, can't say everyone is on the same page, see the origin feature request #41.
