### ISSUE TITLE
Buffers per Tab

### ISSUE THREAD

**Issue by adelarsq** [liuchengxu/vim-clap#439]
**Is your feature request related to a problem? Please describe.**

Tabs on Vim are just "views" allowing you to arrange buffers visually. I don't find this so useful, so I use buffers per tab.

**Describe the solution you'd like**

For this would be necessary two features:

- list buffers - list buffers per tab on `Clap buffers`
- close buffer - allow to close a buffer selected on `buffers` window (with some mapping), because after close a buffer another on the same tab need to be selected

Also would be nice to provide some information for tabline plugins, like the number of buffers opened per tab.

**Describe alternatives you've considered**

At moment I use another plugin for this ([vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace)).

**Additional context**

I use tabs through [vim-ctrlspace](https://github.com/vim-ctrlspace/vim-ctrlspace) to manage the list buffer per tab. It's a nice feature since keep small the information overload, since we can group buffers per tab, one tab per work or project.

Is it possible something like that on vim-clap?

**Comment by liuchengxu** [comment]
How does it differ from the current `:Clap buffers`? I don't quite understand what this request is, are you hoping to improve the `buffers` provider with some tab info added or create a new provider?

**Comment by adelarsq** [comment]
For example. On the follow screenshot we have 2 tabs, one opened with [material.vim](https://github.com/kaicataldo/material.vim) as current working directory and another for [investigate.vim](https://github.com/Keithbsmiley/investigate.vim) and using the `Clap buffers` to show the current opened buffers:

<img width="678" alt="Captura de Tela 2020-05-21 às 12 38 08" src="https://user-images.githubusercontent.com/430272/82576262-04ec9280-9b60-11ea-9099-a4d9c458570d.png">

The proposal is to hide the buffer from the another tab (buffer 23), so we can see only the `LICENSE` file. So we know that all buffers showed are from [material.vim](https://github.com/kaicataldo/material.vim). Something like on [this question](https://vi.stackexchange.com/questions/4091/how-to-bind-a-set-of-buffers-to-a-tab).

> are you hoping to improve the buffers provider with some tab info added or create a new provider?

The easier way, since can't ignore the default behavior. May be that to create something like `Clap buffers_per_tab` is easier to manage.

**Comment by liuchengxu** [comment]
>The proposal is to hide the buffer from the another tab (buffer 23)

It's very easy.

**Comment by liuchengxu** [comment]
Try #440, and use `let g:clap_provider_buffers_cur_tab_only = v:true` .

**Comment by adelarsq** [comment]
Thanks. I did a test but just shows one buffer opened per tab, even with more opened.

**Comment by liuchengxu** [comment]
Ok, I misunderstood `tabpagebuflist()` then, I thought it returns all the buffer per page.

**Comment by adelarsq** [comment]
You were right. `tabpagebuflist()` returns the list for the current tab. I did a test here, so the bug is on another place.

**Comment by liuchengxu** [comment]
Nope, `tabpagebuflist()` only returns the list of buffers associated with a window, the hidden buffers are not included.

**Comment by adelarsq** [comment]
Ops... I misread.

**Comment by adelarsq** [comment]
One buffer can be part on more than one tab. So hidden buffers don't have association with a tab. I didn't find another way that is not to control "by hand".

**Comment by liuchengxu** [comment]
Try this commit https://github.com/liuchengxu/vim-clap/pull/440/commits/a375df5693d8b50fb072e7580ec30c34756fc87e, should work now, but can't guarantee it can work everywhere as I don't use this feature.

**Comment by adelarsq** [comment]
Nice! I was thinking about one approach similar that you used. I think that works. I will test now.

**Comment by adelarsq** [comment]
@liuchengxu The only bug was when `g:clap_provider_buffers_cur_tab_only` don't exists, that cause an error on `OnBufDelete` function. Others use cases are working fine.

**Comment by liuchengxu** [comment]
What's the error? I don't see it.

**Comment by adelarsq** [comment]
Without the variable, after to open NeoVim with Startify and call `:NERDTree` shows:

<img width="592" alt="Captura de Tela 2020-05-28 às 14 19 41" src="https://user-images.githubusercontent.com/430272/83172677-5233ab80-a0ee-11ea-898a-058b4db48832.png">

From portuguese to english:

```
Detected error to process <SNR>80_OnBufDelete:
E716: Missing key on dictionary: 1
E116: Invalids arguments for the function index
E15: Invalid expression: index(g:__clap_tab_buffers[tabpagenr()], a:bufnr)
```

This bug occurs always that the var don't exists and open a new NeoVim instance or create a new tab.

**Comment by liuchengxu** [comment]
Should be fixed in the latest commit 79fea46.

**Comment by adelarsq** [comment]
Good job! It's working for the three use cases: without `g:clap_provider_buffers_cur_tab_only`, with `v:false` and with `v:true`.

**Comment by adelarsq** [comment]
@liuchengxu For some reason this feature stopped to work on this week.

On the first time that I call `Clap buffers` shows as expected. But after successive calls for `Clap buffers` just shows one or none file. I'm trying to figure out why this occurs.

**Comment by QiBaobin** [comment]
Hey @liuchengxu , I am trying this feature, but it always return an empty list of buffers. Below is my config, anything I missed? 

```
    use { 'liuchengxu/vim-clap', run = ':Clap install-binary', config = function()
      vim.api.nvim_command[[
        let g:clap_layout = { 'relative': 'editor' }
        let g:clap_provider_buffers_cur_tab_only = v:true
      ]]
      vim.api.nvim_set_keymap('n', '<Leader>f',  ':Clap files<CR>', { noremap = true })
      vim.api.nvim_set_keymap('n', '<Leader>b',  ':Clap buffers<CR>', { noremap = true })
end}
```
