### ISSUE TITLE
"Clap buffers" fails when :term is the current buffer

### ISSUE THREAD

**Issue by sscherfke** [liuchengxu/vim-clap#44]
**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: 0.4.x
 - vim-clap version: bf6d561
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When the neovim term (`:term`) is the current buffer, `:Clap buffers` only shows an error message in the flowting window: `provider.get_source: Vim(lcd):E472: Command failed`

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:term<CR>:Clap buffers<CR>`

**Expected behavior**
Show the list of openbuffers.

**Comment by liuchengxu** [comment]
Try #45.

**Comment by sscherfke** [comment]
Other commands (e.g., files and grep) have similar issues.

**Comment by liuchengxu** [comment]
Should be fixed now.

**Comment by sscherfke** [comment]
Thanks a lot! :-)
