### ISSUE TITLE
Is it possible to replace command-mode with vim-clap ?

### ISSUE THREAD

**Issue by collegeimprovements** [liuchengxu/vim-clap#441]
Vim-Clap is very nice.
Is there a way to type/run command from vim-clap's ui that we generally run from command-mode (i.e. by pression `:` from normal mode).

![Screenshot 2020-05-24 at 8 59 27 PM](https://user-images.githubusercontent.com/1519705/82757988-772fd200-9e01-11ea-89ec-208a8d16cd46.png)

That way we don't need to look at the bottom of the screen very often.

**Comment by liuchengxu** [comment]
That looks kind of `:Clap command_history`, the missing part in `command_history` is when you insert a new command that does not exist in the history, just execute the new command instead of showing no matches found prompt.

**Comment by collegeimprovements** [comment]
Thanks @liuchengxu, this is very close to what i was trying. I am trying to configure `vim-clap` more like what `alfred` is to `mac`.
