### ISSUE TITLE
Prefer files in the current directory

### ISSUE THREAD

**Issue by hanschen** [liuchengxu/vim-clap#455]
**Is your feature request related to a problem? Please describe.**
I usually use `Clap files/gfiles/grep` to open files. In most cases I'm looking for a file in the current working directory, but in some cases I want to open a file in a different project directory.

Currently Clap shows matches from all project directories, which often requires me to scroll to the file in the current working directory.

**Describe the solution you'd like**
It would be nice to have an option to sort matches from `Clap files/gfiles/grep` (and possibly other commands?) so that files in the current working directory are shown at the top, followed by matches in subdirectories of the current directory, and finally other project directories.

**Describe alternatives you've considered**
 I know I can use e.g. `Clap files .` to only search for files in the current working directory only, but then I would need two mappings for each command, one for the current working directory and another for all project directories.

**Comment by liuchengxu** [comment]
By default vim-clap will use the project root directory for these providers. If you want to search another directory, you have to specify that directory explicitly.

>so that files in the current working directory are shown at the top, followed by matches in subdirectories of the current directory, and finally other project directories.

Not all people are fan of this assumption, and I don't know how to implement this. PR welcome anyway.
