### ISSUE TITLE
non-popup window for clap

### ISSUE THREAD

**Issue by 20jam** [liuchengxu/vim-clap#462]
I’m used to the old style of `ctrlp` and `commandt` fuzzy without floating windows which I dislike in spite of the hype around it.

I’d like an option to have non-floating, commandt/ctrlp like interface.

I use `commandT`, its great and all but `clap` is just awesome and great. (thanks for all the effort)

**Comment by liuchengxu** [comment]
I accept PR but won't do it myself, see https://github.com/liuchengxu/vim-clap/issues/304#issuecomment-582444284 if you don't like the default layout.
