### ISSUE TITLE
Neovim crashes on resize

### ISSUE THREAD

**Issue by PsiPhire** [liuchengxu/vim-clap#466]
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - (Neo)Vim version: 0.4.3
 - vim-clap version: latest master
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**
After opening vim-clap, resizing neovim will lead to a segfault:
```
/home/travis/build/neovim/bot-ci/build/neovim/src/nvim/message.c:2231: msg_scroll_flush: Assertion `pos_delta >= 0' failed.
```
This doesn't happen if I rollback to the vim-clap version before #460, so I suspect it has to do with the `VimResized` event.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Open vim-clap (e.g. `:Clap files`)

4. Resize neovim window (multiple times) and observe crash.

**Expected behavior**
To not crash.

**Comment by erw7** [comment]
This is a known issue with neovim/neovim#12432. Also, neovim should not be crashed by any behavior of the plugin. Therefore, this is not an appropriate place to report to. Please close this.

**Comment by liuchengxu** [comment]
Hopefully https://github.com/liuchengxu/vim-clap/pull/593 has solved this too. Feel free to reopen if you still see it.
