### ISSUE TITLE
Publish static maple binary to release page

### ISSUE THREAD

**Issue by patrickpichler** [liuchengxu/vim-clap#469]
Wouldn't it make more sense to publish the static binary of maple to the release page instead of the dynamically linked one? 

Then people should not run into issues with libssl when giving vim-clap a shot.

**Comment by liuchengxu** [comment]
PR welcome, Linux users can also build the binary using Docker https://github.com/liuchengxu/vim-clap/blob/master/INSTALL.md#linux.

**Comment by patrickpichler** [comment]
Yes I saw it, but thought it would be a better user experience to use the statically compiled binary as it should work for more people out of the box.

I might have some time to take a look at it. But anyway thanks!

**Comment by liuchengxu** [comment]
The static binary has been provided since https://github.com/liuchengxu/vim-clap/releases/tag/v0.20.
