### ISSUE TITLE
Issue with the vim-numbertoggle plugin

### ISSUE THREAD

**Issue by runiq** [liuchengxu/vim-clap#472]
**Environment**

 - OS: **Fedora 32**
 - Neovim version: **0.4.3**
 - vim-clap version: **0.19**
 - Have you reproduced with a minimal vimrc: **Yes (see below)**
 - Have you updated to the latest plugin version: **Yes**
 - Have you upgraded to/compiled the latest Rust binary: **Yes** 

**Describe the bug**

After closing the vim-clap window, `relativenumber` is not being set, even though it should be.

**Clap debug**

```
            has cargo: 1
            has maple: /home/ajaam/.local/share/nvim/pack/minpac/start/vim-clap/target/release/maple
           maple info: version 0.1.19, built for x86_64-unknown-linux-gnu by rustc 1.45.0-beta.3 (8196407f0 2020-06-27).

         has +python3: 1
has py dynamic module: 1
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/ajaam/.local/share/nvim/pack/minpac/start/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

    ```vim
    set nocompatible
    set runtimepath^=/path/to/vim-clap
    augroup numbertoggle
      autocmd!
      autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu | set rnu   | endif
      autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu | set nornu | endif
    augroup END

    set relativenumber number
    syntax on
    filetype plugin indent on
    ```

2. Start (neo)vim with command: `vim -u min.vim min.vim`
4. Observe relative line numbers in the left column
3. Type `:Clap`, numbers of original window switch to absolute numbers
4. Press `Esc` key twice
4. The numbers in the original window 

**Expected behavior**

The numbers should be relative again, i.e. `relativenumber` should be activated upon returning to the original window. 

**Screenshots**

The issue is directly visible at the end of this GIF—the number column on the left should switch back to relative numbers when the Clap window closes, but doesn't:

![](https://user-images.githubusercontent.com/620981/85034923-e4295400-b182-11ea-9ac1-5a9852ff0a44.gif)

**Comment by liuchengxu** [comment]
That's due to clap uses `noautocmd` when closing the floating wins. The interesting thing is only neovim's floating win is affected, vim's popup don't have this problem.

**Comment by runiq** [comment]
Yeah, I figured it was something to do with `noautocmd`, but I wasn't sure where exactly. Thank you for the prompt fix! :heart:
