### ISSUE TITLE
Cannot match dotfiles exactly

### ISSUE THREAD

**Issue by xinhangliu** [liuchengxu/vim-clap#475]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macOS 10.15.5
 - (Neo)Vim version: vim 8.2.1123
 - vim-clap version: latest master
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
`Clap files --hidden` cannot match dotfiles in the current directory exactly.

**To Reproduce**

1. Start vim with the minimal `.vimrc`:

```vim
" My minimal .vimrc
syntax on
set runtimepath^=/path/to/vim-clap

let g:clap_theme = 'material_design_dark'
```

2. Run `:Clap files --hidden` at the home directory, for example

3. If searches for `.vimrc`, `.vimrc` is not the first match.

4. While searches for `. vimrc`, `.vimrc` is the first match.

**Expected behavior**
Match dotfiles exactly.

**Screenshots**
![image](https://user-images.githubusercontent.com/21138560/86502823-0e614f80-bdda-11ea-8d38-15d1caf911a9.png)

![image](https://user-images.githubusercontent.com/21138560/86502795-bb879800-bdd9-11ea-9382-a7ce2f923cd9.png)

**Comment by liuchengxu** [comment]
That's expected. `.vimrc` uses the fuzzy filter algorithm(fzy right now), `. vimrc` will use the substring filter algorithm, which will match each substring exactly.

![image](https://user-images.githubusercontent.com/8850248/86502996-073b4100-bddc-11ea-9842-112ac777d165.png)

My final goal is to implemet something like fzf's extended search mode, but for now, you can only use either fuzzy or substring filter algorithm.

**Comment by xinhangliu** [comment]
@liuchengxu I got it, thanks!
