### ISSUE TITLE
Support neovim's floating_win when using action

### ISSUE THREAD

**Issue by ray-x** [liuchengxu/vim-clap#478]
With same vimrc config. <S-Tab> can trigger action pop in vim/macvim but not for neovim(0.4/0.5)
Added some log in action.vim. I think the `function! s:invoke_action() abort` was not called after <S-Tab> pressed. Also tried to change the keymap from <S-Tab> to <C-w> or <C-q>, neither of them work for me.

**Comment by liuchengxu** [comment]
Neovim uses `confirm()`, floating_win-based action is unsupported, ref https://github.com/liuchengxu/vim-clap/pull/396#issuecomment-616012166. PR welcome.

**Comment by ray-x** [comment]
Okey. That is why. I did not check the messages in command window.

**Comment by liuchengxu** [comment]
#655 should fix this, please have a try.

**Comment by ray-x** [comment]
Is it the same key map as vim? The readme.md might need updates as well  :-P

**Comment by liuchengxu** [comment]
Not really, only https://github.com/liuchengxu/vim-clap/pull/655/files#diff-f9b32693c567b591deb63a1ad7fb974b5421fde66d7d4a4afc8779de733636d6.

**Comment by ray-x** [comment]
Looks great, thanks!
