### ISSUE TITLE
How to search files relative to the current buffer?

### ISSUE THREAD

**Issue by yujinyuz** [liuchengxu/vim-clap#484]
When using fzf, I have this line

`nnoremap <leader>ff :Files %:p:h<CR>`

and it lists all files in the current folder.

How can I achieve the same in `vim-clap`?

I tried
`:Clap filer %:p:h<CR>` 
`:Clap filer expand('%:p:h')<CR>`

But manually typing directory name works as expected `:Clap filer app`

but it's not working. It opens search from the root project

**Comment by liuchengxu** [comment]
`filer` also supports this. BTW the equivalent of `Files` is `:Clap files` not `:Clap filer`.

**Comment by yujinyuz** [comment]
@liuchengxu How do I exactly use the new update?

```
:Clap filer %:p:h<CR>
:Clap filer expand('%:p:h')<CR>
```

Tried both but it's still not working. I've already updated my vim-clap

**Comment by liuchengxu** [comment]
Well, works for me. Ensure you are using the latest commit https://github.com/liuchengxu/vim-clap/commit/b5b33d74bb6ae5568fd451476aed0a0ca0783e3e.

**Comment by yujinyuz** [comment]
@liuchengxu Can you take a look at this asciinema I made? It works for the first time but it doesn't when tried for the second time.

[![asciicast](https://asciinema.org/a/vZRZ3LsK827eEmy1jmoeoz9ab.svg)](https://asciinema.org/a/vZRZ3LsK827eEmy1jmoeoz9ab)

**Comment by liuchengxu** [comment]
This commit also adds the support for the other providers https://github.com/liuchengxu/vim-clap/commit/31d255eed79073d7409430b4456b40adc8179cd9.

**Comment by yujinyuz** [comment]
@liuchengxu Just tested the latest commit but still not working as intended

[![asciicast](https://asciinema.org/a/vsquaFH4vp6rhmQgxQKmEG318.svg)](https://asciinema.org/a/vsquaFH4vp6rhmQgxQKmEG318)

**Comment by liuchengxu** [comment]
Please file a new issue with reproduciable steps. With the video only, I have to spend more time to see what happens.
