### ISSUE TITLE
:Clap files %:p:h doesn't list files relative to the current open buffer

### ISSUE THREAD

**Issue by yujinyuz** [liuchengxu/vim-clap#485]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: 0.4.3
 - vim-clap version: 31d255e / master
 - Have you reproduced with a minimal vimrc: ???
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**

Having this kind of directory structure

```
folder1
  - file1.txt
  - file2.txt
  - file3.txt
folder2
  - file4.txt
  - file5.txt
```

If I open `folder2/file5.txt`, and type `:Clap files %:p:h` and press enter, it should only list `file4.txt` and `file5.txt`. But in this case, it lists all files as if I was just typing `:Clap files`.

**Clap debug**

```
            has cargo: 0
            has maple: /Users/eugene/.vim/plugged/vim-clap/bin/maple
           maple info: version 0.1.19 (git v0.19), built for x86_64-apple-darwin by rustc 1.44.1 (c7087fe00 2020-06-17).
         has +python3: 0
has py dynamic module: 0
     Current FileType:
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/eugene/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap files` open a file. Then, type `:Clap files %:p:h`, it should list files under the directory of the current open buffer

**Expected behavior**

**Screenshots**

![2020-07-23 at 23 16 45 - Specified Ackbar](https://user-images.githubusercontent.com/10972027/88305261-de073400-cd3b-11ea-85ab-2c10e16afa3e.gif)

**Additional context**

**Comment by liuchengxu** [comment]
Try this branch https://github.com/liuchengxu/vim-clap/tree/fix-%25-expand

**Comment by yujinyuz** [comment]
@liuchengxu Thanks! It's working now as expected
