### ISSUE TITLE
Where are project tags file located?

### ISSUE THREAD

**Issue by yujinyuz** [liuchengxu/vim-clap#487]
When using fzf or guttentags, it creates a `tags` file.

vim-clap has `g:clap_cache_directory`

But when I look inside the folder `~/.cache/nvim/clap`, I only see `help_tags/help_tags.txt`

<img width="1440" alt="Screen Shot 2020-07-26 at 1 09 56 PM" src="https://user-images.githubusercontent.com/10972027/88471969-4ecb6d80-cf41-11ea-91c3-024e1769ce7d.png">

I'm trying to look for the cached version of the project tags

**Comment by liuchengxu** [comment]
vim-clap does not always create the tags file, the tags generation might be all in memory if they are not huge.

**Comment by yujinyuz** [comment]
@liuchengxu So even the cached version of the tags are in memory?

**Comment by liuchengxu** [comment]
Yep.

**Comment by yujinyuz** [comment]
@liuchengxu where are the contents stored?

I wanted to know this because I want to take advantage of vim's `C-]` for jumping to tags. Currently it would say no tags file found.

**Comment by liuchengxu** [comment]
That won't work out as even the cached tag file exists it does not follow the format of regular `tags` file.

**Comment by yujinyuz** [comment]
Thanks! I guess I'll keep gutentags for generating tags file for me
