### ISSUE TITLE
How can i add icon for my person provider.

### ISSUE THREAD

**Issue by glepnir** [liuchengxu/vim-clap#488]
Sorry for break the issue template. I write an easy provider that can show all my dotfiles and go source code . I get the files list and set into `provider .source`.  I check the wiki and doc doesn't find some useful information about add the icon for files list. So how can i add the icons for file that in files list.

**Comment by liuchengxu** [comment]
Use the clap API(or write your own) for getting the icon and then format the line as you wish, see https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/icon.vim#L167 and https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/icon.vim#L180.

**Comment by glepnir** [comment]
@liuchengxu  Thanks i got it. but miss highlight for pure item. what i missed?
![image](https://user-images.githubusercontent.com/41671631/88483808-e01bfd80-cf9c-11ea-82a9-53eedf2be9a4.png)

**Comment by liuchengxu** [comment]
Set the `syntax` attribute to `clap_files`, e.g., https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/files.vim#L79.

**Comment by glepnir** [comment]
Thanks. I got it.
