### ISSUE TITLE
Integrate with External Tools easily

### ISSUE THREAD

**Issue by butterflyfish** [liuchengxu/vim-clap#489]
https://code.visualstudio.com/docs/editor/tasks

usage:
Clap tasks --> prompt user defined tasks, then let user to select. Display behavior just likes *Clap provides*.
Allow user to define mapping, .e.g map  F5 to build task.
Provide simple configuration interface. And clap can provide builtin template, e.g. support rust cargo build/run etc.
Output is allowed to defined: terminal or float term.

Example build task:
Run in neovim terminal. If build failed, capture error log into quickfix, then open it automatically.

Example run task:
Run in neovim terminal.

Example tig task:
open *tig* and run in float term.

**Comment by butterflyfish** [comment]
I'm just a vim user without vim script coding ability. Hope someone in community can help.

**Comment by liuchengxu** [comment]
A fairly trivial example has been added in https://github.com/liuchengxu/vim-clap/wiki/Examples#simple-tasks, you can extend it to whatever you like, basically, you have to write some scripts for your own needs if you choose to use vim.
