### ISSUE TITLE
How to search using exact match?

### ISSUE THREAD

**Issue by yujinyuz** [liuchengxu/vim-clap#490]
When searching for references of `console.log`, I'm also getting some fuzzy matches. Is it possible to search for exact match?

![Screen Shot 2020-07-28 at 5 31 17 PM](https://user-images.githubusercontent.com/10972027/88646998-2e91df00-d0f8-11ea-9df9-69905c04093c.png)

When I was using fzf, it has a command `:RG` and I just add `'` for searching an exact match `'console.log'`

**Comment by liuchengxu** [comment]
vim-clap does not support the extended search syntax like fzf. The workaround is to press one more space to use the substring matcher.

**Comment by yujinyuz** [comment]
@liuchengxu I think that works for now. Thanks!

Are there any plans for supporting something similar to fzf?

**Comment by liuchengxu** [comment]
That takes quite an effort and I'm busy recently. It's on the schedule but no ETA :(.

**Comment by liuchengxu** [comment]
Closing this in the favor of #492.
