### ISSUE TITLE
Clap proj_tags does not seem to work

### ISSUE THREAD

**Issue by rbhanot4739** [liuchengxu/vim-clap#491]
**Environment (please complete the following information):**
 - OS: MacOs catalina 10.15.6
 - NeoVim version: 0.5.0-4496628
 - vim-clap version: latest
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: ???  Yes

**Describe the bug**
Running `:Clap proj_tags` does not seem to work at all, it opens the empty floating window with no tags listed and as soon as you start typing following error is thrown.

`vim-clap: on_event:['thread ''main'' panicked at ''byte index 97 is not a char boundary; it is inside ''е'' (bytes 96...src/libcore/str/mod.rs:1920:47', 'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace', '']`

**Clap debug**

```

            has cargo: 1
            has maple: /Users/rbhanot/.config/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.19, built for x86_64-apple-darwin by rustc 1.45.0 (5c1f21c3b 2020-07-13).

         has +python3: 1
has py dynamic module: 1
     Current FileType: python
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/rbhanot/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_cache_directory = '/Users/rbhanot/.cache/vim/clap'
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:true
    let g:clap_layout = {'col': '17%', 'row': '33%', 'width': '67%', 'height': '33%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_session_dir = '/Users/rbhanot/.cache/vim/sessions'
  Provider Variables:
    let g:clap_provider_coc_blink = [2, 100]
    let g:clap_provider_grep_blink = [2, 100]
    let g:clap_provider_grep_delay = 100
    let g:clap_provider_yanks_min_len = 4
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start neovim with command: `vim -u min.vim`

3. Type `:Clap proj_tags`

**Expected behavior**
The tags for the project should be displayed in the floating window.

**Comment by liuchengxu** [comment]
Just as the error message said, the Rust binary paniced. It would be helpful you can provide the exact files to reproduce this error.

**Comment by rbhanot4739** [comment]
> Just as the error message said, the Rust binary paniced. It would be helpful you can provide the exact files to reproduce this error.

What more files ?

**Comment by liuchengxu** [comment]
The source files you run `:Clap proj_tags`. Without these source files, I can't reproduce.

**Comment by rbhanot4739** [comment]
The source files can be any file inside a project, for my case its a python file from a project.

**Comment by liuchengxu** [comment]
>The source files can be any file inside a project, for my case its a python file from a project.

Nope. I never have this issue. You must provide the source files to reproduce, otherwise I can't help.

**Comment by rbhanot4739** [comment]
Its happening in every project, not just one, so I believe it is irrespective of the source files.

**Comment by liuchengxu** [comment]
Can not reproduce.

**Comment by rbhanot4739** [comment]
Here is a simple helloworld script from my project where i get the error.

```
fab = "hello"
baz = "world"


print(fab + baz)

if fab:
    print("Yes")

```

I still don't understand how does source file has any thing to do here, since it is happening for every project. `:Clap proj_tags` simply shows a empty floating window and when i start to type, the error appears.

**Comment by liuchengxu** [comment]
`:Clap proj_tags` works great for me. If you can't provide a way to help reproduce this issue, I can't help more. It's very common that some issues happen in some particular cases.

**Comment by rbhanot4739** [comment]
The error message clearly states the rust file where the error occures, `src/libcore/str/mod.rs:1920:47`. Further there is no way for me to reproduce this since it is not happening for some particular case/project. No matter which project I open, same issue occures for me. There is some isssue with rust itself here but since I am not familier with rust I can't debug it anymore.

`vim-clap: on_event:['thread ''main'' panicked at ''byte index 97 is not a char boundary; it is inside ''е'' (bytes 96...src/libcore/str/mod.rs:1920:47', 'note: run with RUST_BACKTRACE=1 environment variable to display a backtrace', '']`

**Comment by rbhanot4739** [comment]
I tested this on two different machines Mac and Linux with different codes and same issue.

**Comment by cj** [comment]
I have a similar issue `Clap tags` works just fine, but `Clap proj_tags` is just empty, typing does not throw an error for me.

![CleanShot 2020-09-09 at 20 52 39](https://user-images.githubusercontent.com/1819/92672543-8a967880-f2de-11ea-8ce3-01b001f6be44.png)

Please let me know the best way to get you any debug info you need!

**Comment by liuchengxu** [comment]
@cj You can try `let g:clap_enable_debug = v:true` to see if there are any errors.

**Comment by mrded** [comment]
I'm also having the same issues.

MacOS Catalina 10.15.6 (19G2021), NVIM v0.4.3, Ctags 5.8, cargo 1.46.0, maple 0.1.20

**Comment by liuchengxu** [comment]
@mrded vim-clap has declared the ctags JSON requirement for `proj_tags`. Refer to https://github.com/liuchengxu/vista.vim#compile-ctags-with-json-format-support for reinstalling ctags.

**Comment by liuchengxu** [comment]
I have added the ctags JSON output feature check, you'll see an error message if your ctags is not compiled with JSON support.

**Comment by mrded** [comment]
Thanks. I think it will also make sense to update `vim-clap` docs, as instructions on how to install ctags are in a different project.
