### ISSUE TITLE
Feature to navigate line-wise without preview window?

### ISSUE THREAD

**Issue by rafi** [liuchengxu/vim-clap#495]
**Is your feature request related to a problem? Please describe.**
I'd like to navigate the search results **without** opening the preview window.

**Describe the solution you'd like**
Navigate line-wise without opening the preview window.

**Comment by liuchengxu** [comment]
I don't follow, you can always navigate the results in any cases, which is a very fundamental function. And the preview window is a plus, not all the providers has the preview feature.

**Comment by liuchengxu** [comment]
Closing, feel free to reopen if you still have some questions about this.

**Comment by rafi** [comment]
@liuchengxu it'll be nice to have an option to disable the automatic preview window, and only open it with a keyboard mapping on-demand. I like scrolling a file or grep results without the extra delay of preview window, and only _toggle_ it on-demand. Let me know what you think..

**Comment by liuchengxu** [comment]
No delay if you are using the Rust binary, it's all async.

**Comment by rafi** [comment]
Supported by 2afffaa using `let g:clap_open_preview = 'never'`
