### ISSUE TITLE
What difference about Clap files  and Clap gfiles

### ISSUE THREAD

**Issue by kdurant** [liuchengxu/vim-clap#50]
In a git project, I use `Clap files`, it get 35 files. And  I use `Clap gfiles`, it get 38 files. 
This is a very strange phenomenon.

When I use `Clap files`,  I want get all files in root directory, Otherwise I can use `Clap gfiles`.

**Comment by liuchengxu** [comment]
The only difference is the command they use to get the files.

https://github.com/liuchengxu/vim-clap/blob/a29c79e71249f4763993b67d28dfe87829353354/autoload/clap/provider/git_files.vim#L10

https://github.com/liuchengxu/vim-clap/blob/1cf9c54b6cb90ffb0f9d2caa8efaeab1b68b27a0/autoload/clap/provider/files.vim#L11-L16

**Comment by kdurant** [comment]
> By default, ripgrep will respect your .gitignore and automatically skip hidden files/directories and binary files.

So, `Clap files` and `Clap gfiles` has similar results.

What should I do if I want to search for files that in .gitignore file?

**Comment by liuchengxu** [comment]
Refer to the help of fd and rg. I don't have a direct answer.

**Comment by liuchengxu** [comment]
Once #28 is resolved, you can change the default command used by vim-clap on our own. For now, if you want a different behavior, e.g, including the files in .gitignore, you have to modify the related command locally.
