### ISSUE TITLE
Filer: Tab on a file/directory with no permissions

### ISSUE THREAD

**Issue by Grueslayer** [liuchengxu/vim-clap#500]
If you choose a directory (or even a file) which got listed and you do not have permission to and press TAB you'll see an error like

```
vim-clap: thread 'session-1-filer' panicked at 'called `Result::unwrap()` on an `Err` value: Permission denied (os error 13)', crates/stdio_server/src/filer.rs:94:17
vim-clap: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/', 'message': 'Permission denied (os error 13)'}
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/.Spotlight-V100/', 'message': 'Permission denied (os error 13)'}
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/', 'message': 'Permission denied (os error 13)'}
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/', 'message': 'Permission denied (os error 13)'}
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/', 'message': 'Permission denied (os error 13)'}
vim-clap: [client_handle] {'dir': '/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/.Spotlight-V100/Users/', 'message': 'Permission denied (os error 13)'}
```

which is okay BUT if you already can see in the log: the filer *thinks* it has changed to the directory and still displays the old content where you can select the same (or another) entry. This will be appended to the *current* path. In the example above, i multiple chose the Spotlight cache.

If you press TAB on a file where you do not have access to filer treads the filename as directory and behaves like above.

I think choosing a directory (or file) should only lead to an error without modifying the current path. 

P.S. on my Windows machine, sometimes an backtrace will be displayed as file list (where you can choose of the backtrace as file/dir)

**Comment by liuchengxu** [comment]
#504 should be able to resolve this issue.
