### ISSUE TITLE
c has no highlight support 

### ISSUE THREAD

**Issue by zyp2005** [liuchengxu/vim-clap#508]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: archlinux
 - (Neo)Vim version: 0.4.3
 - vim-clap version: latest 
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
c files have no highlight support 
c文件没有语法高亮支持

**Clap debug**

```

            has maple: /home/zyp/.config/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.19, built for x86_64-unknown-linux-gnu by rustc 1.43.0.
         has +python3: 1                                                          
has py dynamic module: 1
     Current FileType:                                  
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/zyp/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}

```

**To Reproduce**
  :clap files

1. Create the minimal vimrc `min.vim`:

```
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liuchengxu** [comment]
`:Clap files` use the `clap_files` syntax https://github.com/liuchengxu/vim-clap/blob/master/syntax/clap_files.vim.
