### ISSUE TITLE
Support for buffer deletion through Clap buffer 

### ISSUE THREAD

**Issue by ratheesh** [liuchengxu/vim-clap#51]
When we have too many opened buffers in a vim session, it will be nice to have feature to mark and delete buffers not required without restarting vim.

**Comment by liuchengxu** [comment]
It's not hard to implement the delete function, but if we want an intuitive interaction, that is not easy. What keybindings should we use for this feature?

**Comment by sscherfke** [comment]
Maybe this can be generalized to
- allow multi-select for files/buffers
- run_command_for_selected_items (Create a list like in grep, delete, close, ...)

**Comment by balta2ar** [comment]
> complete and easy-to-use workflow

we can start somewhere and learn from user's feedback. I also miss this feature. in Unite I could filter buffers in Insert mode, and then I could switch to Normal mode and use `d` to close buffers. I think adding a simple Insert-mode shortcut like "ctrl-d" or "ctrl-delete" could be a good start.

**Comment by liuchengxu** [comment]
>I think adding a simple Insert-mode shortcut like "ctrl-d" or "ctrl-delete" could be a good start.

Ctrl-d in insert mode is already being used for deleting next character.

I'm curious if you use `d` to close a buffer when using`buffers` provider, whan happens when you use `d` in the other providers? `d` in normal mode will obviously be a `nnoremap` for the `clap_input` buffer which is applicable for all the providers.

And for popup of vim, I believe you have to manage an internal insert or normal mode flag as it's focusable you have to emulate this mode specific behaviour. Since there are only two modes, that's not very complex, but it still takes some more work.

**Comment by rafi** [comment]
> in Unite [..] I could switch to Normal mode and use `d` to close buffers (edit: same in `LeaderF` plugin).

Same with [Denite](https://github.com/Shougo/denite.nvim). Using "Normal mode" in selection window has a great intuitive feel, seamless with Vim's "mode" paradigm. vim-clap is impressive and looks beautiful, but having to stretch my fingers to <kbd>Ctrl</kbd> for any movement or command feels opposite to Vim's nature.

<details>
<summary>Example of my Denite's selection window mappings</summary>

```viml
autocmd FileType denite call s:denite_settings()

" Denite main window settings
function! s:denite_settings() abort
	" Window options
	setlocal signcolumn=no cursorline

	" Denite selection window key mappings
	nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
	nnoremap <silent><buffer><expr> i    denite#do_map('open_filter_buffer')
	nnoremap <silent><buffer><expr> /    denite#do_map('open_filter_buffer')
	nnoremap <silent><buffer><expr> dd   denite#do_map('do_action', 'delete')
	nnoremap <silent><buffer><expr> p    denite#do_map('do_action', 'preview')
	nnoremap <silent><buffer><expr> st   denite#do_map('do_action', 'tabopen')
	nnoremap <silent><buffer><expr> sg   denite#do_map('do_action', 'vsplit')
	nnoremap <silent><buffer><expr> sv   denite#do_map('do_action', 'split')
	nnoremap <silent><buffer><expr> '    denite#do_map('quick_move')
	nnoremap <silent><buffer><expr> q    denite#do_map('quit')
	nnoremap <silent><buffer><expr> r    denite#do_map('redraw')
	nnoremap <silent><buffer><expr> yy   denite#do_map('do_action', 'yank')
	nnoremap <silent><buffer><expr> <Esc>   denite#do_map('quit')
	nnoremap <silent><buffer><expr> <Tab>   denite#do_map('choose_action')
	nnoremap <silent><buffer><expr><nowait> <Space> denite#do_map('toggle_select').'j'
endfunction
```

</details>

**Comment by liuchengxu** [comment]
It's easy to use the actions supported in the input window for the display window, we merely need to add some more mappings for the existing actions. And if you jump to the display window, you already are able to act like exploring in a normal window.

The question is that some actions are not clear, e.g., `delete`, for `buffers` provider, it could be the deletion of buffer, for `history` provider, it could be deleting the entry from the history, then what for these that don't have the obvious semantics, e.g., `colors`, `grep`, what does `delete` action do for them?.

**Comment by rafi** [comment]
Each provider will need to set applicable global actions, only few support `delete`, and implement custom ones if needed, e.g.

| provider | actions |
|---------|-----|
| buffers | switch (default), delete, unload, split h/v, tabnew, yank
| colors | set colorscheme (default), split edit h/v, tabnew, yank
| commits | show diff (default), diff with ref, populate location-list, cherry-pick, yank SHA
| files/grep | edit (default), split h/v, tabnew, delete, yank
| filetypes | set filetype (default), yank
| yanks | paste (default), replace with paste, delete, yank

**Comment by liuchengxu** [comment]
Would be helpful if someone can show me the whole workflow of insert/normal mode actions, from entering the clap input window, then apply the action and exit. I always stay in the insert mode and not familiar with the such features.

**Comment by Bakudankun** [comment]
@liuchengxu 
unite.vim and denite.nvim are a kind of object-oriented finders. Candidates have `kind` param, which means that candidates know what they are, like `buffer`, `file`, `colorscheme`, `bookmark`, ..., and what they can do, like `open`, `delete`, `apply`, `bookmark`, ....

### Launch
First, you launch the finder with some source name and optional argument like `:Unite file:~`, and you enter the finder window. The initial mode may be customizable, but I prefer the normal-mode.

### Normal-mode
In normal-mode, you can seek for candidates with `j`, `k`, `<C-F>`, `<C-B>`, `gg`, `G`, ..., just like in normal windows. You can select multiple candidates with `<Space>`, and call default action for the selected candidate(s) with `<CR>`. Some other keys may be mapped to call specific actions.
If there are only a few candidates, or the second or the third one is what you want, normal-mode is easier to select that.
By pressing `i` or `a`, you can enter insert-mode.

### Insert-mode
(I feel "filter-mode" is more proper)
In insert-mode, you can filter candidates with input, and even call default action for the first candidate with `<CR>`.
With `<Esc>` you can return to normal-mode.

### `<Tab>` menu
In both insert and normal modes, pressing `<Tab>` prompts you for an action available for selected candidate(s). This is just like the context menu of desktop environment.
Since prompt can have completion (`:h input()`), you don't need to remember all shortcuts for each actions for every kinds.

denite.nvim removed most default mappings, so some may have different workflow.

**Comment by liuchengxu** [comment]
It's easy to support navigating the results in the normal mode. The example as follows, you can enter the input window in normal mode and use j/k for navigation, using `i/a` goes to insert mode and `<Esc>` back to normal mode.

```diff
diff --git a/autoload/clap/floating_win.vim b/autoload/clap/floating_win.vim
index 3fc22f9..24f68fd 100644
--- a/autoload/clap/floating_win.vim
+++ b/autoload/clap/floating_win.vim
@@ -339,7 +339,7 @@ function! clap#floating_win#open() abort

   silent doautocmd <nomodeline> User ClapOnEnter

-  startinsert
+  " startinsert

   call g:clap.provider.apply_query()
 endfunction
diff --git a/ftplugin/clap_input.vim b/ftplugin/clap_input.vim
index 27a3422..ff58598 100644
--- a/ftplugin/clap_input.vim
+++ b/ftplugin/clap_input.vim
@@ -47,13 +47,16 @@ inoremap <silent> <buffer> <expr> <C-E> col('.')>strlen(getline('.'))<bar><bar>p
 inoremap <silent> <buffer> <CR> <Esc>:call clap#handler#sink()<CR>

 nnoremap <silent> <buffer> <C-c> :call clap#handler#exit()<CR>
-nnoremap <silent> <buffer> <Esc> :call clap#handler#exit()<CR>
+" nnoremap <silent> <buffer> <Esc> :call clap#handler#exit()<CR>
 nnoremap <silent> <buffer> <C-g> :call clap#handler#exit()<CR>

 inoremap <silent> <buffer> <C-c> <Esc>:call clap#handler#exit()<CR>
-inoremap <silent> <buffer> <Esc> <Esc>:call clap#handler#exit()<CR>
+" inoremap <silent> <buffer> <Esc> <Esc>:call clap#handler#exit()<CR>
 inoremap <silent> <buffer> <C-g> <Esc>:call clap#handler#exit()<CR>

+nnoremap <silent> <buffer> j :<c-u>call clap#navigation#linewise('down')<CR>
+nnoremap <silent> <buffer> k :<c-u>call clap#navigation#linewise('up')<CR>
+
 inoremap <silent> <buffer> <C-j> <C-R>=clap#navigation#linewise('down')<CR>
 inoremap <silent> <buffer> <C-k> <C-R>=clap#navigation#linewise('up')<CR>
```

It's not easy to support the other actions like deleting as I can't imagine the workflow. For example, `<Tab>` is now used for (un)selecting the entry  and I won't change this default behaviour, then how to prompt the avaliable actions for current provider? We don't use `input()` and have no completion in the input window.

**Comment by rafi** [comment]
@liuchengxu awesome! I prefer having `startinsert` for now. Added following mappings to access and call sink in normal mode. Is there a better way to make \<Esc\> (and `jj`) trigger the _preview_ window and exit insert mode at once?

```viml
inoremap <silent> <buffer> <Esc> <C-R>=clap#navigation#linewise('down')<CR><C-R>=clap#navigation#linewise('up')<CR><Esc>
inoremap <silent> <buffer> jj    <C-R>=clap#navigation#linewise('down')<CR><C-R>=clap#navigation#linewise('up')<CR><Esc>

nnoremap <silent> <buffer> <CR> :<c-u>call clap#handler#sink()<CR>
nnoremap <silent> <buffer> q    :<C-u>call clap#handler#exit()<CR>
```

**Comment by liuchengxu** [comment]
@rafi  I found these normal mode mappings are convinent so I add them as the default mappings #322, feel free to leave any suggestions there. You don't have to trigger the preview window manually as it will show automatically on your move.  Just use `<Esc>` to enter normal mode and use j/k to scroll, you'll have the preview.

**Comment by liuchengxu** [comment]
Maybe we can use a dialog provided by `confirm()`, then we only need one shortcut for invoking the action dialog.

<img width="483" alt="截屏2020-03-08下午10 24 52" src="https://user-images.githubusercontent.com/8850248/76164669-a97b4d00-618b-11ea-9130-2b5e1f9ea30e.png">

**Comment by liuchengxu** [comment]
I have introduced the provider actions in #396, feel free to try it and any feedback would be lovely. Currently it's implemented using `confirm()` for both vim and neovim.

**Comment by nirrub** [comment]
Sorry - but I'm getting lost trying to config these. Can someone please share the vim snippet that allows the use of menu action items for buffers? 

Thanks and sorry

**Comment by liuchengxu** [comment]
@nirrub See `<Shift-Tab>` in https://github.com/liuchengxu/vim-clap#keybindings, you don't have to add extra config, it's native to the `buffers` provider.

**Comment by nirrub** [comment]
@liuchengxu - Thanks a lot, works like a charm!

**Comment by ludvikn** [comment]
Is it possible to invoke the action dialog on all selected buffers? (for deletion is my case)
