### ISSUE TITLE
remove columns to save horizontal realestate

### ISSUE THREAD

**Issue by barkanido** [liuchengxu/vim-clap#510]
**Is your feature request related to a problem? Please describe.**
Although I use a widescreen most of the time, it is usually split with vim on one side (the other side being another vim split or just a terminal). When opening one of the buffers provider (which is very useful), there is a lot of info like [buffer number, file size, the current line that occupy a lot of valuable horizontal space. This leaves little room for the filename itself, which in most cases just hides outside the window.

**Describe the solution you'd like**
I think giving the option to specify the specific columns that are important to, will help to compact the view.

**Describe alternatives you've considered**
1. reducing font size making it harder to read
2. the layout os already occupying almost all window width.

**Comment by liuchengxu** [comment]
It depends too much on user's personal preference, I'm not a fan of this and it's not easy to come up with a way that can satisfy everyone. You can fork this provider and change the format https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/buffers.vim#L31 on your own. You don't have to fork the whole clap repo, just the `buffers` provider should be fine.
