### ISSUE TITLE
how to add tabs provider

### ISSUE THREAD

**Issue by likelxl** [liuchengxu/vim-clap#511]
**Is your feature request related to a problem? Please describe.**
i want to add tabs provider, it's vim builtin command, like as buffer

**Describe the solution you'd like**
let g:clap_provider_tabs = {
       \ 'source': "excute('tabs')",
       \ 'sink': 'open',
       \ }

**Describe alternatives you've considered**
copy buffers, but i don't how to write vimscript

**Additional context**

**Comment by liuchengxu** [comment]
Try `'source': split(execute('tabs'), "\n")`, the `sink` is also not correct, you have to learn some vimscript to write your own provider :(.
