### ISSUE TITLE
Neovim redraw “freezes” when clap is enabled

### ISSUE THREAD

**Issue by phaazon** [liuchengxu/vim-clap#516]
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Archlinux (5.8.6-arch1-1)
 - (Neo)Vim version:
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
 - vim-clap version: git commit `973ebcf5411eea777450673b0b3f132beb5004d7`
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**
Neovim somehow freezes” until I type something, regardless of whether a clap window is open or not (I don’t have that problem if I remove clap from my plugins).

---

Step 1: simply open neovim on a file with another window next to it.

![img_090320_124113](https://user-images.githubusercontent.com/506592/92105248-daf36f00-ede2-11ea-93af-dca830aa42a9.png)

Step 2: expand the neovim window and don’t touch anything. You can see a glitched window (half the window is not redrawn).

![img_090320_124123](https://user-images.githubusercontent.com/506592/92105294-eba3e500-ede2-11ea-98b3-494adba18eeb.png)

Step 3: type any key (I simply move the cursor). The window gets redrawn completely.

![img_090320_124132](https://user-images.githubusercontent.com/506592/92105319-f52d4d00-ede2-11ea-9d07-1c50353cdd40.png)

**Clap debug**

```
            has cargo: 1
            has maple: /home/phaazon/.config/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.20, built for x86_64-unknown-linux-gnu by rustc 1.45.2 (d3fb005a3 2020-07-31).

         has +python3: 1
has py dynamic module: 1
     Current FileType: toml
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/phaazon/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': '->'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    let g:clap_insert_mode_only = v:true
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_selected_sign = {'texthl': 'ClapSelectedSign', 'linehl': 'ClapSelected', 'text': ' ·'}
  Provider Variables:
                     []
```

**Comment by liuchengxu** [comment]
I don't think vim-clap is responsible for this issue as you even don't open it. And you are opening two Vim windows, but two terminal windows. I don't see how vim-clap is related.

**Comment by phaazon** [comment]
No problem with fzf.vim; as mentioned in the issue, the problem disappears as soon as I remove `vim-clap` from my plugins.

**Comment by liuchengxu** [comment]
I still don't see why vim-clap is related.

**Comment by phaazon** [comment]
I tried to `:profile` but I got a zero-byte profile file (maybe I miss something here). Do you have any idea how I could debug that issue?

**Comment by liuchengxu** [comment]
Maybe this can help https://vi.stackexchange.com/a/277

**Comment by phaazon** [comment]
Yeah, I get a trace but I’m not sure how it’s going to be interesting. I guess you are using a display feature and not resetting it / using it correctly, because I don’t have the bug with other plugins. However, it looks like it’s not triggered if I start neovim and do not use any clap feature (it starts doing it as soon as I do for instance `:Clap buffers`). Even with the clap floating window closed, it still behaves incorrectly afterwards.

**Comment by liuchengxu** [comment]
>it looks like it’s not triggered if I start neovim and do not use any clap feature

That's why I don't understand clap is related here, if you don't open clap, there is only a few autocmds of clap taking effect, see https://github.com/liuchengxu/vim-clap/blob/master/plugin/clap.vim, which won't lead to this issue in my opinion.

**Comment by phaazon** [comment]
Yes, agreed. So the problem happens _after_ a clap window has been opened. I can open a clap window, close it, resize the window: the problem appears. A clap window doesn’t have to be open for the problem to appear, but it looks like one has to have been opened previously (at least once).

**Comment by karlc1** [comment]
I just want to confirm that I have this exact same issue using neovim nightly and clap on ubuntu. I have tried using both ctrlp and fzf, without getting this issue, but as soon as I search using clap the rescaling on window resize stops working correctly and requires an additional key press before looking correct again. As op mentioned, this behavior starts when I open clap, and persists even after I close the clap window until I exit neovim.

**Comment by phaazon** [comment]
Yes, I still have it too. I’m not sure what causes it, though. :(

**Comment by romgrk** [comment]
Does it still happen if you apply this patch?

```diff
diff --git a/autoload/clap/floating_win.vim b/autoload/clap/floating_win.vim
index e94ad1a..9cdf23a 100644
--- a/autoload/clap/floating_win.vim
+++ b/autoload/clap/floating_win.vim
@@ -84,6 +84,7 @@ function! g:clap#floating_win#display.open() abort
 endfunction
 
 function! clap#floating_win#redo_layout() abort
+  return
   let s:display_opts = clap#layout#calc()
   call nvim_win_set_config(s:display_winid, s:display_opts)
   call nvim_win_set_config(s:spinner_winid, s:get_config_spinner())
```

**Comment by Galicarnax** [comment]
No, it doesn't. The problem disappers after applying the patch.
