### ISSUE TITLE
Render relative to whole vim

### ISSUE THREAD

**Issue by timsofteng** [liuchengxu/vim-clap#518]
Hello.
Vim-clap window now renders relative to current window where it was open. How can I open it raletive to whole vim terminal instance?

![image](https://user-images.githubusercontent.com/51912173/92473905-ed571980-f1e3-11ea-9a71-eb1c10a934bc.png)

**Comment by liuchengxu** [comment]
`let g:clap_layout = {'relative': 'editor'}`, also see `:h g:clap_layout`.

**Comment by timsofteng** [comment]
Thanks!
