### ISSUE TITLE
`:Clap tags` command navigates to incorrect buffer window

### ISSUE THREAD

**Issue by macintacos** [liuchengxu/vim-clap#523]
**Environment (please complete the following information):**
 - OS: macOS 10.15.6
 - (Neo)Vim version: 0.4.4
 - vim-clap version: whatever is latest as I open this (I don't really know how to find this?)
 - Have you reproduced with a minimal vimrc: Not yet, trying
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes 

**Describe the bug**

Sometimes if I have a few splits open and I use `:Clap tags` to search for a variable or something in the current buffer, when I hit `<enter>` to select the tag that I want to navigate to, it'll navigate in a completely different buffer to an unrelated line, presumably at the line number that the tag _would've_ been in the buffer that I was in. It seems to be much more reliable when I have a split above and below and to the left/right.

I got a recording of the latest occurrence: https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/NQurGXN6/Screen%20Recording%202020-09-14%20at%2011.05.29.mp4

I'm not sure if this is an issue with Vista or an issue with vim-clap. I'm going to try out another tag searching mechanism that integrates with Vista to see if I can reproduce the issue and see if that's the common denominator.

**Clap debug**

```

            has cargo: 1
            has maple: /Users/juliant/.config/vim-plug/vim-clap/target/release/maple
           maple info: version 0.1.20, built for x86_64-apple-darwin by rustc 1.45.2.

         has +python3: 1
has py dynamic module: 1
     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/juliant/.config/vim-plug/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
```

**To Reproduce**

1. Open two files (one above, one below). Only tested with two Vim files as of right now
2. In the first window buffer (I don't think it matters which one), invoke `:Clap tags`. It should work fine.
3. Make the second window buffer have focus, and invoke the same thing (`:Clap tags`). The list seems to be correct.
4. Select a tag by hitting `<enter>`

**Expected behavior**
I expect at step 4 that I'll navigate to the symbol that I searched for in the current buffer

**Actual behavior**
I am brought to the other window buffer for some reason that I cannot explain.

**Comment by macintacos** [comment]
By the way, this was reproduced in my dotfiles project, which you can find here: github.com/macintacos/dotfiles (neovim config is in the aptly named `nvim` folder).

**Comment by macintacos** [comment]
Just verified that this doesn't seem to be an issue with Vista, I was able to run `:Vista finder` with fzf installed and it worked as expected there. I'll use that for the time being since I don't have time to debug further.

**Comment by liuchengxu** [comment]
Please update both vista.vim and vim-clap to the latest master.
