### ISSUE TITLE
:Clap install-binary! don't work on Windows

### ISSUE THREAD

**Issue by Grueslayer** [liuchengxu/vim-clap#529]
If maple is already available (once downloaded) it will be started by Clap immediatly (at any startup routine, haven't examined). So maple.exe (for windows) is already running as process, therefore the downloaded (new version) can not been saved on the location (because the OS has a write lock on the running file),

Furthermore the plugin says the download was successful and the user can not examine the error log bacuse the split window has been closed so fast, you had no chance to read the message.

Solution:
If updating binary, temporary stop maple job,

**Comment by liuchengxu** [comment]
Never tried Windows, the newer release binary will be fetched to a temp location and then be renamed to `bin/maple`, I guess this does not work on Windows?

https://github.com/liuchengxu/vim-clap/blob/6fb4b9e3acb2a77e4ffa81a21551100011b0e72f/crates/upgrade/src/lib.rs#L51-L54

**Comment by Grueslayer** [comment]
I do not think your code will be used. It seems rather that "install.ps1" will be called. But in both cases it will not work. You can not replace a file already in process. You need to stop maple first (so that no OS is accessing the file) and after  that you can replace it (by direct download or renaming a temp file to the original name)

**Comment by liuchengxu** [comment]
If you never downloaded the Rust binary, `install.ps1` will be used. If you already have it and are trying to upgrade, the upgrade feature of Rust binary will be used instead of `install.ps1`. Since I don't have a Windows, I'd love to see some Windows expert help resolve this.

**Comment by Grueslayer** [comment]
No, you do not force the maple.exe to upgrade itself, because your check ist wrong:

```vim
function! s:do_download() abort
  if !exists('s:current_version')
    let version_line = readfile(s:maple_cargo_toml)[:5][-1]    
```

do not match the file

```
[package]
name = "maple"
build = "build.rs"
edition = "2018"
version = "0.1.21"
license = "MIT"
publish = false
include = ["/Cargo.toml", "src/*.rs"]
authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
homepage = "https://github.com/liuchengxu/vim-clap"
categories = ["command-line-utilities"]
description = "vim-clap external filter gadget"

[dependencies]
maple_cli = { path = "crates/maple_cli" }

[build-dependencies]
built = { package = "built", version = "0.4", features = ["git2"]}
```

bacause the list is 0-based and the 6th line is "licence....". You should iterate through the list and match for version instead of taking a fix line number.

**Comment by Grueslayer** [comment]
Why don't you call `system(s:prebuilt_maple_binary.' version')` and parse the output from maple executable?

**Comment by liuchengxu** [comment]
Your PR time then, I personally do not need the prebuilt binary, thus it's not an issue for me.

I'm not a fan of `system()` because it is slow.

**Comment by Grueslayer** [comment]
Okay... but the "toml" file (which will be checked for version) comes from repository, So it is everytime on newest version and does not tell you which version is installed. If "upgrade" comes with version >=14 you need to check the exe and not the current package info, don't you?

**Comment by liuchengxu** [comment]
The version in `Cargo.toml` always implys the latest remote release version. If the version of binary you are running is not same with the version of latest remote release, then just download the latest binary.

**Comment by liuchengxu** [comment]
You are right, if you are using v0.13, pull the latest commit and run the update command inside vim, the update will run into error. Fixing it is not hard, patch welcome, I'm not motivated to do this as I'm not the user of this feature.

**Comment by liuchengxu** [comment]
The most safe way is just to run `install.ps1`/`install.sh` in your terminal.

**Comment by Grueslayer** [comment]
The problem I start do describe about locks on file also exists when comoiling by source:

```
= note: LINK : fatal error LNK1104: cannot open file 'C:\Users\jstocker9330\vimfiles\bundle\vim-clap\target\release\deps\maple.exe'
```

It is the same reason, there is a process ob "maple rpc" which will start as soon as you call any :Clap action. This keeps open as process while vim is running. A running process "locks" that file (at least on windows) so you cannot overwrite it.

Therefore we need to stop that "maple rpc" job (you spawn somewhere early) BEFORE any update of maple and after that restart it,

**Comment by liuchengxu** [comment]
Not an issue I'm interested in tackling, before someone resolves this completely, you can run `install.ps1`/`install.sh` when you are not running any vim instances.

**Comment by Grueslayer** [comment]
Come on, it also happens while building by source (not only download) like described above.

Here you go (of couse this does not help if running multiple vims and / or maple by other calls)

```diff
diff --git a/autoload/clap/installer.vim b/autoload/clap/installer.vim
index 3c93a60..81db763 100644
--- a/autoload/clap/installer.vim
+++ b/autoload/clap/installer.vim
@@ -17,6 +17,9 @@ function! s:run_term(cmd, cwd, success_info) abort
       execute 'silent! bd! '.bufnr
       call clap#helper#echo_info(a:success_info)
     endif
+    if clap#maple#is_available()
+      call clap#job#daemon#start(function('clap#client#handle'))
+    endif
   endfunction
 
   if has('nvim')
@@ -106,8 +109,13 @@ endfunction
 
 function! s:do_download() abort
   if !exists('s:current_version')
-    let version_line = readfile(s:maple_cargo_toml)[:5][-1]
-    let s:current_version = str2nr(matchstr(version_line, '0.1.\zs\d\+'))
+    if executable(s:prebuilt_maple_binary)
+      "Since v0.7
+      let version_line = system(s:prebuilt_maple_binary.' version')
+      let s:current_version = str2nr(matchstr(version_line, '0.1.\zs\d\+'))
+    else
+      let s:current_version = -1
+    endif
   endif
   " Since v0.14 maple itself is able to download the latest release binary.
   if executable(s:prebuilt_maple_binary) && s:current_version >= 14
@@ -123,6 +131,10 @@ function! clap#installer#force_download() abort
 endfunction
 
 function! clap#installer#install(try_download) abort
+  if clap#job#daemon#is_running()
+    call clap#job#daemon#stop()
+  endif
+
   " Always prefer to compile it locally.
   if executable('cargo')
     call clap#installer#build_all()

```

**Comment by liuchengxu** [comment]
I never have issue with these stuffs myself. I haven't added new features into vim-clap for a while as I'm busy recently, but patches are always welcome anyway. I'm happy to review and merge if you send an official patch.
