### ISSUE TITLE
A filetype for the Clap Window

### ISSUE THREAD

**Issue by 00sapo** [liuchengxu/vim-clap#530]
I need to disable a plugin (e.g. SemanticHighlight) on the floating window. A usual way to filter plugins is the filetype.

Having a filetype for the Clap window would allow more compatibility with other plugins.

For instance I'm using this command in my vimrc:
`autocmd Syntax * if (index(blacklist, &ft) < 0 ) | :SemanticHighlight`
It simply executes a command only if the filetype is not in the blacklist. 

Since I don't have a filetype for Clap, Clap window always uses SemanticHighlight, even if the filetype opened in the buffer is set to a filetype where SemanticHighlight is disabled ('qf' in this screenshot) ![screenshot](https://imgur.com/FV21y4m.png)

Is there an alternative method?

**Comment by liuchengxu** [comment]
You can disable the plugin using `ClapOnEnter` hook, see `:h ClapOnEnter`.

```vim
  autocmd User ClapOnEnter call clap#api#win_execute(g:clap.display.winid, 'SemanticHighlightRevert')
```
