### ISSUE TITLE
Download binary regardless cargo existed or not

### ISSUE THREAD

**Issue by ray-x** [liuchengxu/vim-clap#531]
**Is your feature request related to a problem? Please describe.**
Currently, clap takes too much disk space because build maple cost me around 460MB.  

```vim
function! clap#installer#install(try_download) abort
  " Always prefer to compile it locally.
  if executable('cargo')
    call clap#installer#build_all()
 
```

The code shows that if cargo installed, there is no option to download the prebuild.

**Describe the solution you'd like**
An option to download package directly.  Specially for the user have cargo installed.

**Comment by liuchengxu** [comment]
Use:

```vim
Plug 'liuchengxu/vim-clap', { 'do': { -> clap#installer#force_download() } }
```
