### ISSUE TITLE
Consider using new matchfuzzy() built in function

### ISSUE THREAD

**Issue by craigmac** [liuchengxu/vim-clap#535]
**Describe the solution you'd like**
Ability to use this plugin using only built in Vim feature for fuzzy matching. A really new fuzzy match function written in C should make it possible to not rely on Rust if user has a Vim version with the correct patch.

**Additional context**
The PR and function I’m talking about: https://github.com/vim/vim/pull/6932

**Comment by romgrk** [comment]
Neovim will probably get it too: https://github.com/neovim/neovim/pull/12995 It might make it more attractive then if both vim & neovim have it.

**Comment by liuchengxu** [comment]
Yeah, this also just needs some glue code similar to #565. But we have to take care of some extra stuffs that the Rust binary maple does:

- Ensure the matched items won't be totally invisible #317.
- Can apply the filter on the substring of origin line, like filename only in #379.

Not sure `matchfuzzy()` and `fzy-lua` already handle these cases.

**Comment by liuchengxu** [comment]
@craigmac Try #607, you can use `let g:clap_force_matchfuzzy = 1` to test it. Any suggestions are welcome.
