### ISSUE TITLE
Use ctrl-n and ctrl-p for up and down

### ISSUE THREAD

**Issue by oguzbilgic** [liuchengxu/vim-clap#536]
As far as I can tell, in vim world `ctrl-n` and `ctrl-p` combinations are used for up and down during text editing such as insert mode or command line mode.

I believe that vim-clap can follow this route as well, to be backwards compatible, this could be behind a feature flag

**Comment by liuchengxu** [comment]
Now you can add this to your vimrc:

```vim
let g:clap_popup_move_manager = {
      \ "\<C-N>": "\<Down>",
      \ "\<C-P>": "\<Up>",
      \ }
```
