### ISSUE TITLE
Allow preserving the full filename when truncating the result lines for grep provider

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#537]
![Screenshot_2020-10-11_17-08-33](https://user-images.githubusercontent.com/1241845/95682248-8cf13880-0be4-11eb-8271-19b1c28de695.png)

I can't read most of the file names. I  think these should always be visible (not the whole path, but the filename).

**Comment by liuchengxu** [comment]
When you move the cursor to the line, the whole filepath will be displayed in the preview window below.

**Comment by hasufell** [comment]
I'm aware, but that doesn't solve my issue. It's about having an overview of the results per file, so i instantly see where the results are without moving through the entire list.

**Comment by liuchengxu** [comment]
You have to understand that the window size is always limited and can't display the whole line, therefore it has to be truncated for displaying the part containing the matched items.

**Comment by liuchengxu** [comment]
Hmm, I'm not interested unless someone sends a PR.

**Comment by hasufell** [comment]
> Hmm, I'm not interested unless someone sends a PR.

I might have a look at it when I have time this week. Can you give me pointers to the code where the truncation happens?

**Comment by liuchengxu** [comment]
The truncation processing is in `printer` crate, https://github.com/liuchengxu/vim-clap/blob/41dc711da187cb6c48e9f7f47faf7cd5edbd55ed/crates/printer/src/lib.rs#L53

Currently it's not flexible to support various truncation style, for the result lines can have distinct formats, but at least you can fork it to meet your own need :)

**Comment by liuchengxu** [comment]
I realize this is a nice-to-have feature, we should support it. The printer crate might need to be refactored first.

**Comment by liuchengxu** [comment]
@hasufell Can you try this branch https://github.com/liuchengxu/vim-clap/tree/preserve-file-name? `:Clap grep` should always show the file name.

<img width="1431" alt="截屏2023-02-25 14 49 02" src="https://user-images.githubusercontent.com/8850248/221343129-f981d2a1-cb89-4806-a67d-ebfb21dc1daa.png">
