### ISSUE TITLE
Add <CTRL-W> to delete a word, like command line mode

### ISSUE THREAD

**Issue by oguzbilgic** [liuchengxu/vim-clap#538]
In command line typing mode `<CTRL-U>` is used to delete the whole input, and **vim-clap** already implements that. Similarly,  `<CTRL-W>` deletes a single word in command line, however vim-clap doesn't implement `<CTRL-W>`.

There are potentially other command-line editing key mappings in vim, I suggest that moving forward, **vim-clap** adopts those as much as possible. 

p.s. I want to thank @liuchengxu for implementing my previous feature request #536 within hours

**Comment by liuchengxu** [comment]
Neovim already has this, but not vim as it's not focusable and I won't do this kind of job in the plugin, ref https://github.com/vim/vim/issues/5639 and #306.

**Comment by liuchengxu** [comment]
Seemingly not super hard to support this feature, feel free to try #927.
