### ISSUE TITLE
'Clap tags' command "freezes"

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#539]
**Environment (please complete the following information):**
 - OS: Linux Exherbo
 - (Neo)Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758
 - vim-clap version: 5f239116f1b428dcb7a132806d7808225aa095f5
 - Have you reproduced with a minimal vimrc: tried with one, it isn't reproducible there
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

I enter `Clap tags` in an empty buffer and vim "freezes" (not the UI). I cannot stop or cancel the Command. No key combination works.

**Clap debug**

```

            has cargo: 1
            has maple: /home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/target/release/maple
           maple info: version 0.1.21 (git v0.21-2-g5f23911), built for x86_64-unknown-linux-gnu by rustc 1.42.0-nightly (3bf71b3d5 2020-01-25).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('71'), 'open': function('<SNR>103_create_display'), 'shrink_if_undersize': function('70')}
    let g:clap#popup#preview = {'line_count': function('<SNR>102__line_count'), 'show': function('72'), 'hide': function('73'), 'add_highlight': function('74'), 'get_lines': function('<SNR>102__get_lines'), 'getbufvar': function('<SNR>102__getbufvar'), 'setbufvar_batch': function('<SNR>102__setbufvar_batch'), 'setbufvar': function('<SNR>102__setbufvar'), 'win_is_valid': function('<SNR>102__win_is_valid'), 'goto_win': function('<SNR>102__goto_win'), 'set_syntax': function('75')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '5%', 'row': '33%', 'width': '95%', 'relative': 'editor', 'height': '33%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_use_pure_python = 1
  Provider Variables:
                     []
```

**To Reproduce**

1. start vim with the following config: https://gogs.hasufell.de/hasufell/vim-config/src/commit/f559e8b2426757f3be2097e4bf1923d5d4e54937
2. run `:Clap tags`

**Expected behavior**
Tags show/no tags show/there's a proper error/I can cancel the command

**Screenshots**

![Screenshot_2020-10-12_18-19-29](https://user-images.githubusercontent.com/1241845/95783797-e041b480-0cd2-11eb-9b0e-46995df8210b.png)

**Comment by liuchengxu** [comment]
What's the version of vista.vim you are using? `:Clap tags` relys on vista.vim. And the minimal vimrc is required.

**Comment by hasufell** [comment]
> What's the version of vista.vim you are using?

27889ff58d4340167bb8dd4abbe9ff4a8869da8f

> And the minimal vimrc is required.

I can't reproduce it with one.

**Comment by liuchengxu** [comment]
Can't reproduce. It's probably your some vimrc config that caused this. You have to narrow it down.

**Comment by hasufell** [comment]
> It's probably your some vimrc config that caused this.

Well, maybe, but I've never had a Command that can't be canceled and it isn't easy to debug it either, because I have to kill the editor.

**Comment by liuchengxu** [comment]
What you can do is to keep only the clap and vista.vim related config in your vimrc, removing all the other plugins and settings, see if you can reproduce this issue. If you still see it, share the deduced vimrc here, otherwise add your old configs slowly until you find the culprit line.

**Comment by liuchengxu** [comment]
Not sure if you still can see this issue. Feel free to reopen if you can provide some way for the reproduction.
