### ISSUE TITLE
Sort file list by hits, not alphabetical

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#542]
CtrlP does that too... when you've visited a file before via the menu, it gets a score and will be shown first if the match is as good as the others. This is also the behavior of many other tools, such as rofi. It just means I spend less time looking for the file I actually want.

**Comment by liuchengxu** [comment]
If I understand correctly, CtrlP maintains a list of files selected before using the CtrlP menu in memory and gives a score bonus to them. It's not hard to keep a hits list, but we need to pass them to the Rust end.

**Comment by hasufell** [comment]
I'm not sure if it's in memory. I believe it persists restarts. I'll check out the implementation later.

**Comment by hasufell** [comment]
So does the current implementation persist restarts?

**Comment by liuchengxu** [comment]
Nope

>But it's neither persistent nor well-ordered as I hesitate to write them to the disk and do some more calculations on these BufEnter hooks.

**Comment by liuchengxu** [comment]
The persistent recent files will be supported in #724, feel free to have a try.
