### ISSUE TITLE
Clap preview is slow if the preview line is insanely long

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#543]
**Environment (please complete the following information):**
 - OS: Linux Exherbo
 - (Neo)Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758
 - vim-clap version: 5f239116f1b428dcb7a132806d7808225aa095f5
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

When there's a semi-large json file in the repository with the whole payload on one line, vim-clap gets sluggish and unresponsive when walking over that file in `Clap files`. I have a suspicion that it's trying to render the entire line, no matter how long it is.

**Clap debug**

```

            has cargo: 1
            has maple: /home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/target/release/maple
           maple info: version 0.1.21 (git v0.21-2-g5f23911), built for x86_64-unknown-linux-gnu by rustc 1.42.0-nightly (3bf71b3d5 2020-01-25).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('71'), 'open': function('<SNR>103_create_display'), 'shrink_if_undersize': function('70')}
    let g:clap#popup#preview = {'line_count': function('<SNR>102__line_count'), 'show': function('72'), 'hide': function('73'), 'add_highlight': function('74'), 'get_lines': function('<SNR>102__get_lines'), 'getbufvar': function('<SNR>102__getbufvar'), 'setbufvar_batch': function('<SNR>102__setbufvar_batch'), 'setbufvar': function('<SNR>102__setbufvar'), 'win_is_valid': function('<SNR>102__win_is_valid'), 'goto_win': function('<SNR>102__goto_win'), 'set_syntax': function('75')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '5%', 'row': '33%', 'width': '95%', 'relative': 'editor', 'height': '33%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_use_pure_python = 1
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```
2. Put this file into a repo: https://gist.github.com/hasufell/e7507d33552d3acf692700dfffa8a914

3. Start (neo)vim with command: `vim -u min.vim` from inside that repo

4. See slow behavior

**Expected behavior**

Clap is reponsive.

**Comment by liuchengxu** [comment]
Can not reproduce. And it's theoretically not possible, since `:Clap files` does not read the file content, but only the filename, see https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/provider/files.vim#L9. If you feel some sluggish, please  also post the `profile` result, ref https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow.

**Comment by hasufell** [comment]
> And it's theoretically not possible, since :Clap files does not read the file content

I don't understand. It clearly shows a file preview and while doing so, slows down the plugin:

![clap_files](https://user-images.githubusercontent.com/1241845/96229347-1020de80-0f97-11eb-853c-67af5b0e2d58.png)

> If you feel some sluggish, please also post the profile result, ref https://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow.

I don't see why this needs debugging, because there are *no other plugins* installed.

**Comment by liuchengxu** [comment]
>It clearly shows a file preview and while doing so

That makes sense if you were in fact saying the preview on moving as it indeed read the related lines.

The solution is not reading the whole line but the partial of it because vim can not handle the line insanely lone. I see `E363: pattern uses more memory than 'maxmempattern''` error on my machine.

But the profile is still helpful as it can facilitate finding which function in fact is slow.

**Comment by hasufell** [comment]
> But the profile is still helpful as it can facilitate finding which function in fact is slow.

Let me get that for you: https://gist.github.com/hasufell/8cfe8a160f42a4a33b965ecc8e306a36

**Comment by liuchengxu** [comment]
@hasufell #544 should be able to resolve this issue.
