### ISSUE TITLE
Can this be run in vim in Windows? 

### ISSUE THREAD

**Issue by hy172574895** [liuchengxu/vim-clap#548]
**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: gvim 8.20
 - vim-clap version: newest

**Describe the bug**
:Clap filer
![搜狗截图20201017192303](https://user-images.githubusercontent.com/31300347/96336049-739e2f80-10af-11eb-8b70-8ea873d68409.png)
Others features, like :Clap buffers, are fine.

**Comment by liuchengxu** [comment]
`filer` provider requires the Rust binary of clap, as mentioned in README.
