### ISSUE TITLE
Vim-clap became more and more bigger

### ISSUE THREAD

**Issue by 66RING** [liuchengxu/vim-clap#551]
I don't know if it is a feature or not. But my vim-clap has became more and more bigger.

![bigger](https://user-images.githubusercontent.com/49358576/96346764-1d8db400-10d0-11eb-8eb2-217f349687cf.png)

And it don't seems like a cache. Because the most part from 
![source](https://user-images.githubusercontent.com/49358576/96346762-18c90000-10d0-11eb-820a-a000c26e7b51.png)

**Comment by liuchengxu** [comment]
Try run `cargo clean` and `cargo build --release`periodly then, Rust is responsible for this.
