### ISSUE TITLE
Trying to make kPageUp and kPageDown work

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#552]
I tried adding these bindings to `clap_input.vim`, but it didn't work. Any Ideas? Are these somehow special?

```diff
diff --git a/ftplugin/clap_input.vim b/ftplugin/clap_input.vim
index 1f88861..c751607 100644
--- a/ftplugin/clap_input.vim
+++ b/ftplugin/clap_input.vim
@@ -59,6 +59,9 @@ inoremap <silent> <buffer> <Up>   <C-R>=clap#navigation#linewise('up')<CR>
 inoremap <silent> <buffer> <PageDown> <C-R>=clap#navigation#scroll('down')<CR>
 inoremap <silent> <buffer> <PageUp>   <C-R>=clap#navigation#scroll('up')<CR>

+inoremap <silent> <buffer> <kPageDown> <C-R>=clap#navigation#scroll('down')<CR>
+inoremap <silent> <buffer> <kPageUp>   <C-R>=clap#navigation#scroll('up')<CR>
+
 inoremap <silent> <buffer> <Tab>       <C-R>=clap#handler#tab_action()<CR>
 inoremap <silent> <buffer> <Backspace> <C-R>=clap#handler#bs_action()<CR>

@@ -86,6 +89,9 @@ nnoremap <silent> <buffer> <Up>   :<c-u>call clap#navigation#linewise('up')<CR>
 nnoremap <silent> <buffer> <PageDown> :<c-u>call clap#navigation#scroll('down')<CR>
 nnoremap <silent> <buffer> <PageUp>   :<c-u>call clap#navigation#scroll('up')<CR>

+nnoremap <silent> <buffer> <kPageDown> :<c-u>call clap#navigation#scroll('down')<CR>
+nnoremap <silent> <buffer> <kPageUp>   :<c-u>call clap#navigation#scroll('up')<CR>
+
 nnoremap <silent> <buffer> <C-d> :<c-u>call clap#navigation#scroll('down')<CR>
 nnoremap <silent> <buffer> <C-u> :<c-u>call clap#navigation#scroll('up')<CR>
```

**Comment by liuchengxu** [comment]
I believe it's not an issue of vim-clap, you have to ensure you can trigger `<kPageDown>` and `<kPageUp>` properly. I don't try this, but I heard of `<M-foo>` may not work for some terminals, `<kPageDown>` might be the same case, you need to configure your terminal emulator or something to make it work.

**Comment by hasufell** [comment]
I don't use a terminal, i use gvim. kPageDown and up seem to work, they scroll editor scroll view just fine. I can also rebind them just fine to something else. But they don't work with vim-clap.

**Comment by liuchengxu** [comment]
Since `<PageDown>` and `<PageUp>` can work with vim-clap, so I don't think it's an issue of vim-clap.

**Comment by hasufell** [comment]
> Since <PageDown> and <PageUp> can work with vim-clap, so I don't think it's an issue of vim-clap.

I don't see how that is a proof. Did you try to make `kPageUp` work in vim-clap?

**Comment by liuchengxu** [comment]
Nope, I don't use `<kPageUp>`.

**Comment by hasufell** [comment]
> Nope, I don't use <kPageUp>, and I don't know how to trigger this :).

Very simple...

1. apply the patch:

```diff
diff --git a/ftplugin/clap_input.vim b/ftplugin/clap_input.vim
index 1f88861..c751607 100644
--- a/ftplugin/clap_input.vim
+++ b/ftplugin/clap_input.vim
@@ -59,6 +59,9 @@ inoremap <silent> <buffer> <Up>   <C-R>=clap#navigation#linewise('up')<CR>
 inoremap <silent> <buffer> <PageDown> <C-R>=clap#navigation#scroll('down')<CR>
 inoremap <silent> <buffer> <PageUp>   <C-R>=clap#navigation#scroll('up')<CR>

+inoremap <silent> <buffer> <kPageDown> <C-R>=clap#navigation#scroll('down')<CR>
+inoremap <silent> <buffer> <kPageUp>   <C-R>=clap#navigation#scroll('up')<CR>
+
 inoremap <silent> <buffer> <Tab>       <C-R>=clap#handler#tab_action()<CR>
 inoremap <silent> <buffer> <Backspace> <C-R>=clap#handler#bs_action()<CR>

@@ -86,6 +89,9 @@ nnoremap <silent> <buffer> <Up>   :<c-u>call clap#navigation#linewise('up')<CR>
 nnoremap <silent> <buffer> <PageDown> :<c-u>call clap#navigation#scroll('down')<CR>
 nnoremap <silent> <buffer> <PageUp>   :<c-u>call clap#navigation#scroll('up')<CR>

+nnoremap <silent> <buffer> <kPageDown> :<c-u>call clap#navigation#scroll('down')<CR>
+nnoremap <silent> <buffer> <kPageUp>   :<c-u>call clap#navigation#scroll('up')<CR>
+
 nnoremap <silent> <buffer> <C-d> :<c-u>call clap#navigation#scroll('down')<CR>
 nnoremap <silent> <buffer> <C-u> :<c-u>call clap#navigation#scroll('up')<CR>
```

2. start vim
3. run `:Clap files`
4. try to use `<kPageDown>`/`<kPageUp>`

**Comment by hasufell** [comment]
Actually I think I'm wrong. It must be something else interfering. It works with a minimal vimrc. I double checked that.

**Comment by hasufell** [comment]
Actually no... it isn't about my config. The situation is this: it doesn't work in **gvim**, but in **vim** and **neovim**. This is quite confusing.

**Comment by liuchengxu** [comment]
Not sure, but since terminal vim and neovim is good, I think it's an issue of gvim then.

**Comment by hasufell** [comment]
@liuchengxu this is a plugin issue and not a gvim issue, see https://github.com/vim/vim/issues/7174#issuecomment-712856307

**Comment by liuchengxu** [comment]
You should use `g:clap_popup_move_manager` for vim popup, `:h change-clap-default-keybindings`. `clap_input.vim` is for neovim only. If you provide the more complete issue report, thent there will be less misunderstandings here.

**Comment by hasufell** [comment]
> If you provide the more complete issue report, then there will be less misunderstandings here.

The title clearly said **vim**, not neovim.

**Comment by hasufell** [comment]
> You should use g:clap_popup_move_manager

That works great!
