### ISSUE TITLE
How to run grep with multiple words/a selection

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#553]
I'm currently using
```vim
command -nargs=* Rag Clap grep ++query=<args>
```
This doesn't work for multiple words. Only the first word will be picked. I tried all sorts of stuff with quotes, but nothing worked.

Is there a function I could call instead?

**Comment by liuchengxu** [comment]
`:Clap grep ++query=<query1> ++query=<query2>`, `grep` will search for the input `query1 query2`.

**Comment by hasufell** [comment]
> :Clap grep ++query=<query1> ++query=<query2>, grep will search for the input query1 query2.

That doesn't answer my question. I don't know how many words `<args>` has.

**Comment by liuchengxu** [comment]
You can write your parser to parse `args` and then feed the parsed multiple words into clap using the way of `++query=word1 ++query=word2`.

**Comment by liuchengxu** [comment]
```vim
command! -nargs=* Rag call MultiGrep(<f-args>)

function! MultiGrep(...) abort
  let opts = map(copy(a:000), "printf('++query=%s', v:val)")
  execute 'Clap grep' join(opts, ' ')
endfunction
```

**Comment by hasufell** [comment]
@liuchengxu this won't preserve whitespace and will not work too nicely with visual selection

**Comment by liuchengxu** [comment]
Use `:Clap grep ++query=@visual` if you want to search the visual selection.

**Comment by QiBaobin** [comment]
[Take a look at this](https://github.com/liuchengxu/vim-clap/pull/689), we can discuss on it.
