### ISSUE TITLE
Sign and rooter related options renaming

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vim-clap#56]
These two options will be renamed:

- `g:clap_current_selection_sign_definition` -> `g:clap_current_selection_sign`
- `g:clap_selected_sign_definition` -> `g:clap_selected_sign`

**Comment by alerque** [comment]
Sometimes less words bring more clarity. This is one of those times.

**Comment by liuchengxu** [comment]
`g:clap_disable_run_from_project_root` will be renamed to `g:clap_disable_run_rooter`.
