### ISSUE TITLE
:Clap install-binary don't work on Windows (continues #529)

### ISSUE THREAD

**Issue by Grueslayer** [liuchengxu/vim-clap#560]
At least on Windows updating binary by compiling leads to the same problem as #529.

Something else must lock the file. Solution from #529 also applies here but file still can not be overwritten. 

```
warning: unused import: `Path`
 --> crates\upgrade\src\download.rs:4:17
  |
4 | use std::path::{Path, PathBuf};
  |                 ^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 2.69s
   Compiling pyo3 v0.12.0
   Compiling fuzzymatch-rs v0.1.0 (C:\Users\jstocker9330\vimfiles\bundle\vim-clap\pythonx\clap\fuzzymatch-rs)
    Finished release [optimized] target(s) in 15.81s
Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
        0 Datei(en) kopiert.   
```

**Comment by liuchengxu** [comment]
If `cargo` exists in your system, `:Clap install-binary!` will always recompile the binary. You just do not run `:Clap install-binary` when you are using vim then. Always compile the binary from the terminal. I don't use Windows, can't help more.
