### ISSUE TITLE
Improve file filtering

### ISSUE THREAD

**Issue by romgrk** [liuchengxu/vim-clap#561]
**Problem**

When I search for a file, the first thing I'll remember is its name. The matching algorithm doesn't give a bonus if the needle matches in the basename of the haystack.

**Solution**

Give a bonus if the needle matches in the basename.

![Screenshot from 2020-10-21 13-48-59](https://user-images.githubusercontent.com/1423607/96757981-30d8a200-13a4-11eb-9a2f-20f0af90c2e0.png)
In this examples, files names as `**/fil*` should appear first.

**Comment by liuchengxu** [comment]
#614 simply adds a bonus for the matches in filename, feel tree to have a try.
