### ISSUE TITLE
Improve file searching: add bonus for recently opened files

### ISSUE THREAD

**Issue by romgrk** [liuchengxu/vim-clap#563]
**Problem**

I use `:Clap files` as my generic switch-to-file. Often I'll switch between recent files more than between recent and old files. I would be nice if the searching algorithm could give a bonus to recent files, instead of other less intuitive bonuses (eg shorter match).

**Solution**

Maintain a list of recent files and give a bonus to them.

**Other comments**

This behavior could be generalised for all other providers, that a recently selected item should be given a bonus if its score is the same as other matches.

This suggestion is also related to having a MRU provider, one that works and isn't based on the unreliable `:oldfiles`. I found a nice implementation here: https://github.com/markwu/vim-mrufiles

**Comment by liuchengxu** [comment]
Actually vim-clap already has a sort of in-memory MRU list `g:__clap_buffers` . https://github.com/liuchengxu/vim-clap/blob/a7bd31a5dbdbd8bd6436edcc358851405f0c3fc3/plugin/clap.vim#L48

For this issue, we can maintain a persistent MRU list by writing `g:__clap_buffers` to a file when leaving vim. When we match the source item that is a file path, read the MRU file and add a bonus to the match result produced by the base algorithm like #614.
