### ISSUE TITLE
Support fzy in lua

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vim-clap#565]
Now clap already supports `fzy` in pure Python, Python dynamic module in Rust and pure Rust, but none of them is native to neovim. And lua is generally much faster than Python, especically neovim uses luajit. There is already a fzy implementation in lua https://github.com/swarn/fzy-lua, [related telescope.nvim PR](https://github.com/nvim-lua/telescope.nvim/pull/184), I think it's great to also support it in clap. We merely need some glue code like https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/filter/sync/python.vim for this task.

**Comment by romgrk** [comment]
I've implemented luajit-ffi bindings for lua. This repo contains telescope's port of lua as well as bindings to a modified C fzy version: https://github.com/romgrk/fzy-lua-native

For more context: https://github.com/nvim-lua/telescope.nvim/issues/215#issuecomment-720888143

(I'm not planning on switching fuzzy-finder don't worry, I was just reading their code :laughing: )

**Comment by romgrk** [comment]
Update: the implementation doesn't choke on utf8 more-than-one-byte character, but it does consider those bytes as single characters and returns, eg 2 positions if those bytes match.

```lua
local native = require'native'

local positions = native.positions('pé', 'spécial')

for i, p in ipairs(positions) do
  print(p)
end

-- Outputs: (zero-indexed)
--  1 (p)
--  2 (é first byte)
--  3 (é second byte)
```

That seems similar to lua's `string:sub` that will substring by byte (from what I can see) rather than by character.

**Comment by tjdevries** [comment]
:eyes:
