### ISSUE TITLE
Hitting "enter"/`<CR>` doesn't create file if it doesn't exist anymore

### ISSUE THREAD

**Issue by macintacos** [liuchengxu/vim-clap#568]
**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - (Neo)Vim version: 0.4.4
 - vim-clap version: cb61e9a
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**
When I open `:Clap filer` and type the name of a file that doesn't exist and hit "enter", the file isn't created (as I would expect).

**Clap debug**

```
            has cargo: 1
            has maple: /Users/juliant/.config/vim-plug/vim-clap/target/release/maple
           maple info: version 0.1.21 (git v0.21), built for x86_64-apple-darwin by rustc 1.46.0.
         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
     Current FileType: vim-plug
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/juliant/.config/vim-plug/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'row': '20%', 'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`
3. Type `:Clap filer`
4. Attempt to create a file in the a directory by just typing the name of a file that doesn't exist and hit "enter".
5. Nothing happens

**Expected behavior**
A file is created when hitting "enter"

**Screenshots**

**Additional context**
I believe that the ability to hit "enter" to create a file was added [here](https://github.com/liuchengxu/vim-clap/commit/f5f9f60558c7bc1bfe6a577f1fd9f91ff9ab55bf) and the issue might've been introduced by #547.

**Comment by romgrk** [comment]
I can reproduce the issue and this is totally my fault (#547). I'm on it.

**Comment by romgrk** [comment]
Done

**Comment by macintacos** [comment]
Sweet, thanks @romgrk!
