### ISSUE TITLE
Support tags via gutentags as alternative to vista

### ISSUE THREAD

**Issue by alerque** [liuchengxu/vim-clap#57]
The current tag provider implementation requires [vista]. While vista is quite a nice system and I've evaluated switching to it in the past, I keep settling back on [gutentags] and [tagbar] as my preferred plugins for tag management. Some of my uses for tagbar could be better served with Clap. It's nice to have the overview pane stick around sometimes, but when I just want to jump to something and be done with it Clap would make more sense.

Supporting tags via gutentags without requiring vista would be a nice future addition. Of course this doesn't have to be done by the plugin author, anybody could contribute this! I might try someday but won't get around to it soon if anybody else wants to take a stab at it go ahead.

 [vista]: https://github.com/liuchengxu/vista.vim
 [gutentags]: https://github.com/ludovicchabant/vim-gutentags
 [tagbar]: https://github.com/majutsushi/tagbar

**Comment by alerque** [comment]
@github-actions The only thing stale around here is you.

**Comment by alerque** [comment]
Request re-open, feature request still stands. Bot closure is overly aggressive. Adding a tag is one thing...

**Comment by liuchengxu** [comment]
@alerque With #795, no other vim plugins are neccessary as vim-clap can generate the source of `tags` provider using the Rust binary no matter if the ctags executable supports the json output format.

**Comment by alerque** [comment]
Interesting…
