### ISSUE TITLE
Scroll Preview

### ISSUE THREAD

**Issue by sphynx79** [liuchengxu/vim-clap#573]
Please can you implement or tell me how can i scroll the preview.

Thanks

**Comment by polyzen** [comment]
https://github.com/liuchengxu/vim-clap#keybindings

**Comment by sphynx79** [comment]
good but i don't want scroll the file list, but the preview file window

**Comment by liuchengxu** [comment]
That can be done, but need a bit more work as the current preview implementation does not read the whole file but the neccessary lines for being performant. When you scroll the preview window, we have to keep reading more of the origin file.

**Comment by comfortablynick** [comment]
This would be great, since fzf is able to do it (seemingly without a performance penalty).

**Comment by liuchengxu** [comment]
The preview of vim-clap will also be enhanced once #798 is merged, which is to extract and show the current context symbol using ctags. Maybe helpful for those who are interested in this issue.

**Comment by liuchengxu** [comment]
I finally find some time to implement this feature that I'm also looking forward to for a long time. Feel free to try out #933, don't forget to recompile the binary before the next release is available.
