### ISSUE TITLE
[coc.nvim]: Error on InsertLeave: Cannot read property 'textDocument' of undefined

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vim-clap#574]
Since a72ccfb, I see this error when I press `<CR>` to apply the sink:

<img width="1527" alt="截屏2020-10-30 下午5 34 19" src="https://user-images.githubusercontent.com/8850248/97689161-26ba5000-1ad6-11eb-935d-29167733a0db.png">

I have opened #575 to fix this, not sure whether you have the same problem, please take a look at it :) @romgrk

**Comment by liuchengxu** [comment]
>does not using stopinsert prevents InsertLeave from being triggered?

Or prevent triggering insertLeave when the document is undefined?

Since #575 is equivalent as before from the view of vim-clap, and some people might have not upgraded coc-rust-analyzer, #575 does not bring any harm, I think it's ok to merge it in even the upstream already fixed this issue.

**Comment by romgrk** [comment]
Ok, sounds good to me then :)
