### ISSUE TITLE
Filer does not work anymore (Vim)

### ISSUE THREAD

**Issue by Grueslayer** [liuchengxu/vim-clap#581]
With one of the last commits filer has been corrupted (at least on Windows / can test on MacOS this evening):

The filename is been stripped of the selected entry:

`s:cr_action()` line 239 `s:get_current_entry()` is still correct (path including filename). Here the sink handler will be called.

`s:filer_sink()` line 260 `s:get_current_entry()` is defect and contains only the directory without the filename.

This is happening because `g:clap.display.getcurline()` don't give you the correct line anymore at this time.

Why not using the `selected` argument from the sink anymore?

```diff
index f084d12..cdc06a8 100644
--- a/autoload/clap/provider/filer.vim
+++ b/autoload/clap/provider/filer.vim
@@ -154,8 +154,8 @@ function! s:reset_to(new_dir) abort
   call s:filter_or_send_message()
 endfunction
 
-function! s:get_current_entry() abort
-  let curline = g:clap.display.getcurline()
+function! s:get_entry_by_line(line) abort
+  let curline = a:line
   if g:clap_enable_icon
     let curline = curline[4:]
   endif
@@ -163,6 +163,10 @@ function! s:get_current_entry() abort
   return s:smart_concatenate(s:current_dir, curline)
 endfunction
 
+function! s:get_current_entry() abort
+  return s:get_entry_by_line(g:clap.display.getcurline())
+endfunction
+
 function! s:try_go_to_dir_is_ok() abort
   let input = g:clap.input.get()
   if input[-1:] ==# s:PATH_SEPERATOR
@@ -257,7 +261,7 @@ function! s:smart_concatenate(cur_dir, curline) abort
 endfunction
 
 function! s:filer_sink(selected) abort
-  execute 'edit' s:get_current_entry()
+  execute 'edit' s:get_entry_by_line(a:selected)
 endfunction
 
 function! s:filer_on_typed() abort
```

**Comment by romgrk** [comment]
I could reproduce the issue in vim, the fix has been applied. Thanks for the report, please re-open if you encounter anymore issue.
