### ISSUE TITLE
Refresh while scrolling brakes with other plugins installed

### ISSUE THREAD

**Issue by BonaBeavis** [liuchengxu/vim-clap#586]
- OS: Linux
 - (Neo)Vim version: neovim-0.5.0+ubuntu2+git202011062021-d17e50879-d569569c9
 - vim-clap version: 45a91bf
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
With multiple plugins installed 'linewise down' breaks. It is sluggish and does not refresh the clap window until key is released.

**Clap debug**

has cargo: 1
            has maple: /home/beavis/.vim/bundle/vim-clap/target/release/maple
           maple info: version 0.1.21 (git v0.21), built for x86_64-unknown-linux-gnu by rustc 1.43.0.
         has +python3: 1
has py dynamic module: 1
            has ctags: ctags without JSON output support
     Current FileType: vim
Third Party Providers: []
       Global Options:

```vim
set nocompatible
filetype off

call plug#begin('~/.vim/bundle')
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'sheerun/vim-polyglot'
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
call plug#end()

let g:python_host_prog = '/home//.virtualenvs/neovim/bin/python'
let g:python3_host_prog = '/home//.virtualenvs/neovim3/bin/python3'

syntax on
filetype plugin indent on
set hidden
```
1. `:Clap command`
1. Keep `<c-j>` pressed (scroll down)

I could not isolate a single plugin, the behavior only happens with all of them installed. Would be surprised if this is reproducible.

**Comment by romgrk** [comment]
Can you test again twice, but before:
 - the first one, set `set verbosefile=out-autocmd.txt verboselevel=9`
 - the second one, set `set verbosefile=out-functions.txt verboselevel=12`
And after each test, run `set verboselevel=0` as quickly as possible, otherwise those log files become too big to be readable & usable because we don't know where the test happened.

And you're 100% positive that you can't disable a single one of those plugins while still being able to reproduce the issue?

**Comment by BonaBeavis** [comment]
It I is a gradual decline, the more plugins the choppier it gets, with all these plugins activated nvim stops to refresh. Like [this](https://asciinema.org/a/CVHxfOs7NemtnajIWokMcBTXw).

I did your test and it gets even weirder, setting verbose level to 9 actually improves scrolling o.O"

I created two test files, one is just a single `<c-j>`, other is burst mode `<c-j>`.
[out-autocmd.txt](https://github.com/liuchengxu/vim-clap/files/5510559/out-autocmd.txt)
[out-autocmd-one-line.txt](https://github.com/liuchengxu/vim-clap/files/5510561/out-autocmd-one-line.txt)

Maybe you see something, but I think the underlying issue is that every line seems to be a file and because of this a load of autocommands get triggered and those autocommands are intended to be called one time when opening a file and not 20 times a second for every scroll.

**Comment by romgrk** [comment]
Yep, those autocommands are clearly affecting performance. Ideally there should be none of that. From the log file I can't see what is triggering the autocommands, but could you test the branch `draft-scrolling-issue` of this repository, and let me know if it works better?

**Comment by BonaBeavis** [comment]
With the new branch it works perfectly! Thanks a lot.

**Comment by romgrk** [comment]
I'll keep the issue open. I just added a bunch of `noautocmd` where I thought it might be good to have some but we'll need to make a proper PR to merge the changes. I have no idea if those `noautocmd` might cause unwanted behavior. I'll try to make a PR soon.

**Comment by liuchengxu** [comment]
After some profile, I found it's the update of airline that should be blamed, https://github.com/liuchengxu/vim-clap/commit/aeea08750add11dde8717274bfa53dc38cee38c8 just works for me, let me know if the issue persists. @BonaBeavis
