### ISSUE TITLE
Reopen last grep window

### ISSUE THREAD

**Issue by jheroy** [liuchengxu/vim-clap#588]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Like CtrlSF's CtrlSFOpen command, when I grep something, after I jumped one of them, the grep window closed. But I want jump another again. There is no need to grep again, just popup last grep result and put the cursor to my last jump item. 

If there are other ways to achieve this function, just let me know please. Thanks.

**Comment by romgrk** [comment]
Related to #235 right?

To be clear, you want the possibility to cycle through grep results, right?
One easy way to handle this could be to populate the location list.

**Comment by jheroy** [comment]
> Related to #235 right?
> 
> To be clear, you want the possibility to cycle through grep results, right?
> One easy way to handle this could be to populate the location list.
Yes, I want to cycle through grep results with out search it again.
BTW, Is there any way to put grep result in location list now?

**Comment by romgrk** [comment]
Off the top of my head I don't know. We'd need to add a `setloclist()` call somewhere, but grep results are async, and I'm not sure if they are present in-memory in vim, or if part of the results are lazy-loaded from the rust searcher (out of process).

**Comment by liuchengxu** [comment]
>BTW, Is there any way to put grep result in location list now?

When you select multiple items, the quickfix window will be populated and opened automatically., see https://github.com/liuchengxu/vim-clap.git/blob/45a91bf706e9dcf85172c126bbac8964e209a4ae/autoload/clap/provider/grep.vim#L246.

It's not hard to keep and restore the results in the display window, we can simply keep the lines of clap display window when applying the sink, but that's not guranteed to be the complete results of last search.

**Comment by liuchengxu** [comment]
Closing as you can just select the items you need, press `<Enter>` to open them in the quickfix window, and cycle through these results.
