### ISSUE TITLE
Cannot create new file with `Clap filer`

### ISSUE THREAD

**Issue by phongnh** [liuchengxu/vim-clap#589]
**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  4 2020 11:27:02)
macOS version
Included patches: 1-1950
Compiled by Homebrew
 - vim-clap version: 45a91bf706e9dcf85172c126bbac8964e209a4ae
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes - Tried run `:Clap install-binary!` in vim

**Describe the bug**

**Clap debug**

```

            has cargo: 1
            has maple: /Users/phong/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.21, built for x86_64-apple-darwin by rustc 1.47.0 (18bf6b4f0 2020-10-07).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/phong/.vim/plugged/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('51'), 'open': function('<SNR>27_create_display'), 'width': 69, 'shrink_if_undersize': function('50')}
    let g:clap#popup#preview = {'line_count': function('<SNR>26__line_count'), 'show': function('52'), 'hide': function('53'), 'bufnr': 6, 'add_highlight': function('54'), 'get_lines': function('<SNR>26__get_lines'), 'getbufvar': function('<SNR>26__getbufvar'), 'setbufvar_batch': function('<SNR>26__setbufvar_batch'), 'setbufvar': function('<SNR>26__setbufvar'), 'winid': 1008, 'win_is_valid': function('<SNR>26__win_is_valid'), 'goto_win': function('<SNR>26__goto_win'), 'set_syntax': function('55')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_indicator_winid = 1009
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1011
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set encoding=utf-8
scriptencoding utf-8
set nocompatible
set termguicolors
set runtimepath^=~/.vim/plugged/vim-clap
syntax on
filetype plugin indent on
```
2. Start (neo)vim with command: `vim -u min.vim`

3. Type `Clap filer` and input inexistent path and press Enter `<CR>`

4. See error: `No such file or directory (os error 2)`

**Expected behavior**

I can create new file on pressing Enter

**Screenshots**

<img width="1792" alt="Screen Shot 2020-11-14 at 12 35 48 AM" src="https://user-images.githubusercontent.com/438791/99102929-59edfa80-2611-11eb-8508-ffc4b8d1a111.png">

<img width="1792" alt="Screen Shot 2020-11-14 at 12 41 58 AM" src="https://user-images.githubusercontent.com/438791/99103489-37a8ac80-2612-11eb-9c08-f0322f99e255.png">

Could you help check this issue? Thanks.

**Comment by romgrk** [comment]
Can reproduce, will take a more detailed look later.

**Comment by liuchengxu** [comment]
@phongnh Can you see if this patch works?

```diff
diff --git a/autoload/clap/provider/filer.vim b/autoload/clap/provider/filer.vim
index cdc06a8..caf8811 100644
--- a/autoload/clap/provider/filer.vim
+++ b/autoload/clap/provider/filer.vim
@@ -218,7 +218,7 @@ function! s:cr_action() abort
     return
   endif

-  if exists('g:__clap_has_no_matches') && g:__clap_has_no_matches
+  if g:clap.display.line_count() == 1 && g:clap.display.get_lines()[0] =~# s:CREATE_FILE
     " Create file if it doesn't exist
     stopinsert
     call clap#handler#sink()
```

Since we injected the `query` line into the candidates, `g:__clap_has_no_matches` will never be true then. @romgrk 
https://github.com/liuchengxu/vim-clap/blob/5d2a04ca8c33f4031cd89a012663ca34ae854b8f/autoload/clap/provider/filer.vim#L143-L144

**Comment by phongnh** [comment]
Thanks @liuchengxu. It works for these case:
- creating new file from current folder
- creating new file from non-empty folder

<img width="713" alt="Screen Shot 2020-11-14 at 10 32 07 AM" src="https://user-images.githubusercontent.com/438791/99138671-df4eca80-2664-11eb-9939-5e16d0ebb2be.png">

<img width="386" alt="Screen Shot 2020-11-14 at 10 32 15 AM" src="https://user-images.githubusercontent.com/438791/99138673-e37ae800-2664-11eb-9790-a47abda60d10.png">

<img width="667" alt="Screen Shot 2020-11-14 at 10 32 47 AM" src="https://user-images.githubusercontent.com/438791/99138676-ebd32300-2664-11eb-8ac8-d488a968f012.png">

<img width="469" alt="Screen Shot 2020-11-14 at 10 32 53 AM" src="https://user-images.githubusercontent.com/438791/99138677-efff4080-2664-11eb-88f3-aa5ce734f977.png">

It does not work for the case - empty folder. Please check screenshots:


<img width="651" alt="Screen Shot 2020-11-14 at 10 33 23 AM" src="https://user-images.githubusercontent.com/438791/99138688-fd1c2f80-2664-11eb-854b-d7eb916abf6c.png">

<img width="457" alt="Screen Shot 2020-11-14 at 10 33 29 AM" src="https://user-images.githubusercontent.com/438791/99138686-fbeb0280-2664-11eb-8492-b57923d3b327.png">

**Comment by romgrk** [comment]
> Since we injected the query line into the candidates, g:__clap_has_no_matches will never be true then.

Indeed, I've applied your patch in #590. 

@phongnh Please update to latest master and reopen if it happens again :]

**Comment by liuchengxu** [comment]
@phongnh The issue of creating a new file under empty folder has been resovled in https://github.com/liuchengxu/vim-clap/commit/b2fe93fbee23c3dba24439e0e0bf8c5b77eb5447, please have a try.

**Comment by phongnh** [comment]
Thanks @romgrk. I fixed problem for creating new file.

@liuchengxu I tried to test two cases:

1. I typed `emptydir/new.txt`, and pressed Enter, it created `new.txt` correctly

![Screen Shot 2020-11-16 at 10 42 21 AM](https://user-images.githubusercontent.com/438791/99210626-e4448300-27f8-11eb-88f3-77fc611fc7a4.png)

![Screen Shot 2020-11-16 at 10 42 35 AM](https://user-images.githubusercontent.com/438791/99210642-ed355480-27f8-11eb-94aa-7c54332cc73c.png)


2. I typed `emp`, and press `TAB` to go to `emptydir`, then I typed `new.txt`, it did not show option to create new file. I'm not sure this case is a bug or not.

![Screen Shot 2020-11-16 at 10 44 14 AM](https://user-images.githubusercontent.com/438791/99210648-f2929f00-27f8-11eb-89c7-d8ebf46e59e2.png)
![Screen Shot 2020-11-16 at 10 44 18 AM](https://user-images.githubusercontent.com/438791/99210654-f58d8f80-27f8-11eb-91b4-a37486799160.png)
![Screen Shot 2020-11-16 at 10 44 25 AM](https://user-images.githubusercontent.com/438791/99210658-f8888000-27f8-11eb-961b-902b8a9095d6.png)

**Comment by liuchengxu** [comment]
@phongnh You can still create the new file as expected, but the prompt message `Directory is empty` can definitely be improved.

**Comment by phongnh** [comment]
@liuchengxu Just tried again, press `ENTER` on `new.txt` in last screenshot. It works. Thank you.
