### ISSUE TITLE
"Clap buffers" should be ordered in LRU-order

### ISSUE THREAD

**Issue by sscherfke** [liuchengxu/vim-clap#59]
The list displayed by `:Clap buffers` is currently sorted by buffer number. It would be more convenient if it was sorted descencingly by the time of last use.

I have mapped `:Clap buffers` to `<leader>ob` (**o**pen **b**uffer).  If the list was sorted by LRU, I could simply type `,ob<CR>` to toggle between the both last used buffers (e.g., implementation and corresponding tests).

**Comment by sscherfke** [comment]
Thank you for that fix! :-)

It would be nice, if the current buffer was omitted from the list (or at least, put at its end). Currently, you have to type an additioanl `Ctrl+j` (or `down`) to move to the second entry when you want to toggle between buffers.

**Comment by liuchengxu** [comment]
Makes some sense. Please create a new issue for that feature.
