### ISSUE TITLE
Grep isn't linear in memory

### ISSUE THREAD

**Issue by hasufell** [liuchengxu/vim-clap#592]
**Environment (please complete the following information):**
 - OS: Linux Exherbo
 - (Neo)Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758
 - vim-clap version: 5f239116f1b428dcb7a132806d7808225aa095f5
 - Have you reproduced with a minimal vimrc: tried with one, it isn't reproducible there
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

I just grepped in a project (`Clap grep`) and it hit my memory limit (I have 32GB of ram).

![Screenshot_2020-11-16_17-55-14](https://user-images.githubusercontent.com/1241845/99283317-2390c500-2835-11eb-97aa-3741c101e7ee.png)

**Clap debug**

I can't debug, because I have to wait until the process is OOM killed.

**To Reproduce**

No idea how to reproduce. I cannot bundle my code or the project. It's possible this is a bug in `rg`.

**Comment by liuchengxu** [comment]
Try `:Clap grep2`?

**Comment by romgrk** [comment]
@liuchengxu Does `grep` has advantages over `grep2`? Could be nice to delete it if it's less polished than `grep2`.

**Comment by liuchengxu** [comment]
Hmm, I think the only advantage of `grep` is it can work without the Rust binary, but `grep2` can't :(.

**Comment by liuchengxu** [comment]
@hasufell There are not many things that can be done on the plugin side, see also https://github.com/liuchengxu/vim-clap. What you can do is to just use `:Clap grep2` in this case.
