### ISSUE TITLE
Add a way to disable background shadow per provider

### ISSUE THREAD

**Issue by comfortablynick** [liuchengxu/vim-clap#594]
**Is your feature request related to a problem? Please describe.**
I have a provider to cycle through theme variations similar to the built-in . I like the background shadow, but it gets in the way of this provider.

**Describe the solution you'd like**
I'd like the ability to set this option for a specific provider, or at least a hook that can be used to run general configuration before the windows are drawn. If there is a way, I must have overlooked it.

**Describe alternatives you've considered**
I tried setting `g:clap_enable_background_shadow = v:false` in an `init()` method but that didn't seem to work.

**Comment by romgrk** [comment]
So it's a provider in your personal config?

If so, wouldn't something like this work for your use-case?

```vim
com! ClapColors call ClapColors()
fu! ClapColors()
  let g:clap_enable_background_shadow = v:false
  Clap custom_colors
endfu
" and reset g:clap_enable_background_shadow in your provider's exit
```

**Comment by comfortablynick** [comment]
Yes, that does work. I was just wondering if there was something like the inverse of `on_exit` that could be called to set variables before running the provider, without wrapping in a function. 

It works doing what you suggested.

**Comment by romgrk** [comment]
I don't see any hook for that so it doesn't seem to be possible to run a function before the init function.
