### ISSUE TITLE
Conflict with vim-better-whitespace since commit 0470873

### ISSUE THREAD

**Issue by zhyu** [liuchengxu/vim-clap#596]
**Environment (please complete the following information):**
 - OS: macOS 10.13.6 / Ubuntu 18.04
 - (Neo)Vim version: NVIM v0.4.4
 - vim-clap version: 0470873 and later versions
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: downloaded the latest prebuilt binary

**Describe the bug**
Using `Clap grep` (`Clap files` as well, but hard to reproduce), Clap will fail to clear displayed matches when the query being updated and no matches found. An error will be raised like:
```
Error detected while processing function <SNR>99_apply_grep[11]..<SNR>99_spawn[13]..<SNR>99_clear_job_and_matches[3]..33
[8]..41:
line    2:
E803: ID not found: 4
```

**Clap debug**

```
            has cargo: 0
            has maple: /Users/zhyu/.vim/plugged/vim-clap/bin/maple
           maple info: version 0.1.21 (git v0.21), built for x86_64-apple-darwin by rustc 1.46.0 (04488afe3 2020-08-24).

         has +python3: 0
has py dynamic module:
Error detected while processing /Users/zhyu/.vim/plugged/vim-clap/autoload/clap/filter/sync/python.vim:
line   39:
E319: No "python" provider found. Run ":checkhealth provider"0
            has ctags:
vim-clap: Ensure ctags executable is in your PATH and has the JSON output featurectags without JSON output support
     Current FileType: clap_input
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/zhyu/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
Press ENTER or type command to continue
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
set runtimepath^=/path/to/vim-better-whitespace
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim` in a directory with some files

3. Execute `Clap grep`, type a query to get some matches, like:
query: `abc`
matches:
* `abc1`
* `abc2`
* `abc3`

4. Type something more so there should be no matches, like:
query: `abc4`

5. See error

**Expected behavior**
All matches displayed in step 3 should be cleared, and show "NO MATCHES" without any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/1728523/100402492-bfc19400-309f-11eb-997d-7c4afc78a1e3.png)

**Additional context**
1. I found it seems to be a conflict with [ntpeters/vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace), and I guess it's because `vim-better-whitespace` having some `autocmd` setups. I'm not sure whether it would be in conflict with other plugins
2. I tried with various Clap commits and discovered it only happens since 0470873
3. I checked the changeset of 0470873. Not sure the reason, but the following patch solves the issue for me:
```
diff --git a/autoload/clap/api.vim b/autoload/clap/api.vim
index b55932c..2ac897b 100644
--- a/autoload/clap/api.vim
+++ b/autoload/clap/api.vim
@@ -8,7 +8,7 @@ let s:is_nvim = has('nvim')
 let s:cat_or_type = has('win32') ? 'type' : 'cat'

 function! s:_goto_win() dict abort
-  call win_gotoid(self.winid)
+  noautocmd call win_gotoid(self.winid)
 endfunction

 function! s:_getbufvar(varname) dict abort
```

**Comment by liuchengxu** [comment]
Fixed in the master.
