### ISSUE TITLE
Option to open files and grep from git/svn base directory

### ISSUE THREAD

**Issue by ratheesh** [liuchengxu/vim-clap#6]
The interface of this plugin is very nice and looking forward for more features.

It would be really nice to provide commands to `open files` from git base directory of the current buffer, `MRU`(both systemwide and withing git repositoryones(if buffer in git)) and `grep` inside git repository. With these, I can ditch ctrlp and start using this plugin fulltime.

Thank you for this promising plugin!

**Comment by liuchengxu** [comment]
Currently, vim-clap doesn't touch the `cwd` of vim, so if you use https://github.com/airblade/vim-rooter, I believe `Clap files` or `Clap grep` will always use the project root as the cwd, is that what you want, right? I can also add some simple detection for the git repository in vim-clap itself, it should not be hard.

>MRU(both systemwide and withing git repositoryones(if buffer in git)) 

I don't quite understand _systemwide and withing git repositoryones_. I do have a plan to support mru, but haven't started the work.

**Comment by ratheesh** [comment]
> MRU(both systemwide and withing git repositoryones(if buffer in git))

Sorry for confusing words. `Systemwide` here means MRU files which include all files(default). Within `git repository ones` means that MRU files only within the repo of the current editing file. I hope this clarifies.

> is that what you want, right? 
Yes. But it will nice to support in the plugin rather than adding and external dependency. It is just a thought.

**Comment by liuchengxu** [comment]
I understand your `MRU` now, but I haven't have a clear idea to implement this atm, will definitely look into this later.

>But it will nice to support in the plugin rather than adding and external dependency. 

I have the same feeling :(. vim-clap will support this feature.

**Comment by liuchengxu** [comment]
Please have a try with #31 which will try to run from the project root(git base directory for now). Any feedback is appreciated.

**Comment by cIvanrc** [comment]
hi, this is a awesome plugin

question, there is a way to using `files` or `grep` in a specific directory??

example: `Clap files app/`

**Comment by liuchengxu** [comment]
Not now.
