### ISSUE TITLE
popup vim-clap floating window when quickfix needs openning

### ISSUE THREAD

**Issue by zanglg** [liuchengxu/vim-clap#601]
Is there any way to use vim-clap as an instead of quickfix window.
I know Clap quickfix, but it doesn't trigger automatically. 
Many plugins like nvim-lsp send results to quickfix and open automatically,  I need to close quickfix and then open Clap quickfix again.

**Comment by liuchengxu** [comment]
I actually have no idea about what your request is, can you describe some more concrete use cases? BTW vim-clap is not intended to be an alternative to quickfix window.

**Comment by zanglg** [comment]
Em... I indeed to find some way to make vim-clap to an alternative to quickfix window.
Some plugin or built-in command sends result to quickfix windows and pop up it, I want to it can be send to vim-clap.

**Comment by liuchengxu** [comment]
You can certainly do that by preparing your own data source and then feed them into vim-clap. In another word, just write your own clap provider.

**Comment by liuchengxu** [comment]
Closing as basically there is no general solution, if you want to show something using vim-clap, write a clap provider.
