### ISSUE TITLE
Vertical positioning of preview window

### ISSUE THREAD

**Issue by bapjiws** [liuchengxu/vim-clap#603]
Thanks a lot for the awesome plugin ❤️ 

Would it be possible to implement a layout option for vertical positioning of the preview window, like in [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim), for example?

<img width="1680" alt="telescope" src="https://user-images.githubusercontent.com/10408485/103226910-729a4180-492d-11eb-9a48-ca21a1e99d71.png">

**Comment by liuchengxu** [comment]
@bapjiws Please have a try with #634.
