### ISSUE TITLE
Open preview by default

### ISSUE THREAD

**Issue by Toqozz** [liuchengxu/vim-clap#606]
https://user-images.githubusercontent.com/6947819/103506891-961f3800-4ea9-11eb-9bd1-e9ce228256a8.mp4

The preview window doesn't open until I move my selection up or down in the search box.  I would like an option to have it show a preview for the top file in the list when searching.

The reason it doesn't do this already is probably because of performance(?).  Simply implementing a delay after typing before showing the preview should resolve this.

Thanks!

**Comment by liuchengxu** [comment]
Try #625, but there are still some annoying things to deal with, we often hide/close the preview window which can cause some flicker, we need to keep the preview always open and avoid hiding/closing it frequently.

**Comment by Toqozz** [comment]
Thank you, I will try this when I get a chance (moving currently).
