### ISSUE TITLE
--color=always in .ripgreprc overrides --color=never in vim-clap

### ISSUE THREAD

**Issue by paulgrow-octane** [liuchengxu/vim-clap#609]
**Environment (please complete the following information):**
 - OS: Catalina 10.15.6
 - NeoVim version: 0.4.4
 - vim-clap version: 0.1.22
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

**Clap debug**

```
            has cargo: 1
            has maple: /Users/paul.garaud/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.22, built for x86_64-apple-darwin by rustc 1.48.0 (7eac88abb 2020-11-16).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags without JSON output support
    Current sync impl: Python
     Current FileType: markdown
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/paul.garaud/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. create a `.ripgreprc` with `--color=always`

2. export `RIPGREP_CONFIG_PATH=<location of .ripgreprc>`

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vim-clap'
call plug#end()
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap grep` and enter a few arbitrary character

4. See something akin to:

![image](https://user-images.githubusercontent.com/74255970/103947422-a3ccfb80-50fd-11eb-97a7-d85152a32616.png)

**Expected behavior**
I see references to `--color=never` in some of the rust code and my expectation would be that `vim-clap` would disable/override any problematic options when invoking `rg` internally. The problem goes away if color != always in the `.ripgreprc`. Also note that passing `--color=never` on the command line overrides the `.ripgreprc` setting as intended.

**Screenshots**
See above.

**Additional context**

**Comment by liuchengxu** [comment]
Thanks for the report, should be resolved in the latest commit. BTW, it's recommended to use `:Clap grep2` since you have the Rust binary which is much more responsive than `:Clap grep`.

**Comment by paulgrow-octane** [comment]
Thanks for the suggestion!

Two quick questions:

1. does `space-vim` default to `Clap grep` when searching projects? (i think it does, which is actually how i encountered the above issue)
2. `grep2` seems to have different behavior from `grep`-- the former appears to do fuzzy match whereas the latter is exact. that may not matter in practice for my use cases (time will tell), but it seems like they're not exact substitutes.

**Comment by liuchengxu** [comment]
1. https://github.com/liuchengxu/space-vim/commit/45e6bbcf35ea5fbf86a5529680b4d43c92f48197 changed the default to `grep2` now. And you can actually always redefine the related key mapping to any other command.

2. Yeah, `grep` and `grep2` is not exactly the same, `grep` will spawn a job to run ripgrep and display the grepped result on your every input. `grep2` will firstly get the total results and then do the fuzzy match on your every input.

**Comment by paulgrow-octane** [comment]
Got it, thanks for the explanation 🙇
