### ISSUE TITLE
Clap files doesn't work

### ISSUE THREAD

**Issue by SzymonSolecki** [liuchengxu/vim-clap#61]
- OS: Arch Linux
 - NeoVim version: 0.4.2
 - Have you reproduced with a minimal vimrc: yes

When I try to use `:Clap files`it firstly displays all files, but when I start typing something it just says `provider.on_typed: clap:No external filter available `.
I checked on my laptop with older version of plugin installed and it works, but after an update it is also broken.

**Comment by liuchengxu** [comment]
See `:h g:clap_disable_optional_async`. You can set it to `v:false` to obtain the previous behavior. But I suggest you install the related external filters to make it work, current they are `fzy` or `fzf`.

**Comment by SzymonSolecki** [comment]
It fixed that. Thank you very much.

**Comment by liuchengxu** [comment]
I have also improved this behavior in #63. After it's merged, vim-clap will not try using the async way to do the filtering when none of the external filters is avaliable, then this issue will never happen again.
