### ISSUE TITLE
Transparent background becomes black in neovim with termguicolors

### ISSUE THREAD

**Issue by againxx** [liuchengxu/vim-clap#610]
**Environment (please complete the following information):**
 - OS: Ubuntu18.04
 - (Neo)Vim version: NVIM v0.5.0-dev+nightly-42-gb535575ac, and also tested in NVIM v0.4.4
 - vim-clap version: 284ef9a0b7776ab34d387fb403d500371a65cbda
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**
I'm using a transparent background in neovim, with `hi Normal ctermbg=NONE guibg=NONE`.
After the clap's floating window comes up, the background color in the main window will become black.

**Clap debug**

```
            has cargo: 1
            has maple: /home/ustc-1314/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.22, built for x86_64-unknown-linux-gnu by rustc 1.48.0.

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
    Current sync impl: Lua
     Current FileType: clap_input
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/ustc-1314/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
call plug#end()

set termguicolors
hi Normal ctermbg=NONE guibg=NONE
```

2. Start (neo)vim with command: `nvim -u min.vim`

3. Type ':Clap files'

The background color is changed to black.

**Expected behavior**
The background color of the main window keeps transparent.

**Screenshots**
Before: `:Clap files`
![vim_clap1](https://user-images.githubusercontent.com/22728604/104118687-b8133180-5365-11eb-9b87-ef5b3f63709e.png)

-----

After: `:Clap files`
![vim_clap2](https://user-images.githubusercontent.com/22728604/104118689-b9dcf500-5365-11eb-8469-ed6e9b93c47c.png)

**Additional context**
Fortunately, vim 8 works fine.
Neovim without `set termguicolors` also works fine.

**Comment by liuchengxu** [comment]
Just disable the shadow background then: `let g:clap_enable_background_shadow = v:false`.
