### ISSUE TITLE
"files" searches the whole disk

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#618]
**Environment (please complete the following information):**
 - OS: MacOS
 - Vim version: 8.2.2350
 - vim-clap version: master
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
After today's pull, `:files` now shows results from all home directory instead of the root of the project's git

**Screenshots**

![Screenshot 2021-01-19 at 16 01 20](https://user-images.githubusercontent.com/849640/105059815-973a9280-5a6f-11eb-8e2e-96e0a4273663.png)

**Comment by liuchengxu** [comment]
Works for me. I don't see how https://github.com/liuchengxu/vim-clap/pull/614/files affects this.

**Comment by arashm** [comment]
It's not today's changes. Maybe it was there for a while and I didn't notice. I tried to checkout vim-clap to some commit before, and still have the issue. Will try to figure out.

**Comment by arashm** [comment]
Added `let g:clap_disable_run_rooter = v:true` to my `vimrc` and it fixed the issue. Probably clap's rooter messes with something I have in my config.

**Comment by arashm** [comment]
Seems like I have the same issue with `grep` as well. Pretty sure I didn't have this issue yesterday.

**Comment by liuchengxu** [comment]
You should try to reproduce with a minimal vimrc then.

**Comment by arashm** [comment]
I figured something now. If I invoke `files`/`grep` on buffer/file in vim which is not yet committed into the git repo, it start the search from `~`. At the same time, if I invoke it from the buffer/file that is already committed in the repo, it searches the project itself. Here is a screencast:


https://user-images.githubusercontent.com/849640/105350046-79da0580-5be2-11eb-854a-fbfddbdcc374.mov

**Comment by liuchengxu** [comment]
Can not reproduce, works for me even for the uncommitted files.
