### ISSUE TITLE
Allow option to disable icons from being drawn

### ISSUE THREAD

**Issue by Dom-R** [liuchengxu/vim-clap#62]
**Is your feature request related to a problem? Please describe.**
Yes, the icons being used to drawn on `grep` are being displayed as a bunch of boxes. I have attached two examples of how they look to me.
I do not know why they aren't showing up, but I believe it probably has to do with either the font, os or locale.

**Describe the solution you'd like**
I think adding an option to disable drawing icons would be beneficial, as I and probably others prefer to not have icons shown.

**Describe alternatives you've considered**
The current alternative that I am using is to remove the `converter` configuration from `grep` provider.

https://github.com/liuchengxu/vim-clap/blob/1cf9c54b6cb90ffb0f9d2caa8efaeab1b68b27a0/autoload/clap/provider/grep.vim#L170

**Additional context**
![image](https://user-images.githubusercontent.com/9275937/66948811-c58b2000-f02b-11e9-8dad-bfd611a4f8f0.png)

![image](https://user-images.githubusercontent.com/9275937/66948931-008d5380-f02c-11e9-9202-9d161e39988d.png)

PS: Thank you for the amazing plugin. :heart:

**Comment by liuchengxu** [comment]
Try #63 with `let g:clap_provider_grep_enable_icon = 0` added to your vimrc.

**Comment by Dom-R** [comment]
Thank you for responding quickly.

The changes on #63 are working perfectly for me, but I could not truly test if `g:clap_provider_grep_enable_icon` works, since the default was already disabled for me.
