### ISSUE TITLE
Add mouse support

### ISSUE THREAD

**Issue by fedorenchik** [liuchengxu/vim-clap#629]
**Is your feature request related to a problem? Please describe.**
When bind clap to GUI menus, it would be faster to use mouse buttons & mouse wheel to select candidates.

**Describe the solution you'd like**
Can use mouse click to select and mouse wheel to navigate list.

**Describe alternatives you've considered**
Can use keyboard, but use mouse buttons in GUI menus would be faster.

**Comment by RyannDaGreat** [comment]
I second this! This would be really nice!

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-clap/pull/906 adds the initial mouse support, the mouse wheel can navigate the result list, and the mouse click can toggle the selection.
