### ISSUE TITLE
Setting to disable preview pane

### ISSUE THREAD

**Issue by svermeulen** [liuchengxu/vim-clap#635]
**Is your feature request related to a problem? Please describe.**
My preference would be to use the space currently being used for the preview pane to display longer file names instead.  

**Describe the solution you'd like**
I'd prefer if I could fully disable the preview part of the popup

**Describe alternatives you've considered**
None

**Comment by liuchengxu** [comment]
Use `g:clap_open_preview = 'never'` in #636 .

**Comment by svermeulen** [comment]
Wow that was fast.  Thank you!
