### ISSUE TITLE
Allow source to run in powershell

### ISSUE THREAD

**Issue by svcop3** [liuchengxu/vim-clap#640]
**Is your feature request related to a problem? Please describe.**
When I set up an exec provider with a powershell command as source, it returns nothing. I suspect this is because maple only uses two shells - cmd on windows, or bash.

**Describe the solution you'd like**
If i set my shell variable to pwsh, maple runs my exec command in pwsh. 

**Describe alternatives you've considered**
There are a couple of workarounds, like calling pwsh from .bat or even just calling execute from a vim function as the source, but these are really just working around the main issue. I haven't tried either yet.

**Comment by liuchengxu** [comment]
I don't use Windows, so can't help more here. If maple can't work with powershell, either someone opens a PR to fix it or you have to run the command in the other ways for now.

**Comment by liuchengxu** [comment]
@svcop3 Can you provide some concrete commands I can try? It'd be nice if you can also provide the steps and provider so that I can reproduce and test it easily. Recently, I can access a Windows machine and I'm happy to take a look at this issue if I get some time.
