### ISSUE TITLE
Interactive directory traversing for grep

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#642]
### Is your feature request related to a problem? Please describe

Sometimes I don't want to `grep` the whole project, but only under a certain child directory. I know `Clap grep` already supports passing the path to search in, but there are two issues with it:
- It doesn't show you the directory you're searching under
- It doesn't allow you to interactively change the directory to search under different directories

### Describe the solution you'd like

I was wondering if we could have the same interface of `filer` for `grep` (if a specific path was given to it), that you could traverse through different directories, and when something, instead of filtering based on the file name, it would filter based on content, and when you delete what you entered, it again shown the directories to traverse around.

**Comment by liuchengxu** [comment]
`filer` has been heavily rewritten in Rust in the latest version, this feature request can be started by reusing the filer implementation, any name suggestion for this new provider? I guess it would be something like `foo_grep`?
