### ISSUE TITLE
Clap files: file selection incorrect after modifying pattern

### ISSUE THREAD

**Issue by circld** [liuchengxu/vim-clap#646]
**Environment (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - (Neo)Vim version: 0.4.4
 - vim-clap version: 0.23 (`8b618fc`)
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
After selecting multiple files to open using `<tab>` and updating the search pattern, the files selected change. Put differently, the selections appear to be index-based and when the list updates in response to a change in search pattern, the same indices are selected even though the filenames in those indices are now different.

**Clap debug**

```
            has cargo: 1
            has maple: /<user_path>/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.23, built for x86_64-apple-darwin by rustc 1.50.0 (cb75ad5db 2021-02-10).
         has +python3: 1
has py dynamic module: 1
            has ctags:
vim-clap: Ensure ctags executable is in your PATH and has the JSON output featurectags without JSON output support
    Current sync impl: Python
     Current FileType:
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/<user_path>/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vim-clap'
call plug#end()
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Create a directory with the following structure:

```
base/
├─ sub1/
│  ├─ file1
|  ├─ ...
│  ├─ file100
├─ sub2/
│  ├─ file3
```

4. Navigate to `base/`
5. Enter `:Clap files`
5. Select the first 5 entries
6. Type `sub2`
7.  Note that the selections have updated to different files. Hitting `<Enter>` now will open the visible files, not the original selection.

**Expected behavior**

One of either:

1. When a file is selected and the search pattern is changed, the selected file is persisted. This behavior would make `Clap files` much more powerful as it would allow the user to quickly add files adhering to different patterns to the quickfix list for easy navigation.
2. If this behavior is not the desired behavior, then all selections should be cleared upon pattern change. I struggle to think of a use case where updating the selected files in place based on the pattern is desirable.

**Screenshots**

Selecting first 5:
![image](https://user-images.githubusercontent.com/5423134/109438233-a9084180-79ee-11eb-9197-961f7efc3331.png)

Updating pattern:
![image](https://user-images.githubusercontent.com/5423134/109438239-b6253080-79ee-11eb-8ae3-730c38e259f3.png)

Hitting `enter`:
![image](https://user-images.githubusercontent.com/5423134/109438249-c0472f00-79ee-11eb-90f0-8a59ee1e3421.png)

**Comment by liuchengxu** [comment]
What I can do is clearing the old selections when the input updates, you have to reselect these items.

**Comment by circld** [comment]
That would be better and more intuitive behavior for sure.

The ability to retain selected entries across different patterns within a single Clap search session would be _amazing_ though. I imagine the current implementation is largely "stateless", and therefore persisting selections and displaying them would require some nontrivial changes to the existing implementation. Happy to make a separate feature request for this though.

**Comment by liuchengxu** [comment]
The current selections can be retained when the input updates, but they can't be displayed in the window anymore.
