### ISSUE TITLE
grep provider preview breaks on input

### ISSUE THREAD

**Issue by goolord** [liuchengxu/vim-clap#648]
**Environment (please complete the following information):**
 - OS: Arch linux 5.11.1-arch1-1
 - (Neo)Vim version: NVIM v0.5.0-dev+1115-gc1fbc2ddf
 - vim-clap version: 8b618fcbbee7cf30ce9d05be00706ddb558f96af
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
scrolling through `:Clap grep` with no input changes the preview window accordingly
once you input text the preview window is frozen

**Clap debug**

```

            has cargo: 1
            has maple: /home/zach/.local/share/nvim/site/pack/packer/start/vim-clap/target/release/maple
           maple info: version 0.1.23, built for x86_64-unknown-linux-gnu by rustc 1.51.0-nightly (44e3daf5e 2020-12-31).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
    Current sync impl: Lua
     Current FileType: clap_input
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/zach/.local/share/nvim/site/pack/packer/start/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': ''}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:true
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_frames = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘']
  Provider Variables:
                     []
```

**Screenshots**
![image](https://user-images.githubusercontent.com/24906808/109556063-512c1200-7aa4-11eb-949a-875e4318e76c.png)

**Comment by goolord** [comment]
i can reproduce this behavior on 2 machines (though they are mostly similarly configured).
hmm, the preview window seems to be broken for me with several providers.. i'll do more digging. the issue might be local to me

**Comment by goolord** [comment]
hmm after messing with my settings, i can't reproduce this bug anymore, even with an identical configuration. closing, i'll reopen with more details if i can reproduce this again. sorry for the trouble

**Comment by goolord** [comment]
ah, setting     `vim.g.clap_enable_icon = 1` breaks it

**Comment by liuchengxu** [comment]
I always enable the icon, no issues, please provide a minimal vimrc to reproduce.

**Comment by goolord** [comment]
this combination
``` lua
vim.g.clap_enable_icon = 1
vim.g.clap_provider_grep_enable_icon = 1
```
produces the expected behavior but this 
``` lua
vim.g.clap_enable_icon = 1
vim.g.clap_provider_grep_enable_icon = 0
```
does not.

i will provide detailed steps to reproduce tomorrow

**Comment by liuchengxu** [comment]
Now I can reproduce this issue, please try #649.
