### ISSUE TITLE
Can vim-clap be lenient with input order of words like fzf does?

### ISSUE THREAD

**Issue by Congee** [liuchengxu/vim-clap#651]
For example, in the screenshot below from fzf, it is possible to type "api" after "docs". Vim-clap requires me to type "docs" and "api", in that order, at least with default settings.

![image](https://user-images.githubusercontent.com/2083950/110139564-2a6e2400-7da1-11eb-8fe3-84acef757ae9.png)
So, is this feature supported?

**Comment by liuchengxu** [comment]
Try #652, you have to compile the Rust binary locally.

**Comment by Congee** [comment]
Woah, that's pretty a quick PR. I checked out #652, unfortunately it does not work yet.

**Comment by liuchengxu** [comment]
@Congee Forget to mention that you need to compile the Python dynamic module too and force using that as the pure Python substring matcher does not support this.

```vim
let g:clap_force_python = v:true
```

If it still doesn't work for you, please post the minimal vimrc and steps to reproduce.

**Comment by Congee** [comment]
Hi, I built against the latest commit with the following minimum nvimrc, and it still is not working for me.
```viml
call plug#begin(stdpath('data') . '/plugged')
Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary' }
call plug#end()

let g:clap_force_python = v:true

" vim: ts=2 sw=2
```

I'm using:
nvim 0.4.3
vim-clap @ 6ca4c58cd1d3e53486d62ad692375672412a19b3 built by `cargo build --release`

Am I missing anything :thinking: ?

**Comment by liuchengxu** [comment]
Can not reproduce with this vimrc, works well for me. `cargo build --release` does not build the Python dynamic module, just running `make` is fine.

**Comment by Congee** [comment]
`make` was what's missing. It works. Thank you!
