### ISSUE TITLE
Implement regex-based jump-to-definition backend in Rust

### ISSUE THREAD

**Issue by liuchengxu** [liuchengxu/vim-clap#656]
LSP is great but it doesn't always work well if the server could be slow to respond when we are working with big projects. A regex-based solution like https://github.com/jacktasia/dumb-jump can be a good complement to LSP, which should be always fast and good enough for most of our use cases. We can implement the searching work on the Rust end, which is easier to test and maintain in the long term.

**Comment by liuchengxu** [comment]
Treesitter is great, but someone needs to first implement the vim support layer like neovim dev team already has done, I'm not a fan of neovim-only features.

**Comment by ray-x** [comment]
Yes, bummer. forget it neovim nightly only...
