### ISSUE TITLE
Support alternative key-binding for navigation

### ISSUE THREAD

**Issue by demon386** [liuchengxu/vim-clap#66]
Personally I'd prefer Ctrl-p/n instead of Ctrl-k/j. It would be great if I can adjust the default key bindings. Thanks!

**Comment by liuchengxu** [comment]
If you are using neovim, it's not hard by adding these two lines in your vimrc:

```vim
autocmd FileType clap_input inoremap <silent> <C-n> <C-R>=clap#handler#navigate_result('down')<CR>
autocmd FileType clap_input inoremap <silent> <C-p> <C-R>=clap#handler#navigate_result('up')<CR>
```

For vim, it's unable to do such a thing atm.

**Comment by demon386** [comment]
Thanks. I use neovim and that solved my problem.

**Comment by jet8a** [comment]
E117: Unknown function: clap#handler#navigate_result

<img width="658" alt="image" src="https://user-images.githubusercontent.com/14956407/83939089-5b053b00-a7da-11ea-8c21-577b1039d768.png">

**Comment by liuchengxu** [comment]
@jet8a Ok, that comment is outdated, you should take a look how `ftplugin/clap_input.vim` does, https://github.com/liuchengxu/vim-clap/blob/master/ftplugin/clap_input.vim.

```vim
autocmd FileType clap_input inoremap <silent> <buffer> <C-n> <C-R>=clap#navigation#linewise('down')<CR>
autocmd FileType clap_input inoremap <silent> <buffer> <C-p> <C-R>=clap#navigation#linewise('up')<CR>
```
