### ISSUE TITLE
Missing results from rg

### ISSUE THREAD

**Issue by zoumi** [liuchengxu/vim-clap#673]
If a source code line contains a unicode chars in comment, rg will return something like this:
```
{"type":"begin","data":{"path":{"text":".\\APP\\app_code\\SC.h"}}}
{"type":"match","data":{"path":{"text":".\\APP\\app_code\\SC.h"},"lines":{                                             "bytes":"xxxxxx"},"line_number":24,"absolute_offset":486,"submatches":[{"match                                             ":{"text":"xxxxxx"},"start":9,"end":23}]}}
{"type":"match","data":{"path":{"text":".\\APP\\app_code\\SC.h"},"lines":{                                             "bytes":"xxxxx"},"line_number":45,"absolute_offset":1751,"submatches":[{"                                             match":{"text":"xxx"},"start":9,"end":23}]}}
```
and clap will ignore this item.

**Comment by zoumi** [comment]
LeaderF use a different data format for rg, it can show the item as usual.

```
cmd.exe /c (rg   --no-config --no-ignore-messages --no-heading --with-filename --color never --line-number -S --context-separator=... -e GAP_S)
app_code\SC.h:24:#define GAP_S                  5      // 5s����ȡOCV 2
app_code\SC.h:45:#define GAP_S               10      // 5s����ȡOCV 2
```

**Comment by liuchengxu** [comment]
Can you provide the source file and detailed steps to help reproduce it?

**Comment by zoumi** [comment]
1,create a file test.txt with this content:
```
test_ddd
test_ddd    //こんにちは、世界
test_ddd    //hello
```
save the file with EUC-JP encoding.

2,cd to the diretory of test.txt

3,move curson to "test_add"

4,Clap! grep ++query=<cword> +no-cache

You will get only two results.

**Comment by liuchengxu** [comment]
Can not reproduce, works for me with `set fileencoding=euc-jp`.

**Comment by zoumi** [comment]
@liuchengxu Did you save the file after change the file encoding?
I'm using :set fenc=EUC-JP
Reproduce with minimal vimrc:
![image](https://user-images.githubusercontent.com/5162901/115666765-8ef83900-a377-11eb-8805-935f698e04e7.png)

**Comment by liuchengxu** [comment]
Ok, reproduced after setting the file encoding and saving the file `:w`. It's an issue of the Rust binary that only takes cares utf-8 now https://github.com/liuchengxu/vim-clap/blob/81f3444650cb0a07be75cdbbc2efc63447fe9b90/crates/maple_cli/src/tools/rg.rs#L75-L78.

For now, you can directly use the ripgrep CLI by disabling the Rust binary:

```diff
diff --git a/autoload/clap/provider/grep.vim b/autoload/clap/provider/grep.vim
index 07e4934..98f9096 100644
--- a/autoload/clap/provider/grep.vim
+++ b/autoload/clap/provider/grep.vim
@@ -136,7 +136,8 @@ function! s:spawn(query) abort

   call clap#rooter#try_set_cwd()

-  if clap#maple#is_available()
+  if 0
     let [grep_opts, query] = s:translate_query_and_opts(a:query)
     " Add ' .' for windows in maple
     call clap#maple#command#start_grep_sync(s:grep_executable.' '.grep_opts, query, s:grep_enable_icon, s:ripgrep_glob)
```

**Comment by liuchengxu** [comment]
@zoumi Try #675, should fix this issue.

**Comment by zoumi** [comment]
@liuchengxu I had tested the "multibyte" branch. I can get all results now. Thank you!
