### ISSUE TITLE
Clap keymap search does not show full list of current keymaps

### ISSUE THREAD

**Issue by ray-x** [liuchengxu/vim-clap#677]
**Is your feature request related to a problem? Please describe.**
It seems keymap missing some keymap. Here is result from clap and telescope

<img width="793" alt="Screen Shot 2021-05-04 at 6 44 17 am" src="https://user-images.githubusercontent.com/1681295/116931566-7c99cb80-aca4-11eb-83a5-636e4c17b083.png">

<img width="937" alt="Screen Shot 2021-05-04 at 6 44 41 am" src="https://user-images.githubusercontent.com/1681295/116931576-7f94bc00-aca4-11eb-9ee7-a9253b56151b.png">

**Describe the solution you'd like**
would be great to return full list

**Comment by romgrk** [comment]
Would you be able to provide the outputs for `execute('verbose nmap')`, `g:clap#provider#maps#.source()` and `nvim_get_keymap('n')` (in a gist/pastebin)?

**Comment by ray-x** [comment]
Gist:
https://gist.github.com/ray-x/242fabf0d9ff011e2ef5e21d9b7eda7d

**Comment by liuchengxu** [comment]
Can you also provide a minimal vimrc to help reproduction as the input sample works well for me locally?

**Comment by ray-x** [comment]
I think this issue is related to how you register your keymap. 
If I am using vim.api.nvim_buf_set_keymap(0, "n", "<space>ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", {}) to bind the keymap to current buffer, it will not show in Clap.
Sample vimrc

```vim
call plug#begin('~/.vim/plugged')
set noswapfile
Plug 'liuchengxu/vim-clap', { 'do': { -> clap#installer#force_download() } }
Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()

lua <<EOF
local nvim_lsp = require('lspconfig')
vim.api.nvim_buf_set_keymap(0, "n", "<space>ff", "<cmd>lua vim.lsp.buf.formatting()<CR>", {})
EOF

```

In the sample, I map <space>ff to a lua function in current buffer. But Clap will not show this mapping in Clap maps.

Telescope will.

**Comment by liuchengxu** [comment]
```diff
diff --git a/autoload/clap/provider/maps.vim b/autoload/clap/provider/maps.vim
index e46dafb..b2e3b97 100644
--- a/autoload/clap/provider/maps.vim
+++ b/autoload/clap/provider/maps.vim
@@ -31,7 +31,7 @@ function! s:maps_source() abort
   let s:map_reg = empty(v:register) ? '' : ('"'.v:register)
   let s:map_op  = mode ==# 'o' ? v:operator : ''
 
-  let cout = execute('verbose '.mode.'map')
+  let cout = clap#api#win_execute(g:clap.start.winid, 'verbose '.mode.'map')
   let list = []
   let curr = ''
   for line in split(cout, "\n")
```

This patch works for me, can you confirm that? @ray-x

**Comment by ray-x** [comment]
Yes. Looks like the issue was fixed with your change. 😀 
Will wait for the merge!

**Comment by liuchengxu** [comment]
The patch has been merged into master now.

**Comment by ray-x** [comment]
Hi, @liuchengxu 
Seems this break again.
If I run
`echo clap#api#win_execute(g:clap.start.winid, 'verbose nmap')`
It will show
```               
...                                                                                                                          
n  gr          *@<Cmd>lua vim.lsp.buf.references()<CR>    
...
```

But if I run `Clap maps` 
The above  maps did not  show in the  clap  list.

**Comment by liuchengxu** [comment]
@ray-x Can not reproduce it locally.
