### ISSUE TITLE
grep provider cannot open paths and filenames with spaces

### ISSUE THREAD

**Issue by bartlibert** [liuchengxu/vim-clap#686]
**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: vim 2.8.2871
 - vim-clap version: 75bf813
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
When using the grep provider, if the search result is in a file that is in path containing spaces, the resulting file is not opened when pressing enter.

**Clap debug**

```

            has cargo: 0
            has maple: C:/Users/BL/_yadm/.vim/pack/minpac/start/vim-clap/bin/maple.exe
           maple info: version 0.1.25 (git v0.25), built for x86_64-pc-windows-msvc by rustc 1.51.0 (2fd73fabe 2021-03-23).

         has +python3: 1
has py dynamic module: 0
            has ctags: ctags with JSON output support
    Current sync impl: Lua
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:/Users/BL/_yadm/.vim/pack/minpac/start/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('70'), 'open': function('<SNR>213_create_display'), 'width': 32, 'shrink_if_undersize': function('69')}
    let g:clap#popup#preview = {'line_count': function('<SNR>212__line_count'), 'show': function('71'), 'hide': function('72'), 'clear': function('73'), 'add_highlight': function('74'), 'get_lines': function('<SNR>212__get_lines'), 'getbufvar': function('<SNR>212__getbufvar'), 'setbufvar_batch': function('<SNR>212__setbufvar_batch'), 'setbufvar': function('<SNR>212__setbufvar'), 'winid': 1002, 'win_is_valid': function('<SNR>212__win_is_valid'), 'goto_win': function('<SNR>212__goto_win'), 'set_syntax': function('75'), 'bufnr': 3}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_indicator_winid = 1003
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1005
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Create a test file in a directory containing a space, e.g.:
```
mkdir "test path"
echo "findme" > "test path\test"
```

3. Start (neo)vim with command: `vim -u min.vim`

4. Type 'Clap grep' and then 'findme'

5. Observe that the result is correctly found and the path is correct in the popup
6.  Press 'Enter'
7. Observe that vim tries to open the path `path\test` instead of `test path\test`

**Expected behavior**
The correct file is opened, even if the path or filename contains spaces

**Screenshots**
Result is found and path is correct:
![image](https://user-images.githubusercontent.com/948770/119102086-2dc09580-ba09-11eb-8351-093dc602375e.png)

Wrong path is opened
![image](https://user-images.githubusercontent.com/948770/119102153-3d3fde80-ba09-11eb-8f1b-ec496a3fa70c.png)

**Additional context**
Clap files opens the file in question correctly

**Comment by liuchengxu** [comment]
Should be fixed in the master. BTW it's recommended to use `grep2` now as it's much faster.

**Comment by bartlibert** [comment]
Thanks for the quick fix. I plan to move to grep2, but I have sporadic issues there that I haven't been able to pinpoint completely, so until I can make a good bug report, I'll stick with grep for now.

**Comment by liuchengxu** [comment]
Fair enough. As a matter of fact, I personally use more of `dumb_jump` now, it's slightly more accurate than the grep tools.
