### ISSUE TITLE
Error when invoking action dialog on a buffer

### ISSUE THREAD

**Issue by osenvosem** [liuchengxu/vim-clap#688]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: MacOS 11.4 (20F71)
 - (Neo)Vim version:  NVIM v0.5.0-dev+192f89ea1
 - vim-clap version: 0.25
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
Got the error

```
Error detected while processing function clap#action#invoke[6]..clap#floating_win#action#create:
line   40:
E5555: API call: 'win' key is only valid with relative='win'
```

**Clap debug**

```

            has cargo: 1
            has maple: /Users/srg/.config/nvim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.25, built for x86_64-apple-darwin by rustc 1.52.1 (9bc8c42bb 2021-05-09).

         has +python3: 1
has py dynamic module: 1
            has ctags: 
vim-clap: Ensure ctags executable is in your PATH and has the JSON output featurectags without JSON output support
    Current sync impl: Lua
     Current FileType: javascript
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/srg/.config/nvim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap buffers' -> choose a buffer -> Normal Mode -> Shift + Tab

**Expected behavior**
Expect to see actions after pressing Shift + Tab instead of the error.

**Screenshots**

<img width="1082" alt="Screenshot 2021-05-27 at 19 17 57" src="https://user-images.githubusercontent.com/6762673/119861612-40166400-bf20-11eb-8c57-5aa243775f00.png">

**Additional context**

**Comment by liuchengxu** [comment]
Please fill in the issue template, otherwise, we can't help more.

**Comment by osenvosem** [comment]
@liuchengxu sorry for that, filled it up.

**Comment by liuchengxu** [comment]
Thanks for the update, should be resolved in the latest master.

**Comment by osenvosem** [comment]
@liuchengxu I updated the pulugin and now can invoke action window. But when I tried to delete currently visible buffer and it failed
<img width="1082" alt="Screenshot 2021-05-28 at 13 10 05" src="https://user-images.githubusercontent.com/6762673/119968662-64248480-bfb6-11eb-9196-f5ed432f2025.png">

**Comment by liuchengxu** [comment]
@osenvosem Thanks for the report. Can you please create a new issue with reproduction steps for that?
