### ISSUE TITLE
Two useful features

### ISSUE THREAD

**Issue by QiBaobin** [liuchengxu/vim-clap#690]
Found two interesting features in [LeaderF](https://github.com/Yggdroot/LeaderF), I think it would be very useful to our daily job.  Any chance we could implement them? Don't have to be input binding, something like provider args/opts would be good enough!

```
<C-R> | switch between fuzzy search mode and regex mode
<C-F> | switch between full path search mode and name only search mode
```

BTW: Good work and Thanks for the excellent job!

**Comment by liuchengxu** [comment]
> <C-R> | switch between fuzzy search mode and regex mode

This is blocked by #492. Now we only have the fuzzy and substring search modes.

> <C-F> | switch between full path search mode and name only search mode

It's done already. You can use `:Clap files +name-only` to search by the file name only. However, it's in fact unneccessary since #561 is resolved, we already add a bonus score for the matches in the file name.
