### ISSUE TITLE
Preview not work for quickfix

### ISSUE THREAD

**Issue by QiBaobin** [liuchengxu/vim-clap#691]
**Environment (please complete the following information):**
 - OS: Mac osx
 - (Neo)Vim version: 0.5
 - vim-clap version: 
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
Can't see any content in the preview panel

**Clap debug**

```
            has cargo: 1
            has maple: /Users/a483334/.local/share/nvim/site/pack/packer/start/vim-clap/target/release/maple
           maple info: version 0.1.25, built for x86_64-apple-darwin by rustc 1.52.1 (9bc8c42bb 2021-05-09).

         has +python3: 1
         has py dynamic module: 1
            has ctags: ctags with JSON output support
    Current sync impl: Lua
     Current FileType: lua
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '~/.local/share/nvim/site/pack/packer/start/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_provider_grep_enable_icon = 0

```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap grep2`, select some items, enter, then run `:Clap quickfix`

4. No preview content loaded, even navigate through items.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by QiBaobin** [comment]
Another finding is that it makes no sense to have preview panel for most builtin providers, like registers, command, etc.
Could we hide it automatically for them?

**Comment by liuchengxu** [comment]
You can try implementing the `on_move` hook for the quickfix provider.

Use `let g:clap_preview_direction =  'UD'` if you prefer not to always enable the preview window. For the `LR` direction, I think it's distracting to close and open the preview window frequently, but I can accept PR if you introduce an option for disabling the preview for specific providers.

**Comment by QiBaobin** [comment]
> Use `let g:clap_preview_direction = 'UD'` if you prefer not to always enable the preview window.

Thanks, good to know!

**Comment by liuchengxu** [comment]
@QiBaobin You can try #697 for the quickfix preview. In addition, since the file preview is a pretty common need, I'm going to make it generalized for easier integration of third-party providers.

**Comment by QiBaobin** [comment]
It seems that it doesn't work on my side, and I got below error when using.
```
vim-clap: clap#handler#sink: Vim(let):E684: list index out of range: 1, throwpoint:function clap#handler#cr_action[5]..clap#handler#sink[12]..42[1]..clap#rooter#run_heuristic[17]..<SNR>108_grep_sink_star[3]..<SNR>108_into_qf_item, line 2
```
```
Error detected while processing function <lambda>2[1]..clap#impl#on_move#invoke_async[5]..84[1]..clap#client#call[1]..clap#client#notify[2]..clap#job#daemon#send_message:
line    1:
-- INSERT --d channel id
```

**Comment by liuchengxu** [comment]
Have you recompiled the Rust binary using that branch?

**Comment by QiBaobin** [comment]
@liuchengxu , good catch, I forgot that!  It works now, thanks a lot for the implementation!
