### ISSUE TITLE
error Clap install-binary

### ISSUE THREAD

**Issue by guolimin1995** [liuchengxu/vim-clap#699]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: 10.15.4
 - (Neo)Vim version: 0.4.4
 - vim-clap version: latest
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes 

**Describe the bug**

**Clap debug**

```
cargo build --release
   Compiling maple_cli v0.1.0 (/Users/zerone/.config/nvim/plugged/vim-clap/crates/maple_cli)
error[E0277]: the trait bound `std::ops::Range<usize>: std::default::Default` is not satisfied
  --> crates/maple_cli/src/tools/ripgrep/mod.rs:54:21
   |
54 |             None => Default::default(),
   |                     ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `std::ops::Range<usize>`
   |
   = note: required by `std::default::Default::default`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `maple_cli`.

To learn more, run the command again with --verbose.
make: *** [maple] Error 101

[Process exited 2]



```

**Comment by liuchengxu** [comment]
This doesn't make sense to me since it implements `Default` already https://doc.rust-lang.org/std/ops/struct.Range.html#impl-Default. Have you tried running `cargo clean` under the vim-clap direcotry? And what does `rustup show` say?

**Comment by guolimin1995** [comment]
> This doesn't make sense to me since it implements `Default` already https://doc.rust-lang.org/std/ops/struct.Range.html#impl-Default. Have you tried running `cargo clean` under the vim-clap direcotry? And what does `rustup show` say?

run cargo clean, then clap install-binary still not working.  `rustup show` it mean this?
```
Default host: x86_64-apple-darwin
rustup home:  /Users/zerone/.rustup

installed toolchains
--------------------

stable-x86_64-apple-darwin
nightly-x86_64-apple-darwin (default)

active toolchain
----------------

nightly-x86_64-apple-darwin (default)
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
```

**Comment by liuchengxu** [comment]
Try running `rustup update` then, your rust version is possibly too old.

**Comment by guolimin1995** [comment]
> Try running `rustup update` and then recompile the binary, your rust version is possibly too old.

its working. sorry I don't know anything about rust. 
thanks for you help.

**Comment by liuchengxu** [comment]
Happy to see it's resolved :P. CI always checks if the binary can compile against the latest stable, so the old compiler does have a chance to fail.
