### ISSUE TITLE
Easymotion conflict

### ISSUE THREAD

**Issue by blayz3r** [liuchengxu/vim-clap#7]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Windows
 - (Neo)Vim version: ???
![image](https://user-images.githubusercontent.com/12205650/65922764-7353c900-e3b4-11e9-85d8-bc2d253f7d81.png)
 - vim-clap version: ???
 
**Describe the bug**
![image](https://user-images.githubusercontent.com/12205650/65922884-e2312200-e3b4-11e9-8c04-b8ded78a9167.png)

**To Reproduce**
Install easymotion, run Clap colors, press C-j

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```
Plug 'easymotion/vim-easymotion'

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/12205650/65922634-f163a000-e3b3-11e9-9ebd-b90d0789800b.png)

**Additional context**

**Comment by liuchengxu** [comment]
Can't reproduce with this minimal vimrc. 

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/vim-clap
set runtimepath^=~/.vim/plugged/vim-easymotion
syntax on
filetype plugin indent on
```

**Comment by blayz3r** [comment]
Sorry should be: 
" Sections:
"Vim-Plug Plugin Manager  {{{
" set the run path
call plug#begin('~/.vim/bundle') "plugins' root path
"Starting screen

Plug 'liuchengxu/vim-clap'
Plug 'easymotion/vim-easymotion'
Plug 'haya14busa/vim-easyoperator-line'
" All of your Plugs must be added before the following line
call plug#end()            " required
"}}}

**Comment by liuchengxu** [comment]
I believe you should report to vim-easyoperator-line.

**Comment by liuchengxu** [comment]
I occasionally found that this issue can be resolved on vim-clap side when developing https://github.com/liuchengxu/vim-clap/pull/43. You could try #43 to see if it persists.

**Comment by blayz3r** [comment]
Yes, works now
