### ISSUE TITLE
Question: How do I process arguments in a custom provider

### ISSUE THREAD

**Issue by bloop132435** [liuchengxu/vim-clap#704]
I wanted to make a custom provider for cht.sh, but I couldn't find a way in the documentation to process arguments. How can I allow my custom providers to take in arguments like the built-in ones, like `Clap files ++finder=...` ?

**Comment by romgrk** [comment]
You can use `g:clap.context.xxxx` where `xxxx` is the name of the option in `Clap my_provider ++xxxx=42`. You can check the [providers](https://github.com/liuchengxu/vim-clap/tree/master/autoload/clap/provider) when you want to copy the functionality of an existing provider.

**Comment by bloop132435** [comment]
Thanks a lot for the help!
