### ISSUE TITLE
Load search results of grep into quickfix list.

### ISSUE THREAD

**Issue by zoumi** [liuchengxu/vim-clap#705]
**Is your feature request related to a problem? Please describe.**
Not.

**Describe the solution you'd like**
Provide a key map to load search results of grep into quickfix list.

**Describe alternatives you've considered**
No.

**Comment by liuchengxu** [comment]
It's the default behavior of `sink`.

**Comment by wongjiahau** [comment]
@liuchengxu so how do we send the results of grep into quickfix list? Sorry when I search `vim sink*` I got the following lol:

![image](https://user-images.githubusercontent.com/23183656/123548742-acdb8300-d798-11eb-8e63-5fc752afe3f2.png)

**Comment by liuchengxu** [comment]
Select the items using tab and then press enter, the selected results will be present in the quickfix window.

**Comment by wongjiahau** [comment]
@liuchengxu Thanks that works. Is there also a shortcut to select all items instead of tabbing one by one?

**Comment by liuchengxu** [comment]
Not now.

**Comment by wongjiahau** [comment]
> Select the items using tab and then press enter, the selected results will be present in the quickfix window.

Is this instruction present in any pages?

**Comment by liuchengxu** [comment]
I thought it's a fairly common workflow of a typical fuzzy finder vim plugin and no need to mention that, but it's not harmful to add some instructions anyway, feel free to add them in https://github.com/liuchengxu/vim-clap/wiki/Tips.

**Comment by wongjiahau** [comment]
@liuchengxu  I can't find the Edit button in the Wiki, I think you might need to open access to allow public users to edit the Wiki,

**Comment by liuchengxu** [comment]
Hi @wongjiahau, it should be editable now.

**Comment by wongjiahau** [comment]
@liuchengxu Done. See if you want to add on more details.

**Comment by zoumi** [comment]
It's nice to use this with https://github.com/stefandtw/quickfix-reflector.vim.
We can do a global replace within vim easily!

**Comment by zoumi** [comment]
Is there a easy way to add all items into quickfix list?

**Comment by liuchengxu** [comment]
You can create a feature request issue for adding a shortcut to select all the items.
