### ISSUE TITLE
add icon for latex file 

### ISSUE THREAD

**Issue by krisfans** [liuchengxu/vim-clap#709]
**Describe the solution you'd like**
There is no icon for latex(.tex).How can I  add an icon to a file type via the vim-clap plugin? 
Or are you considering using [vim-devicons](https://github.com/ryanoasis/vim-devicons) instead of native methods for icon support?

**Additional context**
![Snipaste_2021-06-13_18-37-25](https://user-images.githubusercontent.com/57793534/121804009-b6cc9480-cc76-11eb-9331-63542a4f6377.png)

**Comment by liuchengxu** [comment]
You can extend the icon file https://github.com/liuchengxu/vim-clap/blob/master/crates/icon/extension_map.json and then recompile the binary.

**Comment by liuchengxu** [comment]
Run `cargo clean && cargo build --release` if you compile the Rust binary locally.
