### ISSUE TITLE
"Clap install" assumes a specific location for bash

### ISSUE THREAD

**Issue by spamwax** [liuchengxu/vim-clap#732]
While `bash` generally is found in `/usr/bin/bash`, on FreeBSD it is installed in `/usr/local/bin/bash`
This causes the installation of binaries to fail on FreeBSD.

Additionally, trying to make the python modules causes similar problem on FreeBSD as there are two `make` commands available: `make` and `gmake` (GNU)

If you point me in right direction, I may be able to put together a PR for these.

**Comment by romgrk** [comment]
See https://github.com/liuchengxu/vim-clap/blob/master/autoload/clap/installer.vim

**Comment by liuchengxu** [comment]
vim-clap does not invoke the `bash` command inside vim but executing the script directly:

https://github.com/liuchengxu/vim-clap/blob/fc0022f69509c84f7d5901051f569cec682fc456/autoload/clap/installer.vim#L105

and

https://github.com/liuchengxu/vim-clap/blob/fc0022f69509c84f7d5901051f569cec682fc456/autoload/clap/installer.vim#L90 

So perhaps you can check if https://github.com/liuchengxu/vim-clap/blob/master/install.sh and https://github.com/liuchengxu/vim-clap/blob/master/Makefile have some room for improvement.
