### ISSUE TITLE
CC file preview not highlighted

### ISSUE THREAD

**Issue by aprowe** [liuchengxu/vim-clap#736]
My project uses .cc extension for it's c++ files. 
In `:Clap files`, the preview does not receive any syntax highlighting.

**Comment by liuchengxu** [comment]
Could you please fill out the issue template? It's can be pretty helpful if you can provide the reproduction steps.

**Comment by krisfans** [comment]
# minimal.vim
```vim
set encoding=utf-8
"dein Scripts-----------------------------
if &compatible
    set nocompatible               " Be iMproved
endif
set runtimepath+=~/.cache/nvim/dein/repos/github.com/Shougo/dein.vim
let s:dein_path = $HOME . '/.cache/nvim/dein'
let g:dein#auto_recache = 1
call dein#begin(s:dein_path)
call dein#add(s:dein_path)
call dein#add('liuchengxu/vim-clap')

call dein#end()
call dein#call_hook('source')
call dein#call_hook('post_source')
" Required:
filetype plugin indent on
syntax enable
set background=dark

let g:clap_cache_directory = $DATA_PATH . '/clap'
let g:clap_current_selection_sign= { 'text': '➤', 'texthl': "ClapCurrentSelectionSign", "linehl": "ClapCurrentSelection"}
" hi default link ClapPreview Pmenu
```
# step
1. `nvim -u minimal.vim` 
2. `:Clap files`

# screenshots
![Snipaste_2021-09-26_09-18-00](https://user-images.githubusercontent.com/57793534/134789927-d735fc6e-20f9-42be-b49c-d8764f94d5a1.png)
![Snipaste_2021-09-26_09-17-45](https://user-images.githubusercontent.com/57793534/134789931-f47b0970-240b-4024-801c-e310074fe252.png)
![Snipaste_2021-09-26_09-17-28](https://user-images.githubusercontent.com/57793534/134789933-7ffb132b-6a86-490f-9781-b1b79716ed93.png)
