### ISSUE TITLE
Add results of different searches to Quickfix

### ISSUE THREAD

**Issue by aprowe** [liuchengxu/vim-clap#737]
Sometimes I want to open up several files, but their names are not similar. With FZF, i can search for file1, hit tab, search for file2, hit tab, search for file3 hit tab, then open them in my quick fix. vim-clap appears to clear your tab selections once you change the query.

Feature:
When entries are selected with tab, it would be great to not clear them when the input query changes.

Alternative: 
If you could add a single item to the quickfix instead of replacing the whole list, that works too

**Comment by liuchengxu** [comment]
This has been implemented in #917 finally, feel free to have a try and leave some feedback if it's still helpful :P
