### ISSUE TITLE
g:clap_layout doesn't work on the preview window

### ISSUE THREAD

**Issue by LinHQ1999** [liuchengxu/vim-clap#744]
**Environment (please complete the following information):**
 - OS: Windows10 Professional 21H1
 - (Neo)Vim version: 0.5
 - vim-clap version: master
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
I want to change the overall width but the preview is obscured.

**Clap debug**

```
            has cargo: 1
            has maple: C:\Users\lin11\vimfiles\plugged\vim-clap/target/release/maple.exe
           maple info: version 0.1.28, built for x86_64-pc-windows-msvc by rustc 1.50.0 (cb75ad5db 2021-02-10).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags not found
        rustc version: rustc 1.50.0 (cb75ad5db 2021-02-10)

    Current sync impl: Lua
     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\lin11\vimfiles\plugged\vim-clap\autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '', 'running': '', 'using_cache': ''}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '10%', 'row': '15%', 'width': '50%', 'height': '50%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'double'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_prompt_format = ' %spinner% %provider_id% %forerunner_status% > '
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'triangle'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'triangle': ['', ''], 'arrow': ['', '']}
  Provider Variables:
    let g:clap_provider_grep_opts = '-H --no-heading --vimgrep --smart-case --hidden -g "!.git/"'
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
call plug#begin('~\vimfiles\plugged')
    Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary!' }
call plug#end()

let g:clap_layout = { 'relative': 'editor' }
let g:clap_layout = {'width': '50%', 'col':'10%', 'height': '50%', 'row': '15%' }
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap history'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/50328516/130728728-73dd36c4-2bf1-4cbd-bb67-408cd6b35136.png)

**Additional context**

**Comment by liuchengxu** [comment]
I don't see the problem. Please provide more info and the expectation in your mind.

**Comment by LinHQ1999** [comment]
The default settings look like this:
![image](https://user-images.githubusercontent.com/50328516/130736599-c17f2d11-91e2-4eef-b68f-fc646f14208e.png)
I want  the whole float window to be wider, then I increased the width `let g:clap_layout = {'width': '70%', 'col':'15%', 'height': '50%', 'row': '15%' }
` and it looked like this:
![image](https://user-images.githubusercontent.com/50328516/130736761-050d9c36-4a27-4e23-9833-d5e1c61df387.png)

**Comment by liuchengxu** [comment]
Well, you have to two options:

1. `let g:clap_preview_direction = 'UD'`
2. When the preview direction is `'LR'`, the display window shares the same size with the preview window, so the maximum value of `width` is `50%`, which means you can use `let g:clap_layout = {'width': '49%', 'col':'0%', 'height': '80%', 'row': '15%' } `

**Comment by LinHQ1999** [comment]
It works, thank you!
