### ISSUE TITLE
Plugin hangs when `Cmd files` in executed from $HOME CWD

### ISSUE THREAD

**Issue by ratheesh** [liuchengxu/vim-clap#75]
If `Clap files` or similar command related to searching is executed with `$HOME` or a folder with large number of files/folders as current working directory, command hangs without a way out. Only way to recover is killing vim(I tested using neovim).
Is there a way out in this situation?

**Comment by liuchengxu** [comment]
Yes, I'm seeing this too. Unfortunately it's hard to resolve, although everything in vim-clap can be async now, for it is essentially a problem that how to keep reponsive when dealing with the CPU-intensive jobs.  Use fzf.vim instead if you do often searching under the home directory. I don't have a solution for now.

**Comment by ratheesh** [comment]
With PR  #70 , I don't see this issue.

**Comment by liuchengxu** [comment]
I indeed did some optimizations in #70, but I don't believe that could eliminate this issue. And I guess you are using neovim? With #70 neovim are truely more responsive than before, but for vim, the response will still unsatisfactory.

**Comment by Yggdroot** [comment]
I don't know what kind of algorithm clap uses, LeaderF doesn't wait until all the files indexing is finished, it uses one thread to index the files and uses another thread to do fuzzy matching and display the results.

**Comment by liuchengxu** [comment]
The strategy of clap is trivial. What clap actually does is to start a fd/rg job in the background to do the searching task, whenever the output callback gets some results, display or cache them. And I think it because the out_cb of vim is linewise that you will feel less responsive in this situation compared to neovim.

I guess the thread model used in LeaderF is not appliable to clap as it's in pure vimscript :(. I have no idea vimscript could do the same thing.

**Comment by Yggdroot** [comment]
Bad luck, vimscript does not have the concept of thread.
I'm not familiar with the Job APIs, I am afraid I can't give any help now.

**Comment by ratheesh** [comment]
> I indeed did some optimizations in #70, but I don't believe that could eliminate this issue. And I guess you are using neovim? With #70 neovim are truely more responsive than before, but for vim, the response will still unsatisfactory.

Yes, I am using neovim. But one can come out by pressing `ESC` key. I will take it for now.

**Comment by Yggdroot** [comment]
@liuchengxu Maybe you need to `redraw` when necessary. There is a situation that the results are ready but the UI is not refreshed.

**Comment by liuchengxu** [comment]
Can you elaborate? @Yggdroot  I don't see it on my side.

**Comment by Yggdroot** [comment]
I did not mean Clap has such a situation, just a hint.
Because when I use the popup window of vim, I found that it need to call `redraw` sometimes to refresh the UI.

**Comment by liuchengxu** [comment]
Thanks for the heads up :(. Will do when neccessary.

**Comment by liuchengxu** [comment]
Closing this in favor of #140.
