### ISSUE TITLE
Error message when opening a file that has a swap file warning

### ISSUE THREAD

**Issue by aprowe** [liuchengxu/vim-clap#761]
I'm sorry I dont have time to fill the template out right now, but would rather report than just stay quiet. May have time to dig later. 
When I load a file that warns me about a swap this error pops up after hitting E to edit the file anyway. 
It goes away and doesn't seem to cause an issue, but it does appear. 
On nvim 0.5.0, ubuntu 16.04, 
Clap is on latest master, and updated binary build.
```
vim-clap: target_dir:/home/<redacted>/src, Run:function('69', {'source_type': 3, 'is_sync': function('88'), 'get_source': function('87'), 'init_default_impl': function('91'), 'can_async': function('90'), 'init_display_win': function('92'), 
'support_multi_select': function('79'), '_apply_sink': function('69'), 'id': 'files', 'filter': function('78'), 'sink_star': 
function('72'), 'sink': function('71'), 'support_open_action': function('80'), '_': function('67'), 'is_pure_async': function('89'), 
'try_set_syntax': function('82'), 'on_typed': function('74'), 'source_async_or_default': function('84'), 'on_exit': 
function('76'), 'has_enable_rooter': function('70'), 'source_async': function('85'), 'jobstop': function('77'), 'abort': 
function('68'), 'is_rpc_type': function('81'), 'apply_query': function('83'), 'on_enter': function('73'), '_apply_source': 
function('86'), 'on_move': function('75')}), run_args:['<redacted file path>'], exception:Vim(edit):
E325: ATTENTION
```

**Comment by liuchengxu** [comment]
The swap file might make some sense for some people, so I don't it's a good idea to simply swallow this warning message in vim-clap. You have a few options to avoid this message on your side:

- https://stackoverflow.com/questions/40620983/is-there-a-way-to-disable-vims-swap-file-warning/40621040
- https://vi.stackexchange.com/questions/21784/vim-edit-anyway-without-prompting
- https://superuser.com/questions/218262/how-to-get-rid-of-the-warnings-when-opening-a-file-that-has-a-swp-file/498658
