### ISSUE TITLE
`clap#run` doesn't call `on_move` for the first entry in a provider

### ISSUE THREAD

**Issue by goolord** [liuchengxu/vim-clap#768]
**Environment (please complete the following information):**
 - OS: Arch linux 5.14.2-arch1-2
 - (Neo)Vim version: NVIM v0.6.0-dev+334-g9cde1e589
 - vim-clap version: https://github.com/liuchengxu/vim-clap/commit/fd3b2b2f842e25032d5704fb1534a6c6f762de25

**Describe the bug**
`clap#run` doesn't run `on_move` for the first entry in a provider and must be manually called. it seems inconsistent weather the manually called `on_move` will update the preview as well.

**Clap debug**

<details>

```
            has cargo: 1
            has maple: /home/zach/.local/share/nvim/site/pack/packer/start/vim-clap/target/release/maple
           maple info: version 0.1.29, built for x86_64-unknown-linux-gnu by rustc 1.57.0-nightly (aa8f2d432 2021-09-18).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
        rustc version: rustc 1.57.0-nightly (aa8f2d432 2021-09-18)

    Current sync impl: Lua
     Current FileType: alpha
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/zach/.local/share/nvim/site/pack/packer/start/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': ''}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:true
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '5%', 'row': '11%', 'width': '45%', 'relative': 'editor', 'height': '80%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'nil'
    let g:clap_preview_direction = 'LR'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_frames = ['🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘']
    let g:clap_theme = 'gruvbox_dark'
  Provider Variables:
    let g:clap_provider_grep_delay = 100
    let g:clap_provider_grep_enable_icon = 1
```

</details>

**Expected behavior**
`on_move` is called on  `clap#run`

**Screenshots**
example with https://github.com/goolord/nvim-clap-lsp/blob/main/lua/clap-lsp/symbols.lua#L37 commented out
![image](https://user-images.githubusercontent.com/24906808/134749131-9c55fa46-55b7-472c-a59c-90ec3fb1527c.png)
![image](https://user-images.githubusercontent.com/24906808/134749137-a595b0a4-2033-45a0-b92b-a94e93d46e5b.png)
![image](https://user-images.githubusercontent.com/24906808/134749143-1161d192-b823-4fa5-88fb-d472532bcebc.png)

**Additional context**
this is for my plugin https://github.com/goolord/nvim-clap-lsp which provides handlers for nvim's builtin lsp. it doesn't register a provider and calls `clap#run` directly, so maybe it's missing the branch that makes this behavior work for the built in providers.

source example: https://github.com/goolord/nvim-clap-lsp/blob/main/lua/clap-lsp/symbols.lua#L37

**Comment by liuchengxu** [comment]
Could you please provide a minimal vimrc so that I can reproduce it easier? `clap#run` simply tries to register the provider and then execute it directly, therefore it might be unrelated to `clap#run` but some internal glitch.

https://github.com/liuchengxu/vim-clap/blob/fd3b2b2f842e25032d5704fb1534a6c6f762de25/autoload/clap.vim#L391-L399

**Comment by goolord** [comment]
```vim
set nocompatible
set runtimepath^=~/Dev/vim-clap
syntax on
filetype plugin indent on

let s:n = 0

function Min_on_move()
  let curline = g:clap.display.getcurline()
  echo s:n
  let s:n = s:n + 1
endfunction

function Min_clap()
  call clap#run(
        \ { 'id': 'quick_run',
        \   'source': ['example 1', 'example 2'],
        \   'on_move': function('Min_on_move'),
        \   'sink': 'echo'
        \ })
endfunction
```
to reproduce, run `call Min_clap()`, move your cursor around the results, observe the `n` echoed on the command line

**Comment by goolord** [comment]
maybe the intention is to use `on_enter = on_move_impl,` but the file provider for example does not and it's not really the behavior i would expect

**Comment by liuchengxu** [comment]
Previously `on_move` is intentionally not triggered due to the performance consideration, the sync `on_move` can be slow, but I think it's fine to invoke it as the provider author should be responsible for the performance and `on_move_async` is always preferred.
