### ISSUE TITLE
Cannot execute a provider from the list obtained by :Clap

### ISSUE THREAD

**Issue by ronisbr** [liuchengxu/vim-clap#77]
**Environment (please complete the following information):**
 - OS: macOS Catalina
 - (Neo)Vim version: v0.4.2
 - vim-clap version: `master` (commit `177e0ec3`)
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When I type `:Clap`, it opens a window with all providers. However, after selecting any of them, I get the message `unimplemented` on the command line.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap<ENTER>'

4. Select any provider.

5. The message `_ unimplemented` will be printed on the command line.

**Expected behavior**
The selected provider should be executed.

**Comment by liuchengxu** [comment]
It was in an unimplemented state, but will be resolved in #74 thanks to @wookayin .
