### ISSUE TITLE
help_tags doesn't show plugin helps

### ISSUE THREAD

**Issue by QiBaobin** [liuchengxu/vim-clap#776]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: MacOS 11.6
 - (Neo)Vim version: Neovim 0.6
 - vim-clap version: head
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: ??? 

**Describe the bug**

Only internal help tags are shown, no external plugins' help.

**Clap debug**

```

            has cargo: 1
            has maple: ~/.local/share/nvim/site/pack/packer/start/vim-clap/target/release/maple
           maple info: version 0.1.30, built for x86_64-apple-darwin by rustc 1.56.0 (09c42c458 2021-10-18).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
        rustc version: rustc 1.56.0 (09c42c458 2021-10-18)

    Current sync impl: Lua
     Current FileType: packer
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '~/.local/share/nvim/site/pack/packer/start/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'single'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liuchengxu** [comment]
I'm guessing you use some plugin lazy load strategy. In order to show the help of external plugins, the path of the plugin needs to be included in `&runtimepath`, ensure your plugin is loaded at that time.

https://github.com/liuchengxu/vim-clap/blob/17bb71a1f604de26b6f7d34d1ce074aba75330bd/autoload/clap/provider/help_tags.vim#L17

**Comment by QiBaobin** [comment]
I am using packer, none of plugin's help is shown, even for vim-clap itself.

**Comment by liuchengxu** [comment]
As I have said, only the plugins whose paths have been included in `&runtimepath` will be shown when you invoke `:Clap help_tags`. If it doesn't, then the path is not included at that time, try to add a debugging statement to see the value of `&runtimepath`.

**Comment by QiBaobin** [comment]
It's OK if it's only an issue on my local. Although I think my runtimepath is good as below:
```
~/.config/nvim,/etc/xdg/nvim,~/.local/share/nvim/site,~/.local/share/nvim/site/pack/packer/start/packer.nvim,~/.local/share/nvim/site/pack/*/start/*,/usr/local/share/nvim/site,/usr/share/nvim/site,~/homebrew/Cellar/neovim/HEAD-a5d6f36/share/nvim/runtime,~/homebrew/Cellar/neovim/HEAD-a5d6f36/share/nvim/runtime/pack/dist/opt/matchit,~/homebrew/Cellar/neovim/HEAD-a5d6f36/lib/nvim,~/.local/share/nvim/site/pack/*/start/*/after,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after
```

**Comment by liuchengxu** [comment]
Basically, `&runtimepath` is used to locate the path of vim help file, I'm not sure if it's enough for neovim tto find all the help files though. You can try to hack it around if you get some time.
