### ISSUE TITLE
Cannot install-binary on mac M1

### ISSUE THREAD

**Issue by kbwo** [liuchengxu/vim-clap#778]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: OS: mac OS big sur (m1 macbook air)
 - (Neo)Vim version: 0.5.0
 - vim-clap version: 0.30

**Describe the bug**
When I execute ":Clap install-binary" or ":Clap install-binary!" command, this error occured.

```
Error detected while processing function clap#client#notify_recent_file[4]..clap#client#call[1]..clap#client#notify[2]..clap#job#daemon#send_message:
line    1:
E900: Invalid channel id
E900: Invalid channel id
```
Is there any solution?

**Comment by liuchengxu** [comment]
Are you using the latest commit from master? If you don't compile the Rust binary locally but use the prebuilt one, please stick with the tag release on both the cloned source and binary, otherwise, the latest master commit might have incompatibility with the prebuilt binary.

**Comment by kbwo** [comment]
I solved it according to your comment. Thank you!
