### ISSUE TITLE
Clap jumps does not set correct syntax highlight when opening a file

### ISSUE THREAD

**Issue by ronisbr** [liuchengxu/vim-clap#78]
**Environment (please complete the following information):**
 - OS: macOS Catalina
 - (Neo)Vim version: v0.4.2
 - vim-clap version: `master` (commit `177e0ec3 `)
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When a file is opened and `:Clap jumps` is used to go to another file, this new file is opened without any syntax highlight.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Open a file.

4. Use `:Clap jumps` to go to another file.

5. The new file will be opened without any syntax highlight.

**Expected behavior**
The new file should be opened with the correct syntax highlight.

**Comment by ronisbr** [comment]
I also found the same behavior in `:Clap marks`.

**Comment by liuchengxu** [comment]
I believe this issue is caused by this `noautocmd`:

https://github.com/liuchengxu/vim-clap/blob/177e0ec345e76d3ff8939a9f2dbedaa83bb8102b/autoload/clap/util.vim#L35-L37

For some filetypes, the syntax highlight seems to be fine. You can use `:edit` when losing the syntax highlight until this issue is resolved.

**Comment by liuchengxu** [comment]
Try #81.

**Comment by ronisbr** [comment]
Hi @liuchengxu !

Thanks, I cannot see the issue anymore when I used this branch. Both jumps and marks start to work correctly.
