### ISSUE TITLE
Set  preview size depending on available space

### ISSUE THREAD

**Issue by BonaBeavis** [liuchengxu/vim-clap#780]
Right know, the preview size (height) is hardcoded, that leads to some ugliness with tiled window managers. With the preview height set small, space is wasted when vim occupies the whole screen and with the height set taller, clap breaks when vim occupies a quarter of the screen.

**Comment by liuchengxu** [comment]
The preview window is now basically affiliated with the display window, the size of the preview window is determined by `g:clap_preview_direction` and the size of the display window(you can configure it using `g:clap_layout`). With a proper setting of `g:clap_preview_direction` and `g:clap_layout`, I think most cases can be handled. Calculating the preview on the fly will be indeed convenient, but I don't have much bandwidth recently :P.

**Comment by liuchengxu** [comment]
Hi, @BonaBeavis Today I find some time to revisit this issue and find no problems with the default setting `g:clap_preview_direction = 'AUTO'` now. If this issue's still annoying to you, can you provide some more info to reproduce it?

**Comment by BonaBeavis** [comment]
Thanks for looking into it, but I cannot reproduce it anymore because I do not use clap anymore.

**Comment by qlixes** [comment]
Dear Sir, I got issued about clap_preview_direction.
<img width="1225" alt="image" src="https://github.com/liuchengxu/vim-clap/assets/521054/a608bbe9-afc3-4f25-966f-7a3bc49b756d">
Please inform how to patch these responsive clap window.
Thank you
