### ISSUE TITLE
How to do a case-insensitive search

### ISSUE THREAD

**Issue by raoweijian** [liuchengxu/vim-clap#784]
**Is your feature request related to a problem? Please describe.**
Every time when I want to find a ruby file, for example, `DocumentTaskHelper` defined in `document_task_helper.rb`, I will try to copy the `DocumentTaskHelper`, and paste it in the `:Clap files` popup window, but can't find the file I wanted, because my search contains uppercase characters.

I know that when I type a string without uppercase characters, I can find files with uppercase characters in name, for example, I can find `README.md` by searching `readme`, but can't find it using `Readme`.

**Describe the solution you'd like**
Give an option, maybe like `:Clap files -i`, to always enable case insensitive search, even if it contains uppercase character.

**Describe alternatives you've considered**

**Additional context**

**Comment by liuchengxu** [comment]
Please try #814 using `:Clap files +ignorecase` for case-insensitive search.
