### ISSUE TITLE
Mac M1 pre-built Install Error

### ISSUE THREAD

**Issue by Desongyao** [liuchengxu/vim-clap#786]
- OS: Mac M1
 - (Neo)Vim version: 8.2
 - vim-clap version: 0.31

BugReport:
when execute  Plug 'liuchengxu/vim-clap', { 'do': ':Clap install-binary!' }, Occur Error:No prebuilt maple binary available for Darwin arm64

**Comment by liuchengxu** [comment]
The building on M1 is not yet supported by GitHub Action, see https://github.com/actions/virtual-environments/issues/2187.

**Comment by Desongyao** [comment]
How Can I Install this by manual? ./install.sh? or make && make install?

> The building on M1 is not yet supported by GitHub Action, see [actions/virtual-environments#2187](https://github.com/actions/virtual-environments/issues/2187).

**Comment by liuchengxu** [comment]
Just `make` should be fine.

**Comment by liuchengxu** [comment]
`maple-aarch64-apple-darwin` will be provided in the next release, you need to download and open it manually the first time as the binary is not signed. Once it's ensured to be runnable, rename `maple-aarch64-apple-darwin` to `maple` and move it into `bin/maple`.
