### ISSUE TITLE
Only show file name

### ISSUE THREAD

**Issue by kdurant** [liuchengxu/vim-clap#79]
![QQ截图20191022085723](https://user-images.githubusercontent.com/2704364/67253394-02cb3400-f4aa-11e9-9645-0bd8af58af9b.png)

Need an option, when the option is true, only show the result of matching the file name and search word.
Like above, only show `_nvimrc`

**Comment by liuchengxu** [comment]
You can use `:Clap files ++finder=[YOUR FINDER] [YOUR FINDER ARGS]` to meet your own need. See `:h Clap-files`.
