### ISSUE TITLE
[Question] Is Clap files support preview? And why not ?

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/vim-clap#799]
https://github.com/liuchengxu/vim-clap/blob/master/doc/clap-support.txt#L38

**Comment by liuchengxu** [comment]
`:Clap files` does have the preview support. Please post the env info if you don't see it.

**Comment by liuchengxu** [comment]
Basically, most of the built-in clap providers have the preview, which is mostly async using the Rust binary as the backend. Closing as the question has been answered. Please create another issue report if you have trouble with the preview feature.

**Comment by tracyone** [comment]
@liuchengxu 

Yes, I do have trouble of using `Clap files`, there is no preview.  But `:Clap jumps` and `:Clap marks` have preview. 

In clap-support.txt say `Clap jumps` and `Clap marks` support preview but not `Clap files` 

https://github.com/liuchengxu/vim-clap/blob/master/doc/clap-support.txt#L146-L147

**Comment by tracyone** [comment]
I can use vim-clap without :Clap install-binary, maybe this is the reason why no preview of Clap files?

**Comment by liuchengxu** [comment]
Perhaps, the files provider has both the `on_move` and `on_move_async` impl for the preview, it should work out of the box in theory, but it's possible to have some glitches there. I don't suggest people use clap without the Rust binary as most of my efforts will be spent on improving the Rust backend for a more efficient and smoother user experience in Vim.
