### ISSUE TITLE
C language files have no highlight color in preview window

### ISSUE THREAD

**Issue by krisfans** [liuchengxu/vim-clap#800]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - (Neo)Vim version: vim8.2.3458
 - vim-clap version: lastest
 - Have you reproduced with a minimal vimrc: Yes
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes 

**Describe the bug**
C language files have no highlight color in preview window

**Clap debug**

```

            has cargo: 1
            has maple: /home/kris/.cache/vim/dein/repos/github.com/liuchengxu/vim-clap/bin/maple
           maple info: version 0.1.32 (git v0.32), built for x86_64-unknown-linux-musl by rustc 1.60.0-nightly (5e57faa78 2022-01-19).

         has +python3: 1
has py dynamic module: 0
            has ctags: ctags with JSON output support
        rustc version: rustc 1.53.0

    Current sync impl: Lua
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/kris/.cache/vim/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('51'), 'open': function('<SNR>31_create_display'), 'shrink_if_undersize': function('50')}
    let g:clap#popup#preview = {'line_count': function('<SNR>30__line_count'), 'show': function('52'), 'hide': function('53'), 'clear': function('54'), 'add_highlight': function('55'), 'get_lines': function('<SNR>30__get_lines'), 'getbufvar': function('<SNR>30__getbufvar'), 'setbufvar_batch': function('<SNR>30__setbufvar_batch'), 'setbufvar': function('<SNR>30__setbufvar'), 'win_is_valid': function('<SNR>30__win_is_valid'), 'goto_win': function('<SNR>30__goto_win'), 'set_syntax': function('56')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" Disable Vim's native pack feature
set packpath=


set runtimepath+=~/.cache/vim/dein/repos/github.com/liuchengxu/vim-clap
filetype plugin indent on
syntax enable
set termguicolors

```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap history'

**Expected behavior**
C language files have no highlight color in preview window

**Screenshots**
![2022-02-09 21-46-56屏幕截图](https://user-images.githubusercontent.com/57793534/153214590-eb77714d-3ac7-4a3b-829a-726c66003a9d.png)

**Comment by liuchengxu** [comment]
Nope, I don't see the other way. In order to get the proper syntax highlight, you need to know the filetype given the file path, parsing the output of `autocmd filetypedetect` is the only way I can come up with.

**Comment by liuchengxu** [comment]
Try adding more mappings like https://github.com/liuchengxu/vim-clap/commit/936edac04920196b331edf3a056c42e5b926c0aa if you miss the highlight for some kinds of files.

**Comment by liuchengxu** [comment]
@krisfans  I opened up #801 to make it easier to add support for the missing file types, we could pre-define the filename map and extension map there.

**Comment by krisfans** [comment]
Thanks for your reply! I want to know how to make the changed `crates/maple_cli/src/stdio_server/vim.rs` file take effect? Do I need to recompile the clap?

**Comment by liuchengxu** [comment]
Yes, add new items to the map accordingly and recompile the Rust binary to take effect. In the future, we can also make them a toml config so that people can update them without writing any Rust.
