### ISSUE TITLE
Can't choose options from `:Clap tags`

### ISSUE THREAD

**Issue by arashm** [liuchengxu/vim-clap#810]
**Environment (please complete the following information):**
 - OS: MacOS 11.6.3
 - (Neo)Vim version: NVIM v0.6.1
 - vim-clap version: master
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
Clap throws an error when selecting an option from `Clap tags`.

**Clap debug**

```
            has cargo: 1
            has maple: /Users/amousavi/.vim/plugged/vim-clap/target/release/maple
           maple info: version 0.1.33, built for x86_64-apple-darwin by rustc 1.59.0 (9d1b2106e 2022-02-23).
         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
        rustc version: rustc 1.59.0 (9d1b2106e 2022-02-23)
    Current sync impl: Lua
     Current FileType: ruby
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/amousavi/.vim/plugged/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:true
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'single'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_theme = 'dogrun'
  Provider Variables:
                     []
```

**To Reproduce**
I see the list of options in the Clap window when I invoke `Clap tags`, but when I choose one, I get the following error:

```
vim-clap: clap#handler#sink: Vim(let):E684: list index out of range: 1, throwpoint:function clap#handler#cr_action[5]..clap#handler#sink[13]..62[1]..clap#rooter#run_heuristic[4]..60[3]..115[1]..vista#finder#fzf#sink[1]..vista#finder#fzf#extract, li
ne 13
```
I do have both `vista.vim` and `maple` installed. When I run `:Vista` I see the options in the sidebar and I can choose them just fine, but it doesn't work in Clap for some reason.

**Comment by liuchengxu** [comment]
Since https://github.com/liuchengxu/vim-clap/pull/795 vista.vim is not necessary for `tags` provider, you could use `let g:clap_provider_tags_force_vista = 1` before the bug fix. Can you provide the source file for running `:Clap tags` so that I can reproduce locally?

**Comment by arashm** [comment]
So it doesn't really matter what file I try to do it with, they all end up with that error. I tried [this file](https://raw.githubusercontent.com/arashm/PoParser/master/lib/poparser/header.rb), and it was the same. I have these related configurations in my n/vim config:

```viml
" Clap
let g:clap_layout = { 'relative': 'editor' }
let g:clap_disable_run_rooter = v:true

nnoremap <silent> <c-p> :Clap files!<CR>
nnoremap <silent> <leader>' :Clap filer<CR>
nnoremap <silent> <leader><leader>' :Clap filer %:p:h<CR>
nnoremap <silent> <leader>g :Clap grep2<CR>
nmap <silent> <leader>gg :Clap grep2 ++query=<cword><CR>
vmap <silent> <leader>gg :Clap grep2 ++query=@visual<CR>
vmap <silent> <leader>gf :Clap grep2 %:p:h<CR>
nnoremap <silent> <leader>b :Clap buffers<CR>
nnoremap <leader>z :Clap tags<CR>

" Vista
let g:vista_default_executive = 'coc'
```
There's nothing else related to them there. I'm not using any tags generator plugin, but I do have ctags installed:

```sh
─$ ctags --version
Universal Ctags 5.9.0(p5.9.20210905.0), Copyright (C) 2015 Universal Ctags Team
Universal Ctags is derived from Exuberant Ctags.
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep  8 2021, 17:51:41
  URL: https://ctags.io/
  Optional compiled features: +wildcards, +regex, +gnulib_regex, +iconv, +option-directory, +xpath, +json, +interactive, +sandbox, +yaml, +packcc, +optscript
```

**Comment by liuchengxu** [comment]
Can not reproduce with the file you gave, works great for me. You can try debugging yourself: add some debugging statements after https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/finder/fzf.vim#L75, `items` seems to be problematic there.

**Comment by Neur1n** [comment]
> Can not reproduce with the file you gave, works great for me. You can try debugging yourself: add some debugging statements after https://github.com/liuchengxu/vista.vim/blob/master/autoload/vista/finder/fzf.vim#L75, `items` seems to be problematic there.
> 
> Based on your env, I don't see any problem obviously related to vim-clap.

In my case, working with a python file using coc.nvim+coc-jedi, the result of `icon_stripped` in function `vista#finder#fzf#extract` is (for instance) `135:run` which means the "run" method is one line 135. Even though the option `g:vista#renderer#enable_icon` is set to 1(by default), there is no icon/glyph or any whitespace before "135:run" to be split by `split(icon_tag_lnum)[1:]`. Therefore, the output `icon_stripped` contains only one element, which is "135:run" and leads to the "list index out of range" error.

Setting `g:vista#renderer#enable_icon` to 0 is a workaround for me.

**Comment by arashm** [comment]
>  Since https://github.com/liuchengxu/vim-clap/pull/795 vista.vim is not necessary for tags provider

I totally removed Vista and  `g:clap_provider_tags_force_vista` from my config, and Clap is still calling for vista:

```
vim-clap: clap#handler#sink: Vim(call):E117: Unknown function: vista#finder#fzf#sink, throwpoint:function clap#handler#cr_action[5]..clap#handler#sink[13]..69[1]..clap#rooter#run_heuristic[4]..67[3]..110, line 1
```

I have maple installed and locally compiled it.

**Comment by liuchengxu** [comment]
@arashm @Neur1n Sorry for the inconvinence, the rust-backed tags impl is incomplete, can you see if https://github.com/liuchengxu/vim-clap/pull/827 fixes it?

**Comment by arashm** [comment]
@liuchengxu with #827, it works fine without Vista now. With Vista, `g:vista#renderer#enable_icon = 0` should still be set 👍  thank you

**Comment by liuchengxu** [comment]
@arashm Since vista is no longer required, I believe this issue can be closed?

**Comment by arashm** [comment]
Sure, agreed!
