### ISSUE TITLE
files, grep, grep2 are no working on Windows

### ISSUE THREAD

**Issue by Neur1n** [liuchengxu/vim-clap#816]
- OS: Window 10
 - (Neo)Vim version: NVIM 0.6.1
 - vim-clap version: d2a5259
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
With the d2a5259 release, `file`, `grep`, `grep2` are not working at all on Windows while `filer`, `tags` are working (I've not tested all other providers yet). The popup window just not lists anything at all.

For `files`, the error output (with `:message`) is
```
vim-clap: on_stdio_event:['error: Found argument ''--case-matching'' which wasn''t expected, or isn''t valid in this context', '', '^IIf you tried to supply `--case-matching` as a value rather than a flag, use `-- --case-matching`', '', 'USAGE:', '    maple.exe --number <NUM> --winwidth <WINWIDTH>', '', 'For more information try --help', '']
```

For `grep2`, the error message is
```
vim-clap: on_stdio_event:['error: ']
vim-clap: on_stdio_event:['The system cannot find the file specified. (os error 2)', '']
```

And no error messages for `grep`.

**Clap debug**
```
            has cargo: 0
            has maple: D:\Workspaces\git_ws\dotfiles\neovim\plugged\vim-clap/bin/maple.exe
           maple info: version 0.1.33 (git v0.33), built for x86_64-pc-windows-msvc by rustc 1.58.1 (db9d1b20b 2022-01-20).

         has +python3: 1
has py dynamic module: 0
            has ctags: ctags with JSON output support
    Current sync impl: Lua
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'D:\Workspaces\git_ws\dotfiles\neovim\plugged\vim-clap\autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = 1
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'single'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible

if has('win32')
  let $VIMCONFIG=$HOME.'/AppData/Local/nvim'
else
  let $VIMCONFIG=$HOME.'/.config/nvim'
endif
set runtimepath^=$VIMCONFIG/plugged/vim-clap
let g:clap_enable_debug=1
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':Clap files<CR>' and input some texts into the popup window

**Expected behavior**
These functionalities should list corresponding search results.

**Screenshots**
The `filer` shows the files in cwd:
![image](https://user-images.githubusercontent.com/17579247/160057930-5403d77d-0b41-4152-a05e-31cda1e82748.png)
![image](https://user-images.githubusercontent.com/17579247/160058065-d46f3598-4905-4801-a541-2205e356b342.png)

While `files` not showing anyhing:
![image](https://user-images.githubusercontent.com/17579247/160058032-7f93734d-7ac0-4e91-ace2-34c3eafe27b5.png)

**Additional context**

**Comment by liuchengxu** [comment]
Although the Rust binary is kind of stable now, there is still a great chance that incompatible changes will be introduced from time to time. It's recommended to stick with some release until the new release is out given you are using the prebuilt binary. Upgrading the binary to the latest release https://github.com/liuchengxu/vim-clap/releases/tag/v0.34 should fix your problem.

**Comment by Neur1n** [comment]
So... a similar issue occurs (since a couple months ago) which `grep2`/maple is not working on Windows. The error message is:

> vim-clap: on_stdio_event:['error: Found argument ''--par-run'' which wasn''t expected, or isn''t valid in this context', '', '^IIf you tried to supply `--par-run` as a value rather than a flag, use `-- --par-run`', '', 'USAGE:', '    maple.exe grep --grep-query <GREP_QUERY> --input<INPUT>', '', 'For more information try --help', '']

Adding '--' before '--par-run' in `autoload/clap/filter/async/dyn.vim` does not solve the problem.

**Comment by liuchengxu** [comment]
@Neur1n `--par-run` is a new feature added after the last release, https://github.com/liuchengxu/vim-clap/pull/859. You are probably not compiling the latest Rust binary, you can stick with the repo under the latest tag with the latest binary release for now, the next binary release should be soon.

**Comment by Neur1n** [comment]
By "the latest Rust binary", do you mean maple?

**Comment by liuchengxu** [comment]
Yes.
