### ISSUE TITLE
Why grep filter returns more results with more search chars?

### ISSUE THREAD

**Issue by zoumi** [liuchengxu/vim-clap#819]
**Environment (please complete the following information):**
 - OS: Windows 10 64 bit
 - (Neo)Vim version: 
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Mar 24 2022 23:02:44)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-4621
```
 - vim-clap version: SHA-1: 6fd4fecaf8b1da31c625e5f02822778d4a2a08b5
 - Have you reproduced with a minimal vimrc: no
 - Have you updated to the latest plugin version: yes

**Describe the bug**
When I input more chars in clap's grep input panel the sum of results increase.

**To Reproduce**
1,grep search "__"
```vim
:Clap grep +no-cache  ++query=__
```
clap indicate there are 51 result
2,enter P in the end
the the sum of results increase.

**Expected behavior**
the sum of results should decrease.

**Screenshots**
![Snipaste_2022-04-06_14-20-11](https://user-images.githubusercontent.com/5162901/161915503-9bcebb38-f714-4e2a-8565-7f797bb71cea.jpg)

![Snipaste_2022-04-06_14-20-42](https://user-images.githubusercontent.com/5162901/161915490-3ae34729-59b7-49e3-84e5-30be13a264c5.jpg)

**Comment by zoumi** [comment]
By the way vim-clap has bug when run without maple:
I got an error when I press <C-j> to move in result list when maple is removed:
![Snipaste_2022-04-12_11-12-04](https://user-images.githubusercontent.com/5162901/162872534-c351ac64-58da-4028-a518-251bb2a6c7d7.jpg)

I have to temporarily change
```vim
  function! clap#job#daemon#send_message(msg) abort
    call ch_sendraw(s:job, a:msg."\n")
  endfunction
```
to
```vim
  function! clap#job#daemon#send_message(msg) abort
    if exists('s:job')
        call ch_sendraw(s:job, a:msg."\n")
    endif
  endfunction
```

**Comment by liuchengxu** [comment]
>There is bug in maple or vim-clap. rg returns 97 matches, but vim-clap only show 49 matches.

I don't think so, I believe the main reason is that you are not using the same rg command that vim-clap is using, otherwise please create a new issue with a detailed report.

>I got an error when I press <C-j> to move in result list when maple is removed:

Please file a new issue in order to solve it properly.

**Comment by zoumi** [comment]
I got it:
when use maple.exe the sum of results is limited by:
g:clap.display.preload_capacity

I can get all results if I modify:
```vim
function! clap#maple#command#start_grep_sync(cmd, query, enable_icon, glob) abort
  let global_opts = s:prepare_global_opts(g:clap.display.preload_capacity)

  let subcommand = [
        \ 'grep', a:query,
        \ '--grep-cmd', a:cmd,
        \ '--cmd-dir', clap#rooter#working_dir(),
        \ '--sync',
        \ ]

  if a:glob isnot v:null
    let subcommand += ['--glob', a:glob]
  endif

  call clap#job#regular#maple#start([s:maple_bin] + global_opts + subcommand)
endfunction
```
to 
```vim
function! clap#maple#command#start_grep_sync(cmd, query, enable_icon, glob) abort
  let global_opts = s:prepare_global_opts(g:clap.display.preload_capacity+3000)

  let subcommand = [
        \ 'grep', a:query,
        \ '--grep-cmd', a:cmd,
        \ '--cmd-dir', clap#rooter#working_dir(),
        \ '--sync',
        \ ]

  if a:glob isnot v:null
    let subcommand += ['--glob', a:glob]
  endif

  call clap#job#regular#maple#start([s:maple_bin] + global_opts + subcommand)
endfunction
```
