### ISSUE TITLE
Could not exclude .git directory

### ISSUE THREAD

**Issue by cgxxv** [liuchengxu/vim-clap#829]
:Clap files ++finder=fd --type f -H -E ".git/"
:Clap files ++finder=rg --files --follow --hidden -g "!.git/"

The reference:

https://github.com/liuchengxu/vim-clap/blob/master/doc/clap-support.txt#L48

https://github.com/liuchengxu/vim-clap/blob/master/doc/clap-support.txt#L51

But not support exclude some directories.

What I have missed???

**Comment by liuchengxu** [comment]
`.git` is excluded by default, it's enough to simply run `:Clap files` with either fd or rg is installed. You probably want to tweak the ignore file if you have some special requirements, ref https://github.com/BurntSushi/ripgrep/discussions/1578#discussioncomment-12394.

**Comment by zhuzhzh** [comment]
I use `Clap files --hidden`, then .git is in the list. I hope  `--hidden` will show the hidden file except .git, .svn file,  only `--no-ignore` will show .git .svn and so on.

**Comment by liuchengxu** [comment]
>I use Clap files --hidden, then .git is in the list.

`:Clap files --hidden` is to search the hidden files, so it's expected.

I don't understand what the problem is. Please specify the command you use and the output you expect in Vim and the terminal.

**Comment by zhuzhzh** [comment]
I hope `:Clap files --hidden` show the hidden files except .svn, .git.
it's okay for me to write the command `nnoremap <leader>ff :Clap files ++finder=rg --files --hidden -g '!.git/'` to implement it.

I think we could close this issue.
