### ISSUE TITLE
Can't open file in git recursive directory.

### ISSUE THREAD

**Issue by kdurant** [liuchengxu/vim-clap#84]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: win7
 - (Neo)Vim version: 0.5.0-180
 - vim-clap version: new

**Describe the bug**
```
--git directory
-----file0
-----another git directory(not gitsubmodule)
-------------file1
-------------file2
-----another git directory(not gitsubmodule)
-------------file3
-------------file4
```
I use `Clap files` command, it can search file1, file2, but can't use `<C-x>, <C-t>, <C-v>` open it, only use `<Enter>` open it.

**Comment by liuchengxu** [comment]
Can't reproduce.

**Comment by kdurant** [comment]
I reproduce this problem on different computers and different  system(win10, ubuntu18.04).
I only save one plugin(vim-clap)

What a strange question！

**Comment by liuchengxu** [comment]
If you provide the sample data source and detailed steps to reproduce, then I can talk a look, otherwise I can't help.

**Comment by kdurant** [comment]
```viml
call plug#begin('~/nvim/bundle')
Plug 'liuchengxu/vim-clap'
call plug#end()
```
Only use one plugin, and use default configuation.
I test it on Win10, Win7, WSL
