### ISSUE TITLE
Cannot install the binary file

### ISSUE THREAD

**Issue by seongs1024** [liuchengxu/vim-clap#854]
**Environment:**
 - OS: `WSL2 ubuntu`
 - (Neo)Vim version: `Vim 8.1.2269`
 - vim-clap version: `v0.35`

**Describe the bug**
> Cannot install the binary file with `Plug 'liuchengxu/vim-clap', { 'do': { -> clap#installer#force_download() } }`

**Clap debug**
```
Error detected while processing function clap#[5]..clap#installer#install[7]..clap#installer#build_all[7]..SNR>30_unix_sanity_check_is_ok:
line   12:
E484: Can't open file /tmp/vaC0B75/3
has cargo: 1
has maple: v:null
has +python3: 1
has py dynamic module: 0
has ctags: ctags not found
rustc version:
Error detected while processing function clap#[25]..clap#debugging#info:
line   44:
E484: Can't open file /tmp/vaC0B75/4
```

**Additional context**
> After following the guide, [downloading pre-built binary](https://github.com/liuchengxu/vim-clap/blob/master/INSTALL.md#download-the-prebuilt-binary-from-github-release), `vim-clap` works except git-related commands.
> 
> Same error message of:
> - `:Clap bcommits`
> - `:Clap commits`
> - `:Clap git_diff_files`
```
Error detected while processing function clap#[46]..clap#for[23]..SNR>69_detect_source_type[9]..79[1]..clap#provider#commits#source_common[1]..clap#path#get_git_root:
line    1:
E484: Can't open file /tmp/vm6phQZ/7
E684: list index out of range: 0
```
> Especially `:Clap gfiles` works though.

**Comment by liuchengxu** [comment]
Some providers can work without the Rust binary,  but some are not.

Looks like your vim failed to call `system()` somehow, can you see what `:echo system("uname")` says?

**Comment by seongs1024** [comment]
```
E484: Can't open file /tmp/vZdM1Y0/0
```

`echo` works but `system()` doesn't work

**Comment by liuchengxu** [comment]
It's probably caused by the shell you are using, a few useful links, https://github.com/kristijanhusak/vim-js-file-import/issues/31, https://github.com/dag/vim-fish/issues/50.

**Comment by seongs1024** [comment]
I'm using `nushell` so the vim `system()` call doesn't work.
I put `set shell=/bin/bash` on the `~/.vimrc` file, which fixed the problem.
