### ISSUE TITLE
Request to apply bugfix patch

### ISSUE THREAD

**Issue by ktjjang** [liuchengxu/vim-clap#856]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: it doesn't matter
 - (Neo)Vim version: it doesn't matter
 - vim-clap version: it doesn't matter
 - Have you reproduced with a minimal vimrc: it doesn't matter
 - Have you updated to the latest plugin version: yes, i have updated to the latest version
 - Have you upgraded to/compiled the latest Rust binary: ??? 

**Describe the bug**

It is a fault due to conditional statement check in the state where there is no initial value.
The patch below will fix it. please apply

diff --git a/autoload/clap/spinner.vim b/autoload/clap/spinner.vim
index ff3e247..55c2d2c 100644
--- a/autoload/clap/spinner.vim
+++ b/autoload/clap/spinner.vim
@@ -13,6 +13,7 @@ let s:IDLE = ' '

 let s:frame_index = 0
 let s:spinner = s:IDLE
+let s:is_busy = 0

 " The spinner and current provider prompt are actually displayed in a same window.
 function! s:fill_in_placeholders(prompt_format) abort

**Clap debug**

```
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:
it doesn't matter

2. Start (neo)vim with command: `vim -u min.vim`
it doesn't matter

3. Type '....'
Run "Clap filer" as soon as you start vi editor
and type any character to the textbox in Clap filer window

you can see following error

Error detected while processing function <SNR>48_apply_input[4]..31[14]..function <SNR>48_apply_input[4]..31[13]..clap#spinner#set_idle:
line    1:
E121: Undefined variable: s:is_busy
Press ENTER or type command to continue 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liuchengxu** [comment]
Thanks for the report, I had the fix on another WIP branch and forgot to patch it to the master :(. BTW, feel free to try out https://github.com/liuchengxu/vim-clap/tree/arc-item which has a lot of improvements, the performance of filtering is 2x faster (9s to 4s for more than 3 million items) by running in parallel, it's not yet quite stable though.

**Comment by ktjjang** [comment]
Thank you for you to fix it. I have being used this tool about two years. I'm really glad to use this state of the art tool.
