### ISSUE TITLE
The first call :Clap history fails

### ISSUE THREAD

**Issue by vds2212** [liuchengxu/vim-clap#865]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: 8.2 or 9.0
 - vim-clap version: head
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: head
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
1. Start gVim.exe
2. Run the command `:Clap history`

You get the following error message: 
```
vim-clap: Vim(Python3): ImportError: cannot import name 'clap_fzy_rs' from 'clap_fzy'
```

On the second call of `:Clap history` everything goes ok

**Clap debug**

```

            has cargo: 1
            has maple: C:\Users\vds\vimfiles\plugged\vim-clap/target/release/maple.exe
           maple info: version 0.1.34, built for x86_64-pc-windows-msvc by rustc 1.60.0 (7737e0b5c 2022-04-04).

         has +python3: 1
has py dynamic module: ERROR: Vim(echon):E117: Unknown function: clap#filter#sync#python#has_dynamic_module
            has ctags: ctags with JSON output support
        rustc version: rustc 1.60.0 (7737e0b5c 2022-04-04)

    Current sync impl: VimL
     Current FileType: dosbatch
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\vds\vimfiles\plugged\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('159'), 'open': function('<SNR>188_create_display'), 'width': 188, 'shrink_if_undersize': function('158')}
    let g:clap#popup#preview = {'line_count': function('<SNR>187__line_count'), 'show': function('160'), 'hide': function('161'), 'clear': function('162'), 'add_highlight': function('163'), 'get_lines': function('<SNR>187__get_lines'), 'getbufvar': function('<SNR>187__getbufvar'), 'setbufvar_batch': function('<SNR>187__setbufvar_batch'), 'setbufvar': function('<SNR>187__setbufvar'), 'win_is_valid': function('<SNR>187__win_is_valid'), 'goto_win': function('<SNR>187__goto_win'), 'set_syntax': function('164')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_indicator_winid = 1013
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_match_color = ['#5E81AC', '12']
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'never'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_project_root_markers = ['.gitignore', '.vimspector.json', '.root', '.git', '.git/']
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1015
  Provider Variables:
                     []
```

**Comment by liuchengxu** [comment]
An error message was raised to tell that your Python dynamic module does not work somehow, and the vim-clap will fall back to the slowest VimL implementation for this provider.

https://github.com/liuchengxu/vim-clap/blob/13e227b0a28a373ff09aa5492cda6f1cd75bdd1d/autoload/clap/filter.vim#L78-L85

This patch can probably make this switch more smooth, can you see if it helps?

```diff
diff --git a/autoload/clap/filter/sync/python.vim b/autoload/clap/filter/sync/python.vim
index 5b435e5a..83411f4a 100644
--- a/autoload/clap/filter/sync/python.vim
+++ b/autoload/clap/filter/sync/python.vim
@@ -36,7 +36,11 @@ else
   endif
 endif

-execute s:py_exe 'from clap.fzy import' s:py_fn
+try
+  execute s:py_exe 'from clap.fzy import' s:py_fn
+catch
+  let s:using_dynamic_module = v:false
+endtry
```

**Comment by vds2212** [comment]
Thanks for your message.
I'll test yor patch and let you know.

I'm surprised the Python version is not working. I have Python support on my version of Vim and Python installed. UltiSnip is working fine.

Should I install something particular? How can I grab more Information about that problem?

**Comment by vds2212** [comment]
Thanks. I have testerd and it is now smooth :-)

I would like to understand why the Python version is not working for me.

**Comment by vds2212** [comment]
After further investigation I believe the problem is that I have a Win32 version of Vim that use a Win32 version of Python but vim-clap comes with a x64 version of `fuzzymatch_rs.pyd`.

**Comment by vds2212** [comment]
After investigating even more vim-clap ship with a version of fuzzymatch_rs.pyd that requires Python 3.6 for amd64 and the corresponding version of Vim.
I have managed to compile a version of fuzzymatch_rs.pyd that requires Python 3.10 for amd 64 and that works with the x64 version of Vim 9.0 from the [tux project](https://tuxproject.de/projects/vim/).

**Comment by liuchengxu** [comment]
Glad you figured it out.

I'm currently working on [a branch](https://github.com/liuchengxu/vim-clap/tree/remove-deprecated-runner) which will delegate all the heavy jobs to the Rust backend and retire Python dynamic module entirely, it will also unlock a lot of new features I'm looking forward to, hopefully, it can land in master soon, this issue will no longer exist once that happens.

**Comment by vds2212** [comment]
Thanks you very much for Clap!
I'm impatient to test your new features :-)
