### ISSUE TITLE
Clap refuse digit in the hint box with Azerty keyboard

### ISSUE THREAD

**Issue by vds2212** [liuchengxu/vim-clap#871]
**Environment (please complete the following information):**
 - OS: Windows 10
 - (Neo)Vim version: Vim 9.0
 - vim-clap version: head
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: download from GitHub

**Describe the bug**
When I trigger a provider using `:Clap history` I'm prompted with a box where I can give Clap some hint about the file I'm searching.

On a Belgian keyboard (Azerty) I can't type digit (`0`, `1`, ..., `9`) on that box

**Clap debug**

```

            has cargo: 1
            has maple: C:\Users\vds\vimfiles\plugged\vim-clap/target/release/maple.exe
           maple info: version 0.1.34, built for x86_64-pc-windows-msvc by rustc 1.60.0 (7737e0b5c 2022-04-04).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
        rustc version: rustc 1.60.0 (7737e0b5c 2022-04-04)

    Current sync impl: Python
     Current FileType: psi
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\vds\vimfiles\plugged\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('212'), 'open': function('<SNR>217_create_display'), 'width': 93, 'shrink_if_undersize': function('211')}
    let g:clap#popup#preview = {'line_count': function('<SNR>216__line_count'), 'show': function('213'), 'hide': function('214'), 'clear': function('215'), 'add_highlight': function('216'), 'get_lines': function('<SNR>216__get_lines'), 'getbufvar': function('<SNR>216__getbufvar'), 'setbufvar_batch': function('<SNR>216__setbufvar_batch'), 'setbufvar': function('<SNR>216__setbufvar'), 'win_is_valid': function('<SNR>216__win_is_valid'), 'goto_win': function('<SNR>216__goto_win'), 'set_syntax': function('217')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_indicator_winid = 1140
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_match_color = ['#5E81AC', '12']
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'never'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_project_root_markers = ['.gitignore', '.vimspector.json', '.root', '.git', '.git/']
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1142
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type `:Clap history`

4. Try to type `phase3`

5. The box fills with `phase` but the `3` is stripped

**Expected behavior**
I expect Clap to accept `phase3` has a hint

**Screenshots**

![image](https://user-images.githubusercontent.com/160393/189301972-b1cc7f62-62c2-4f15-922b-d4d9fba99a93.png)

**Additional context**
The problem occurs with Belgium keyboard (Azerty keyboard)

**Comment by vds2212** [comment]
If I switch to UK (Qwerty) keyboard it works fine (but it refuse the `£` sign).

**Comment by liuchengxu** [comment]
So you can't type any number in the box? That's interesting. I don't know how to reproduce this, perhaps you can check if the key has been handled and displayed as expected. 

```diff
diff --git a/autoload/clap/popup/move_manager.vim b/autoload/clap/popup/move_manager.vim
index b682b8e6..0220381a 100644
--- a/autoload/clap/popup/move_manager.vim
+++ b/autoload/clap/popup/move_manager.vim
@@ -230,8 +230,11 @@ function! clap#popup#move_manager#filter(winid, key) abort
 
     let char_nr = char2nr(a:key)
 
+    echom 'char_nr:'.string(char_nr)
+
     " ASCII printable characters and multibyte characters
     if char_nr >= 32 && char_nr < 126 || byteidx(a:key, 1) > 1
+      echom 'printable:'.string(a:key)
       call s:move_manager.printable(a:key)
     endif
   catch
```

Unlike neovim's floating window, vim's popup is not a regular one, the input box is mocked by the plugin which can have bugs in rendering the input.

**Comment by vds2212** [comment]
Thanks for your fast answer and your pointer.

When I hit `3` I get: `char_nr:128`
But not `printable:` output.

I have the same behavior for every digit `0` ...  `9`

Best regards,
Vivian.

**Comment by vds2212** [comment]
Actually it seems that the `a:key` argument is `<80><fc>^B3` for the key `3`.
Where `<80>`, `<fc>` and `^B` are probably each a character (they are dark grey)

**Comment by vds2212** [comment]
I have tested with Vim 8.2 and it seems that the behavior is specific to Vim 9.0

**Comment by liuchengxu** [comment]
If so, then you probably have to bisect the related vim commits to find the culprit and report to the [vim repo](https://github.com/vim/vim).

**Comment by vds2212** [comment]
I doubt they will change that . There are change made to be able to handle more keyboards and they way forward is most probably not a rollback. I suppose we should discuss with Vim to understand better what is the "new" meaning of key attribute of the filter callback.

**Comment by vds2212** [comment]
I have created an issue #11109 in Vim [Receive key '<80><fc>^B3' in the filter callback of the create_popup method when unsing Belgium keyboard](https://github.com/vim/vim/issues/11109)

**Comment by vds2212** [comment]
It seems that they key argument is now filled with a vim internal representation of the key (that include the key modifier like <kbd>Ctrl</kbd>, <kbd>Shift</kbd>.
To get the internal representation you can use the `*` syntax: `"\<*S-3>"` == `<80><fc>^B3`

```
echo "\<*S-3>"
<80><fc>^B3
```

I'm in discussion to find a way to translate the internal representation into something more useful.
I'll keep you posted.

**Comment by vds2212** [comment]
There is a new patch that will solve the problem :-) The problem was also in Startify and probably in other plugins.

**Comment by vds2212** [comment]
The problem is solve with patch Vim 9.0.0453

**Comment by vds2212** [comment]
The problem is solve with version 9.0.0453
