### ISSUE TITLE
Maple build failing in master

### ISSUE THREAD

**Issue by eliavo** [liuchengxu/vim-clap#877]
_Instructions: Just installing clap...
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: ubuntu20.04
 - (Neo)Vim version: neovim 0.7.2
 - vim-clap version: latest to date
 - Have you reproduced with a minimal vimrc: havn't tried
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**
when compiling with :Clap install-binary an error occurs, related to the source code:
error[E0515]: cannot return value referencing temporary value
  --> crates/filter/src/source.rs:61:5
   |
61 |       std::io::stdin()
   |       ^---------------
   |       |
   |  _____temporary value created here
   | |
62 | |         .lock()
63 | |         .lines()
64 | |         .filter_map(move |lines_iter| {
...  |
68 | |             })
69 | |         })
   | |__________^ returns a value referencing data owned by the current function
   |
   = help: use `.collect()` to allocate the iterator

For more information about this error, try `rustc --explain E0515`.
error: could not compile `filter` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
make: *** [Makefile:6: maple] Error 101

**Clap debug**

```

            has cargo: 1
            has maple: v:null
         has +python3: 1
has py dynamic module: 0
            has ctags: 
vim-clap: Ensure ctags executable is in your PATH and has the JSON output featurectags without JSON output support
        rustc version: rustc 1.59.0

    Current sync impl: Lua
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/eopatowsky/.vim/bundle/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'single'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liuchengxu** [comment]
Try to run `rustup update && cargo build --release` under the vim-clap plugin directory.

**Comment by eliavo** [comment]
@liuchengxu still fails with same res code
![image](https://user-images.githubusercontent.com/76263733/192110001-87e89570-b04f-46a3-a8d7-9af4939e64c9.png)

**Comment by liuchengxu** [comment]
Interesting, never seen this before, what does `rustup show` say now?

**Comment by eliavo** [comment]
says the following
![Screen Shot 2022-09-25 at 10 55 05](https://user-images.githubusercontent.com/76263733/192133919-3d758952-1101-4e82-872b-f26855d75e69.png)

**Comment by eliavo** [comment]
found this about the "no active toolchain"
`rustup install stable
rustup default stable
`
after this rustup shows prompts: 
![Screen Shot 2022-09-25 at 11 02 54](https://user-images.githubusercontent.com/76263733/192134103-81c5a0fb-a382-414a-86b0-9d7186908e08.png)

even though, after `rustup update && cargo build --release` it fails with same res code, and after `cargo clean` and repeating the same command,  it fails the same.

**Comment by liuchengxu** [comment]
Not sure what happened on your side, but you can build the binary using docker according to the instruction here https://github.com/liuchengxu/vim-clap/blob/5cd460ca66a734824d35e95f51750858bce1dc1c/INSTALL.md#linux.

**Comment by liuchengxu** [comment]
This issue should be fixed in the latest master as the related code has been refactored away anyway.
