### ISSUE TITLE
Clap grep chinese support.

### ISSUE THREAD

**Issue by yongnianliu** [liuchengxu/vim-clap#893]
grep is a really good feature.but nothing happen when i input chinese.Can add chinese support?Thank you.

**Comment by liuchengxu** [comment]
If I recall right, it's fine to grep Chinese characters, but there is a glitch in the highlighting. Please provide more info if it doesn't work for you at all, such as the source file and query word.

**Comment by liuchengxu** [comment]
The highlights of multi-byte characters is fixed in #907.

<img width="721" alt="截屏2023-01-15 09 16 32" src="https://user-images.githubusercontent.com/8850248/212504391-612f747e-e767-44c1-888d-9343e3ec5627.png">
