### ISSUE TITLE
Disable popup menu in the floating window

### ISSUE THREAD

**Issue by ratheesh** [liuchengxu/vim-clap#9]
**Is your feature request related to a problem? Please describe.**
If an autocompletion plugin like `deoplete` is enabled, entering a query in floating window displaying pum which covers the results. This is very annoying.

**Describe the solution you'd like**
Disabling popupmenu in the floating window solves this problem.

**Comment by liuchengxu** [comment]
I also have this idea. Before I push a commit, can you see if this works?

```vim
autocmd User ClapOnEnter call g:clap.input.setbufvar('&completeopt', '')
```

**Comment by ratheesh** [comment]
Yes, the latest edited change works in `neovim`. Thank you.
This issue can be closed once this tested on `ViM`.
