### ISSUE TITLE
E591: 'winheight' cannot be smaller than 'winminheight'

### ISSUE THREAD

**Issue by xorander00** [liuchengxu/vim-clap#908]
**Environment (please complete the following information):**
 - OS: FreeBSD 13.1-STABLE
 - (Neo)Vim version: NeoVim v0.8.2
 - vim-clap version: 0d630e4aa23315c086e858c1a41ff40e082d0fe7
 - Have you reproduced with a minimal vimrc: TBD
 - Have you updated to the latest plugin version: Yes
 - Have you upgraded to/compiled the latest Rust binary: Yes

**Describe the bug**  

When opening the vim-clap window via ':Clap<CR>', the following error is thrown...  
```
Error detected while processing function clap#[46]..clap#for[41]..clap#floating_win#open:
line    4:
E591: 'winheight' cannot be smaller than 'winminheight'
```  

':verbose set winheight' and ':verbose set winminheight' didn't produce any useful information, just said that it was set by vim-clap.  
    
I tried disabling other plugins that I suspected might be messing with related options, but to no avail. What did work was commenting out line vim-clap/autoload/clap/floating_win.vim:451

```
let s:save_winheight = &winheight
" let &winheight = 1
```

Then the window popped up and worked as expected without throwing any errors.  
  
I'm not sure how else to further diagnose if this is something that I should work-around in another plugin or whether it's something that vim-clap should guard for maybe? Figured I'd post here to get any further tips/feedback. Wish I could provide a bit more context, but currently still exploring. Feel free to ask me for whatever further info you might need. Thanks! 

**Clap debug**

```
has cargo: 1
has maple: /usr/home/me/.local/share/nvim/lazy/vim-clap/target/release/maple
maple info: version 0.1.39 (git v0.39-3-g0d630e4), built for x86_64-unknown-freebsd by rustc 1.68.0-nightly (0b90256ad 2023-01-13).
has +python3: 1
has py dynamic module: 0
has ctags: ctags with JSON output support
rustc version: rustc 1.68.0-nightly (0b90256ad 2023-01-13)
Current sync impl: Lua
Current FileType: noice
Third Party Providers: []
Global Options:
    let g:clap#autoload_dir = '/usr/home/me/.local/share/nvim/lazy/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'single'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
```

**To Reproduce**

:Clap<CR>

**Expected behavior**
Open without throwing any errors

**Additional context**
Will provide as I explore further or as requested.

**Comment by liuchengxu** [comment]
Can you provide a minimal vimrc to reproduce it? I don't see it using the following vimrc in NVIM v0.9.0-dev-613+gef18c9f9b.

```vim
set nocompatible

filetype off
filetype plugin indent on

set runtimepath^=~/.vim/plugged/vim-clap

set winminheight=0
```

**Comment by liuchengxu** [comment]
Tried on another machine using NVIM v0.6.0-dev+594-g36538417f with the above vimrc, can't reproduce it. Therefore, I don't think the root cause is on the clap side, feel free to reopen if you have new findings.

**Comment by xorander00** [comment]
Sorry, finally got around to exploring this a bit further.  
  
It looks like winminheight, in some cases, is greater than 1.  In my case, I use [beauwilliams/focus.nvim](https://github.com/beauwilliams/focus.nvim) to auto-resize my layouts. After digging a bit, it's the block at line 83 in  [modules/resizer.lua](https://github.com/beauwilliams/focus.nvim/blob/master/lua/focus/modules/resizer.lua#L83) that sets it to the golden ratio value (7 in my case).

For me, that value is 7.  So when the Clap float was being triggered at clap#floating_win#open(), it was throwing the error due to winminheight=7 > winheight=1. I tried adding clap_input and clap_action to excluded filetypes for focus.nvim, but that didn't work for whatever reason. I'm not good with VimScript at all, so all I can tell is that it has something to do with the way winminheight is being set (or maybe the order? not sure).
  
Anyway, generally winminheight should be small (0-3 according to vimhelp), but I don't think it should be assumed to be the default value of 1 when modifying winheight. It's probably best to just save and restore winminheight along with winheight.  
  
Haven't forked + submitted a PR due to time, but the patch that fixed it for me is pretty small:  
  
```
diff --git a/autoload/clap/floating_win.vim b/autoload/clap/floating_win.vim
index 810e723..17a11fa 100644
--- a/autoload/clap/floating_win.vim
+++ b/autoload/clap/floating_win.vim
@@ -448,6 +448,8 @@ function! clap#floating_win#open() abort
   let g:__clap_display_curlnum = 1

   let s:save_winheight = &winheight
+  let s:save_winminheight = &winminheight
+  let &winminheight = 1
   let &winheight = 1

   let s:indicator_width = clap#layout#indicator_width()
@@ -508,6 +510,7 @@ endfunction

 function! clap#floating_win#close() abort
   let &winheight = s:save_winheight
+  let &winminheight = s:save_winminheight
   silent! autocmd! ClapEnsureAllClosed

   if s:symbol_width > 0
```

**Comment by liuchengxu** [comment]
The patch is fine to me, I can merge if you send a PR.
