### ISSUE TITLE
Make ctags executable configurable

### ISSUE THREAD

**Issue by xorander00** [liuchengxu/vim-clap#909]
**Is your feature request related to a problem? Please describe.**
When running ':Clap debug' just now, it complained about not being able to find ctags with proper JSON support.

**Describe the solution you'd like**
Variable with default value (e.g. vim.g.clap_ctags_exec) that can be explicitly set if required (e.g. 'uctags').

**Describe alternatives you've considered**
None, currently just patched source to use uctags instead of ctags for checking JSON support.

**Additional context**
Searched for configuration variable, but didn't find one. If I missed it, please let me know.

**Comment by liuchengxu** [comment]
Why don't you just make an alias `ctags` for `uctags`? I mean I'm not against adding this support, but feel it not absolutely necessary as it seems not hard to work around it on your side.

**Comment by liuchengxu** [comment]
Closing as this issue can be fixed by yourself without much effort, e.g., add `alias ctags='uctags'` to your bashrc. Feel free to reopen if this does not help.
