### ISSUE TITLE
`make` does not work at master (4aea08196fb9d3dcf365192f4bf7da7d3813a23d)

### ISSUE THREAD

**Issue by halostatue** [liuchengxu/vim-clap#947]
## Environment (please complete the following information):
 - OS: macOS
 - (Neo)Vim version: n/a
 - vim-clap version: master (4aea08196fb9d3dcf365192f4bf7da7d3813a23d)
 - Have you reproduced with a minimal vimrc: n/a
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: that's what this issues is about

## Describe the bug

`cargo build --release` fails.

## To Reproduce

```console
> make # or cargo build --release
error: failed to determine package fingerprint for build script for icon v0.1.0 (/Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon)

Caused by:
  failed to determine the most recently modified file in /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon

Caused by:
  failed to determine list of files in /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon

Caused by:
  failed to open git index at /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/.git/

Caused by:
  invalid data in index - calculated checksum does not match expected; class=Index (10)
make: *** [maple] Error 101
```

## Expected behavior

`maple` builds correctly.

I have a workaround by fixing #946 to download the pre-built binary, but it would be nice to be able to build this manually.

**Comment by halostatue** [comment]
This *may* be related to the edition (I’m using `cargo 1.68.0` and `rustc 1.68.0`), but I’m seeing success in building with the following diff:

```diff
diff --git crates/icon/Cargo.toml crates/icon/Cargo.toml
index fb2512945544..9bda9425395e 100644
--- crates/icon/Cargo.toml
+++ crates/icon/Cargo.toml
@@ -5,6 +5,7 @@ authors = ["Liu-Cheng Xu <xuliuchengxlc@gmail.com>"]
 edition = "2021"
 license = "MIT"
 publish = false
+include = ["/Cargo.toml", "src/*.rs"]
 homepage = "https://github.com/liuchengxu/vim-clap"
 description = """
 icon is a tool for drawing an icon according to the path name for vim-clap.
```

**Comment by liuchengxu** [comment]
Can't reproduce it on my machine. This error info `calculated checksum does not match expected` looks suspicious, have you tried purging the repo and downloading it again?

**Comment by halostatue** [comment]
> Can't reproduce it on my machine. This error info `calculated checksum does not match expected` looks suspicious, have you tried purging the repo and downloading it again?

I just removed vim-clap from its location and told `kristijanhusak/vim-packager` to install uninstalled packages. It cloned the repo fresh and ran `:Clap install-binary!` with this as the output (this also happens with `:Clap install-binary!` *not* run by vim-packager).

```
error: failed to determine package fingerprint for build script for icon v0.1.0 (/Users/austin/.local/share/vim/site/p
ack/packager/start/vim-clap/crates/icon)

Caused by:
  failed to determine the most recently modified file in /Users/austin/.local/share/vim/site/pack/packager/start/vim-c
lap/crates/icon

Caused by:
  failed to determine list of files in /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon

Caused by:
  failed to open git index at /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/.git/

Caused by:
  invalid data in index - calculated checksum does not match expected; class=Index (10)
```

I don’t do much with rust development, but I do `rustup` periodically and I’m on 1.68.0. Updating to 1.68.2 and running `make` in `vim-clap` results in the same thing:

```console
❯ make
cargo build --release
error: failed to determine package fingerprint for build script for icon v0.1.0 (/Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon)

Caused by:
  failed to determine the most recently modified file in /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon

Caused by:
  failed to determine list of files in /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/crates/icon

Caused by:
  failed to open git index at /Users/austin/.local/share/vim/site/pack/packager/start/vim-clap/.git/

Caused by:
  invalid data in index - calculated checksum does not match expected; class=Index (10)
make: *** [maple] Error 101
```

Adding the `include` line to `crates/icon/Cargo.toml` allows the build to run, but I’m not sure if it’s right (`crates/icon/` has a `build.rs` but does not have a `build = "build.rs"` in `crates/icon/Cargo.toml`).

In case it matters, I’m on macOS 13.3.1 on M1.

```console
> sw_vers
ProductName:		macOS
ProductVersion:		13.3.1
BuildVersion:		22E261
> uname -a
Darwin Austins-MacBook-Pro.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 arm64
```

If #946 weren’t also exhibiting, I may have never seen this.

**Comment by liuchengxu** [comment]
Interesting, `build.rs` is the default value of `package.build` https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field, I don't think it has to be declared explicitly. In terms of adding `include` into the Cargo.toml, I'm unsure what happens exactly, but I'm not against adding it if it's helpful.

**Comment by halostatue** [comment]
> Interesting, `build.rs` is the default value of `package.build` https://doc.rust-lang.org/cargo/reference/manifest.html#the-build-field, I don't think it has to be declared explicitly. In terms of adding `include` into the Cargo.toml, I'm unsure what happens exactly, but I'm not against adding it if it's helpful.

As far as I can tell, `build = "build.rs"` doesn’t change anything; the missing `include` is all that is required to be able to build on my system.
