### ISSUE TITLE
Clap-Filer cannot show results for filtering file or directory name

### ISSUE THREAD

**Issue by ktjjang** [liuchengxu/vim-clap#948]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: NAME="Ubuntu"
          VERSION="20.04.6 LTS (Focal Fossa)"
 - (Neo)Vim version: vim version 8.2.5172
 - vim-clap version: latest commit 4aea08196fb9d3dcf365192f4bf7da7d3813a23d (HEAD -> master, origin/master, origin/HEAD) Upgrade clap to 4.2)
 - Have you reproduced with a minimal vimrc: yes, it's still reproduced
 - Have you updated to the latest plugin version: yes, it's still reproduced
 - Have you upgraded to/compiled the latest Rust binary: yes, it's still reproduced

**Describe the bug**
Clap-Filer cannot show me the correct file list when I typed the part of the target file name 
![GIF 2023-04-14 오전 12-59-18](https://user-images.githubusercontent.com/24411265/231817755-5cc940a0-fe2a-4daf-a059-0fddc54a386e.gif)

**Clap debug**
            has ctags: ctags not found
            has cargo: 0
            has maple: /home/kitak/my-settings/bundle/vim-clap/bin/maple
           maple info: version 0.1.42 (git v0.42), compiled at: 2023-03-11 09:50:34.257498574 +00:00, built for x86_64-unknown-linux-musl by rustc 1.68.0 (2c8cc3432 2023-03-06).
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/kitak/my-settings/bundle/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('46'), 'open': function('<SNR>28_create_display'), 'shrink_if_undersize': function('45')}
    let g:clap#popup#preview = {'line_count': function('<SNR>27__line_count'), 'show': function('47'), 'hide': function('48'), 'clear': function('49'), 'add_highlight': function('51'), 'get_lines': funct
ion('<SNR>27__get_lines'), 'getbufvar': function('<SNR>27__getbufvar'), 'setbufvar_batch': function('<SNR>27__setbufvar_batch'), 'setbufvar': function('<SNR>27__setbufvar'), 'win_is_valid': function('<SN
R>27__win_is_valid'), 'goto_win': function('<SNR>27__goto_win'), 'set_syntax': function('50')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start vim and open clap filer : :Clap filer
3. Type target file name (above gif image, I targeted bundle.tar file)

5. See unexpected results
I expected that if I type only the letter b, a list of all files starting with b would be displayed.
But, nothing came.

**Comment by liuchengxu** [comment]
I don't see anything wrong with the gif. There are no results found for given input `bundle.tar`, hence the prompt of create new file is created.

>I expected that if I type only the letter b, a list of all files starting with b would be displayed.
But, nothing came.

Not reflected in the gif, please upload a new one. It works on my machine.

**Comment by liuchengxu** [comment]
Feel free to reopen if you can provide more context.

**Comment by ktjjang** [comment]
there are files starting with character 'b' in the current directory like below gif
![exsist_bundle](https://user-images.githubusercontent.com/24411265/232827471-a051a1a7-89e4-4f50-9cc6-a0e5f34e9349.gif)

So, when I open clap filer and type the letter b, I expected  all the files starting with b would be displayed.
But, nothing came like below.
![no_bundle](https://user-images.githubusercontent.com/24411265/232828213-5c174390-4ca1-4fda-a3eb-25f7a778f4e6.gif)
