### ISSUE TITLE
Python import problem

### ISSUE THREAD

**Issue by stockyard** [liuchengxu/vim-clap#95]
**Environment (please complete the following information):**
 - OS: macOS
 - Vim version: 8.1.2168 (with `+python/dyn`, `+python3/dyn`)
 - vim-clap version: 820980f

**Describe the bug**
After running `Clap blines`, for example, and starting typing, I get this error (probably, should be line 115 but this number, 5, is omitted):

    provider.on_typed:
    /PATH/plugged/vim-clap/autoload/clap/filter.vim, line 11
    Vim(python):ImportError: No module named clap

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start Vim with command: `vim -u min.vim`

3. Type `Clap blines`:

https://i.imgur.com/bnJ2HJF.png

4. See error:

https://i.imgur.com/Z1E6ws7.png

**Comment by liuchengxu** [comment]
I don't have this issue, using the vim installed via brew.

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct  5 2019 20:12:11)
macOS version
Included patches: 1-2115
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +cmdline_info      -farsi             +libcall           -mouse_sysmouse    +python3           -tag_any_white     +visualextra
+arabic            +comments          +file_in_path      +linebreak         +mouse_urxvt       +quickfix          -tcl               +viminfo
+autocmd           +conceal           +find_in_path      +lispindent        +mouse_xterm       +reltime           +termguicolors     +vreplace
+autochdir         +cryptv            +float             +listcmds          +multi_byte        +rightleft         +terminal          +wildignore
-autoservername    +cscope            +folding           +localmap          +multi_lang        +ruby              +terminfo          +wildmenu
-balloon_eval      +cursorbind        -footer            +lua               -mzscheme          +scrollbind        +termresponse      +windows
+balloon_eval_term +cursorshape       +fork()            +menu              +netbeans_intg     +signs             +textobjects       +writebackup
-browse            +dialog_con        +gettext           +mksession         +num64             +smartindent       +textprop          -X11
++builtin_terms    +diff              -hangul_input      +modify_fname      +packages          -sound             +timers            -xfontset
+byte_offset       +digraphs          +iconv             +mouse             +path_extra        +spell             +title             -xim
+channel           -dnd               +insert_expand     -mouseshape        +perl              +startuptime       -toolbar           -xpm
+cindent           -ebcdic            +job               +mouse_dec         +persistent_undo   +statusline        +user_commands     -xsmp
-clientserver      +emacs_tags        +jumplist          -mouse_gpm         +postscript        -sun_workshop      +vartabs           -xterm_clipboard
+clipboard         +eval              +keymap            -mouse_jsbterm     +printer           +syntax            +vertsplit         -xterm_save
+cmdline_compl     +ex_extra          +lambda            +mouse_netterm     +profile           +tag_binary        +virtualedit
+cmdline_hist      +extra_search      +langmap           +mouse_sgr         -python            -tag_old_static    +visual
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector-strong -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib  -L/
usr/local/lib -o vim        -lncurses -liconv -lintl -framework AppKit  -L/usr/local/opt/lua/lib -llua5.3 -mmacosx-version-min=10.14 -fstack-protector-strong -
L/usr/local/lib  -L/usr/local/Cellar/perl/5.30.0/lib/perl5/5.30.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Pyt
hon.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.6
```

You can add a debugging print to see if the related path is included:

```diff
--- a/autoload/clap/filter.vim
+++ b/autoload/clap/filter.vim
@@ -112,6 +112,7 @@ import vim
 plugin_root_dir = vim.eval('g:__clap_dir')
 python_root_dir = normpath(join(plugin_root_dir, '..', 'pythonx'))
 sys.path.insert(0, python_root_dir)
+print(sys.path)
 import clap

 from clap.fzy import clap_fzy
```

For me, it's `['/Users/xlc/.vim/plugged/vim-clap/pythonx', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python37.zip', '/usr/local/opt/python/Framewor
ks/Python.framework/Versions/3.7/lib/python3.7', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', '/Users/xlc/Librar
y/Python/3.7/lib/python/site-packages', '/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages', '_vim_path_']`.

**Comment by stockyard** [comment]
> I don't have this issue

Well, I have no doubts about that but this doesn't really help much, does it? :)

> You can add a debugging print to see if the related path is included

And this related path is what exactly? `plugged/vim-clap/pythonx`? Then yes, it's included for me, too.

**Comment by liuchengxu** [comment]
>using the vim installed via brew.

Perhaps this could be helpful? :)

Then I have no idea why the error occurs. A try-catch should be added here. If any exception happens, just fall back to the regexp matching mode.

**Comment by stockyard** [comment]
> Perhaps this could be helpful? :)

I'm assume you aren't here really telling your users how exactly they should install Vim, are you? :)

> A try-catch should be added here [...]

Well, would be great to hear some news on this in the future.

**Comment by liuchengxu** [comment]
Just saying my local environment, maybe it's related, I'm not sure :(.

The try-catch approach is a workaround actually, not a real solution. Pull the latest version to see the error persists. If the error disappears, the fallback strategy should be used then.
