### ISSUE TITLE
Clap-Filer cannot show results for filtering file or directory name (reopen)

### ISSUE THREAD

**Issue by ktjjang** [liuchengxu/vim-clap#954]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: NAME="Ubuntu"
          VERSION="20.04.6 LTS (Focal Fossa)"
 - (Neo)Vim version: vim version 8.2.5172
 - vim-clap version: latest commit 4aea08196fb9d3dcf365192f4bf7da7d3813a23d (HEAD -> master, origin/master, origin/HEAD) Upgrade clap to 4.2)
 - Have you reproduced with a minimal vimrc: yes, it's still reproduced
 - Have you updated to the latest plugin version: yes, it's still reproduced
 - Have you upgraded to/compiled the latest Rust binary: yes, it's still reproduced

**Describe the bug**
Hi @liuchengxu,
I sincerly appreciate your support for this useful vim plugin

There are files starting with character 'b' in the current directory like below gif (bundle, bundle.tar)

![exsist_bundle](https://user-images.githubusercontent.com/24411265/233129738-1b220bc5-a662-49f0-b2f7-54ae7f35a9d1.gif)

So, when I open clap filer and type the letter b, I expected all the files starting with b would be displayed.
But, nothing came like below.

![no_bundle](https://user-images.githubusercontent.com/24411265/233129762-9bf7de08-3f70-47eb-9a65-cefe7f6d74e3.gif)

**Clap debug**
            has ctags: ctags not found
            has cargo: 0
            has maple: /home/kitak/my-settings/bundle/vim-clap/bin/maple
           maple info: version 0.1.42 (git v0.42), compiled at: 2023-03-11 09:50:34.257498574 +00:00, built for x86_64-unknown-linux-musl by rustc 1.68.0 (2c8cc3432 2023-03-06).
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/kitak/my-settings/bundle/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('46'), 'open': function('<SNR>28_create_display'), 'shrink_if_undersize': function('45')}
    let g:clap#popup#preview = {'line_count': function('<SNR>27__line_count'), 'show': function('47'), 'hide': function('48'), 'clear': function('49'), 'add_highlight': function('51'), 'get_lines': funct
ion('<SNR>27__get_lines'), 'getbufvar': function('<SNR>27__getbufvar'), 'setbufvar_batch': function('<SNR>27__setbufvar_batch'), 'setbufvar': function('<SNR>27__setbufvar'), 'win_is_valid': function('<SN
R>27__win_is_valid'), 'goto_win': function('<SNR>27__goto_win'), 'set_syntax': function('50')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
  Provider Variables:
                     []

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start vim and open clap filer : :Clap filer
3. Type target file name (above gif image, I targeted bundle.tar file)

5. See unexpected results
I expected that if I type only the letter b, a list of all files starting with b would be displayed.
But, nothing came.

**Comment by liuchengxu** [comment]
Thanks for the report, https://github.com/liuchengxu/vim-clap/pull/955 should solve this issue. You have to compile the binary locally before the next release.

**Comment by ktjjang** [comment]
It works well after rebuild rust binary! 
Thank you.

**Comment by ktjjang** [comment]
It works well after rebuild rust binary! 
Thank you.
