### ISSUE TITLE
Clap does not work after updating it on gvim(windows)

### ISSUE THREAD

**Issue by hylwxqwq** [liuchengxu/vim-clap#985]
**Environment (please complete the following information):**
 - OS: Windows 11
 - (Neo)Vim version: vim9.0 (gvim)
 - vim-clap version: Latest(May 27th)
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: tried, but failed, it shows `Error detected while processing function clap#[9]..clap#installer#install[10]..<SNR>48_do_download: line 4: E282 Cannot read from "C:\Users\ADMINI~1\AppData\Local\Temp\VZ73EC3.tmp" `
**Describe the bug**
After running `:PlugUpdate` in Vim-Plug to update Clap, I got nothing when I type `:Clap files`, `:Clap blines` in my gvim.

I have tried to install binary but it reports error(the infomation is above).

**Clap debug**

```
            has ctags: Exuberant Ctags 5.8 (-json)
            has cargo: 0
            has maple: C:\Program Files (x86)\Vim\vimfiles\plugged\vim-clap/bin/maple.exe
           maple info: version 0.1.44 (git v0.44), compiled at: 2023-05-27 04:06:48.432734300 +00:00, built for x86_64-pc-windows-msvc by rustc 1.69.0 (84c898d65 2023-04-16).

     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Program Files (x86)\Vim\vimfiles\plugged\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('61'), 'open': function('<SNR>38_create_display'), 'width': 32, 'shrink_if_undersize': function('60')}
    let g:clap#popup#preview = {'line_count': function('<SNR>37__line_count'), 'show': function('62'), 'hide': function('63'), 'clear': function('64'), 'add_highlight': function('66'), 'get_lines': function('<SNR>37__get_lines'), 'getbufvar': function('<SNR>37__getbufvar'), 'setbufvar_batch': function('<SNR>37__setbufvar_batch'), 'bufnr': 3, 'setbufvar': function('<SNR>37__setbufvar'), 'winid': 1002, 'win_is_valid': function('<SNR>37__win_is_valid'), 'goto_win': function('<SNR>37__goto_win'), 'set_syntax': function('65')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_indicator_winid = 1003
    let g:clap_insert_mode_only = v:false
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'always'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1005
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim

let $VIMCONFIG='C:/Program Files (x86)/Vim/vimfiles'

set nocompatible
set runtimepath^=$VIMCONFIG/plugged/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `gvim -u min.vim`

3. Type `:Clap files`

**Expected behavior**

If there's a file called `example.cpp` in the current directory, type `:Clap files` and then type `example.cpp`, nothing was on the screen. 

**Screenshots**

![image](https://github.com/liuchengxu/vim-clap/assets/77879721/ac453204-8232-47f2-b028-01797f693501)

![image](https://github.com/liuchengxu/vim-clap/assets/77879721/1d1f225e-5bfa-464a-99c3-7cbdaec9e75d)

![image](https://github.com/liuchengxu/vim-clap/assets/77879721/38875e78-6002-4bec-8f1e-cde592005119)

**Additional context**

**Comment by hylwxqwq** [comment]
I guess the problem is that the Rust binary is lost, but I could not install it :(

**Comment by liuchengxu** [comment]
Should be a duplicate as https://github.com/liuchengxu/vim-clap/issues/967, the prebuilt binary for Windows is somehow problematic, you have these options for now:

- Roll back to the last release (v0.43), note the binary and repo should both switch to v0.43.
- Compile the Rust binary yourself before the next release.

**Comment by hylwxqwq** [comment]
Thanks! I have tried to rollback to v0.43, and it works.
