### ISSUE TITLE
Clap files seems not to be working on Windows

### ISSUE THREAD

**Issue by vds2212** [liuchengxu/vim-clap#988]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Windows
 - (Neo)Vim version: 9.0
 - vim-clap version: 0;45
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: I use the binary version provided by the site

**Describe the bug**
When I use `Clap file` I get error message and the file list is not populated

**Clap debug**

```
:Verbose Clap debug
            has ctags: Universal Ctags 5.9.0(6f544dfc) (+json)
            has cargo: 1
            has maple: C:\Users\vds\vimfiles\plugged\vim-clap/target/release/maple.exe
           maple info: version 0.1.44 (git v0.44-15-gb4ee1e6), compiled at: 2023-05-28 10:48:10.366539600 +02:00, built for x86_64-pc-windows-msvc by rustc 1.69.0 (84c898d65 2023-04-16).

        rustc version: rustc 1.69.0 (84c898d65 2023-04-16)

     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\vds\vimfiles\plugged\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('165'), 'open': function('<SNR>222_create_display'), 'width': 188, 'shrink_if_undersize': function('164')}
    let g:clap#popup#preview = {'line_count': function('<SNR>221__line_count'), 'show': function('166'), 'hide': function('167'), 'clear': function('168'), 'add_highlight': function('170'), 'get_lines': function('<SNR>221__get_lines'), 'getbufvar': function('<SNR>221__getbufvar'), 'setbufvar_batch': function('<SNR>221__setbufvar_batch'), 'setbufvar': function('<SNR>221__setbufvar'), 'win_is_valid': function('<SNR>221__win_is_valid'), 'goto_win': function('<SNR>221__goto_win'), 'set_syntax': function('169')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_indicator_winid = 1006
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_match_color = ['#5E81AC', '12']
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'never'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_project_root_markers = ['.gitignore', '.vimspector.json', '.root', '.git', '.git/']
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1008
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

vim-clap: Vim(echoerr):[clap#api#call] method: clap#state#update_progress_full, args: [945, 1569, {'icon_added': v:true, 'indices': [[11, 12, 13], [25, 26, 27], [4, 24, 25], [11, 12, 13], [10, 11, 12], [20, 21, 22], [25, 26, 27], [25, 26, 27], [17, 18, 19], [29, 30, 31], [29, 30, 31], [21, 22, 23], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [26, 27, 28], [31, 32, 33], [31, 32, 33], [23, 24, 25], [32, 33, 34], [43, 44, 45], [4, 18, 19], [4, 15, 16], [44, 45, 46], [4, 24, 25], [43, 44, 45], [44, 45, 46], [43, 44, 45], [43, 44, 45], [4, 19, 20], [43, 44, 45], [43, 44, 45], [43, 44, 45], [43, 44, 45], [4, 26, 27], [37, 38, 39], [4, 19, 20], [55, 56, 57]], 'lines': [' Config\Categories.cfg', ' Scripts\generateKPIs\categories.py', ' Config\ScheduleTemplates.tsn', ' Config\CategoryPenalties.cfg', ' Input\CategoriesImpositions.cfg', ' Config\JobDynamicAttributes.cfg', ' Exchange\MaterialAllocation.fmt', ' Exchange\MaterialAllocation.txt', ' Exchange\RuleCatalog_fromPPL.tsn', ' Exchange\vds\MaterialAllocation.fmt', ' Exchange\vds\MaterialAllocation.txt', ' Exchange\vds\RuleCatalog_fromPPL.tsn', ' Sequences\20230623003\Categories.cfg', ' Sequences\20230623004\Categories.cfg', ' Sequences\20230623005\Categories.cfg', ' Sequences\20230623006\Categories.cfg', ' Sequences\20230616001\Categories.cfg', ' Sequences\20230623007\Categories.cfg', ' Sequences\20230623001\Categories.cfg', ' Sequences\20230623002\Categories.cfg', ' Sequences\20230623008\Categories.cfg', ' Exchange\trash\MaterialAllocation.fmt', ' Exchange\trash\MaterialAllocation.txt', ' Exchange\trash\RuleCatalog_fromPPL.tsn', ' Gui\ObjectEditor2CombinationCategorySet.cfg', ' CustomJumps\SerialObject\SerialObjectLocator.h', ' Config\Colorizations.tsn', ' Config\DueDateFunction.xls', ' CustomJumps\SerialObject\ISerialObjectLocator.h', ' CustomJumps\Deploy.bat', ' CustomJumps\SerialObject\SerialObjectLocator.cpp', ' CustomJumps\SerialObject\ISerialObjectLocator.cpp', ' CustomJumps\SerialObject\SerialObjectLocatorElement.h', ' CustomJumps\SerialObject\SerialObjectLocatorAbsolute.h', ' CustomJumps\expatlib\.archive', ' CustomJumps\SerialObject\SerialObjectLocatorElement.cpp', ' CustomJumps\SerialObject\SerialObjectLocatorAttribute.h', ' CustomJumps\SerialObject\SerialObjectLocatorAbsolute.cpp', ' CustomJumps\SerialObject\SerialObjectLocatorAttribute.cpp', ' CustomJumps\UtilsLib\Path.h', ' Scripts\generateKPIs\__pycache__\categories.cpython-39.pyc', ' CustomJumps\expatlib\lib\.archive', ' CustomJumps\SerialObject\x64\DebugV9\SerialObjectLocator.obj'], 'truncated_map': {}}], exception: Vim(return):E117: Unknown function: clap#state#update_progress_full, throwpoint:function <SNR>75_out_cb[6]..clap#client#handle[12]..clap#api#call, line 10
vim-clap: Vim(echoerr):[clap#api#call] method: clap#state#update_progress_full, args: [700, 1569, {'icon_added': v:true, 'indices': [[11, 12, 13, 14], [25, 26, 27, 28], [4, 24, 25, 26], [11, 12, 13, 14], [10, 11, 12, 13], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [26, 27, 28, 29], [32, 33, 34, 35], [4, 15, 16, 17], [37, 38, 39, 40], [4, 24, 25, 26], [4, 37, 38, 39], [4, 37, 38, 39], [6, 14, 15, 16], [4, 46, 47, 48], [4, 46, 47, 48], [16, 23, 24, 25], [4, 49, 50, 51], [4, 51, 52, 53], [5, 17, 18, 19], [4, 58, 59, 60], [4, 60, 61, 62], [31, 41, 42, 43], [4, 71, 72, 73], [4, 71, 72, 73], [4, 73, 74, 75], [4, 73, 74, 75], [4, 80, 81, 82], [4, 82, 83, 84], [4, 83, 84, 85], [4, 85, 86, 87], [9, 15, 16, 17], [6, 14, 15, 16], [6, 14, 15, 16], [6, 14, 15, 16], [5, 17, 18, 19]], 'lines': [' Config\Categories.cfg', ' Scripts\generateKPIs\categories.py', ' Config\ScheduleTemplates.tsn', ' Config\CategoryPenalties.cfg', ' Input\CategoriesImpositions.cfg', ' Sequences\20230623008\Categories.cfg', ' Sequences\20230623007\Categories.cfg', ' Sequences\20230623006\Categories.cfg', ' Sequences\20230623005\Categories.cfg', ' Sequences\20230623004\Categories.cfg', ' Sequences\20230623003\Categories.cfg', ' Sequences\20230623002\Categories.cfg', ' Sequences\20230623001\Categories.cfg', ' Sequences\20230616001\Categories.cfg', ' Gui\ObjectEditor2CombinationCategorySet.cfg', ' Config\DueDateFunction.xls', ' Scripts\generateKPIs\__pycache__\categories.cpython-39.pyc', ' Config\ScheduleTemplatesDynamic.tsn', ' CustomJumps\SerialObject\format_date.h', ' CustomJumps\SerialObject\format_date.cpp', ' Exchange\MaterialUnits.fmt', ' CustomJumps\SerialObject\SerialObjectTypeDateTime.h', ' CustomJumps\SerialObject\SerialObjectTypeDateTime.cpp', ' Input\preprocessedMaterialUnits.fmt', ' CustomJumps\SerialObject\x64\DebugV9\format_date.obj', ' CustomJumps\SerialObject\x64\ReleaseV9\format_date.obj', ' Scripts\generateKPIs\generateKPIs.py', ' CustomJumps\SerialObject\x64\DebugV9\SerialObjectTypeDateTime.obj', ' CustomJumps\SerialObject\x64\ReleaseV9\SerialObjectTypeDateTime.obj', ' Scripts\generatePossibleMatches\generatePossibleMatches.py', ' CustomJumps\expatlib\x64\DebugV9\expatlib.tlog\expatlib.lastbuildstate', ' CustomJumps\UtilsLib\x64\DebugV9\UtilsLib.tlog\UtilsLib.lastbuildstate', ' CustomJumps\UtilsLib\x64\ReleaseV9\UtilsLib.tlog\UtilsLib.lastbuildstate', ' CustomJumps\expatlib\x64\ReleaseV9\expatlib.tlog\expatlib.lastbuildstate', ' CustomJumps\customJumps\x64\DebugV9\CustomJumps.tlog\CustomJumps.lastbuildstate', ' CustomJumps\customJumps\x64\ReleaseV9\CustomJumps.tlog\CustomJumps.lastbuildstate', ' CustomJumps\SerialObject\x64\DebugV9\SerialObject.tlog\SerialObject.lastbuildstate', ' CustomJumps\SerialObject\x64\ReleaseV9\SerialObject.tlog\SerialObject.lastbuildstate', ' Gui\Icons\date.ico', ' Exchange\MaterialUnits.tsn', ' Exchange\MaterialUnits.txt', ' Exchange\MaterialUnits.bat', ' Scripts\generateKPIs\kpi.py'], 'truncated_map': {}}], exception: Vim(return):E117: Unknown function: clap#state#update_progress_full, throwpoint:function <SNR>75_out_cb[6]..clap#client#handle[12]..clap#api#call, line 10

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by vds2212** [comment]
There seems to be a call to `clap#state#update_progress_full` that do not exist anymore. But I fail to understand the origin of the call since I don't see that function in the actual code.

**Comment by liuchengxu** [comment]
According to the info of `:Clap debug`, you're still using the binary of v0.44, which is outdated. You should upgrade to v0.45, I saw the locally compiled one is being used (`C:\Users\vds\vimfiles\plugged\vim-clap/target/release/maple.exe`), but you mentioned you used the prebuilt binary from GitHub, I recommend you to either run `cargo clean` to remove `target/release/maple.exe` and ensure `bin/maple.exe` is v0.45, or recompile the binary using `cargo build --release`.

**Comment by vds2212** [comment]
Thanks. It works! 

I had both the version downloaded from the repository and the version compiled and it seems that compiled version wins.

Thank for the support,
Best regards,
Vivian.

**Comment by liuchengxu** [comment]
Yes, the locally compiled binary has a higher priority by default, and then the prebuilt binary.
