### ISSUE TITLE
Permanent floating window

### ISSUE THREAD

**Issue by DanCardin** [liuchengxu/vim-clap#99]
**Environment (please complete the following information):**
 - OS: osx
 - (Neo)Vim version: 0.4
 - vim-clap version: 0.1(?) latest as of right now

**Describe the bug**
It is possible to get into scenarios where the floating window is permanently on screen and prevents you from continuing to use that vim instance.

**To Reproduce**
As far as I can tell, this is due to mappings still being picked up when in normal mode on the floating window buffer.

1. Given mappings
```vim
map <Leader>o :Clap gfiles<cr>
map <Leader>b :Clap buffers<cr>
```

2. type `<leader>o`
3. type something (or not)
4. hit escape once (i assume this is a feature, being able to use normal vim navigation on what you typed). the floating window should still be visible.
5. type `<leader>b`
6. now you're stuck, no matter what you do (escape multiple times, selecting an item, etc) there should be a floating window above everything.

**Expected behavior**
Probably `:Clap` inside a clap floating window shouldn't do anything? I like the ability to hit escape once and edit my input as normal vim input, so not allowing all the mappings (if that's an option) is probably not ideal.

**Comment by liuchengxu** [comment]
I don't quite understand what your issue is. Please provide the minimal vimrc and reproducible steps, and screenshot or GIF if possible.

**Comment by DanCardin** [comment]
Sorry, `<leader>` outside code blocks just hides the leader bit.

But also sorry, I had assumed the ability to hit escape once and remain in the floating window (and twice to exit) was a feature. I guess with the minimal vim, that appears to be not true.

Once I determine *why* this is happening, what are the odds that *can* be a feature, and the subsequent fallout it causes could be fixed?

**Comment by DanCardin** [comment]
So this turns out to be an interaction with https://github.com/cohama/lexima.vim

```vim
set nocompatible
set runtimepath^=~/.local/share/nvim/site/plugged/vim-clap/
set runtimepath^=~/.local/share/nvim/site/plugged/lexima.vim/

map <Leader>o :Clap gfiles<cr>
map <Leader>b :Clap buffers<cr>
syntax on
filetype plugin indent on
```

I guess specifically because lexima has this `inoremap <unique> <Esc><Esc> <Esc>` mapping.

**Comment by liuchengxu** [comment]
Currently ESC is truly meant to exit, see https://github.com/liuchengxu/vim-clap/blob/master/ftplugin/clap_input.vim, but I think it could be improved in future to utilize the multiple mode feature of vim. For instance, we could use the normal mode mappings for the actions mentioned in #51, but the design is not clear now.

**Comment by DanCardin** [comment]
So i didn't have a lot invested in lexima, i pretty trivially switched to delimitMate which does not appear to have the same behavior.

However, if you think enabling normal mode navigation on the text input is possible, then maybe this can turn into a feature request?

The 2 big issues i noticed when seeing this behavior was:
* `:Clap` when there was already a clap floating window open should no-op
* things like `bnext` would take focus away and leave the window open.

With those addressed (if possible), i think that'd be a totally usable mode.

**Comment by liuchengxu** [comment]
>:Clap when there was already a clap floating window open should no-op

What's the meaning of `no-op`?

>things like bnext would take focus away and leave the window open.

This is not a complete design.

**Comment by DanCardin** [comment]
Just so we're clear on the behavior I was experiencing (and happen to like)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/701548/67682323-76b38380-f965-11e9-800a-b57e86b3bf5f.gif)

> What's the meaning of no-op?
by no-op, I mean: If `:Clap` were to do nothing if there was a clap floating window already visible; then it wouldn't be possible to recursively open clap from inside clap's window. Not even as a feature, this seems like maybe seems like a good behavior to guard against actual bugs anyways, no?

by my comment about bnext, i meant that that's another case where the floating window stays permanently open and control goes back to the original buffer instead of the floating window. Similarly to the above, if you know of a way to prevent this from happening, i can live with the wonky unintended behavior i was experienced, without any changes to clap itself.

> * navigate the result list like the insert mode.
> * run some command on the current selected item or multiple selected items. 
So the current behavior is that normal in-line command (e.g. `b`, `e`, `ciw`) operate on the query, and that's what I would want. The main additional thing that'd be nice is if `j` and `k` moved up and down in the result set in command mode.

I'm not particularly interested in performing other commands on the items themselves really, so i'll leave that unspecified.

> the popup of vim is unable to be focused
I suppose that's a problem if this is more complicated or impossible with vim.

**Comment by liuchengxu** [comment]
>this seems like maybe seems like a good behavior to guard against actual bugs anyways,
This actually should be achieved by not opening new windows if they already exist.

Current only the behavior in insert mode of the input window is guaranteed, otherwise it's all not well defined, although you can try `<C-W>W` to jump around all the windows without closing clap when in the normal mode, but that may be changed later. Again, the behaviors in the normal mode are not specified at the moment.

>The main additional thing that'd be nice is if j and k moved up and down in the result set in command mode.

That's actually the input history if I'm right, which could be added eventually.
