### ISSUE TITLE
Clap provide no result after some times

### ISSUE THREAD

**Issue by vds2212** [liuchengxu/vim-clap#995]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the info of `:Clap debug` the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: Windows 10
 - vim-clap version: 0.45
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

After some times Clap do not provide any suggestion for:
- `Clap buffers`
- `Clap history`
- ...

**Clap debug**

```
:Verbose Clap debug
            has ctags: Universal Ctags 5.9.0(6f544dfc) (+json)
            has cargo: 1
            has maple: C:\Users\vds\vimfiles\plugged\vim-clap/target/release/maple.exe
           maple info: version 0.1.45 (git v0.45-3-g3ffa9f5), compiled at: 2023-07-04 22:24:40.383526900 +02:00, built for x86_64-pc-windows-msvc by rustc 1.70.0 (90c541806 2023-05-31).

        rustc version: rustc 1.69.0 (84c898d65 2023-04-16)

     Current FileType: vim
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = 'C:\Users\vds\vimfiles\plugged\vim-clap\autoload'
    let g:clap#popup#display = {'shrink': function('163'), 'open': function('<SNR>186_create_display'), 'width': 188, 'shrink_if_undersize': function('162')}
    let g:clap#popup#preview = {'line_count': function('<SNR>185__line_count'), 'show': function('164'), 'hide': function('165'), 'clear': function('166'), 'add_highlight': function('168'), 'get_lines': function('<SNR>185__get_lines'), 'getbufvar': function('<SNR>185__getbufvar'), 'setbufvar_batch': function('<SNR>185__setbufvar_batch'), 'setbufvar': function('<SNR>185__setbufvar'), 'win_is_valid': function('<SNR>185__win_is_valid'), 'goto_win': function('<SNR>185__goto_win'), 'set_syntax': function('167')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_actions = ['open-config', 'generate-toc', 'update-toc', 'delete-toc']
    let g:clap_background_shadow_blend = 50
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 1
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_fuzzy_match_hl_groups = [0]
    let g:clap_indicator_winid = 1007
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'relative': 'editor'}
    let g:clap_match_color = ['#5E81AC', '12']
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_open_preview = 'never'
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_direction = 'AUTO'
    let g:clap_preview_size = 5
    let g:clap_project_root_markers = ['.gitignore', '.vimspector.json', '.root', '.git', '.git/']
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_spinner_winid = 1009
  Provider Variables:
                     []
```

**To Reproduce**

I have unfortunately no simple way to reproduce it.
It happen several time a day.

If I restart Vim the problem disappear for some times

**Comment by vds2212** [comment]
Is there a way to restart clap within Vim?

**Comment by liuchengxu** [comment]
>Is there a way to restart clap within Vim?

No, not supported at the moment.

Any error info in the log file from the binary? https://github.com/liuchengxu/vim-clap#config-file

**Comment by liuchengxu** [comment]
Thanks for the log, now it explains why you get no results, the source initialization is unable to finish within a fixed timeout (300ms for now), we should wait for the completion of source initialization for providers like buffers and history, will propose a fix.

**Comment by liuchengxu** [comment]
@vds2212 Can you try this branch https://github.com/liuchengxu/vim-clap/tree/fix-initialization, needs to recompile the binary locally.

**Comment by vds2212** [comment]
Thanks, I'll try tonight and let you know probably tomorrow.

**Comment by liuchengxu** [comment]
There is a debugging statement that sleeps 5s in the initialization to mimic the situation in this issue, which has been removed in the latest commit,  please try again, should be fine now. Furthermore, if you type anything while the initialization is still a work in progress in case it takes too long, you'll see a corresponding message echoed from cmdline.

**Comment by vds2212** [comment]
Thanks this give result when I start Vim. I'll test it during the day. If I have no error before the end of the day. I'll propose to close the issue.

Thanks once more for you wonderful support :-)

Best regards,
Vivian.

**Comment by vds2212** [comment]
I didn't had the problem a single time today. Although it was not an extensive Vim day. I'll be in holiday for 3 weeks. I'll be back on the 16th of August.

Thanks for your support :-)
Best regards,
Vivian.

**Comment by vds2212** [comment]
After few days of utilization of your branch I confirm that I don't have the problem anymore.

Once again thanks for your wonderful support :-)
